In [1]:
import pandas as pd

# Load datasets
sellers_file = "FashionHub_sellers_updated.csv"
products_file = "FashionHub_products_updated.csv"

sellers_df = pd.read_csv(sellers_file)
products_df = pd.read_csv(products_file)

# --- 1. Inspect datasets ---
print("Sellers Dataset Info:")
print(sellers_df.info())
print(sellers_df.head())

print("\nProducts Dataset Info:")
print(products_df.info())
print(products_df.head())

# --- 2. Check for missing values ---
print("\nMissing values in Sellers:")
print(sellers_df.isnull().sum())

print("\nMissing values in Products:")
print(products_df.isnull().sum())

# --- 3. Check for duplicate rows ---
print("\nDuplicate rows in Sellers:", sellers_df.duplicated().sum())
print("Duplicate rows in Products:", products_df.duplicated().sum())

# --- 4. Verify SellerID links -

Sellers Dataset Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 432 entries, 0 to 431
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   SellerID         432 non-null    object
 1   SellerName       432 non-null    object
 2   SellerType       432 non-null    object
 3   Location         432 non-null    object
 4   Verified         432 non-null    object
 5   StoreOnPlatform  432 non-null    object
 6   Rating           432 non-null    float64
dtypes: float64(1), object(6)
memory usage: 23.8+ KB
None
  SellerID               SellerName    SellerType    Location Verified  \
0     S001        Okara Dress House  Local Seller      Multan      Yes
1     S002                Limelight     Big Brand    Peshawar       No
2     S003  Faisalabad Fabric Point  Local Seller  Rawalpindi      Yes
3     S004   Karachi Bazaar Fashion  Local Seller  Faisalabad       No
4     S005       Chiniot Cloth Mart  Local Seller      Lahore      Yes

  StoreOnPlatform  Rating
0             Yes     4.0
1             Yes     4.8
2             Yes     4.2
3             Yes     4.9
4             Yes     4.3

Products Dataset Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1559 entries, 0 to 1558
Data columns (total 13 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   ProductID    1559 non-null   object
 1   SellerID     1559 non-null   object
 2   SellerName   1559 non-null   object
 3   Category     1559 non-null   object
 4   SubCategory  1559 non-null   object
 5   ProductName  1559 non-null   object
 6   PricePKR     1559 non-null   int64
 7   Gender       1559 non-null   object
 8   Color        1559 non-null   object
 9   Material     1559 non-null   object
 10  Season       1559 non-null   object
 11  StockQty     1559 non-null   int64
 12  AI_Tags      1559 non-null   object
dtypes: int64(2), object(11)
memory usage: 158.5+ KB
None
  ProductID SellerID         SellerName            Category SubCategory  \
0     P0001     S001  Okara Dress House              Others         Cap
1     P0002     S001  Okara Dress House  Bags & Accessories      Wallet
2     P0003     S001  Okara Dress House        Western Wear     T-Shirt
3     P0004     S002          Limelight        Western Wear     T-Shirt
4     P0005     S002          Limelight  Bags & Accessories      Wallet

               ProductName  PricePKR Gender   Color   Material      Season  \
0      White Polyester Cap     18057    Men   White  Polyester  All-season
1  Yellow Polyester Wallet     11044  Women  Yellow  Polyester      Summer
2    Green Leather T-Shirt      1628   Kids   Green    Leather      Summer
3      Yellow Wool T-Shirt     13215  Women  Yellow       Wool      Winter
4     Brown Leather Wallet       887    Men   Brown    Leather      Winter

   StockQty                  AI_Tags
0       245   summer, ethnic, casual
1       119    formal, party, summer
2       229  ethnic, casual, wedding
3       461  trendy, casual, wedding
4       386    formal, party, winter

Missing values in Sellers:
SellerID           0
SellerName         0
SellerType         0
Location           0
Verified           0
StoreOnPlatform    0
Rating             0
dtype: int64

Missing values in Products:
ProductID      0
SellerID       0
SellerName     0
Category       0
SubCategory    0
ProductName    0
PricePKR       0
Gender         0
Color          0
Material       0
Season         0
StockQty       0
AI_Tags        0
dtype: int64

Duplicate rows in Sellers: 0
Duplicate rows in Products: 0

In [2]:
import pandas as pd

# Load cleaned sellers dataset
sellers_df = pd.read_csv("FashionHub_sellers_updated.csv")

# Basic info
print("Sellers Dataset Info:")
print(sellers_df.info())

# Total sellers
print("\nTotal sellers:", len(sellers_df))

# Seller type distribution
if 'SellerType' in sellers_df.columns:
    print("\nSeller Type Distribution:")
    print(sellers_df['SellerType'].value_counts())

# Location distribution
if 'Location' in sellers_df.columns:
    print("\nLocation Distribution:")
    print(sellers_df['Location'].value_counts())

# Optional: check unique seller names
if 'SellerName' in sellers_df.columns:
    print("\nSample Sellers:")
    print(sellers_df['SellerName'].head(10))

Sellers Dataset Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 432 entries, 0 to 431
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   SellerID         432 non-null    object
 1   SellerName       432 non-null    object
 2   SellerType       432 non-null    object
 3   Location         432 non-null    object
 4   Verified         432 non-null    object
 5   StoreOnPlatform  432 non-null    object
 6   Rating           432 non-null    float64
dtypes: float64(1), object(6)
memory usage: 23.8+ KB
None

Total sellers: 432

Seller Type Distribution:
SellerType
Local Seller      145
Instagram Shop    145
Big Brand         142
Name: count, dtype: int64

Location Distribution:
Location
Lahore        60
Faisalabad    58
Peshawar      57
Multan        54
Rawalpindi    53
Islamabad     51
Karachi       51
Quetta        48
Name: count, dtype: int64

Sample Sellers:
0          Okara Dress House
1                  Limelight
2    Faisalabad Fabric Point
3     Karachi Bazaar Fashion
4         Chiniot Cloth Mart
5       Ethnic by Outfitters
6                 Outfitters
7     Karachi Bazaar Fashion
8    Faisalabad Fabric Point
9                ModishMoods
Name: SellerName, dtype: object

In [3]:
# Explore products dataset
print("Products Dataset Info:")
print(products_df.info())

# Total products
print("\nTotal products:", len(products_df))

# Category distribution
if 'Category' in products_df.columns:
    print("\nCategory Distribution:")
    print(products_df['Category'].value_counts())

# Price stats
if 'PricePKR' in products_df.columns:
    print("\nPrice Statistics:")
    print(products_df['PricePKR'].describe())

# Products per seller
if 'SellerID' in products_df.columns:
    print("\nProducts per Seller (Top 10):")
    print(products_df['SellerID'].value_counts().head(10))

# Sample products
print("\nSample Products:")
print(products_df.head(10))

Products Dataset Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1559 entries, 0 to 1558
Data columns (total 13 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   ProductID    1559 non-null   object
 1   SellerID     1559 non-null   object
 2   SellerName   1559 non-null   object
 3   Category     1559 non-null   object
 4   SubCategory  1559 non-null   object
 5   ProductName  1559 non-null   object
 6   PricePKR     1559 non-null   int64
 7   Gender       1559 non-null   object
 8   Color        1559 non-null   object
 9   Material     1559 non-null   object
 10  Season       1559 non-null   object
 11  StockQty     1559 non-null   int64
 12  AI_Tags      1559 non-null   object
dtypes: int64(2), object(11)
memory usage: 158.5+ KB
None

Total products: 1559

Category Distribution:
Category
Jewelry               319
Eastern Wear          309
Western Wear          303
Bags & Accessories    291
Others                175
Shoes                 162
Name: count, dtype: int64

Price Statistics:
count     1559.000000
mean     10101.840282
std       5674.155396
min        505.000000
25%       5315.500000
50%       9939.000000
75%      14873.000000
max      19973.000000
Name: PricePKR, dtype: float64

Products per Seller (Top 10):
SellerID
S217    5
S318    5
S150    5
S236    5
S235    5
S088    5
S087    5
S086    5
S314    5
S084    5
Name: count, dtype: int64

Sample Products:
  ProductID SellerID               SellerName            Category SubCategory  \
0     P0001     S001        Okara Dress House              Others         Cap
1     P0002     S001        Okara Dress House  Bags & Accessories      Wallet
2     P0003     S001        Okara Dress House        Western Wear     T-Shirt
3     P0004     S002                Limelight        Western Wear     T-Shirt
4     P0005     S002                Limelight  Bags & Accessories      Wallet
5     P0006     S002                Limelight             Jewelry    Earrings
6     P0007     S003  Faisalabad Fabric Point        Western Wear      Hoodie
7     P0008     S003  Faisalabad Fabric Point        Western Wear  Maxi Dress
8     P0009     S003  Faisalabad Fabric Point  Bags & Accessories        Belt
9     P0010     S003  Faisalabad Fabric Point             Jewelry    Necklace

               ProductName  PricePKR  Gender   Color   Material      Season  \
0      White Polyester Cap     18057     Men   White  Polyester  All-season
1  Yellow Polyester Wallet     11044   Women  Yellow  Polyester      Summer
2    Green Leather T-Shirt      1628    Kids   Green    Leather      Summer
3      Yellow Wool T-Shirt     13215   Women  Yellow       Wool      Winter
4     Brown Leather Wallet       887     Men   Brown    Leather      Winter
5      Blue Linen Earrings     17571  Unisex    Blue      Linen  All-season
6        Green Lawn Hoodie     12948     Men   Green       Lawn      Summer
7    Beige Silk Maxi Dress      3152  Unisex   Beige       Silk      Summer
8          White Silk Belt      5732     Men   White       Silk      Summer
9       Pink Wool Necklace      3101  Unisex    Pink       Wool  All-season

   StockQty                   AI_Tags
0       245    summer, ethnic, casual
1       119     formal, party, summer
2       229   ethnic, casual, wedding
3       461   trendy, casual, wedding
4       386     formal, party, winter
5       389   wedding, casual, ethnic
6       179  western, wedding, formal
7        97   formal, wedding, summer
8       453     party, summer, winter
9       286    ethnic, formal, trendy

In [4]:
# Check all SellerIDs in products exist in sellers
invalid_sellers = products_df[~products_df['SellerID'].isin(sellers_df['SellerID'])]
print("Products with invalid SellerID:", len(invalid_sellers))

# Count products per seller
products_per_seller = products_df.groupby('SellerID')['ProductID'].count()
print("\nProducts per Seller (Top 10):")
print(products_per_seller.sort_values(ascending=False).head(10))

# Merge products with seller info for easy access
merged_df = pd.merge(products_df, sellers_df, on='SellerID', how='left')
print("\nMerged dataset sample:")
print(merged_df.head(5))

Products with invalid SellerID: 0

Products per Seller (Top 10):
SellerID
S217    5
S318    5
S150    5
S236    5
S235    5
S088    5
S087    5
S086    5
S314    5
S084    5
Name: ProductID, dtype: int64

Merged dataset sample:
  ProductID SellerID       SellerName_x            Category SubCategory  \
0     P0001     S001  Okara Dress House              Others         Cap
1     P0002     S001  Okara Dress House  Bags & Accessories      Wallet
2     P0003     S001  Okara Dress House        Western Wear     T-Shirt
3     P0004     S002          Limelight        Western Wear     T-Shirt
4     P0005     S002          Limelight  Bags & Accessories      Wallet

               ProductName  PricePKR Gender   Color   Material      Season  \
0      White Polyester Cap     18057    Men   White  Polyester  All-season
1  Yellow Polyester Wallet     11044  Women  Yellow  Polyester      Summer
2    Green Leather T-Shirt      1628   Kids   Green    Leather      Summer
3      Yellow Wool T-Shirt     13215  Women  Yellow       Wool      Winter
4     Brown Leather Wallet       887    Men   Brown    Leather      Winter

   StockQty                  AI_Tags       SellerName_y    SellerType  \
0       245   summer, ethnic, casual  Okara Dress House  Local Seller
1       119    formal, party, summer  Okara Dress House  Local Seller
2       229  ethnic, casual, wedding  Okara Dress House  Local Seller
3       461  trendy, casual, wedding          Limelight     Big Brand
4       386    formal, party, winter          Limelight     Big Brand

   Location Verified StoreOnPlatform  Rating
0    Multan      Yes             Yes     4.0
1    Multan      Yes             Yes     4.0
2    Multan      Yes             Yes     4.0
3  Peshawar       No             Yes     4.8
4  Peshawar       No             Yes     4.8

In [5]:
# Step 3.1: Price Buckets
def price_bucket(price):
    if price < 5000:
        return 'Low'
    elif 5000 <= price <= 15000:
        return 'Mid'
    else:
        return 'High'

merged_df['PriceBucket'] = merged_df['PricePKR'].apply(price_bucket)

# Step 3.2: Gender is already in 'Gender'

# Step 3.3: Season & Occasion
# Keep 'Season' and 'AI_Tags' as is, split AI_Tags into a list
merged_df['AI_Tags_List'] = merged_df['AI_Tags'].apply(lambda x: [tag.strip() for tag in x.split(',')])

# Step 3.4: Product Type
merged_df['ProductType'] = merged_df['Category'] + ' - ' + merged_df['SubCategory']

# Preview the enhanced dataset
print(merged_df[['ProductID', 'ProductName', 'PricePKR', 'PriceBucket', 'Gender', 'Season', 'AI_Tags_List', 'ProductType', 'SellerName_y', 'SellerType']].head(10))

  ProductID              ProductName  PricePKR PriceBucket  Gender  \
0     P0001      White Polyester Cap     18057        High     Men
1     P0002  Yellow Polyester Wallet     11044         Mid   Women
2     P0003    Green Leather T-Shirt      1628         Low    Kids
3     P0004      Yellow Wool T-Shirt     13215         Mid   Women
4     P0005     Brown Leather Wallet       887         Low     Men
5     P0006      Blue Linen Earrings     17571        High  Unisex
6     P0007        Green Lawn Hoodie     12948         Mid     Men
7     P0008    Beige Silk Maxi Dress      3152         Low  Unisex
8     P0009          White Silk Belt      5732         Mid     Men
9     P0010       Pink Wool Necklace      3101         Low  Unisex

       Season                AI_Tags_List                  ProductType  \
0  All-season    [summer, ethnic, casual]                 Others - Cap
1      Summer     [formal, party, summer]  Bags & Accessories - Wallet
2      Summer   [ethnic, casual, wedding]       Western Wear - T-Shirt
3      Winter   [trendy, casual, wedding]       Western Wear - T-Shirt
4      Winter     [formal, party, winter]  Bags & Accessories - Wallet
5  All-season   [wedding, casual, ethnic]           Jewelry - Earrings
6      Summer  [western, wedding, formal]        Western Wear - Hoodie
7      Summer   [formal, wedding, summer]    Western Wear - Maxi Dress
8      Summer     [party, summer, winter]    Bags & Accessories - Belt
9  All-season    [ethnic, formal, trendy]           Jewelry - Necklace

              SellerName_y    SellerType
0        Okara Dress House  Local Seller
1        Okara Dress House  Local Seller
2        Okara Dress House  Local Seller
3                Limelight     Big Brand
4                Limelight     Big Brand
5                Limelight     Big Brand
6  Faisalabad Fabric Point  Local Seller
7  Faisalabad Fabric Point  Local Seller
8  Faisalabad Fabric Point  Local Seller
9  Faisalabad Fabric Point  Local Seller

In [6]:
import pandas as pd

# Load datasets
sellers_df = pd.read_csv("FashionHub_sellers_updated.csv")
products_df = pd.read_csv("FashionHub_products_updated.csv")

# Merge on SellerID
merged_df = pd.merge(products_df, sellers_df, on="SellerID", how="left")

# Save merged dataset
merged_df.to_csv("FashionHub_merged.csv", index=False)

print("✅ Merged dataset created and saved as FashionHub_merged.csv")
print("Shape:", merged_df.shape)
print("Columns:", merged_df.columns.tolist())

✅ Merged dataset created and saved as FashionHub_merged.csv
Shape: (1559, 19)
Columns: ['ProductID', 'SellerID', 'SellerName_x', 'Category', 'SubCategory', 'ProductName', 'PricePKR', 'Gender', 'Color', 'Material', 'Season', 'StockQty', 'AI_Tags', 'SellerName_y', 'SellerType', 'Location', 'Verified', 'StoreOnPlatform', 'Rating']

In [7]:
import pandas as pd

# Load merged dataset (you already created this earlier)
merged_df = pd.read_csv("FashionHub_merged.csv")

# ---- AI Stylist: Filter Based ---- #
def ai_stylist(gender=None, price_range=None, occasion=None, season=None, n=5):
    df = merged_df.copy()

    # Filter by gender
    if gender:
        df = df[df["Gender"].str.lower() == gender.lower()]

    # Filter by season
    if season:
        df = df[df["Season"].str.lower() == season.lower()]

    # Filter by occasion (AI_Tags contains multiple tags, so we use "contains")
    if occasion:
        df = df[df["AI_Tags"].str.contains(occasion, case=False, na=False)]

    # Filter by price range
    if price_range == "low":
        df = df[df["PricePKR"] < 5000]
    elif price_range == "mid":
        df = df[(df["PricePKR"] >= 5000) & (df["PricePKR"] <= 12000)]
    elif price_range == "high":
        df = df[df["PricePKR"] > 12000]

    # Random sample of recommendations
    if len(df) > n:
        df = df.sample(n)

    return df[["ProductName", "Category", "SubCategory", "PricePKR", "Gender", "Season", "AI_Tags", "SellerName_x"]]


# ---- Example Usage ---- #
print("🎯 Example 1: Women's Summer Casual Outfit (Mid Price Range)")
print(ai_stylist(gender="Women", price_range="mid", occasion="casual", season="Summer"))

print("\n🎯 Example 2: Men's Wedding Outfit (High Price Range)")
print(ai_stylist(gender="Men", price_range="high", occasion="wedding", season="Winter"))

🎯 Example 1: Women's Summer Casual Outfit (Mid Price Range)
                    ProductName      Category     SubCategory  PricePKR  \
1148         Grey Polyester Cap        Others             Cap     10954
575          Grey Wool Earrings       Jewelry        Earrings     11700
256         Red Cotton Necklace       Jewelry        Necklace     11346
191           Beige Denim Jeans  Western Wear           Jeans     11927
446   Pink Denim Shalwar Kameez  Eastern Wear  Shalwar Kameez      5183

     Gender  Season                 AI_Tags         SellerName_x
1148  Women  Summer   party, casual, winter      StyleHubKarachi
575   Women  Summer  ethnic, formal, casual  Multan Cloth Market
256   Women  Summer  summer, ethnic, casual    Rawalpindi Styles
191   Women  Summer   summer, party, casual           Outfitters
446   Women  Summer  casual, summer, winter         Cross Stitch

🎯 Example 2: Men's Wedding Outfit (High Price Range)
                   ProductName            Category     SubCategory  PricePKR  \
368    Green Polyester T-Shirt        Western Wear         T-Shirt     12698
95           Black Lawn Wallet  Bags & Accessories          Wallet     18891
1180         Pink Leather Ring             Jewelry            Ring     18017
1297        Brown Cotton Abaya        Eastern Wear           Abaya     19894
520   Grey Silk Shalwar Kameez        Eastern Wear  Shalwar Kameez     17375

     Gender  Season                   AI_Tags               SellerName_x
368     Men  Winter    wedding, party, summer       Ethnic by Outfitters
95      Men  Winter   ethnic, wedding, casual            EasternElegance
1180    Men  Winter   winter, wedding, ethnic                 Outfitters
1297    Men  Winter   wedding, winter, trendy  Gujranwala Wardrobe Works
520     Men  Winter  winter, wedding, western       Peshawar Poshak Ghar

In [8]:
import pandas as pd

# Load products dataset
products_df = pd.read_csv("FashionHub_products_updated.csv")

# Function to generate tags
def generate_tags(row):
    tags = []

    # Occasion
    if "Wedding" in row["SubCategory"] or "Shalwar Kameez" in row["SubCategory"] or "Saree" in row["SubCategory"]:
        tags.append("wedding")
    elif row["Category"] in ["Western Wear", "Eastern Wear"]:
        tags.append("casual")
    if "Suit" in row["SubCategory"] or "Blazer" in row["SubCategory"]:
        tags.append("formal")
    if "T-Shirt" in row["SubCategory"] or "Hoodie" in row["SubCategory"]:
        tags.append("trendy")

    # Season
    if row["Season"] in ["Summer", "Winter", "All-season"]:
        tags.append(row["Season"].lower())

    # Style
    if row["Category"] == "Eastern Wear":
        tags.append("ethnic")
    elif row["Category"] == "Western Wear":
        tags.append("western")
    else:
        tags.append("modern")

    # Gender
    tags.append(row["Gender"].lower())

    # Material
    if row["Material"].lower() in ["cotton", "silk", "lawn", "wool", "denim", "polyester", "leather", "linen"]:
        tags.append(row["Material"].lower())

    return ", ".join(sorted(set(tags)))  # remove duplicates + keep tidy

# Apply function
products_df["AI_Tags_Cleaned"] = products_df.apply(generate_tags, axis=1)

# Save updated dataset
products_df.to_csv("FashionHub_products_with_tags.csv", index=False)

# Quick check
print(products_df[["ProductName", "Category", "SubCategory", "Material", "Season", "Gender", "AI_Tags_Cleaned"]].head(10))

               ProductName            Category SubCategory   Material  \
0      White Polyester Cap              Others         Cap  Polyester
1  Yellow Polyester Wallet  Bags & Accessories      Wallet  Polyester
2    Green Leather T-Shirt        Western Wear     T-Shirt    Leather
3      Yellow Wool T-Shirt        Western Wear     T-Shirt       Wool
4     Brown Leather Wallet  Bags & Accessories      Wallet    Leather
5      Blue Linen Earrings             Jewelry    Earrings      Linen
6        Green Lawn Hoodie        Western Wear      Hoodie       Lawn
7    Beige Silk Maxi Dress        Western Wear  Maxi Dress       Silk
8          White Silk Belt  Bags & Accessories        Belt       Silk
9       Pink Wool Necklace             Jewelry    Necklace       Wool

       Season  Gender                                 AI_Tags_Cleaned
0  All-season     Men              all-season, men, modern, polyester
1      Summer   Women                modern, polyester, summer, women
2      Summer    Kids  casual, kids, leather, summer, trendy, western
3      Winter   Women    casual, trendy, western, winter, women, wool
4      Winter     Men                    leather, men, modern, winter
5  All-season  Unisex               all-season, linen, modern, unisex
6      Summer     Men      casual, lawn, men, summer, trendy, western
7      Summer  Unisex           casual, silk, summer, unisex, western
8      Summer     Men                       men, modern, silk, summer
9  All-season  Unisex                all-season, modern, unisex, wool

In [9]:
import pandas as pd

# Load your products dataset
df = pd.read_csv("FashionHub_products_updated.csv")

# --- Tagging function ---
def generate_tags(row):
    tags = []

    # Gender-based
    if pd.notna(row["Gender"]):
        tags.append(row["Gender"].lower())

    # Season-based
    if pd.notna(row["Season"]):
        tags.append(row["Season"].lower())

    # Material-based
    if "leather" in str(row["Material"]).lower():
        tags.append("leather")
    if "wool" in str(row["Material"]).lower():
        tags.append("wool")
    if "linen" in str(row["Material"]).lower():
        tags.append("linen")
    if "silk" in str(row["Material"]).lower():
        tags.append("silk")
    if "lawn" in str(row["Material"]).lower():
        tags.append("lawn")
    if "polyester" in str(row["Material"]).lower():
        tags.append("polyester")

    # Category/Subcategory rules
    if row["Category"] == "Eastern Wear":
        tags.extend(["ethnic", "traditional"])
    if row["Category"] == "Western Wear":
        tags.append("western")
    if row["Category"] == "Jewelry":
        tags.append("trendy")
    if row["Category"] == "Bags & Accessories":
        tags.append("modern")

    # General styles
    if "dress" in str(row["SubCategory"]).lower() or "kameez" in str(row["SubCategory"]).lower():
        tags.append("casual")
    if "hoodie" in str(row["SubCategory"]).lower():
        tags.append("trendy")
    if "saree" in str(row["SubCategory"]).lower():
        tags.append("formal")

    # Remove duplicates
    return ", ".join(sorted(set(tags)))


# Apply function
df["AI_Tags_Cleaned"] = df.apply(generate_tags, axis=1)

# Save new dataset
df.to_csv("FashionHub_products_tagged.csv", index=False)

print("✅ File saved as FashionHub_products_tagged.csv with cleaned tags.")

✅ File saved as FashionHub_products_tagged.csv with cleaned tags.

In [10]:
import pandas as pd

# Load the newly tagged dataset
df_tagged = pd.read_csv("FashionHub_products_tagged.csv")

# Show first 15 rows
print(df_tagged.head(15))

   ProductID SellerID               SellerName            Category  \
0      P0001     S001        Okara Dress House              Others
1      P0002     S001        Okara Dress House  Bags & Accessories
2      P0003     S001        Okara Dress House        Western Wear
3      P0004     S002                Limelight        Western Wear
4      P0005     S002                Limelight  Bags & Accessories
5      P0006     S002                Limelight             Jewelry
6      P0007     S003  Faisalabad Fabric Point        Western Wear
7      P0008     S003  Faisalabad Fabric Point        Western Wear
8      P0009     S003  Faisalabad Fabric Point  Bags & Accessories
9      P0010     S003  Faisalabad Fabric Point             Jewelry
10     P0011     S003  Faisalabad Fabric Point        Eastern Wear
11     P0012     S004   Karachi Bazaar Fashion        Western Wear
12     P0013     S004   Karachi Bazaar Fashion               Shoes
13     P0014     S005       Chiniot Cloth Mart  Bags & Accessories
14     P0015     S005       Chiniot Cloth Mart  Bags & Accessories

   SubCategory              ProductName  PricePKR  Gender   Color   Material  \
0          Cap      White Polyester Cap     18057     Men   White  Polyester
1       Wallet  Yellow Polyester Wallet     11044   Women  Yellow  Polyester
2      T-Shirt    Green Leather T-Shirt      1628    Kids   Green    Leather
3      T-Shirt      Yellow Wool T-Shirt     13215   Women  Yellow       Wool
4       Wallet     Brown Leather Wallet       887     Men   Brown    Leather
5     Earrings      Blue Linen Earrings     17571  Unisex    Blue      Linen
6       Hoodie        Green Lawn Hoodie     12948     Men   Green       Lawn
7   Maxi Dress    Beige Silk Maxi Dress      3152  Unisex   Beige       Silk
8         Belt          White Silk Belt      5732     Men   White       Silk
9     Necklace       Pink Wool Necklace      3101  Unisex    Pink       Wool
10       Abaya         Black Wool Abaya     15601   Women   Black       Wool
11     T-Shirt     White Cotton T-Shirt     18834     Men   White     Cotton
12     Sandals  Beige Polyester Sandals      9380  Unisex   Beige  Polyester
13      Wallet       White Denim Wallet     10394   Women   White      Denim
14      Wallet     Brown Leather Wallet      2931     Men   Brown    Leather

        Season  StockQty                   AI_Tags  \
0   All-season       245    summer, ethnic, casual
1       Summer       119     formal, party, summer
2       Summer       229   ethnic, casual, wedding
3       Winter       461   trendy, casual, wedding
4       Winter       386     formal, party, winter
5   All-season       389   wedding, casual, ethnic
6       Summer       179  western, wedding, formal
7       Summer        97   formal, wedding, summer
8       Summer       453     party, summer, winter
9   All-season       286    ethnic, formal, trendy
10  All-season        53   summer, winter, western
11      Winter        88    winter, casual, formal
12  All-season        80    formal, party, wedding
13      Winter       255   formal, casual, wedding
14  All-season       167     party, formal, ethnic

                                 AI_Tags_Cleaned
0                     all-season, men, polyester
1               modern, polyester, summer, women
2                 kids, leather, summer, western
3                   western, winter, women, wool
4                   leather, men, modern, winter
5              all-season, linen, trendy, unisex
6             lawn, men, summer, trendy, western
7          casual, silk, summer, unisex, western
8                      men, modern, silk, summer
9               all-season, trendy, unisex, wool
10  all-season, ethnic, traditional, women, wool
11                          men, western, winter
12                 all-season, polyester, unisex
13                         modern, winter, women
14              all-season, leather, men, modern

In [11]:
import pandas as pd

# Load your cleaned product dataset
df = pd.read_csv("FashionHub_products_updated.csv")

# Random sample of 20 products for validation
sample_df = df.sample(20, random_state=42)  # fixed seed for reproducibility

# Display the sample
sample_df[['ProductID','SellerName','Category','SubCategory','ProductName','PricePKR',
           'Gender','Material','Season','AI_Tags']]

,ProductID,SellerName,Category,SubCategory,ProductName,PricePKR,Gender,Material,Season,AI_Tags
1524,P1525,StyleHubKarachi,Eastern Wear,Saree,Beige Cotton Saree,17133,Men,Cotton,Winter,"winter, formal, trendy"
1483,P1484,Alkaram Studio,Jewelry,Bracelet,Green Silk Bracelet,8705,Unisex,Silk,Winter,"winter, trendy, wedding"
354,P0355,Ethnic by Outfitters,Jewelry,Bracelet,Grey Cotton Bracelet,9660,Unisex,Cotton,Winter,"western, party, formal"
668,P0669,Cross Stitch,Western Wear,Jeans,Green Silk Jeans,2202,Kids,Silk,Winter,"party, casual, summer"
1422,P1423,Ideas by Gul Ahmed,Jewelry,Earrings,Pink Silk Earrings,2391,Kids,Silk,Summer,"casual, formal, party"
244,P0245,Rawalpindi Styles,Western Wear,T-Shirt,Grey Polyester T-Shirt,17128,Women,Polyester,Summer,"formal, casual, party"
59,P0060,Outfitters,Jewelry,Necklace,Red Polyester Necklace,4905,Men,Polyester,All-season,"wedding, western, party"
597,P0598,Outfitters,Western Wear,Hoodie,Brown Linen Hoodie,19546,Unisex,Linen,Summer,"ethnic, winter, wedding"
237,P0238,OutfitObsession,Eastern Wear,Saree,Red Polyester Saree,13954,Men,Polyester,Summer,"casual, western, trendy"
500,P0501,Ideas by Gul Ahmed,Eastern Wear,Abaya,Black Wool Abaya,1799,Kids,Wool,Summer,"trendy, summer, western"
30,P0031,ModishMoods,Jewelry,Bracelet,Pink Polyester Bracelet,6659,Men,Polyester,Summer,"winter, western, party"
352,P0353,Ethnic by Outfitters,Eastern Wear,Saree,Yellow Cotton Saree,12490,Kids,Cotton,All-season,"wedding, summer, winter"
859,P0860,Okara Dress House,Eastern Wear,Saree,Pink Wool Saree,14100,Women,Wool,Summer,"summer, ethnic, trendy"
1528,P1529,GlamCartPK,Western Wear,Maxi Dress,Beige Cotton Maxi Dress,18140,Unisex,Cotton,Summer,"trendy, formal, western"
1553,P1554,KurtiCraze,Bags & Accessories,Handbag,Blue Denim Handbag,549,Kids,Denim,All-season,"western, wedding, party"
303,P0304,Ethnic by Outfitters,Bags & Accessories,Handbag,Grey Polyester Handbag,2952,Unisex,Polyester,Summer,"party, winter, trendy"
481,P0482,TheFashionRack,Jewelry,Ring,Grey Leather Ring,6695,Kids,Leather,Summer,"trendy, formal, wedding"
1048,P1049,TheFashionRack,Eastern Wear,Abaya,Pink Lawn Abaya,1623,Women,Lawn,Winter,"wedding, trendy, winter"
1510,P1511,Gujranwala Wardrobe Works,Jewelry,Necklace,Pink Leather Necklace,9386,Men,Leather,Winter,"winter, party, trendy"
518,P0519,Alkaram Studio,Western Wear,Maxi Dress,Blue Denim Maxi Dress,10833,Men,Denim,Winter,"party, trendy, summer"

In [12]:
import pandas as pd

# Load your cleaned product dataset
df = pd.read_csv("FashionHub_products_updated.csv")

# --- Step 1: Define the cleaning function ---
def clean_ai_tags(tags):
    if pd.isna(tags):
        return ""
    
    # Split by comma, strip spaces, make lowercase
    tag_list = [t.strip().lower() for t in tags.split(",")]
    
    # Remove duplicates while keeping order
    seen = set()
    cleaned = []
    for tag in tag_list:
        if tag not in seen and tag != "":
            cleaned.append(tag)
            seen.add(tag)
    
    # Join back
    return ", ".join(cleaned)

# --- Step 2: Apply cleaning ---
df["AI_Tags_Cleaned"] = df["AI_Tags"].apply(clean_ai_tags)

# --- Step 3: Random sample of 20 products for validation ---
sample_df = df.sample(20, random_state=42)

# --- Step 4: Display only important columns ---
print(sample_df[['ProductID','SellerName','Category','SubCategory',
                 'ProductName','PricePKR','Gender','Material','Season',
                 'AI_Tags','AI_Tags_Cleaned']])

     ProductID                 SellerName            Category SubCategory  \
1524     P1525            StyleHubKarachi        Eastern Wear       Saree
1483     P1484             Alkaram Studio             Jewelry    Bracelet
354      P0355       Ethnic by Outfitters             Jewelry    Bracelet
668      P0669               Cross Stitch        Western Wear       Jeans
1422     P1423         Ideas by Gul Ahmed             Jewelry    Earrings
244      P0245          Rawalpindi Styles        Western Wear     T-Shirt
59       P0060                 Outfitters             Jewelry    Necklace
597      P0598                 Outfitters        Western Wear      Hoodie
237      P0238            OutfitObsession        Eastern Wear       Saree
500      P0501         Ideas by Gul Ahmed        Eastern Wear       Abaya
30       P0031                ModishMoods             Jewelry    Bracelet
352      P0353       Ethnic by Outfitters        Eastern Wear       Saree
859      P0860          Okara Dress House        Eastern Wear       Saree
1528     P1529                 GlamCartPK        Western Wear  Maxi Dress
1553     P1554                 KurtiCraze  Bags & Accessories     Handbag
303      P0304       Ethnic by Outfitters  Bags & Accessories     Handbag
481      P0482             TheFashionRack             Jewelry        Ring
1048     P1049             TheFashionRack        Eastern Wear       Abaya
1510     P1511  Gujranwala Wardrobe Works             Jewelry    Necklace
518      P0519             Alkaram Studio        Western Wear  Maxi Dress

                  ProductName  PricePKR  Gender   Material      Season  \
1524       Beige Cotton Saree     17133     Men     Cotton      Winter
1483      Green Silk Bracelet      8705  Unisex       Silk      Winter
354      Grey Cotton Bracelet      9660  Unisex     Cotton      Winter
668          Green Silk Jeans      2202    Kids       Silk      Winter
1422       Pink Silk Earrings      2391    Kids       Silk      Summer
244    Grey Polyester T-Shirt     17128   Women  Polyester      Summer
59     Red Polyester Necklace      4905     Men  Polyester  All-season
597        Brown Linen Hoodie     19546  Unisex      Linen      Summer
237       Red Polyester Saree     13954     Men  Polyester      Summer
500          Black Wool Abaya      1799    Kids       Wool      Summer
30    Pink Polyester Bracelet      6659     Men  Polyester      Summer
352       Yellow Cotton Saree     12490    Kids     Cotton  All-season
859           Pink Wool Saree     14100   Women       Wool      Summer
1528  Beige Cotton Maxi Dress     18140  Unisex     Cotton      Summer
1553       Blue Denim Handbag       549    Kids      Denim  All-season
303    Grey Polyester Handbag      2952  Unisex  Polyester      Summer
481         Grey Leather Ring      6695    Kids    Leather      Summer
1048          Pink Lawn Abaya      1623   Women       Lawn      Winter
1510    Pink Leather Necklace      9386     Men    Leather      Winter
518     Blue Denim Maxi Dress     10833     Men      Denim      Winter

                      AI_Tags          AI_Tags_Cleaned
1524   winter, formal, trendy   winter, formal, trendy
1483  winter, trendy, wedding  winter, trendy, wedding
354    western, party, formal   western, party, formal
668     party, casual, summer    party, casual, summer
1422    casual, formal, party    casual, formal, party
244     formal, casual, party    formal, casual, party
59    wedding, western, party  wedding, western, party
597   ethnic, winter, wedding  ethnic, winter, wedding
237   casual, western, trendy  casual, western, trendy
500   trendy, summer, western  trendy, summer, western
30     winter, western, party   winter, western, party
352   wedding, summer, winter  wedding, summer, winter
859    summer, ethnic, trendy   summer, ethnic, trendy
1528  trendy, formal, western  trendy, formal, western
1553  western, wedding, party  western, wedding, party
303     party, winter, trendy    party, winter, trendy
481   trendy, formal, wedding  trendy, formal, wedding
1048  wedding, trendy, winter  wedding, trendy, winter
1510    winter, party, trendy    winter, party, trendy
518     party, trendy, summer    party, trendy, summer

In [13]:
import pandas as pd

# Load dataset
df = pd.read_csv("FashionHub_products_updated.csv")

# --- Rule-based Gender Correction ---
def fix_gender(row):
    subcat = row['SubCategory'].lower()
    gender = row['Gender']

    # Eastern Wear rules
    if subcat in ['saree', 'lehenga', 'kurti', 'abaya', 'dupatta']:
        return 'Women'
    # Jewelry rules (usually unisex, but not kids-only)
    elif subcat in ['necklace', 'ring', 'bracelet', 'earrings']:
        return 'Unisex'
    # Bags & Accessories
    elif subcat in ['handbag', 'wallet', 'belt']:
        return 'Unisex'
    # Shoes (sandals, heels, sneakers)
    elif subcat in ['sandals', 'heels']:
        return 'Women'
    elif subcat in ['sneakers', 'shoes']:
        return 'Men'
    # Western Wear rules
    elif subcat in ['t-shirt', 'jeans', 'hoodie', 'maxi dress']:
        if subcat == 'maxi dress':
            return 'Women'
        else:
            return 'Men' if gender == 'Men' else 'Unisex'
    # Default keep existing
    else:
        return gender

# Apply corrections
df['Corrected_Gender'] = df.apply(fix_gender, axis=1)

# Save corrected dataset
df.to_csv("FashionHub_products_corrected.csv", index=False)

# Show sample of corrected records
print(df[['ProductID','SellerName','Category','SubCategory','ProductName','Gender','Corrected_Gender']].sample(20, random_state=42))

     ProductID                 SellerName            Category SubCategory  \
1524     P1525            StyleHubKarachi        Eastern Wear       Saree
1483     P1484             Alkaram Studio             Jewelry    Bracelet
354      P0355       Ethnic by Outfitters             Jewelry    Bracelet
668      P0669               Cross Stitch        Western Wear       Jeans
1422     P1423         Ideas by Gul Ahmed             Jewelry    Earrings
244      P0245          Rawalpindi Styles        Western Wear     T-Shirt
59       P0060                 Outfitters             Jewelry    Necklace
597      P0598                 Outfitters        Western Wear      Hoodie
237      P0238            OutfitObsession        Eastern Wear       Saree
500      P0501         Ideas by Gul Ahmed        Eastern Wear       Abaya
30       P0031                ModishMoods             Jewelry    Bracelet
352      P0353       Ethnic by Outfitters        Eastern Wear       Saree
859      P0860          Okara Dress House        Eastern Wear       Saree
1528     P1529                 GlamCartPK        Western Wear  Maxi Dress
1553     P1554                 KurtiCraze  Bags & Accessories     Handbag
303      P0304       Ethnic by Outfitters  Bags & Accessories     Handbag
481      P0482             TheFashionRack             Jewelry        Ring
1048     P1049             TheFashionRack        Eastern Wear       Abaya
1510     P1511  Gujranwala Wardrobe Works             Jewelry    Necklace
518      P0519             Alkaram Studio        Western Wear  Maxi Dress

                  ProductName  Gender Corrected_Gender
1524       Beige Cotton Saree     Men            Women
1483      Green Silk Bracelet  Unisex           Unisex
354      Grey Cotton Bracelet  Unisex           Unisex
668          Green Silk Jeans    Kids           Unisex
1422       Pink Silk Earrings    Kids           Unisex
244    Grey Polyester T-Shirt   Women           Unisex
59     Red Polyester Necklace     Men           Unisex
597        Brown Linen Hoodie  Unisex           Unisex
237       Red Polyester Saree     Men            Women
500          Black Wool Abaya    Kids            Women
30    Pink Polyester Bracelet     Men           Unisex
352       Yellow Cotton Saree    Kids            Women
859           Pink Wool Saree   Women            Women
1528  Beige Cotton Maxi Dress  Unisex            Women
1553       Blue Denim Handbag    Kids           Unisex
303    Grey Polyester Handbag  Unisex           Unisex
481         Grey Leather Ring    Kids           Unisex
1048          Pink Lawn Abaya   Women            Women
1510    Pink Leather Necklace     Men           Unisex
518     Blue Denim Maxi Dress     Men            Women

In [14]:
import pandas as pd

# Load your dataset
df = pd.read_csv("FashionHub_products_updated.csv")

# Define mapping to correct genders
gender_map = {
    'Men': 'Unisex',
    'Women': 'Women',
    'Kids': 'Unisex',
    'Unisex': 'Unisex'
}

# Create Corrected_Gender column
df['Corrected_Gender'] = df['Gender'].map(gender_map)

# Function to update AI_Tags with corrected gender
def update_gender_in_tags(row):
    tags = row['AI_Tags'].split(', ')
    # Remove old gender tags
    tags = [t for t in tags if t.lower() not in ['men','women','kids','unisex']]
    # Add corrected gender
    tags.append(row['Corrected_Gender'].lower())
    return ', '.join(tags)

# Update AI_Tags_Cleaned
df['AI_Tags_Cleaned'] = df.apply(update_gender_in_tags, axis=1)

# Save updated dataset
df.to_csv("FashionHub_products_gender_cleaned.csv", index=False)

In [15]:
# Display a random sample of 10 rows to verify changes
sample_df = df.sample(10, random_state=42)
print(sample_df[['ProductID','SellerName','Category','SubCategory','ProductName',
                 'PricePKR','Gender','Corrected_Gender','Season','AI_Tags','AI_Tags_Cleaned']])

     ProductID            SellerName      Category SubCategory  \
1524     P1525       StyleHubKarachi  Eastern Wear       Saree
1483     P1484        Alkaram Studio       Jewelry    Bracelet
354      P0355  Ethnic by Outfitters       Jewelry    Bracelet
668      P0669          Cross Stitch  Western Wear       Jeans
1422     P1423    Ideas by Gul Ahmed       Jewelry    Earrings
244      P0245     Rawalpindi Styles  Western Wear     T-Shirt
59       P0060            Outfitters       Jewelry    Necklace
597      P0598            Outfitters  Western Wear      Hoodie
237      P0238       OutfitObsession  Eastern Wear       Saree
500      P0501    Ideas by Gul Ahmed  Eastern Wear       Abaya

                 ProductName  PricePKR  Gender Corrected_Gender      Season  \
1524      Beige Cotton Saree     17133     Men           Unisex      Winter
1483     Green Silk Bracelet      8705  Unisex           Unisex      Winter
354     Grey Cotton Bracelet      9660  Unisex           Unisex      Winter
668         Green Silk Jeans      2202    Kids           Unisex      Winter
1422      Pink Silk Earrings      2391    Kids           Unisex      Summer
244   Grey Polyester T-Shirt     17128   Women            Women      Summer
59    Red Polyester Necklace      4905     Men           Unisex  All-season
597       Brown Linen Hoodie     19546  Unisex           Unisex      Summer
237      Red Polyester Saree     13954     Men           Unisex      Summer
500         Black Wool Abaya      1799    Kids           Unisex      Summer

                      AI_Tags                  AI_Tags_Cleaned
1524   winter, formal, trendy   winter, formal, trendy, unisex
1483  winter, trendy, wedding  winter, trendy, wedding, unisex
354    western, party, formal   western, party, formal, unisex
668     party, casual, summer    party, casual, summer, unisex
1422    casual, formal, party    casual, formal, party, unisex
244     formal, casual, party     formal, casual, party, women
59    wedding, western, party  wedding, western, party, unisex
597   ethnic, winter, wedding  ethnic, winter, wedding, unisex
237   casual, western, trendy  casual, western, trendy, unisex
500   trendy, summer, western  trendy, summer, western, unisex

In [16]:
import pandas as pd

# Load your dataset
df = pd.read_csv("FashionHub_products_updated.csv")

# ---- Column Cleaning Function ---- #
def clean_columns(df):
    # Strip whitespace and standardize capitalization
    for col in ['Category', 'SubCategory', 'Material', 'Season', 'Gender']:
        df[col] = df[col].astype(str).str.strip().str.title()
    
    # Standardize Material names
    material_map = {
        'Cottn': 'Cotton',
        'Silkk': 'Silk',
        'Polyester ': 'Polyester',
        'Leather ': 'Leather',
        'Wool ': 'Wool',
        'Denim ': 'Denim',
        'Linen ': 'Linen'
    }
    df['Material'] = df['Material'].replace(material_map)
    
    # Standardize Season
    season_map = {
        'Summer ': 'Summer',
        'Winter ': 'Winter',
        'All season': 'All-season',
        'All season ': 'All-season'
    }
    df['Season'] = df['Season'].replace(season_map)
    
    # Replace Gender with Corrected_Gender if exists
    if 'Corrected_Gender' in df.columns:
        df['Gender'] = df['Corrected_Gender'].astype(str).str.strip().str.title()
    
    # Update AI_Tags_Cleaned: add corrected gender
    def update_tags(row):
        tags = row['AI_Tags'].split(',') if pd.notna(row['AI_Tags']) else []
        # Remove existing gender tags
        tags = [t.strip().lower() for t in tags if t.strip().lower() not in ['men','women','kids','unisex']]
        # Add corrected gender
        tags.append(row['Gender'].lower())
        return ', '.join(tags)
    
    df['AI_Tags_Cleaned'] = df.apply(update_tags, axis=1)
    
    return df

# Apply cleaning
df_cleaned = clean_columns(df)

# Save cleaned dataset
df_cleaned.to_csv("FashionHub_products_cleaned.csv", index=False)

# Display sample
sample_df = df_cleaned.sample(10, random_state=42)
sample_df[['ProductID','SellerName','Category','SubCategory','ProductName','PricePKR','Gender','Material','Season','AI_Tags_Cleaned']]

,ProductID,SellerName,Category,SubCategory,ProductName,PricePKR,Gender,Material,Season,AI_Tags_Cleaned
1524,P1525,StyleHubKarachi,Eastern Wear,Saree,Beige Cotton Saree,17133,Men,Cotton,Winter,"winter, formal, trendy, men"
1483,P1484,Alkaram Studio,Jewelry,Bracelet,Green Silk Bracelet,8705,Unisex,Silk,Winter,"winter, trendy, wedding, unisex"
354,P0355,Ethnic by Outfitters,Jewelry,Bracelet,Grey Cotton Bracelet,9660,Unisex,Cotton,Winter,"western, party, formal, unisex"
668,P0669,Cross Stitch,Western Wear,Jeans,Green Silk Jeans,2202,Kids,Silk,Winter,"party, casual, summer, kids"
1422,P1423,Ideas by Gul Ahmed,Jewelry,Earrings,Pink Silk Earrings,2391,Kids,Silk,Summer,"casual, formal, party, kids"
244,P0245,Rawalpindi Styles,Western Wear,T-Shirt,Grey Polyester T-Shirt,17128,Women,Polyester,Summer,"formal, casual, party, women"
59,P0060,Outfitters,Jewelry,Necklace,Red Polyester Necklace,4905,Men,Polyester,All-Season,"wedding, western, party, men"
597,P0598,Outfitters,Western Wear,Hoodie,Brown Linen Hoodie,19546,Unisex,Linen,Summer,"ethnic, winter, wedding, unisex"
237,P0238,OutfitObsession,Eastern Wear,Saree,Red Polyester Saree,13954,Men,Polyester,Summer,"casual, western, trendy, men"
500,P0501,Ideas by Gul Ahmed,Eastern Wear,Abaya,Black Wool Abaya,1799,Kids,Wool,Summer,"trendy, summer, western, kids"

In [17]:
duplicate_products = df[df.duplicated(subset='ProductID', keep=False)]
duplicate_products

Empty DataFrame
Columns: [ProductID, SellerID, SellerName, Category, SubCategory, ProductName, PricePKR, Gender, Color, Material, Season, StockQty, AI_Tags, AI_Tags_Cleaned]
Index: []

In [18]:
missing_values = df.isnull().sum()
missing_values

ProductID          0
SellerID           0
SellerName         0
Category           0
SubCategory        0
ProductName        0
PricePKR           0
Gender             0
Color              0
Material           0
Season             0
StockQty           0
AI_Tags            0
AI_Tags_Cleaned    0
dtype: int64

In [19]:
# Assuming seller_df is loaded
missing_sellers = df[~df['SellerName'].isin(sellers_df['SellerName'])]
missing_sellers

Empty DataFrame
Columns: [ProductID, SellerID, SellerName, Category, SubCategory, ProductName, PricePKR, Gender, Color, Material, Season, StockQty, AI_Tags, AI_Tags_Cleaned]
Index: []

In [20]:
duplicates = df[df.duplicated(subset='ProductID', keep=False)]
duplicates

Empty DataFrame
Columns: [ProductID, SellerID, SellerName, Category, SubCategory, ProductName, PricePKR, Gender, Color, Material, Season, StockQty, AI_Tags, AI_Tags_Cleaned]
Index: []

In [21]:
missing_sellers = df[df['SellerName'].isnull() | df['SellerID'].isnull()]
missing_sellers

Empty DataFrame
Columns: [ProductID, SellerID, SellerName, Category, SubCategory, ProductName, PricePKR, Gender, Color, Material, Season, StockQty, AI_Tags, AI_Tags_Cleaned]
Index: []

In [22]:
# Check if Gender/Season/Material are correctly reflected in AI_Tags_Cleaned
df[['Gender', 'Season', 'Material', 'AI_Tags_Cleaned']].head(20)

    Gender      Season   Material                  AI_Tags_Cleaned
0      Men  All-Season  Polyester      summer, ethnic, casual, men
1    Women      Summer  Polyester     formal, party, summer, women
2     Kids      Summer    Leather    ethnic, casual, wedding, kids
3    Women      Winter       Wool   trendy, casual, wedding, women
4      Men      Winter    Leather       formal, party, winter, men
5   Unisex  All-Season      Linen  wedding, casual, ethnic, unisex
6      Men      Summer       Lawn    western, wedding, formal, men
7   Unisex      Summer       Silk  formal, wedding, summer, unisex
8      Men      Summer       Silk       party, summer, winter, men
9   Unisex  All-Season       Wool   ethnic, formal, trendy, unisex
10   Women  All-Season       Wool   summer, winter, western, women
11     Men      Winter     Cotton      winter, casual, formal, men
12  Unisex  All-Season  Polyester   formal, party, wedding, unisex
13   Women      Winter      Denim   formal, casual, wedding, women
14     Men  All-Season    Leather       party, formal, ethnic, men
15     Men      Winter  Polyester     summer, casual, western, men
16   Women  All-Season  Polyester   western, ethnic, winter, women
17    Kids      Summer      Linen    western, formal, summer, kids
18   Women  All-Season  Polyester    wedding, summer, party, women
19    Kids      Summer     Cotton    formal, ethnic, wedding, kids

In [23]:
import pandas as pd

# Load the cleaned product dataset
df = pd.read_csv("FashionHub_products_updated.csv")

def ai_stylist(gender=None, season=None, occasion=None, price_range=None, n=5):
    """
    Recommend products based on AI stylist logic.
    
    Parameters:
    - gender: 'Men', 'Women', 'Kids', 'Unisex' (string)
    - season: 'Summer', 'Winter', 'All-season' (string)
    - occasion: e.g., 'wedding', 'casual', 'party', 'formal' (string)
    - price_range: tuple(min_price, max_price)
    - n: number of products to recommend
    
    Returns:
    - DataFrame of recommended products
    """
    df_filtered = df.copy()
    
    # Gender filter
    if gender:
        df_filtered = df_filtered[df_filtered['Gender'].str.lower() == gender.lower()]
    
    # Season filter
    if season:
        df_filtered = df_filtered[df_filtered['Season'].str.lower() == season.lower()]
    
    # Occasion filter (check if occasion tag exists in AI_Tags_Cleaned)
    if occasion:
        df_filtered = df_filtered[df_filtered['AI_Tags'].str.contains(occasion, case=False, na=False)]
    
    # Price range filter
    if price_range:
        min_price, max_price = price_range
        df_filtered = df_filtered[(df_filtered['PricePKR'] >= min_price) & (df_filtered['PricePKR'] <= max_price)]
    
    # Randomize and select top N products
    recommendations = df_filtered.sample(n=min(n, len(df_filtered)), random_state=42)
    
    return recommendations[['ProductID','SellerName','Category','SubCategory','ProductName','PricePKR','Gender','Material','Season','AI_Tags']]

# Example usage
# Recommend 5 products for Women in Summer for casual occasion priced 1000-15000 PKR
sample_recommendations = ai_stylist(gender='Women', season='Summer', occasion='casual', price_range=(1000,15000), n=5)

print(sample_recommendations)

     ProductID         SellerName            Category SubCategory  \
341      P0342    EasternElegance  Bags & Accessories    Backpack
1409     P1410    StyleHubKarachi               Shoes     Sandals
312      P0313  Rawalpindi Styles               Shoes       Heels
1053     P1054             Khaadi  Bags & Accessories     Handbag
29       P0030        ModishMoods             Jewelry        Ring

              ProductName  PricePKR Gender Material  Season  \
341    Pink Lawn Backpack      2259  Women     Lawn  Summer
1409  Brown Linen Sandals     10953  Women    Linen  Summer
312       Pink Silk Heels     13155  Women     Silk  Summer
1053   Black Lawn Handbag      7525  Women     Lawn  Summer
29      Pink Leather Ring      9237  Women  Leather  Summer

                      AI_Tags
341    ethnic, formal, casual
1409    party, casual, trendy
312   western, trendy, casual
1053   winter, casual, ethnic
29      party, casual, formal

In [24]:
import pandas as pd

# Load your dataset
df = pd.read_csv("FashionHub_products_updated.csv")

# If you have a corrected gender column, use it; otherwise, fix using rules
# Example rule: Kids → Unisex, Men/Women → keep or adjust
def correct_gender(gender):
    if gender in ['Men', 'Women']:
        return gender
    elif gender == 'Kids':
        return 'Unisex'
    else:
        return 'Unisex'

df['Corrected_Gender'] = df['Gender'].apply(correct_gender)

# Function to create AI_Tags_Cleaned
def create_clean_tags(row):
    tags = []
    # Original tags
    if pd.notnull(row['AI_Tags']):
        tags += [t.strip().lower() for t in row['AI_Tags'].split(',')]
    # Add corrected gender
    tags.append(row['Corrected_Gender'].lower())
    # Add season
    tags.append(row['Season'].lower())
    # Remove duplicates
    tags = list(dict.fromkeys(tags))
    return ', '.join(tags)

df['AI_Tags_Cleaned'] = df.apply(create_clean_tags, axis=1)

# Save the cleaned dataset
df.to_csv("FashionHub_products_cleaned.csv", index=False)

In [25]:
# Display first 10 rows of AI_Tags_Cleaned
print(df[['ProductID', 'AI_Tags_Cleaned']].head(10))

# Check unique tags in the dataset
all_tags = df['AI_Tags_Cleaned'].str.split(', ').explode().unique()
print("All unique tags:", all_tags)

# Test filtering by a tag, e.g., 'summer'
summer_products = df[df['AI_Tags_Cleaned'].str.contains('summer', case=False, na=False)]
print("Products tagged with 'summer':")
print(summer_products[['ProductID', 'ProductName', 'AI_Tags_Cleaned']])

  ProductID                              AI_Tags_Cleaned
0     P0001      summer, ethnic, casual, men, all-season
1     P0002                 formal, party, summer, women
2     P0003      ethnic, casual, wedding, unisex, summer
3     P0004       trendy, casual, wedding, women, winter
4     P0005                   formal, party, winter, men
5     P0006  wedding, casual, ethnic, unisex, all-season
6     P0007        western, wedding, formal, men, summer
7     P0008              formal, wedding, summer, unisex
8     P0009                   party, summer, winter, men
9     P0010   ethnic, formal, trendy, unisex, all-season
All unique tags: ['summer' 'ethnic' 'casual' 'men' 'all-season' 'formal' 'party' 'women'
 'wedding' 'unisex' 'trendy' 'winter' 'western']
Products tagged with 'summer':
     ProductID              ProductName  \
0        P0001      White Polyester Cap
1        P0002  Yellow Polyester Wallet
2        P0003    Green Leather T-Shirt
6        P0007        Green Lawn Hoodie
7        P0008    Beige Silk Maxi Dress
...        ...                      ...
1551     P1552      Pink Polyester Ring
1552     P1553      Beige Silk Earrings
1554     P1555        Pink Linen Hoodie
1555     P1556        Red Silk Bracelet
1558     P1559      Brown Silk Sneakers

                              AI_Tags_Cleaned
0     summer, ethnic, casual, men, all-season
1                formal, party, summer, women
2     ethnic, casual, wedding, unisex, summer
6       western, wedding, formal, men, summer
7             formal, wedding, summer, unisex
...                                       ...
1551    ethnic, trendy, winter, women, summer
1552     ethnic, summer, wedding, men, winter
1554  summer, wedding, ethnic, unisex, winter
1555    party, trendy, winter, unisex, summer
1558  casual, western, wedding, women, summer

[892 rows x 3 columns]

In [26]:
# Example: filter for Women, Summer, casual occasion
gender_filter = 'women'
season_filter = 'summer'
occasion_filter = 'casual'

# Filter the dataset
filtered_products = df[
    df['AI_Tags_Cleaned'].str.contains(gender_filter, case=False, na=False) &
    df['AI_Tags_Cleaned'].str.contains(season_filter, case=False, na=False) &
    df['AI_Tags_Cleaned'].str.contains(occasion_filter, case=False, na=False)
]

# Display filtered products
print(f"Number of products matching filters: {len(filtered_products)}")
filtered_products[['ProductID','ProductName','Gender','Season','AI_Tags_Cleaned']]

Number of products matching filters: 71

,ProductID,ProductName,Gender,Season,AI_Tags_Cleaned
22,P0023,Blue Denim Scarf,Women,Summer,"western, ethnic, casual, women, summer"
29,P0030,Pink Leather Ring,Women,Summer,"party, casual, formal, women, summer"
60,P0061,Red Wool Jeans,Women,All-season,"casual, summer, wedding, women, all-season"
78,P0079,Beige Wool Formal Shirt,Women,Summer,"ethnic, western, casual, women, summer"
80,P0081,Green Cotton Hoodie,Women,Summer,"ethnic, casual, wedding, women, summer"
...,...,...,...,...,...
1488,P1489,Red Lawn Handbag,Women,Winter,"casual, summer, western, women, winter"
1500,P1501,Black Cotton Abaya,Women,All-season,"formal, casual, summer, women, all-season"
1513,P1514,Blue Lawn Necklace,Women,All-season,"trendy, summer, casual, women, all-season"
1531,P1532,White Denim Saree,Women,Summer,"formal, wedding, casual, women, summer"
1558,P1559,Brown Silk Sneakers,Women,Summer,"casual, western, wedding, women, summer"

In [27]:
import pandas as pd

# Load the cleaned dataset
df = pd.read_csv("FashionHub_products_cleaned.csv")

def ai_stylist_phase1(gender=None, season=None, occasion=None, price_range=None, n=5):
    """
    Phase 1 AI Stylist: Simple product filter based on tags and price.

    Parameters:
    - gender: 'Men', 'Women', 'Unisex' (string)
    - season: 'Summer', 'Winter', 'All-season' (string)
    - occasion: e.g., 'wedding', 'casual', 'party' (string)
    - price_range: tuple (min_price, max_price)
    - n: number of products to recommend

    Returns:
    - DataFrame of filtered products
    """
    df_filtered = df.copy()

    # Gender filter
    if gender:
        df_filtered = df_filtered[df_filtered['AI_Tags_Cleaned'].str.contains(gender, case=False, na=False)]

    # Season filter
    if season:
        df_filtered = df_filtered[df_filtered['AI_Tags_Cleaned'].str.contains(season, case=False, na=False)]

    # Occasion filter
    if occasion:
        df_filtered = df_filtered[df_filtered['AI_Tags_Cleaned'].str.contains(occasion, case=False, na=False)]

    # Price range filter
    if price_range:
        min_price, max_price = price_range
        df_filtered = df_filtered[(df_filtered['PricePKR'] >= min_price) & (df_filtered['PricePKR'] <= max_price)]

    # Randomize and select top N
    recommendations = df_filtered.sample(n=min(n, len(df_filtered)), random_state=42)

    # Return key columns
    return recommendations[['ProductID','SellerName','Category','SubCategory','ProductName','PricePKR','Gender','Material','Season','AI_Tags_Cleaned']]

# ---- Example Usage ---- #
sample_recommendations = ai_stylist_phase1(
    gender='Women',
    season='Summer',
    occasion='casual',
    price_range=(1000, 15000),
    n=5
)

print(sample_recommendations)

     ProductID               SellerName      Category SubCategory  \
1323     P1324          TrendyThreadsPK         Shoes       Heels
773      P0774          StyleHubKarachi        Others   Kids Wear
790      P0791         WardrobeByAyesha       Jewelry    Necklace
1500     P1501  Faisalabad Fabric Point  Eastern Wear       Abaya
1067     P1068  Faisalabad Fabric Point        Others         Cap

               ProductName  PricePKR Gender Material      Season  \
1323   Beige Leather Heels     12708  Women  Leather      Summer
773   Pink Linen Kids Wear     11213  Women    Linen  All-season
790   Black Linen Necklace     13177  Women    Linen      Summer
1500    Black Cotton Abaya      5215  Women   Cotton  All-season
1067       White Linen Cap     11017  Women    Linen  All-season

                                 AI_Tags_Cleaned
1323        party, ethnic, casual, women, summer
773   summer, western, casual, women, all-season
790        wedding, casual, party, women, summer
1500   formal, casual, summer, women, all-season
1067   casual, summer, ethnic, women, all-season

In [28]:
# Example 2: Recommend 5 products for Men, Winter, formal occasion, priced 5000-20000 PKR
sample_recommendations_2 = ai_stylist_phase1(
    gender='Men',
    season='Winter',
    occasion='formal',
    price_range=(5000, 20000),
    n=5
)

print(sample_recommendations_2)

     ProductID            SellerName            Category SubCategory  \
277      P0278   Junaid Jamshed (J.)        Western Wear      Hoodie
581      P0582  Ethnic by Outfitters        Western Wear      Hoodie
614      P0615             Beechtree             Jewelry    Necklace
1181     P1182            Outfitters  Bags & Accessories        Belt
66       P0067   Junaid Jamshed (J.)             Jewelry    Necklace

                ProductName  PricePKR Gender   Material      Season  \
277   Pink Polyester Hoodie      8573  Women  Polyester      Winter
581       Green Lawn Hoodie     15755  Women       Lawn      Winter
614    Red Leather Necklace     17119    Men    Leather      Summer
1181   Brown Polyester Belt     14338    Men  Polyester      Summer
66      Blue Linen Necklace     14986  Women      Linen  All-season

                                AI_Tags_Cleaned
277       western, party, formal, women, winter
581               winter, formal, summer, women
614         formal, winter, ethnic, men, summer
1181        ethnic, formal, winter, men, summer
66    winter, summer, formal, women, all-season

In [29]:
gender_category_map = {
    'Men': ['Western Wear', 'Shoes', 'Bags & Accessories', 'Others'],
    'Women': ['Eastern Wear', 'Western Wear', 'Shoes', 'Jewelry', 'Bags & Accessories'],
    'Unisex': ['Kids Wear', 'Shoes', 'Accessories', 'Others'],
    'Kids': ['Kids Wear', 'Shoes', 'Others']
}

In [30]:
# ==============================
# FashionHub Phase 2: AI Stylist (Strict Reality-Based)
# ==============================

# ----- 1. Import Libraries -----
import pandas as pd

# ----- 2. Load Cleaned Dataset -----
df = pd.read_csv("FashionHub_products_cleaned.csv")

# ----- 3. Column Cleaning (Optional if already cleaned) -----
def clean_columns(df):
    for col in ['Category', 'SubCategory', 'Material', 'Season', 'Gender']:
        df[col] = df[col].astype(str).str.strip().str.title()
    material_map = {
        'Cottn': 'Cotton',
        'Silkk': 'Silk',
        'Polyester ': 'Polyester',
        'Leather ': 'Leather',
        'Wool ': 'Wool',
        'Denim ': 'Denim',
        'Linen ': 'Linen'
    }
    df['Material'] = df['Material'].replace(material_map)
    return df

df = clean_columns(df)

# ----- 4. Gender-Category Mapping for Strict Reality Check -----
gender_category_map = {
    'Men': ['Western Wear', 'Shoes', 'Bags & Accessories', 'Others'],
    'Women': ['Eastern Wear', 'Western Wear', 'Shoes', 'Jewelry', 'Bags & Accessories'],
    'Unisex': ['Kids Wear', 'Shoes', 'Accessories', 'Others'],
    'Kids': ['Kids Wear', 'Shoes', 'Others']
}

def filter_by_gender_category_strict(df, gender):
    allowed_categories = gender_category_map.get(gender, [])
    return df[df['Category'].isin(allowed_categories)]

# ----- 5. Phase 2 Strict AI Stylist Function -----
def ai_stylist_phase2_strict(gender=None, season=None, occasion=None, price_range=None, n=5):
    """
    Phase 2 AI Stylist with strict reality-based filtering.
    """
    df_filtered = df.copy()

    # Filter by AI_Tags_Cleaned (must match all selected tags)
    if gender:
        df_filtered = df_filtered[df_filtered['AI_Tags_Cleaned'].str.contains(gender, case=False, na=False)]
    if season:
        df_filtered = df_filtered[df_filtered['AI_Tags_Cleaned'].str.contains(season, case=False, na=False)]
    if occasion:
        df_filtered = df_filtered[df_filtered['AI_Tags_Cleaned'].str.contains(occasion, case=False, na=False)]

    # Filter by price
    if price_range:
        min_price, max_price = price_range
        df_filtered = df_filtered[(df_filtered['PricePKR'] >= min_price) & (df_filtered['PricePKR'] <= max_price)]

    # Strict reality-based filter: gender-category enforcement
    if gender:
        df_filtered = filter_by_gender_category_strict(df_filtered, gender)

    # Randomize and select top N
    recommendations = df_filtered.sample(n=min(n, len(df_filtered)), random_state=42)

    return recommendations[['ProductID','SellerName','Category','SubCategory','ProductName','PricePKR','Gender','Material','Season','AI_Tags_Cleaned']]

# ----- 6. Example Usage -----
# Women, Summer, casual, 1000-15000 PKR, top 5
sample_recommendations_1 = ai_stylist_phase2_strict(
    gender='Women',
    season='Summer',
    occasion='casual',
    price_range=(1000, 15000),
    n=5
)
print("---- Sample Recommendations 1 ----")
print(sample_recommendations_1)

# Men, Winter, formal, 5000-20000 PKR, top 5
sample_recommendations_2 = ai_stylist_phase2_strict(
    gender='Men',
    season='Winter',
    occasion='formal',
    price_range=(5000, 20000),
    n=5
)
print("\n---- Sample Recommendations 2 ----")
print(sample_recommendations_2)

---- Sample Recommendations 1 ----
     ProductID               SellerName            Category SubCategory  \
436      P0437       Chiniot Cloth Mart        Eastern Wear       Saree
341      P0342          EasternElegance  Bags & Accessories    Backpack
179      P0180  Faisalabad Fabric Point        Western Wear      Hoodie
1136     P1137             Sana Safinaz        Eastern Wear       Saree
1500     P1501  Faisalabad Fabric Point        Eastern Wear       Abaya

                ProductName  PricePKR Gender   Material      Season  \
436        Brown Wool Saree      1071  Women       Wool  All-Season
341      Pink Lawn Backpack      2259  Women       Lawn      Summer
179   Blue Polyester Hoodie      6224  Women  Polyester      Summer
1136      White Linen Saree      6526  Women      Linen      Summer
1500     Black Cotton Abaya      5215  Women     Cotton  All-Season

                                 AI_Tags_Cleaned
436   summer, casual, wedding, women, all-season
341        ethnic, formal, casual, women, summer
179         party, casual, formal, women, summer
1136       casual, trendy, ethnic, women, summer
1500   formal, casual, summer, women, all-season

---- Sample Recommendations 2 ----
    ProductID              SellerName            Category SubCategory  \
132     P0133       Rawalpindi Styles              Others         Cap
771     P0772         StyleHubKarachi              Others   Kids Wear
285     P0286      Chiniot Cloth Mart               Shoes     Sandals
11      P0012  Karachi Bazaar Fashion        Western Wear     T-Shirt
980     P0981     Multan Cloth Market  Bags & Accessories     Handbag

               ProductName  PricePKR Gender Material      Season  \
132        Blue Cotton Cap      6657    Men   Cotton      Winter
771  Black Linen Kids Wear     11550    Men    Linen      Winter
285    Brown Linen Sandals      8399  Women    Linen      Winter
11    White Cotton T-Shirt     18834    Men   Cotton      Winter
980     Beige Wool Handbag      5509  Women     Wool  All-Season

                                AI_Tags_Cleaned
132         formal, casual, ethnic, men, winter
771         formal, trendy, casual, men, winter
285       ethnic, formal, trendy, women, winter
11                  winter, casual, formal, men
980  winter, western, formal, women, all-season

In [31]:
import pandas as pd

# Load dataset
df = pd.read_csv("FashionHub_products_cleaned.csv")

# Gender-Category mapping
gender_category_map = {
    'Men': ['Western Wear', 'Shoes', 'Bags & Accessories', 'Others'],
    'Women': ['Eastern Wear', 'Western Wear', 'Shoes', 'Jewelry', 'Bags & Accessories'],
    'Unisex': ['Kids Wear', 'Shoes', 'Accessories', 'Others'],
    'Kids': ['Kids Wear', 'Shoes', 'Others']
}

def ai_stylist_fully_strict(gender=None, season=None, occasion=None, price_range=None, n=5):
    df_filtered = df.copy()

    # 1. Strict Gender + Category Filtering
    if gender:
        allowed_categories = gender_category_map.get(gender, [])
        df_filtered = df_filtered[
            (df_filtered['Gender'].str.lower() == gender.lower()) &
            (df_filtered['Category'].isin(allowed_categories))
        ]

    # 2. Filter by Season tag
    if season:
        df_filtered = df_filtered[df_filtered['AI_Tags_Cleaned'].str.contains(season, case=False, na=False)]

    # 3. Filter by Occasion tag
    if occasion:
        df_filtered = df_filtered[df_filtered['AI_Tags_Cleaned'].str.contains(occasion, case=False, na=False)]

    # 4. Filter by Price
    if price_range:
        min_price, max_price = price_range
        df_filtered = df_filtered[(df_filtered['PricePKR'] >= min_price) & (df_filtered['PricePKR'] <= max_price)]

    # 5. Random Sample Top N
    recommendations = df_filtered.sample(n=min(n, len(df_filtered)), random_state=42)

    return recommendations[['ProductID','SellerName','Category','SubCategory','ProductName','PricePKR','Gender','Material','Season','AI_Tags_Cleaned']]

# Example usage
sample_women = ai_stylist_fully_strict(gender='Women', season='Summer', occasion='casual', price_range=(1000,15000), n=5)
print("---- Women Recommendations ----")
print(sample_women)

sample_men = ai_stylist_fully_strict(gender='Men', season='Winter', occasion='formal', price_range=(5000,20000), n=5)
print("---- Men Recommendations ----")
print(sample_men)

---- Women Recommendations ----
     ProductID               SellerName            Category SubCategory  \
436      P0437       Chiniot Cloth Mart        Eastern Wear       Saree
341      P0342          EasternElegance  Bags & Accessories    Backpack
179      P0180  Faisalabad Fabric Point        Western Wear      Hoodie
1136     P1137             Sana Safinaz        Eastern Wear       Saree
1500     P1501  Faisalabad Fabric Point        Eastern Wear       Abaya

                ProductName  PricePKR Gender   Material      Season  \
436        Brown Wool Saree      1071  Women       Wool  All-season
341      Pink Lawn Backpack      2259  Women       Lawn      Summer
179   Blue Polyester Hoodie      6224  Women  Polyester      Summer
1136      White Linen Saree      6526  Women      Linen      Summer
1500     Black Cotton Abaya      5215  Women     Cotton  All-season

                                 AI_Tags_Cleaned
436   summer, casual, wedding, women, all-season
341        ethnic, formal, casual, women, summer
179         party, casual, formal, women, summer
1136       casual, trendy, ethnic, women, summer
1500   formal, casual, summer, women, all-season
---- Men Recommendations ----
     ProductID               SellerName            Category SubCategory  \
776      P0777  Faisalabad Fabric Point              Others   Kids Wear
657      P0658             Sana Safinaz        Western Wear      Hoodie
319      P0320      Multan Cloth Market  Bags & Accessories        Belt
1286     P1287   Sialkot Fashion Corner        Western Wear     T-Shirt
1517     P1518       Chiniot Cloth Mart               Shoes       Heels

                    ProductName  PricePKR Gender   Material  Season  \
776   Black Polyester Kids Wear      7321    Men  Polyester  Winter
657        Brown Leather Hoodie     14107    Men    Leather  Summer
319          Yellow Cotton Belt     16670    Men     Cotton  Summer
1286          Blue Wool T-Shirt      8750    Men       Wool  Winter
1517           Green Wool Heels     12473    Men       Wool  Summer

                           AI_Tags_Cleaned
776           western, winter, formal, men
657   winter, western, formal, men, summer
319   winter, formal, western, men, summer
1286           winter, formal, ethnic, men
1517    winter, party, formal, men, summer

In [32]:
def ai_stylist_strict(gender=None):
    allowed_categories = gender_category_map.get(gender, [])
    df_filtered = df[df['Category'].isin(allowed_categories)]
    return df_filtered

In [33]:
ai_stylist_strict(gender='Men')

,ProductID,SellerID,SellerName,Category,SubCategory,ProductName,PricePKR,Gender,Color,Material,Season,StockQty,AI_Tags,Corrected_Gender,AI_Tags_Cleaned
0,P0001,S001,Okara Dress House,Others,Cap,White Polyester Cap,18057,Men,White,Polyester,All-season,245,"summer, ethnic, casual",Men,"summer, ethnic, casual, men, all-season"
1,P0002,S001,Okara Dress House,Bags & Accessories,Wallet,Yellow Polyester Wallet,11044,Women,Yellow,Polyester,Summer,119,"formal, party, summer",Women,"formal, party, summer, women"
2,P0003,S001,Okara Dress House,Western Wear,T-Shirt,Green Leather T-Shirt,1628,Kids,Green,Leather,Summer,229,"ethnic, casual, wedding",Unisex,"ethnic, casual, wedding, unisex, summer"
3,P0004,S002,Limelight,Western Wear,T-Shirt,Yellow Wool T-Shirt,13215,Women,Yellow,Wool,Winter,461,"trendy, casual, wedding",Women,"trendy, casual, wedding, women, winter"
4,P0005,S002,Limelight,Bags & Accessories,Wallet,Brown Leather Wallet,887,Men,Brown,Leather,Winter,386,"formal, party, winter",Men,"formal, party, winter, men"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1553,P1554,S431,KurtiCraze,Bags & Accessories,Handbag,Blue Denim Handbag,549,Kids,Blue,Denim,All-season,189,"western, wedding, party",Unisex,"western, wedding, party, unisex, all-season"
1554,P1555,S431,KurtiCraze,Western Wear,Hoodie,Pink Linen Hoodie,19432,Unisex,Pink,Linen,Winter,60,"summer, wedding, ethnic",Unisex,"summer, wedding, ethnic, unisex, winter"
1556,P1557,S432,DailyFitStyle,Shoes,Heels,Black Cotton Heels,1385,Men,Black,Cotton,Winter,407,"winter, ethnic, wedding",Men,"winter, ethnic, wedding, men"
1557,P1558,S432,DailyFitStyle,Shoes,Sneakers,Green Wool Sneakers,13774,Women,Green,Wool,Winter,343,"winter, wedding, ethnic",Women,"winter, wedding, ethnic, women"
1558,P1559,S432,DailyFitStyle,Shoes,Sneakers,Brown Silk Sneakers,12368,Women,Brown,Silk,Summer,192,"casual, western, wedding",Women,"casual, western, wedding, women, summer"

In [34]:
import pandas as pd

# Load dataset
df = pd.read_csv("FashionHub_products_cleaned.csv")

# Gender-Category mapping
gender_category_map = {
    'Men': ['Western Wear', 'Shoes', 'Bags & Accessories', 'Others'],
    'Women': ['Eastern Wear', 'Western Wear', 'Shoes', 'Jewelry', 'Bags & Accessories'],
    'Unisex': ['Kids Wear', 'Shoes', 'Accessories', 'Others'],
    'Kids': ['Kids Wear', 'Shoes', 'Others']
}

def ai_stylist_strict(df, gender=None, season=None, occasion=None, price_range=None, n=5):
    df_filtered = df.copy()

    # 1. Strict Gender + Category Filtering using Corrected_Gender
    if gender:
        allowed_categories = gender_category_map.get(gender, [])
        df_filtered = df_filtered[
            (df_filtered['Corrected_Gender'].str.lower() == gender.lower()) &
            (df_filtered['Category'].isin(allowed_categories))
        ]

    # 2. Filter by Season tag
    if season:
        df_filtered = df_filtered[df_filtered['AI_Tags_Cleaned'].str.contains(season, case=False, na=False)]

    # 3. Filter by Occasion tag
    if occasion:
        df_filtered = df_filtered[df_filtered['AI_Tags_Cleaned'].str.contains(occasion, case=False, na=False)]

    # 4. Filter by Price range
    if price_range:
        min_price, max_price = price_range
        df_filtered = df_filtered[(df_filtered['PricePKR'] >= min_price) & (df_filtered['PricePKR'] <= max_price)]

    # 5. Random Sample Top N
    recommendations = df_filtered.sample(n=min(n, len(df_filtered)), random_state=42)

    return recommendations[['ProductID','SellerName','Category','SubCategory','ProductName','PricePKR','Corrected_Gender','Material','Season','AI_Tags_Cleaned']]

# Example usage
women_recs = ai_stylist_strict(df, gender='Women', season='Summer', occasion='casual', price_range=(1000,15000), n=5)
print("---- Women Recommendations ----")
print(women_recs)

men_recs = ai_stylist_strict(df, gender='Men', season='Winter', occasion='formal', price_range=(5000,20000), n=5)
print("---- Men Recommendations ----")
print(men_recs)

---- Women Recommendations ----
     ProductID               SellerName            Category SubCategory  \
436      P0437       Chiniot Cloth Mart        Eastern Wear       Saree
341      P0342          EasternElegance  Bags & Accessories    Backpack
179      P0180  Faisalabad Fabric Point        Western Wear      Hoodie
1136     P1137             Sana Safinaz        Eastern Wear       Saree
1500     P1501  Faisalabad Fabric Point        Eastern Wear       Abaya

                ProductName  PricePKR Corrected_Gender   Material      Season  \
436        Brown Wool Saree      1071            Women       Wool  All-season
341      Pink Lawn Backpack      2259            Women       Lawn      Summer
179   Blue Polyester Hoodie      6224            Women  Polyester      Summer
1136      White Linen Saree      6526            Women      Linen      Summer
1500     Black Cotton Abaya      5215            Women     Cotton  All-season

                                 AI_Tags_Cleaned
436   summer, casual, wedding, women, all-season
341        ethnic, formal, casual, women, summer
179         party, casual, formal, women, summer
1136       casual, trendy, ethnic, women, summer
1500   formal, casual, summer, women, all-season
---- Men Recommendations ----
     ProductID               SellerName            Category SubCategory  \
776      P0777  Faisalabad Fabric Point              Others   Kids Wear
657      P0658             Sana Safinaz        Western Wear      Hoodie
319      P0320      Multan Cloth Market  Bags & Accessories        Belt
1286     P1287   Sialkot Fashion Corner        Western Wear     T-Shirt
1517     P1518       Chiniot Cloth Mart               Shoes       Heels

                    ProductName  PricePKR Corrected_Gender   Material  Season  \
776   Black Polyester Kids Wear      7321              Men  Polyester  Winter
657        Brown Leather Hoodie     14107              Men    Leather  Summer
319          Yellow Cotton Belt     16670              Men     Cotton  Summer
1286          Blue Wool T-Shirt      8750              Men       Wool  Winter
1517           Green Wool Heels     12473              Men       Wool  Summer

                           AI_Tags_Cleaned
776           western, winter, formal, men
657   winter, western, formal, men, summer
319   winter, formal, western, men, summer
1286           winter, formal, ethnic, men
1517    winter, party, formal, men, summer

In [35]:
import pandas as pd

# Load dataset
df = pd.read_csv("FashionHub_products_cleaned.csv")

# Example: create a filtered copy for Men
df_filtered = df[df['Corrected_Gender'] == 'Men']

# Remove Kids Wear for Men
df_filtered = df_filtered[df_filtered['Category'].str.lower() != 'kids wear']

# Display filtered products
print(df_filtered[['ProductID','SellerName','Category','SubCategory','ProductName','Corrected_Gender']])

     ProductID               SellerName            Category SubCategory  \
0        P0001        Okara Dress House              Others         Cap
4        P0005                Limelight  Bags & Accessories      Wallet
6        P0007  Faisalabad Fabric Point        Western Wear      Hoodie
8        P0009  Faisalabad Fabric Point  Bags & Accessories        Belt
11       P0012   Karachi Bazaar Fashion        Western Wear     T-Shirt
...        ...                      ...                 ...         ...
1545     P1546               Outfitters        Eastern Wear       Abaya
1546     P1547             Sana Safinaz             Jewelry    Necklace
1550     P1551             Sana Safinaz        Western Wear       Jeans
1552     P1553               KurtiCraze             Jewelry    Earrings
1556     P1557            DailyFitStyle               Shoes       Heels

                ProductName Corrected_Gender
0       White Polyester Cap              Men
4      Brown Leather Wallet              Men
6         Green Lawn Hoodie              Men
8           White Silk Belt              Men
11     White Cotton T-Shirt              Men
...                     ...              ...
1545    Beige Leather Abaya              Men
1546     Pink Lawn Necklace              Men
1550  Green Polyester Jeans              Men
1552    Beige Silk Earrings              Men
1556     Black Cotton Heels              Men

[417 rows x 6 columns]

In [36]:
allowed_categories = {
    'Men': ['Western Wear', 'Shoes', 'Bags & Accessories', 'Others'],
    'Women': ['Western Wear', 'Eastern Wear', 'Shoes', 'Jewelry', 'Bags & Accessories'],
    'Kids': ['Kids Wear', 'Shoes', 'Others']
}

allowed_subcategories = {
    'Men': ['T-Shirt', 'Hoodie', 'Jeans', 'Shoes', 'Wallet', 'Belt', 'Cap', 'Handbag'],
    'Women': ['Saree', 'Abaya', 'T-Shirt', 'Hoodie', 'Jeans', 'Shoes', 'Wallet', 'Belt', 'Cap', 'Handbag', 'Necklace', 'Earrings'],
    'Kids': ['Kids Wear', 'Shoes', 'Cap', 'Backpack']
}

In [37]:
gender = 'Men'
df_filtered = df[
    (df['Corrected_Gender'] == gender) &
    (df['Category'].isin(allowed_categories[gender])) &
    (df['SubCategory'].isin(allowed_subcategories[gender]))
]

In [38]:
allowed_categories = {
    'Men': ['Western Wear', 'Shoes', 'Bags & Accessories', 'Others'],
    'Women': ['Western Wear', 'Eastern Wear', 'Shoes', 'Jewelry', 'Bags & Accessories'],
    'Kids': ['Kids Wear', 'Shoes', 'Others']
}

allowed_subcategories = {
    'Men': ['T-Shirt', 'Hoodie', 'Jeans', 'Shoes', 'Wallet', 'Belt', 'Cap', 'Handbag'],
    'Women': ['Saree', 'Abaya', 'T-Shirt', 'Hoodie', 'Jeans', 'Shoes', 'Wallet', 'Belt', 'Cap', 'Handbag', 'Necklace', 'Earrings'],
    'Kids': ['Kids Wear', 'Shoes', 'Cap', 'Backpack']
}

In [39]:
gender = 'Men'  # Change to 'Women' or 'Kids' to test others

df_filtered = df[
    (df['Corrected_Gender'] == gender) &
    (df['Category'].isin(allowed_categories[gender])) &
    (df['SubCategory'].isin(allowed_subcategories[gender]))
]

# Display sample results
print(df_filtered[['ProductID','ProductName','Category','SubCategory','Corrected_Gender']].sample(10, random_state=42))

     ProductID            ProductName            Category SubCategory  \
892      P0893  Green Leather Handbag  Bags & Accessories     Handbag
220      P0221      Blue Lawn Handbag  Bags & Accessories     Handbag
1451     P1452     Yellow Denim Jeans        Western Wear       Jeans
775      P0776      Grey Silk Handbag  Bags & Accessories     Handbag
1178     P1179   Yellow Leather Jeans        Western Wear       Jeans
923      P0924      Brown Wool Hoodie        Western Wear      Hoodie
384      P0385     Brown Wool T-Shirt        Western Wear     T-Shirt
623      P0624        Beige Silk Belt  Bags & Accessories        Belt
1464     P1465     Brown Cotton Jeans        Western Wear       Jeans
557      P0558        Red Wool Wallet  Bags & Accessories      Wallet

     Corrected_Gender
892               Men
220               Men
1451              Men
775               Men
1178              Men
923               Men
384               Men
623               Men
1464              Men
557               Men

In [40]:
import pandas as pd

# Load dataset
df = pd.read_csv("FashionHub_products_cleaned.csv")

# Allowed categories/subcategories mapping
allowed_categories = {
    'Men': ['Western Wear', 'Shoes', 'Bags & Accessories', 'Others'],
    'Women': ['Western Wear', 'Eastern Wear', 'Shoes', 'Jewelry', 'Bags & Accessories'],
    'Kids': ['Kids Wear', 'Shoes', 'Others']
}

allowed_subcategories = {
    'Men': ['T-Shirt', 'Hoodie', 'Jeans', 'Shoes', 'Wallet', 'Belt', 'Cap', 'Handbag'],
    'Women': ['Saree', 'Abaya', 'T-Shirt', 'Hoodie', 'Jeans', 'Shoes', 'Wallet', 'Belt', 'Cap', 'Handbag', 'Necklace', 'Earrings'],
    'Kids': ['Kids Wear', 'Shoes', 'Cap', 'Backpack']
}

def ai_stylist(gender=None, season=None, occasion=None, price_range=None, n=5):
    """
    Recommend products based on AI stylist logic with realistic gender-category filtering.
    
    Parameters:
    - gender: 'Men', 'Women', 'Kids' (string)
    - season: 'Summer', 'Winter', 'All-season' (string)
    - occasion: e.g., 'wedding', 'casual', 'party', 'formal' (string)
    - price_range: tuple(min_price, max_price)
    - n: number of products to recommend
    
    Returns:
    - DataFrame of recommended products
    """
    df_filtered = df.copy()
    
    # Gender filter
    if gender:
        df_filtered = df_filtered[df_filtered['Corrected_Gender'] == gender]
        
        # Filter only allowed categories/subcategories for this gender
        df_filtered = df_filtered[
            (df_filtered['Category'].isin(allowed_categories[gender])) &
            (df_filtered['SubCategory'].isin(allowed_subcategories[gender]))
        ]
    
    # Season filter
    if season:
        df_filtered = df_filtered[df_filtered['Season'].str.lower() == season.lower()]
    
    # Occasion filter (check if occasion tag exists in AI_Tags_Cleaned)
    if occasion:
        df_filtered = df_filtered[df_filtered['AI_Tags_Cleaned'].str.contains(occasion, case=False, na=False)]
    
    # Price range filter
    if price_range:
        min_price, max_price = price_range
        df_filtered = df_filtered[(df_filtered['PricePKR'] >= min_price) & (df_filtered['PricePKR'] <= max_price)]
    
    # Randomize and select top N products
    recommendations = df_filtered.sample(n=min(n, len(df_filtered)), random_state=42)
    
    return recommendations[['ProductID','SellerName','Category','SubCategory','ProductName','PricePKR','Corrected_Gender','Material','Season','AI_Tags_Cleaned']]

# --- Example usage ---
women_recs = ai_stylist(gender='Women', season='Summer', occasion='casual', price_range=(1000,15000), n=5)
men_recs = ai_stylist(gender='Men', season='Winter', occasion='formal', price_range=(5000,20000), n=5)

print("--- Women Recommendations ---")
print(women_recs)
print("\n--- Men Recommendations ---")
print(men_recs)

--- Women Recommendations ---
     ProductID         SellerName            Category SubCategory  \
602      P0603          Gul Ahmed  Bags & Accessories      Wallet
813      P0814    StyleHubKarachi        Eastern Wear       Saree
88       P0089   Quetta Style Hub        Eastern Wear       Abaya
1053     P1054             Khaadi  Bags & Accessories     Handbag
256      P0257  Rawalpindi Styles             Jewelry    Necklace

              ProductName  PricePKR Corrected_Gender Material  Season  \
602   Beige Cotton Wallet     14501            Women   Cotton  Summer
813      Green Lawn Saree      3690            Women     Lawn  Summer
88        Pink Lawn Abaya      2040            Women     Lawn  Summer
1053   Black Lawn Handbag      7525            Women     Lawn  Summer
256   Red Cotton Necklace     11346            Women   Cotton  Summer

                            AI_Tags_Cleaned
602           summer, formal, casual, women
813    trendy, casual, party, women, summer
88     party, formal, casual, women, summer
1053  winter, casual, ethnic, women, summer
256           summer, ethnic, casual, women

--- Men Recommendations ---
     ProductID              SellerName            Category SubCategory  \
1468     P1469               Beechtree  Bags & Accessories        Belt
1312     P1313         TrendyThreadsPK              Others         Cap
11       P0012  Karachi Bazaar Fashion        Western Wear     T-Shirt
1286     P1287  Sialkot Fashion Corner        Western Wear     T-Shirt
507      P0508      Chiniot Cloth Mart        Western Wear       Jeans

               ProductName  PricePKR Corrected_Gender Material  Season  \
1468        Red Linen Belt     13947              Men    Linen  Winter
1312      Beige Cotton Cap      7475              Men   Cotton  Winter
11    White Cotton T-Shirt     18834              Men   Cotton  Winter
1286     Blue Wool T-Shirt      8750              Men     Wool  Winter
507       Red Cotton Jeans      9069              Men   Cotton  Winter

                           AI_Tags_Cleaned
1468  western, formal, summer, men, winter
1312  casual, western, formal, men, winter
11             winter, casual, formal, men
1286           winter, formal, ethnic, men
507    casual, formal, ethnic, men, winter

In [41]:
import pandas as pd

# Load dataset
df = pd.read_csv("FashionHub_products_cleaned.csv")

# Allowed categories/subcategories mapping
allowed_categories = {
    'Men': ['Western Wear', 'Shoes', 'Bags & Accessories', 'Others'],
    'Women': ['Western Wear', 'Eastern Wear', 'Shoes', 'Jewelry', 'Bags & Accessories'],
    'Kids': ['Kids Wear', 'Shoes', 'Others']
}

allowed_subcategories = {
    'Men': ['T-Shirt', 'Hoodie', 'Jeans', 'Shoes', 'Wallet', 'Belt', 'Cap', 'Handbag'],
    'Women': ['Saree', 'Abaya', 'T-Shirt', 'Hoodie', 'Jeans', 'Shoes', 'Wallet', 'Belt', 'Cap', 'Handbag', 'Necklace', 'Earrings'],
    'Kids': ['Kids Wear', 'Shoes', 'Cap', 'Backpack']
}

def ai_stylist_combined(seasons=None, occasion=None, price_range=None, n=5):
    """
    Recommend products for Men, Women, and Kids simultaneously.
    
    Parameters:
    - seasons: 'Summer', 'Winter', 'All-season' (string)
    - occasion: e.g., 'wedding', 'casual', 'party', 'formal' (string)
    - price_range: tuple(min_price, max_price)
    - n: number of products per gender
    
    Returns:
    - Dictionary of recommendations by gender
    """
    recommendations = {}
    
    for gender in ['Men', 'Women', 'Kids']:
        df_filtered = df.copy()
        
        # Gender filter
        df_filtered = df_filtered[df_filtered['Corrected_Gender'] == gender]
        df_filtered = df_filtered[
            (df_filtered['Category'].isin(allowed_categories[gender])) &
            (df_filtered['SubCategory'].isin(allowed_subcategories[gender]))
        ]
        
        # Season filter
        if seasons:
            df_filtered = df_filtered[df_filtered['Season'].str.lower() == seasons.lower()]
        
        # Occasion filter
        if occasion:
            df_filtered = df_filtered[df_filtered['AI_Tags_Cleaned'].str.contains(occasion, case=False, na=False)]
        
        # Price filter
        if price_range:
            min_price, max_price = price_range
            df_filtered = df_filtered[(df_filtered['PricePKR'] >= min_price) & (df_filtered['PricePKR'] <= max_price)]
        
        # Random sample
        recommendations[gender] = df_filtered.sample(n=min(n, len(df_filtered)), random_state=42)[
            ['ProductID','SellerName','Category','SubCategory','ProductName','PricePKR','Corrected_Gender','Material','Season','AI_Tags_Cleaned']
        ]
    
    return recommendations

# --- Example usage ---
recs = ai_stylist_combined(seasons='Summer', occasion='casual', price_range=(1000,15000), n=5)

print("--- Women Recommendations ---")
print(recs['Women'])
print("\n--- Men Recommendations ---")
print(recs['Men'])
print("\n--- Kids Recommendations ---")
print(recs['Kids'])

--- Women Recommendations ---
     ProductID         SellerName            Category SubCategory  \
602      P0603          Gul Ahmed  Bags & Accessories      Wallet
813      P0814    StyleHubKarachi        Eastern Wear       Saree
88       P0089   Quetta Style Hub        Eastern Wear       Abaya
1053     P1054             Khaadi  Bags & Accessories     Handbag
256      P0257  Rawalpindi Styles             Jewelry    Necklace

              ProductName  PricePKR Corrected_Gender Material  Season  \
602   Beige Cotton Wallet     14501            Women   Cotton  Summer
813      Green Lawn Saree      3690            Women     Lawn  Summer
88        Pink Lawn Abaya      2040            Women     Lawn  Summer
1053   Black Lawn Handbag      7525            Women     Lawn  Summer
256   Red Cotton Necklace     11346            Women   Cotton  Summer

                            AI_Tags_Cleaned
602           summer, formal, casual, women
813    trendy, casual, party, women, summer
88     party, formal, casual, women, summer
1053  winter, casual, ethnic, women, summer
256           summer, ethnic, casual, women

--- Men Recommendations ---
     ProductID          SellerName            Category SubCategory  \
1243     P1244  Lahore Trend House  Bags & Accessories      Wallet
182      P0183    WardrobeByAyesha        Western Wear      Hoodie
1464     P1465    Hyderabad Drapes        Western Wear       Jeans
1530     P1531          GlamCartPK  Bags & Accessories     Handbag
389      P0390           Gul Ahmed  Bags & Accessories      Wallet

               ProductName  PricePKR Corrected_Gender Material  Season  \
1243   Brown Cotton Wallet      8245              Men   Cotton  Summer
182   White Leather Hoodie     10752              Men  Leather  Summer
1464    Brown Cotton Jeans      1401              Men   Cotton  Summer
1530    Pink Linen Handbag      2983              Men    Linen  Summer
389      Grey Denim Wallet     10588              Men    Denim  Summer

                           AI_Tags_Cleaned
1243           summer, ethnic, casual, men
182   western, casual, formal, men, summer
1464   winter, casual, formal, men, summer
1530   party, western, casual, men, summer
389    casual, ethnic, formal, men, summer

--- Kids Recommendations ---
Empty DataFrame
Columns: [ProductID, SellerName, Category, SubCategory, ProductName, PricePKR, Corrected_Gender, Material, Season, AI_Tags_Cleaned]
Index: []

In [42]:
import pandas as pd

# Load dataset
df = pd.read_csv("FashionHub_products_cleaned.csv")

# Allowed categories per gender
gender_category_map = {
    'Men': ['Western Wear', 'Eastern Wear', 'Shoes', 'Bags & Accessories', 'Others'],
    'Women': ['Western Wear', 'Eastern Wear', 'Shoes', 'Bags & Accessories', 'Jewelry', 'Others'],
    'Unisex': ['Western Wear', 'Eastern Wear', 'Shoes', 'Bags & Accessories', 'Others']
}

# Unrealistic subcategory and product keywords per gender
gender_exclusion_map = {
    'Men': {
        'SubCategory': ['Saree', 'Abaya', 'Kids Wear', 'Necklace', 'Earrings', 'Handbag'],
        'Keywords': ['saree', 'abaya', 'necklace', 'earrings', 'handbag', 'kids']
    },
    'Women': {
        'SubCategory': ['Kids Wear', 'Tie', 'Wallet', 'Cap', 'Belt', 'Shoes (Men)'],
        'Keywords': ['tie', 'wallet', 'cap', 'belt', 'mens', 'boys', 'kids']
    },
    'Unisex': {
        'SubCategory': [],
        'Keywords': []
    }
}

def ai_stylist_advanced(gender=None, season=None, occasion=None, price_range=None, n=5):
    df_filtered = df.copy()

    if gender:
        gender_lower = gender.lower()
        df_filtered = df_filtered[df_filtered['Corrected_Gender'].str.lower() == gender_lower]

        # Allowed categories
        allowed_categories = gender_category_map.get(gender, [])
        df_filtered = df_filtered[df_filtered['Category'].isin(allowed_categories)]

        # Exclude unrealistic subcategories
        exclusions = gender_exclusion_map.get(gender, {})
        subcat_excl = exclusions.get('SubCategory', [])
        keyword_excl = exclusions.get('Keywords', [])

        df_filtered = df_filtered[~df_filtered['SubCategory'].isin(subcat_excl)]
        # Also exclude by product keywords
        for kw in keyword_excl:
            df_filtered = df_filtered[~df_filtered['ProductName'].str.lower().str.contains(kw)]

    # Filter by season
    if season:
        df_filtered = df_filtered[df_filtered['Season'].str.lower() == season.lower()]

    # Filter by occasion
    if occasion:
        df_filtered = df_filtered[df_filtered['AI_Tags_Cleaned'].str.contains(occasion, case=False, na=False)]

    # Filter by price
    if price_range:
        min_price, max_price = price_range
        df_filtered = df_filtered[(df_filtered['PricePKR'] >= min_price) & (df_filtered['PricePKR'] <= max_price)]

    # Randomize and select top N
    recommendations = df_filtered.sample(n=min(n, len(df_filtered)), random_state=42)

    return recommendations[['ProductID','SellerName','Category','SubCategory','ProductName','PricePKR','Corrected_Gender','Material','Season','AI_Tags_Cleaned']]

# Test examples
women_recs = ai_stylist_advanced(gender='Women', season='Summer', occasion='casual', price_range=(1000,15000), n=5)
men_recs = ai_stylist_advanced(gender='Men', season='Winter', occasion='formal', price_range=(1000,15000), n=5)

print("---- Women Recommendations ----")
print(women_recs)
print("\n---- Men Recommendations ----")
print(men_recs)

---- Women Recommendations ----
     ProductID         SellerName            Category     SubCategory  \
312      P0313  Rawalpindi Styles               Shoes           Heels
813      P0814    StyleHubKarachi        Eastern Wear           Saree
29       P0030        ModishMoods             Jewelry            Ring
1053     P1054             Khaadi  Bags & Accessories         Handbag
446      P0447       Cross Stitch        Eastern Wear  Shalwar Kameez

                    ProductName  PricePKR Corrected_Gender Material  Season  \
312             Pink Silk Heels     13155            Women     Silk  Summer
813            Green Lawn Saree      3690            Women     Lawn  Summer
29            Pink Leather Ring      9237            Women  Leather  Summer
1053         Black Lawn Handbag      7525            Women     Lawn  Summer
446   Pink Denim Shalwar Kameez      5183            Women    Denim  Summer

                             AI_Tags_Cleaned
312   western, trendy, casual, women, summer
813     trendy, casual, party, women, summer
29      party, casual, formal, women, summer
1053   winter, casual, ethnic, women, summer
446            casual, summer, winter, women

---- Men Recommendations ----
     ProductID           SellerName            Category     SubCategory  \
1244     P1245      EasternElegance               Shoes        Sneakers
600      P0601           Outfitters  Bags & Accessories            Belt
52       P0053     WardrobeByAyesha        Eastern Wear  Shalwar Kameez
569      P0570  Junaid Jamshed (J.)        Eastern Wear           Kurta
1312     P1313      TrendyThreadsPK              Others             Cap

                     ProductName  PricePKR Corrected_Gender Material  Season  \
1244       White Cotton Sneakers      8822              Men   Cotton  Winter
600              Grey Denim Belt      2064              Men    Denim  Winter
52    Yellow Lawn Shalwar Kameez     12584              Men     Lawn  Winter
569              Pink Wool Kurta      1086              Men     Wool  Winter
1312            Beige Cotton Cap      7475              Men   Cotton  Winter

                           AI_Tags_Cleaned
1244          winter, formal, wedding, men
600   formal, western, summer, men, winter
52    formal, western, summer, men, winter
569           formal, winter, western, men
1312  casual, western, formal, men, winter

In [43]:
def ai_outfit_stylist(starting_product_id, n_matches=1):
    """
    Recommend a matching outfit based on a starting product.
    
    Parameters:
    - starting_product_id: ProductID to base the outfit on
    - n_matches: number of matching items per category
    
    Returns:
    - DataFrame of recommended outfit items
    """
    starting_item = df[df['ProductID'] == starting_product_id]
    if starting_item.empty:
        return pd.DataFrame()
    
    category = starting_item.iloc[0]['Category']
    subcat = starting_item.iloc[0]['SubCategory']
    gender = starting_item.iloc[0]['Corrected_Gender']
    season = starting_item.iloc[0]['Season']
    
    # Determine matching categories
    matching_map = {
        'Western Wear': ['Shoes', 'Bags & Accessories', 'Jewelry'],
        'Eastern Wear': ['Shoes', 'Bags & Accessories', 'Jewelry'],
        'Shoes': ['Western Wear', 'Eastern Wear', 'Bags & Accessories'],
        'Bags & Accessories': ['Western Wear', 'Eastern Wear', 'Shoes'],
        'Jewelry': ['Eastern Wear', 'Western Wear', 'Shoes']
    }
    
    match_cats = matching_map.get(category, [])
    
    outfit_items = [starting_item]
    
    for cat in match_cats:
        matches = df[
            (df['Category'] == cat) &
            (df['Corrected_Gender'] == gender) &
            (df['Season'] == season)
        ].sample(n=min(n_matches, len(df)), random_state=42)
        
        outfit_items.append(matches)
    
    return pd.concat(outfit_items)[['ProductID','SellerName','Category','SubCategory','ProductName','PricePKR','Corrected_Gender','Material','Season','AI_Tags_Cleaned']]

# Example: Generate outfit for a Saree (Women)
outfit = ai_outfit_stylist(starting_product_id='P0814', n_matches=1)
print(outfit)

     ProductID              SellerName            Category   SubCategory  \
813      P0814         StyleHubKarachi        Eastern Wear         Saree
1132     P1133  Karachi Bazaar Fashion               Shoes  Formal Shoes
1        P0002       Okara Dress House  Bags & Accessories        Wallet
1440     P1441        Quetta Style Hub             Jewelry          Ring

                  ProductName  PricePKR Corrected_Gender   Material  Season  \
813          Green Lawn Saree      3690            Women       Lawn  Summer
1132  Grey Denim Formal Shoes     18311            Women      Denim  Summer
1     Yellow Polyester Wallet     11044            Women  Polyester  Summer
1440        Green Cotton Ring      8945            Women     Cotton  Summer

                           AI_Tags_Cleaned
813   trendy, casual, party, women, summer
1132         summer, party, western, women
1             formal, party, summer, women
1440  trendy, casual, party, women, summer

In [44]:
import pandas as pd

# Load the cleaned dataset
df = pd.read_csv("FashionHub_products_cleaned.csv")

# Define matching categories map
matching_map = {
    'Eastern Wear': ['Shoes', 'Bags & Accessories', 'Jewelry'],
    'Western Wear': ['Shoes', 'Bags & Accessories', 'Jewelry'],
    'Shoes': ['Eastern Wear', 'Western Wear', 'Bags & Accessories'],
    'Bags & Accessories': ['Eastern Wear', 'Western Wear', 'Shoes'],
    'Jewelry': ['Eastern Wear', 'Western Wear', 'Shoes']
}

def ai_outfit_builder(start_product_id):
    # Get the starting product
    start_product = df[df['ProductID'] == start_product_id].iloc[0]
    
    gender = start_product['Corrected_Gender']
    season = start_product['Season']
    category = start_product['Category']
    
    outfit = pd.DataFrame([start_product])  # Start with main product
    
    # Find matching categories
    if category in matching_map:
        for match_cat in matching_map[category]:
            # Filter products by matching category, same gender, same season
            matches = df[
                (df['Category'] == match_cat) &
                (df['Corrected_Gender'] == gender) &
                (df['Season'] == season) &
                (df['Category'].str.lower() != 'kids wear')  # skip kids wear
            ]
            if not matches.empty:
                # Pick one matching product randomly
                outfit = pd.concat([outfit, matches.sample(1, random_state=42)])
    
    return outfit[['ProductID', 'ProductName', 'Category', 'SubCategory', 'Corrected_Gender', 'Material', 'Season', 'AI_Tags_Cleaned']]

# ----- Example usage ----- #
# Pick a product, e.g., a Saree
example_outfit = ai_outfit_builder('P0814')
print(example_outfit)

     ProductID              ProductName            Category   SubCategory  \
813      P0814         Green Lawn Saree        Eastern Wear         Saree
1132     P1133  Grey Denim Formal Shoes               Shoes  Formal Shoes
1        P0002  Yellow Polyester Wallet  Bags & Accessories        Wallet
1440     P1441        Green Cotton Ring             Jewelry          Ring

     Corrected_Gender   Material  Season                       AI_Tags_Cleaned
813             Women       Lawn  Summer  trendy, casual, party, women, summer
1132            Women      Denim  Summer         summer, party, western, women
1               Women  Polyester  Summer          formal, party, summer, women
1440            Women     Cotton  Summer  trendy, casual, party, women, summer

In [45]:
import pandas as pd

# Load cleaned dataset
df = pd.read_csv("FashionHub_products_cleaned.csv")

# Define allowed categories per gender to avoid unrealistic items
gender_category_map = {
    'Women': ['Eastern Wear', 'Western Wear', 'Bags & Accessories', 'Jewelry', 'Shoes', 'Others'],
    'Men': ['Western Wear', 'Bags & Accessories', 'Jewelry', 'Shoes', 'Others'],
    'Unisex': ['Western Wear', 'Bags & Accessories', 'Jewelry', 'Shoes', 'Others']
}

# AI Stylist function
def ai_stylist_outfit(gender='Women', season=None, occasion=None, price_range=None, n=5):
    df_filtered = df.copy()
    
    # Apply gender filter
    if gender:
        allowed_categories = gender_category_map.get(gender, [])
        df_filtered = df_filtered[
            (df_filtered['Corrected_Gender'] == gender) & 
            (df_filtered['Category'].isin(allowed_categories)) &
            (~df_filtered['Category'].str.lower().eq('kids wear'))  # skip kids items
        ]
    
    # Season filter
    if season:
        df_filtered = df_filtered[df_filtered['Season'].str.lower() == season.lower()]
    
    # Occasion filter using AI_Tags_Cleaned
    if occasion:
        df_filtered = df_filtered[df_filtered['AI_Tags_Cleaned'].str.contains(occasion, case=False, na=False)]
    
    # Price range filter
    if price_range:
        min_price, max_price = price_range
        df_filtered = df_filtered[(df_filtered['PricePKR'] >= min_price) & (df_filtered['PricePKR'] <= max_price)]
    
    # Select N random products
    recommendations = df_filtered.sample(n=min(n, len(df_filtered)), random_state=42)
    
    # Display relevant columns
    return recommendations[['ProductID','SellerName','Category','SubCategory','ProductName','PricePKR','Corrected_Gender','Material','Season','AI_Tags_Cleaned']]

# Example usage
# Recommend 5 Women outfits for Summer, casual occasion, priced 1000-15000
sample_outfit = ai_stylist_outfit(gender='Women', season='Summer', occasion='casual', price_range=(1000,15000), n=5)
print(sample_outfit)

     ProductID         SellerName            Category SubCategory  \
341      P0342    EasternElegance  Bags & Accessories    Backpack
1409     P1410    StyleHubKarachi               Shoes     Sandals
312      P0313  Rawalpindi Styles               Shoes       Heels
1053     P1054             Khaadi  Bags & Accessories     Handbag
29       P0030        ModishMoods             Jewelry        Ring

              ProductName  PricePKR Corrected_Gender Material  Season  \
341    Pink Lawn Backpack      2259            Women     Lawn  Summer
1409  Brown Linen Sandals     10953            Women    Linen  Summer
312       Pink Silk Heels     13155            Women     Silk  Summer
1053   Black Lawn Handbag      7525            Women     Lawn  Summer
29      Pink Leather Ring      9237            Women  Leather  Summer

                             AI_Tags_Cleaned
341    ethnic, formal, casual, women, summer
1409    party, casual, trendy, women, summer
312   western, trendy, casual, women, summer
1053   winter, casual, ethnic, women, summer
29      party, casual, formal, women, summer

In [46]:
import pandas as pd

# Load cleaned dataset
df = pd.read_csv("FashionHub_products_cleaned.csv")

# Map allowed categories for each gender
gender_category_map = {
    'Women': ['Eastern Wear', 'Western Wear', 'Bags & Accessories', 'Jewelry', 'Shoes', 'Others'],
    'Men': ['Western Wear', 'Bags & Accessories', 'Jewelry', 'Shoes', 'Others'],
    'Unisex': ['Western Wear', 'Bags & Accessories', 'Jewelry', 'Shoes', 'Others']
}

def ai_stylist(gender=None, season=None, occasion=None, price_range=None, n=5):
    """
    Recommend products based on AI stylist logic.

    Parameters:
    - gender: 'Men', 'Women', 'Unisex'
    - season: 'Summer', 'Winter', 'All-season'
    - occasion: e.g., 'wedding', 'casual', 'party', 'formal'
    - price_range: tuple(min_price, max_price)
    - n: number of products to recommend

    Returns:
    - DataFrame of recommended products
    """
    df_filtered = df.copy()
    
    # Gender filter
    if gender:
        allowed_categories = gender_category_map.get(gender, [])
        df_filtered = df_filtered[
            (df_filtered['Corrected_Gender'] == gender) &
            (df_filtered['Category'].isin(allowed_categories)) &
            (~df_filtered['Category'].str.lower().eq('kids wear'))  # skip kids items
        ]
    
    # Season filter
    if season:
        df_filtered = df_filtered[df_filtered['Season'].str.lower() == season.lower()]
    
    # Occasion filter
    if occasion:
        df_filtered = df_filtered[df_filtered['AI_Tags_Cleaned'].str.contains(occasion, case=False, na=False)]
    
    # Price range filter
    if price_range:
        min_price, max_price = price_range
        df_filtered = df_filtered[(df_filtered['PricePKR'] >= min_price) & (df_filtered['PricePKR'] <= max_price)]
    
    # Randomly select top N products
    recommendations = df_filtered.sample(n=min(n, len(df_filtered)), random_state=42)
    
    return recommendations[['ProductID','SellerName','Category','SubCategory','ProductName','PricePKR','Corrected_Gender','Material','Season','AI_Tags_Cleaned']]

# --- Example usage ---
# Recommend 5 Women products for Summer, casual occasion, priced 1000-15000 PKR
sample_recommendations = ai_stylist(gender='Women', season='Summer', occasion='casual', price_range=(1000,15000), n=5)
print(sample_recommendations)

     ProductID         SellerName            Category SubCategory  \
341      P0342    EasternElegance  Bags & Accessories    Backpack
1409     P1410    StyleHubKarachi               Shoes     Sandals
312      P0313  Rawalpindi Styles               Shoes       Heels
1053     P1054             Khaadi  Bags & Accessories     Handbag
29       P0030        ModishMoods             Jewelry        Ring

              ProductName  PricePKR Corrected_Gender Material  Season  \
341    Pink Lawn Backpack      2259            Women     Lawn  Summer
1409  Brown Linen Sandals     10953            Women    Linen  Summer
312       Pink Silk Heels     13155            Women     Silk  Summer
1053   Black Lawn Handbag      7525            Women     Lawn  Summer
29      Pink Leather Ring      9237            Women  Leather  Summer

                             AI_Tags_Cleaned
341    ethnic, formal, casual, women, summer
1409    party, casual, trendy, women, summer
312   western, trendy, casual, women, summer
1053   winter, casual, ethnic, women, summer
29      party, casual, formal, women, summer

In [47]:
import pandas as pd

# Load dataset
df = pd.read_csv("FashionHub_products_cleaned.csv")

# Define gender-appropriate categories
gender_category_map = {
    'Women': ['Eastern Wear', 'Western Wear', 'Bags & Accessories', 'Jewelry', 'Shoes', 'Others'],
    'Men': ['Western Wear', 'Bags & Accessories', 'Jewelry', 'Shoes', 'Others'],
    'Unisex': ['Western Wear', 'Bags & Accessories', 'Jewelry', 'Shoes', 'Others']
}

# Map categories into outfit parts
outfit_parts_map = {
    'Top': ['Western Wear', 'Eastern Wear'],
    'Bottom': ['Western Wear', 'Eastern Wear'],
    'Shoes': ['Shoes'],
    'Accessories': ['Bags & Accessories', 'Jewelry', 'Others']
}

def ai_outfit_stylist(gender=None, season=None, occasion=None, price_range=None):
    """
    Suggests a full outfit: top + bottom + shoes + accessories
    """
    df_filtered = df.copy()
    
    # Gender filter & allowed categories
    if gender:
        allowed_categories = gender_category_map.get(gender, [])
        df_filtered = df_filtered[
            (df_filtered['Corrected_Gender'] == gender) &
            (df_filtered['Category'].isin(allowed_categories)) &
            (~df_filtered['Category'].str.lower().eq('kids wear'))
        ]
    
    # Season filter
    if season:
        df_filtered = df_filtered[df_filtered['Season'].str.lower() == season.lower()]
    
    # Occasion filter
    if occasion:
        df_filtered = df_filtered[df_filtered['AI_Tags_Cleaned'].str.contains(occasion, case=False, na=False)]
    
    # Price filter
    if price_range:
        min_price, max_price = price_range
        df_filtered = df_filtered[(df_filtered['PricePKR'] >= min_price) & (df_filtered['PricePKR'] <= max_price)]
    
    # Build outfit
    outfit = {}
    for part, categories in outfit_parts_map.items():
        part_df = df_filtered[df_filtered['Category'].isin(categories)]
        if not part_df.empty:
            # Randomly select 1 item per outfit part
            outfit[part] = part_df.sample(n=1, random_state=42).iloc[0]
    
    # Combine into a DataFrame for display
    outfit_df = pd.DataFrame([{
        'Part': part,
        'ProductID': item['ProductID'],
        'SellerName': item['SellerName'],
        'Category': item['Category'],
        'SubCategory': item['SubCategory'],
        'ProductName': item['ProductName'],
        'PricePKR': item['PricePKR'],
        'Gender': item['Corrected_Gender'],
        'Material': item['Material'],
        'Season': item['Season'],
        'AI_Tags_Cleaned': item['AI_Tags_Cleaned']
    } for part, item in outfit.items()])
    
    return outfit_df

# --- Example usage ---
outfit = ai_outfit_stylist(gender='Women', season='Summer', occasion='casual', price_range=(1000,15000))
print(outfit)

          Part ProductID        SellerName      Category SubCategory  \
0          Top     P0228  ThreadsAndTrends  Western Wear      Hoodie
1       Bottom     P0228  ThreadsAndTrends  Western Wear      Hoodie
2        Shoes     P0917   OutfitObsession         Shoes    Sneakers
3  Accessories     P1149   StyleHubKarachi        Others         Cap

           ProductName  PricePKR Gender   Material  Season  \
0  Green Cotton Hoodie     14309  Women     Cotton  Summer
1  Green Cotton Hoodie     14309  Women     Cotton  Summer
2  White Wool Sneakers      3504  Women       Wool  Summer
3   Grey Polyester Cap     10954  Women  Polyester  Summer

                          AI_Tags_Cleaned
0  wedding, winter, casual, women, summer
1  wedding, winter, casual, women, summer
2          wedding, casual, summer, women
3    party, casual, winter, women, summer

In [48]:
import pandas as pd

# Load dataset
df = pd.read_csv("FashionHub_products_cleaned.csv")

# Gender-appropriate categories
gender_category_map = {
    'Women': ['Eastern Wear', 'Western Wear', 'Bags & Accessories', 'Jewelry', 'Shoes', 'Others'],
    'Men': ['Western Wear', 'Bags & Accessories', 'Jewelry', 'Shoes', 'Others'],
    'Unisex': ['Western Wear', 'Bags & Accessories', 'Jewelry', 'Shoes', 'Others']
}

# Map categories into outfit parts
outfit_parts_map = {
    'Top': ['Western Wear', 'Eastern Wear'],
    'Bottom': ['Western Wear', 'Eastern Wear'],
    'Shoes': ['Shoes'],
    'Accessories': ['Bags & Accessories', 'Jewelry', 'Others']
}

def ai_outfit_stylist_multi(gender=None, season=None, occasion=None, price_range=None, n_outfits=3):
    """
    Suggests multiple complete outfits: Top + Bottom + Shoes + Accessories
    """
    df_filtered = df.copy()
    
    # Gender filter & allowed categories
    if gender:
        allowed_categories = gender_category_map.get(gender, [])
        df_filtered = df_filtered[
            (df_filtered['Corrected_Gender'] == gender) &
            (df_filtered['Category'].isin(allowed_categories)) &
            (~df_filtered['Category'].str.lower().eq('kids wear'))
        ]
    
    # Season filter
    if season:
        df_filtered = df_filtered[df_filtered['Season'].str.lower() == season.lower()]
    
    # Occasion filter
    if occasion:
        df_filtered = df_filtered[df_filtered['AI_Tags_Cleaned'].str.contains(occasion, case=False, na=False)]
    
    # Price filter
    if price_range:
        min_price, max_price = price_range
        df_filtered = df_filtered[(df_filtered['PricePKR'] >= min_price) & (df_filtered['PricePKR'] <= max_price)]
    
    outfits_list = []
    
    for outfit_index in range(n_outfits):
        outfit = {}
        for part, categories in outfit_parts_map.items():
            part_df = df_filtered[df_filtered['Category'].isin(categories)]
            if not part_df.empty:
                outfit[part] = part_df.sample(n=1, random_state=42+outfit_index).iloc[0]
        
        # Build outfit DataFrame
        outfit_df = pd.DataFrame([{
            'Part': part,
            'ProductID': item['ProductID'],
            'SellerName': item['SellerName'],
            'Category': item['Category'],
            'SubCategory': item['SubCategory'],
            'ProductName': item['ProductName'],
            'PricePKR': item['PricePKR'],
            'Gender': item['Corrected_Gender'],
            'Material': item['Material'],
            'Season': item['Season'],
            'AI_Tags_Cleaned': item['AI_Tags_Cleaned']
        } for part, item in outfit.items()])
        
        outfits_list.append(outfit_df)
    
    return outfits_list

# --- Example usage ---
outfits = ai_outfit_stylist_multi(gender='Women', season='Summer', occasion='casual', price_range=(1000,15000), n_outfits=3)

# Display all outfit options
for idx, outfit in enumerate(outfits):
    print(f"\n--- Outfit Option {idx+1} ---")
    print(outfit)

--- Outfit Option 1 ---
          Part ProductID        SellerName      Category SubCategory  \
0          Top     P0228  ThreadsAndTrends  Western Wear      Hoodie
1       Bottom     P0228  ThreadsAndTrends  Western Wear      Hoodie
2        Shoes     P0917   OutfitObsession         Shoes    Sneakers
3  Accessories     P1149   StyleHubKarachi        Others         Cap

           ProductName  PricePKR Gender   Material  Season  \
0  Green Cotton Hoodie     14309  Women     Cotton  Summer
1  Green Cotton Hoodie     14309  Women     Cotton  Summer
2  White Wool Sneakers      3504  Women       Wool  Summer
3   Grey Polyester Cap     10954  Women  Polyester  Summer

                          AI_Tags_Cleaned
0  wedding, winter, casual, women, summer
1  wedding, winter, casual, women, summer
2          wedding, casual, summer, women
3    party, casual, winter, women, summer

--- Outfit Option 2 ---
          Part ProductID        SellerName      Category SubCategory  \
0          Top     P1137      Sana Safinaz  Eastern Wear       Saree
1       Bottom     P1137      Sana Safinaz  Eastern Wear       Saree
2        Shoes     P1410   StyleHubKarachi         Shoes     Sandals
3  Accessories     P1441  Quetta Style Hub       Jewelry        Ring

           ProductName  PricePKR Gender Material  Season  \
0    White Linen Saree      6526  Women    Linen  Summer
1    White Linen Saree      6526  Women    Linen  Summer
2  Brown Linen Sandals     10953  Women    Linen  Summer
3    Green Cotton Ring      8945  Women   Cotton  Summer

                         AI_Tags_Cleaned
0  casual, trendy, ethnic, women, summer
1  casual, trendy, ethnic, women, summer
2   party, casual, trendy, women, summer
3   trendy, casual, party, women, summer

--- Outfit Option 3 ---
          Part ProductID           SellerName      Category SubCategory  \
0          Top     P0496  Junaid Jamshed (J.)  Western Wear     T-Shirt
1       Bottom     P0496  Junaid Jamshed (J.)  Western Wear     T-Shirt
2        Shoes     P0313    Rawalpindi Styles         Shoes       Heels
3  Accessories     P0576  Multan Cloth Market       Jewelry    Earrings

          ProductName  PricePKR Gender Material  Season  \
0  Pink Denim T-Shirt     11280  Women    Denim  Summer
1  Pink Denim T-Shirt     11280  Women    Denim  Summer
2     Pink Silk Heels     13155  Women     Silk  Summer
3  Grey Wool Earrings     11700  Women     Wool  Summer

                          AI_Tags_Cleaned
0            casual, party, summer, women
1            casual, party, summer, women
2  western, trendy, casual, women, summer
3   ethnic, formal, casual, women, summer

In [49]:
import pandas as pd

# Load the cleaned product dataset
df = pd.read_csv("FashionHub_products_cleaned.csv")

# Define allowed categories per gender
gender_category_map = {
    'men': ['Western Wear', 'Shoes', 'Bags & Accessories', 'Others', 'Jewelry'],
    'women': ['Western Wear', 'Eastern Wear', 'Shoes', 'Bags & Accessories', 'Jewelry', 'Others']
}

def ai_stylist(gender=None, season=None, occasion=None, price_range=None, n=5):
    """
    Recommend products based on AI stylist logic.
    
    Parameters:
    - gender: 'Men', 'Women', 'Unisex' (string)
    - season: 'Summer', 'Winter', 'All-season' (string)
    - occasion: e.g., 'wedding', 'casual', 'party', 'formal' (string)
    - price_range: tuple(min_price, max_price)
    - n: number of products to recommend
    
    Returns:
    - DataFrame of recommended products
    """
    df_filtered = df.copy()
    
    # Gender filter
    if gender:
        gender_lower = gender.lower()
        allowed_categories = gender_category_map.get(gender_lower, [])
        df_filtered = df_filtered[
            (df_filtered['Corrected_Gender'].str.lower() == gender_lower) &
            (~df_filtered['Category'].str.lower().eq('kids wear')) &  # Exclude Kids Wear
            (df_filtered['Category'].isin(allowed_categories))
        ]
    
    # Season filter
    if season:
        df_filtered = df_filtered[df_filtered['Season'].str.lower() == season.lower()]
    
    # Occasion filter
    if occasion:
        df_filtered = df_filtered[df_filtered['AI_Tags_Cleaned'].str.contains(occasion, case=False, na=False)]
    
    # Price range filter
    if price_range:
        min_price, max_price = price_range
        df_filtered = df_filtered[(df_filtered['PricePKR'] >= min_price) & (df_filtered['PricePKR'] <= max_price)]
    
    # Randomize and select top N
    recommendations = df_filtered.sample(n=min(n, len(df_filtered)), random_state=42)
    
    # Return selected features
    return recommendations[[
        'ProductID', 'SellerName', 'Category', 'SubCategory',
        'ProductName', 'PricePKR', 'Corrected_Gender', 'Material',
        'Season', 'AI_Tags_Cleaned'
    ]]

# ---- Example Usage ----
# Recommend 5 products for Women in Summer for casual occasion priced 1000-15000 PKR
sample_recommendations = ai_stylist(gender='Women', season='Summer', occasion='casual', price_range=(1000,15000), n=5)
print(sample_recommendations)

     ProductID         SellerName            Category SubCategory  \
341      P0342    EasternElegance  Bags & Accessories    Backpack
1409     P1410    StyleHubKarachi               Shoes     Sandals
312      P0313  Rawalpindi Styles               Shoes       Heels
1053     P1054             Khaadi  Bags & Accessories     Handbag
29       P0030        ModishMoods             Jewelry        Ring

              ProductName  PricePKR Corrected_Gender Material  Season  \
341    Pink Lawn Backpack      2259            Women     Lawn  Summer
1409  Brown Linen Sandals     10953            Women    Linen  Summer
312       Pink Silk Heels     13155            Women     Silk  Summer
1053   Black Lawn Handbag      7525            Women     Lawn  Summer
29      Pink Leather Ring      9237            Women  Leather  Summer

                             AI_Tags_Cleaned
341    ethnic, formal, casual, women, summer
1409    party, casual, trendy, women, summer
312   western, trendy, casual, women, summer
1053   winter, casual, ethnic, women, summer
29      party, casual, formal, women, summer

In [50]:
import pandas as pd

# Load cleaned dataset
df = pd.read_csv("FashionHub_products_cleaned.csv")

# Define allowed categories for each gender
gender_category_map = {
    'Men': ['Western Wear', 'Shoes', 'Bags & Accessories', 'Others', 'Jewelry'],
    'Women': ['Western Wear', 'Eastern Wear', 'Shoes', 'Bags & Accessories', 'Jewelry', 'Others'],
    'Unisex': ['Western Wear', 'Shoes', 'Bags & Accessories', 'Others', 'Jewelry', 'Eastern Wear']
}

def ai_stylist(gender=None, season=None, occasion=None, price_range=None, n=5):
    """
    Recommend products based on AI Stylist logic.
    
    Parameters:
    - gender: 'Men', 'Women', 'Unisex' (string)
    - season: 'Summer', 'Winter', 'All-season' (string)
    - occasion: e.g., 'wedding', 'casual', 'party', 'formal' (string)
    - price_range: tuple(min_price, max_price)
    - n: number of products to recommend
    
    Returns:
    - DataFrame of recommended products
    """
    
    df_filtered = df.copy()
    
    # Filter by gender and allowed categories
    if gender:
        gender = gender.title()  # standardize
        allowed_categories = gender_category_map.get(gender, [])
        df_filtered = df_filtered[
            (df_filtered['Corrected_Gender'] == gender) &
            (df_filtered['Category'].isin(allowed_categories)) &
            (df_filtered['Category'] != 'Kids Wear')  # skip Kids Wear
        ]
    
    # Filter by season
    if season:
        df_filtered = df_filtered[df_filtered['Season'].str.lower() == season.lower()]
    
    # Filter by occasion (search in AI_Tags_Cleaned)
    if occasion:
        df_filtered = df_filtered[df_filtered['AI_Tags_Cleaned'].str.contains(occasion, case=False, na=False)]
    
    # Filter by price range
    if price_range:
        min_price, max_price = price_range
        df_filtered = df_filtered[(df_filtered['PricePKR'] >= min_price) & (df_filtered['PricePKR'] <= max_price)]
    
    # Randomize and select top N
    recommendations = df_filtered.sample(n=min(n, len(df_filtered)), random_state=42)
    
    # Return selected columns
    return recommendations[['ProductID','SellerName','Category','SubCategory','ProductName',
                            'PricePKR','Corrected_Gender','Material','Season','AI_Tags_Cleaned']]

# ---- Example Usage ----
# Women, Summer, casual occasion, price 1000-15000, top 5
women_recs = ai_stylist(gender='Women', season='Summer', occasion='casual', price_range=(1000,15000), n=5)

# Men, Winter, formal occasion, price 5000-20000, top 5
men_recs = ai_stylist(gender='Men', season='Winter', occasion='formal', price_range=(5000,20000), n=5)

# Display results
print("--- Women Recommendations ---")
print(women_recs)
print("\n--- Men Recommendations ---")
print(men_recs)

--- Women Recommendations ---
     ProductID         SellerName            Category SubCategory  \
341      P0342    EasternElegance  Bags & Accessories    Backpack
1409     P1410    StyleHubKarachi               Shoes     Sandals
312      P0313  Rawalpindi Styles               Shoes       Heels
1053     P1054             Khaadi  Bags & Accessories     Handbag
29       P0030        ModishMoods             Jewelry        Ring

              ProductName  PricePKR Corrected_Gender Material  Season  \
341    Pink Lawn Backpack      2259            Women     Lawn  Summer
1409  Brown Linen Sandals     10953            Women    Linen  Summer
312       Pink Silk Heels     13155            Women     Silk  Summer
1053   Black Lawn Handbag      7525            Women     Lawn  Summer
29      Pink Leather Ring      9237            Women  Leather  Summer

                             AI_Tags_Cleaned
341    ethnic, formal, casual, women, summer
1409    party, casual, trendy, women, summer
312   western, trendy, casual, women, summer
1053   winter, casual, ethnic, women, summer
29      party, casual, formal, women, summer

--- Men Recommendations ---
     ProductID              SellerName      Category SubCategory  \
509      P0510      Chiniot Cloth Mart         Shoes       Heels
820      P0821         EasternElegance        Others         Cap
712      P0713              GlamCartPK        Others   Kids Wear
1312     P1313         TrendyThreadsPK        Others         Cap
11       P0012  Karachi Bazaar Fashion  Western Wear     T-Shirt

                ProductName  PricePKR Corrected_Gender Material  Season  \
509      Black Cotton Heels     19900              Men   Cotton  Winter
820        Blue Leather Cap     17348              Men  Leather  Winter
712   Black Denim Kids Wear     12520              Men    Denim  Winter
1312       Beige Cotton Cap      7475              Men   Cotton  Winter
11     White Cotton T-Shirt     18834              Men   Cotton  Winter

                           AI_Tags_Cleaned
509           winter, western, formal, men
820    summer, casual, formal, men, winter
712           formal, winter, wedding, men
1312  casual, western, formal, men, winter
11             winter, casual, formal, men

In [51]:
import pandas as pd

# Load the cleaned product dataset
df = pd.read_csv("FashionHub_products_cleaned.csv")

def ai_stylist_multi(gender_filters=None, season=None, occasion=None, price_range=None, n=5):
    """
    Recommend products for multiple genders at once.

    Parameters:
    - gender_filters: list of genders, e.g., ['Women', 'Men', 'Kids']
    - season: 'Summer', 'Winter', 'All-season' (optional)
    - occasion: e.g., 'wedding', 'casual', 'party', 'formal' (optional)
    - price_range: tuple(min_price, max_price) (optional)
    - n: number of products per gender

    Returns:
    - Dictionary with keys as gender and values as recommended products DataFrames
    """
    if gender_filters is None:
        gender_filters = ['Women', 'Men', 'Kids']

    recommendations = {}

    for gender in gender_filters:
        df_filtered = df[df['Corrected_Gender'].str.lower() == gender.lower()]

        # Skip 'Kids Wear' for Men/Women
        if gender.lower() in ['men', 'women']:
            df_filtered = df_filtered[~df_filtered['Category'].str.lower().eq('kids wear')]

        if season:
            df_filtered = df_filtered[df_filtered['Season'].str.lower() == season.lower()]

        if occasion:
            df_filtered = df_filtered[df_filtered['AI_Tags_Cleaned'].str.contains(occasion, case=False, na=False)]

        if price_range:
            min_price, max_price = price_range
            df_filtered = df_filtered[(df_filtered['PricePKR'] >= min_price) & (df_filtered['PricePKR'] <= max_price)]

        recommendations[gender] = df_filtered.sample(n=min(n, len(df_filtered)), random_state=42)[
            ['ProductID','SellerName','Category','SubCategory','ProductName','PricePKR','Corrected_Gender','Material','Season','AI_Tags_Cleaned']
        ]

    return recommendations

# --- Example Usage ---
filters = {'season': 'Summer', 'occasion': 'casual', 'price_range': (1000, 15000)}
results = ai_stylist_multi(gender_filters=['Women','Men','Kids'], **filters, n=5)

# Display recommendations for each gender
for gender, df_rec in results.items():
    print(f"\n--- {gender} Recommendations ---")
    print(df_rec)

--- Women Recommendations ---
     ProductID         SellerName            Category SubCategory  \
341      P0342    EasternElegance  Bags & Accessories    Backpack
1409     P1410    StyleHubKarachi               Shoes     Sandals
312      P0313  Rawalpindi Styles               Shoes       Heels
1053     P1054             Khaadi  Bags & Accessories     Handbag
29       P0030        ModishMoods             Jewelry        Ring

              ProductName  PricePKR Corrected_Gender Material  Season  \
341    Pink Lawn Backpack      2259            Women     Lawn  Summer
1409  Brown Linen Sandals     10953            Women    Linen  Summer
312       Pink Silk Heels     13155            Women     Silk  Summer
1053   Black Lawn Handbag      7525            Women     Lawn  Summer
29      Pink Leather Ring      9237            Women  Leather  Summer

                             AI_Tags_Cleaned
341    ethnic, formal, casual, women, summer
1409    party, casual, trendy, women, summer
312   western, trendy, casual, women, summer
1053   winter, casual, ethnic, women, summer
29      party, casual, formal, women, summer

--- Men Recommendations ---
     ProductID           SellerName      Category     SubCategory  \
689      P0690  Junaid Jamshed (J.)  Eastern Wear  Shalwar Kameez
415      P0416          UrbanWearPK         Shoes         Sandals
126      P0127           Generation       Jewelry        Necklace
1353     P1354  Multan Cloth Market        Others             Hat
1534     P1535            Limelight  Eastern Wear  Shalwar Kameez

                        ProductName  PricePKR Corrected_Gender   Material  \
689   Pink Polyester Shalwar Kameez      4106              Men  Polyester
415              Grey Denim Sandals     11621              Men      Denim
126             Black Lawn Necklace      6803              Men       Lawn
1353               Beige Cotton Hat      1030              Men     Cotton
1534  Pink Polyester Shalwar Kameez      1236              Men  Polyester

      Season                       AI_Tags_Cleaned
689   Summer   winter, casual, formal, men, summer
415   Summer           summer, casual, winter, men
126   Summer  western, ethnic, casual, men, summer
1353  Summer           trendy, summer, casual, men
1534  Summer           winter, casual, summer, men

--- Kids Recommendations ---
Empty DataFrame
Columns: [ProductID, SellerName, Category, SubCategory, ProductName, PricePKR, Corrected_Gender, Material, Season, AI_Tags_Cleaned]
Index: []

In [52]:
import pandas as pd

# Load the cleaned product dataset
df = pd.read_csv("FashionHub_products_cleaned.csv")

def ai_stylist_multi(gender_filters=None, season=None, occasion=None, price_range=None, n=5):
    if gender_filters is None:
        gender_filters = ['Women', 'Men', 'Kids']

    recommendations = {}
    for gender in gender_filters:
        df_filtered = df[df['Corrected_Gender'].str.lower() == gender.lower()]

        # Skip 'Kids Wear' for Men/Women
        if gender.lower() in ['men', 'women']:
            df_filtered = df_filtered[~df_filtered['Category'].str.lower().eq('kids wear')]

        if season:
            df_filtered = df_filtered[df_filtered['Season'].str.lower() == season.lower()]

        if occasion:
            df_filtered = df_filtered[df_filtered['AI_Tags_Cleaned'].str.contains(occasion, case=False, na=False)]

        if price_range:
            min_price, max_price = price_range
            df_filtered = df_filtered[(df_filtered['PricePKR'] >= min_price) & (df_filtered['PricePKR'] <= max_price)]

        recommendations[gender] = df_filtered.sample(n=min(n, len(df_filtered)), random_state=42)[
            ['ProductID','SellerName','Category','SubCategory','ProductName','PricePKR','Corrected_Gender','Material','Season','AI_Tags_Cleaned']
        ]

    return recommendations

In [53]:
# Define filters
filters = {
    'season': 'Summer', 
    'occasion': 'casual', 
    'price_range': (1000, 15000)
}

# Get 5 recommendations per gender
results = ai_stylist_multi(gender_filters=['Women','Men','Kids'], **filters, n=5)

# Display recommendations for each gender
for gender, df_rec in results.items():
    print(f"\n--- {gender} Recommendations ---")
    display(df_rec)

--- Women Recommendations ---

,ProductID,SellerName,Category,SubCategory,ProductName,PricePKR,Corrected_Gender,Material,Season,AI_Tags_Cleaned
341,P0342,EasternElegance,Bags & Accessories,Backpack,Pink Lawn Backpack,2259,Women,Lawn,Summer,"ethnic, formal, casual, women, summer"
1409,P1410,StyleHubKarachi,Shoes,Sandals,Brown Linen Sandals,10953,Women,Linen,Summer,"party, casual, trendy, women, summer"
312,P0313,Rawalpindi Styles,Shoes,Heels,Pink Silk Heels,13155,Women,Silk,Summer,"western, trendy, casual, women, summer"
1053,P1054,Khaadi,Bags & Accessories,Handbag,Black Lawn Handbag,7525,Women,Lawn,Summer,"winter, casual, ethnic, women, summer"
29,P0030,ModishMoods,Jewelry,Ring,Pink Leather Ring,9237,Women,Leather,Summer,"party, casual, formal, women, summer"

--- Men Recommendations ---

,ProductID,SellerName,Category,SubCategory,ProductName,PricePKR,Corrected_Gender,Material,Season,AI_Tags_Cleaned
689,P0690,Junaid Jamshed (J.),Eastern Wear,Shalwar Kameez,Pink Polyester Shalwar Kameez,4106,Men,Polyester,Summer,"winter, casual, formal, men, summer"
415,P0416,UrbanWearPK,Shoes,Sandals,Grey Denim Sandals,11621,Men,Denim,Summer,"summer, casual, winter, men"
126,P0127,Generation,Jewelry,Necklace,Black Lawn Necklace,6803,Men,Lawn,Summer,"western, ethnic, casual, men, summer"
1353,P1354,Multan Cloth Market,Others,Hat,Beige Cotton Hat,1030,Men,Cotton,Summer,"trendy, summer, casual, men"
1534,P1535,Limelight,Eastern Wear,Shalwar Kameez,Pink Polyester Shalwar Kameez,1236,Men,Polyester,Summer,"winter, casual, summer, men"

--- Kids Recommendations ---

Empty DataFrame
Columns: [ProductID, SellerName, Category, SubCategory, ProductName, PricePKR, Corrected_Gender, Material, Season, AI_Tags_Cleaned]
Index: []

In [54]:
import pandas as pd

# Load cleaned dataset
df = pd.read_csv("FashionHub_products_cleaned.csv")

# AI Stylist Function
def ai_stylist_filtered(gender, season=None, occasion=None, price_range=None, n=5):
    """
    Recommend products based on gender and optional filters.
    """
    # Filter by gender first
    df_filtered = df[df['Corrected_Gender'].str.lower() == gender.lower()]

    # Skip 'Kids Wear' for Men/Women
    if gender.lower() in ['men', 'women']:
        df_filtered = df_filtered[~df_filtered['Category'].str.lower().eq('kids wear')]

    # Filter by season
    if season:
        df_filtered = df_filtered[df_filtered['Season'].str.lower() == season.lower()]

    # Filter by occasion (AI_Tags_Cleaned)
    if occasion:
        df_filtered = df_filtered[df_filtered['AI_Tags_Cleaned'].str.contains(occasion, case=False, na=False)]

    # Filter by price range
    if price_range:
        min_price, max_price = price_range
        df_filtered = df_filtered[(df_filtered['PricePKR'] >= min_price) & (df_filtered['PricePKR'] <= max_price)]

    # Randomize and pick top N
    recommendations = df_filtered.sample(n=min(n, len(df_filtered)), random_state=42)
    return recommendations[['ProductID','SellerName','Category','SubCategory','ProductName','PricePKR','Corrected_Gender','Material','Season','AI_Tags_Cleaned']]

# --- Generate Recommendations ---
print("--- Women Recommendations ---")
women_recs = ai_stylist_filtered('Women', season='Summer', occasion='casual', price_range=(1000,15000), n=5)
print(women_recs)

print("\n--- Men Recommendations ---")
men_recs = ai_stylist_filtered('Men', season='Winter', occasion='formal', price_range=(5000,20000), n=5)
print(men_recs)

print("\n--- Unisex Recommendations ---")
unisex_recs = ai_stylist_filtered('Unisex', season='All-season', n=5)
print(unisex_recs)

--- Women Recommendations ---
     ProductID         SellerName            Category SubCategory  \
341      P0342    EasternElegance  Bags & Accessories    Backpack
1409     P1410    StyleHubKarachi               Shoes     Sandals
312      P0313  Rawalpindi Styles               Shoes       Heels
1053     P1054             Khaadi  Bags & Accessories     Handbag
29       P0030        ModishMoods             Jewelry        Ring

              ProductName  PricePKR Corrected_Gender Material  Season  \
341    Pink Lawn Backpack      2259            Women     Lawn  Summer
1409  Brown Linen Sandals     10953            Women    Linen  Summer
312       Pink Silk Heels     13155            Women     Silk  Summer
1053   Black Lawn Handbag      7525            Women     Lawn  Summer
29      Pink Leather Ring      9237            Women  Leather  Summer

                             AI_Tags_Cleaned
341    ethnic, formal, casual, women, summer
1409    party, casual, trendy, women, summer
312   western, trendy, casual, women, summer
1053   winter, casual, ethnic, women, summer
29      party, casual, formal, women, summer

--- Men Recommendations ---
     ProductID               SellerName      Category   SubCategory  \
776      P0777  Faisalabad Fabric Point        Others     Kids Wear
681      P0682                Beechtree  Eastern Wear         Abaya
305      P0306     Ethnic by Outfitters  Western Wear       T-Shirt
1355     P1356      Multan Cloth Market         Shoes  Formal Shoes
1524     P1525          StyleHubKarachi  Eastern Wear         Saree

                    ProductName  PricePKR Corrected_Gender   Material  Season  \
776   Black Polyester Kids Wear      7321              Men  Polyester  Winter
681           Yellow Lawn Abaya      8982              Men       Lawn  Winter
305      Blue Polyester T-Shirt      7682              Men  Polyester  Winter
1355    Grey Linen Formal Shoes     18980              Men      Linen  Winter
1524         Beige Cotton Saree     17133              Men     Cotton  Winter

                          AI_Tags_Cleaned
776          western, winter, formal, men
681            formal, winter, party, men
305   formal, western, party, men, winter
1355          formal, ethnic, winter, men
1524          winter, formal, trendy, men

--- Unisex Recommendations ---
     ProductID           SellerName            Category SubCategory  \
1428     P1429          ModishMoods  Bags & Accessories        Belt
855      P0856  Multan Cloth Market        Eastern Wear       Abaya
538      P0539           Generation        Eastern Wear       Abaya
532      P0533           Outfitters  Bags & Accessories     Handbag
1374     P1375   Lahore Trend House  Bags & Accessories      Wallet

                 ProductName  PricePKR Corrected_Gender   Material  \
1428         Beige Wool Belt     10835           Unisex       Wool
855         Brown Silk Abaya     12807           Unisex       Silk
538         Black Wool Abaya     19291           Unisex       Wool
532      Black Denim Handbag     12906           Unisex      Denim
1374  Black Polyester Wallet      9248           Unisex  Polyester

          Season                               AI_Tags_Cleaned
1428  All-season    ethnic, party, wedding, unisex, all-season
855   All-season     party, winter, formal, unisex, all-season
538   All-season    summer, winter, trendy, unisex, all-season
532   All-season  western, wedding, summer, unisex, all-season
1374  All-season    trendy, summer, winter, unisex, all-season

In [55]:
import pandas as pd
from IPython.display import display

# Load cleaned dataset
df = pd.read_csv("FashionHub_products_cleaned.csv")

# AI Stylist Function
def ai_stylist_filtered(gender, season=None, occasion=None, price_range=None, n=5):
    df_filtered = df[df['Corrected_Gender'].str.lower() == gender.lower()]

    # Skip 'Kids Wear' for Men/Women
    if gender.lower() in ['men', 'women']:
        df_filtered = df_filtered[~df_filtered['Category'].str.lower().eq('kids wear')]

    # Filter by season
    if season:
        df_filtered = df_filtered[df_filtered['Season'].str.lower() == season.lower()]

    # Filter by occasion (AI_Tags_Cleaned)
    if occasion:
        df_filtered = df_filtered[df_filtered['AI_Tags_Cleaned'].str.contains(occasion, case=False, na=False)]

    # Filter by price range
    if price_range:
        min_price, max_price = price_range
        df_filtered = df_filtered[(df_filtered['PricePKR'] >= min_price) & (df_filtered['PricePKR'] <= max_price)]

    # Randomize and pick top N
    recommendations = df_filtered.sample(n=min(n, len(df_filtered)), random_state=42)
    return recommendations[['ProductID','SellerName','Category','SubCategory','ProductName','PricePKR','Corrected_Gender','Material','Season','AI_Tags_Cleaned']]

# --- Generate Recommendations ---
women_recs = ai_stylist_filtered('Women', season='Summer', occasion='casual', price_range=(1000,15000), n=5)
men_recs = ai_stylist_filtered('Men', season='Winter', occasion='formal', price_range=(5000,20000), n=5)
unisex_recs = ai_stylist_filtered('Unisex', season='All-season', n=5)

# Add a new column to indicate recommendation type
women_recs['Type'] = 'Women'
men_recs['Type'] = 'Men'
unisex_recs['Type'] = 'Unisex'

# Combine all recommendations
all_recs = pd.concat([women_recs, men_recs, unisex_recs], ignore_index=True)

# Display in Jupyter nicely
display(all_recs)

,ProductID,SellerName,Category,SubCategory,ProductName,PricePKR,Corrected_Gender,Material,Season,AI_Tags_Cleaned,Type
0,P0342,EasternElegance,Bags & Accessories,Backpack,Pink Lawn Backpack,2259,Women,Lawn,Summer,"ethnic, formal, casual, women, summer",Women
1,P1410,StyleHubKarachi,Shoes,Sandals,Brown Linen Sandals,10953,Women,Linen,Summer,"party, casual, trendy, women, summer",Women
2,P0313,Rawalpindi Styles,Shoes,Heels,Pink Silk Heels,13155,Women,Silk,Summer,"western, trendy, casual, women, summer",Women
3,P1054,Khaadi,Bags & Accessories,Handbag,Black Lawn Handbag,7525,Women,Lawn,Summer,"winter, casual, ethnic, women, summer",Women
4,P0030,ModishMoods,Jewelry,Ring,Pink Leather Ring,9237,Women,Leather,Summer,"party, casual, formal, women, summer",Women
5,P0777,Faisalabad Fabric Point,Others,Kids Wear,Black Polyester Kids Wear,7321,Men,Polyester,Winter,"western, winter, formal, men",Men
6,P0682,Beechtree,Eastern Wear,Abaya,Yellow Lawn Abaya,8982,Men,Lawn,Winter,"formal, winter, party, men",Men
7,P0306,Ethnic by Outfitters,Western Wear,T-Shirt,Blue Polyester T-Shirt,7682,Men,Polyester,Winter,"formal, western, party, men, winter",Men
8,P1356,Multan Cloth Market,Shoes,Formal Shoes,Grey Linen Formal Shoes,18980,Men,Linen,Winter,"formal, ethnic, winter, men",Men
9,P1525,StyleHubKarachi,Eastern Wear,Saree,Beige Cotton Saree,17133,Men,Cotton,Winter,"winter, formal, trendy, men",Men
10,P1429,ModishMoods,Bags & Accessories,Belt,Beige Wool Belt,10835,Unisex,Wool,All-season,"ethnic, party, wedding, unisex, all-season",Unisex
11,P0856,Multan Cloth Market,Eastern Wear,Abaya,Brown Silk Abaya,12807,Unisex,Silk,All-season,"party, winter, formal, unisex, all-season",Unisex
12,P0539,Generation,Eastern Wear,Abaya,Black Wool Abaya,19291,Unisex,Wool,All-season,"summer, winter, trendy, unisex, all-season",Unisex
13,P0533,Outfitters,Bags & Accessories,Handbag,Black Denim Handbag,12906,Unisex,Denim,All-season,"western, wedding, summer, unisex, all-season",Unisex
14,P1375,Lahore Trend House,Bags & Accessories,Wallet,Black Polyester Wallet,9248,Unisex,Polyester,All-season,"trendy, summer, winter, unisex, all-season",Unisex

In [56]:
import pandas as pd

# Load the cleaned dataset
df = pd.read_csv("FashionHub_products_cleaned.csv")

def ai_stylist_filtered(gender, season=None, occasion=None, price_range=None, n=5):
    """
    Recommend products based on user-selected gender and optional filters.
    """
    # Filter by gender first
    df_filtered = df[df['Corrected_Gender'].str.lower() == gender.lower()]

    # Skip 'Kids Wear' for Men/Women
    if gender.lower() in ['men', 'women']:
        df_filtered = df_filtered[~df_filtered['Category'].str.lower().eq('kids wear')]

    # Filter by season
    if season:
        df_filtered = df_filtered[df_filtered['Season'].str.lower() == season.lower()]

    # Filter by occasion (check AI_Tags_Cleaned)
    if occasion:
        df_filtered = df_filtered[df_filtered['AI_Tags_Cleaned'].str.contains(occasion, case=False, na=False)]

    # Filter by price range
    if price_range:
        min_price, max_price = price_range
        df_filtered = df_filtered[(df_filtered['PricePKR'] >= min_price) & (df_filtered['PricePKR'] <= max_price)]

    # Randomize and pick top N
    recommendations = df_filtered.sample(n=min(n, len(df_filtered)), random_state=42)

    return recommendations[['ProductID','SellerName','Category','SubCategory','ProductName','PricePKR','Corrected_Gender','Material','Season','AI_Tags_Cleaned']]

# --- Generate recommendations ---
women_rec = ai_stylist_filtered(gender='Women', season='Summer', occasion='casual', price_range=(1000,15000), n=5)
men_rec = ai_stylist_filtered(gender='Men', season='Summer', occasion='casual', price_range=(1000,15000), n=5)
unisex_rec = ai_stylist_filtered(gender='Unisex', season='Summer', occasion='casual', price_range=(1000,15000), n=5)

# --- Display side-by-side in Jupyter ---
from IPython.display import display, HTML

display(HTML("<h3>Women Recommendations</h3>"))
display(women_rec)

display(HTML("<h3>Men Recommendations</h3>"))
display(men_rec)

display(HTML("<h3>Unisex Recommendations</h3>"))
display(unisex_rec)

,ProductID,SellerName,Category,SubCategory,ProductName,PricePKR,Corrected_Gender,Material,Season,AI_Tags_Cleaned
341,P0342,EasternElegance,Bags & Accessories,Backpack,Pink Lawn Backpack,2259,Women,Lawn,Summer,"ethnic, formal, casual, women, summer"
1409,P1410,StyleHubKarachi,Shoes,Sandals,Brown Linen Sandals,10953,Women,Linen,Summer,"party, casual, trendy, women, summer"
312,P0313,Rawalpindi Styles,Shoes,Heels,Pink Silk Heels,13155,Women,Silk,Summer,"western, trendy, casual, women, summer"
1053,P1054,Khaadi,Bags & Accessories,Handbag,Black Lawn Handbag,7525,Women,Lawn,Summer,"winter, casual, ethnic, women, summer"
29,P0030,ModishMoods,Jewelry,Ring,Pink Leather Ring,9237,Women,Leather,Summer,"party, casual, formal, women, summer"

,ProductID,SellerName,Category,SubCategory,ProductName,PricePKR,Corrected_Gender,Material,Season,AI_Tags_Cleaned
689,P0690,Junaid Jamshed (J.),Eastern Wear,Shalwar Kameez,Pink Polyester Shalwar Kameez,4106,Men,Polyester,Summer,"winter, casual, formal, men, summer"
415,P0416,UrbanWearPK,Shoes,Sandals,Grey Denim Sandals,11621,Men,Denim,Summer,"summer, casual, winter, men"
126,P0127,Generation,Jewelry,Necklace,Black Lawn Necklace,6803,Men,Lawn,Summer,"western, ethnic, casual, men, summer"
1353,P1354,Multan Cloth Market,Others,Hat,Beige Cotton Hat,1030,Men,Cotton,Summer,"trendy, summer, casual, men"
1534,P1535,Limelight,Eastern Wear,Shalwar Kameez,Pink Polyester Shalwar Kameez,1236,Men,Polyester,Summer,"winter, casual, summer, men"

,ProductID,SellerName,Category,SubCategory,ProductName,PricePKR,Corrected_Gender,Material,Season,AI_Tags_Cleaned
705,P0706,StyleHubKarachi,Shoes,Formal Shoes,White Lawn Formal Shoes,11304,Unisex,Lawn,Summer,"trendy, summer, casual, unisex"
134,P0135,Lahore Trend House,Eastern Wear,Shalwar Kameez,Red Silk Shalwar Kameez,3640,Unisex,Silk,Summer,"casual, winter, trendy, unisex, summer"
749,P0750,Sana Safinaz,Eastern Wear,Shalwar Kameez,Red Cotton Shalwar Kameez,6774,Unisex,Cotton,Summer,"casual, ethnic, wedding, unisex, summer"
210,P0211,OutfitObsession,Jewelry,Necklace,Beige Wool Necklace,1572,Unisex,Wool,Summer,"ethnic, casual, wedding, unisex, summer"
314,P0315,Karachi Bazaar Fashion,Eastern Wear,Shalwar Kameez,Pink Wool Shalwar Kameez,7426,Unisex,Wool,Summer,"formal, ethnic, casual, unisex, summer"

In [57]:
import pandas as pd

# Load the cleaned product dataset
df = pd.read_csv("FashionHub_products_cleaned.csv")

def ai_stylist_filtered(gender, season=None, occasion=None, price_range=None, n=5, sort_by=None, trending=False):
    """
    Recommend products based on user-selected gender and optional filters.
    
    Parameters:
    - gender: 'Women', 'Men', 'Kids', 'Unisex'
    - season: 'Summer', 'Winter', 'All-season' (optional)
    - occasion: e.g., 'wedding', 'casual', 'party', 'formal' (optional)
    - price_range: tuple(min_price, max_price) (optional)
    - n: number of products to recommend
    - sort_by: 'price_low_to_high', 'price_high_to_low', 'latest', None (optional)
    - trending: bool, if True prioritize trending/popular items (optional)
    
    Returns:
    - DataFrame of recommended products
    """
    df_filtered = df[df['Corrected_Gender'].str.lower() == gender.lower()]

    # Skip 'Kids Wear' for Men/Women
    if gender.lower() in ['men', 'women']:
        df_filtered = df_filtered[~df_filtered['Category'].str.lower().eq('kids wear')]

    # Filter by season
    if season:
        df_filtered = df_filtered[df_filtered['Season'].str.lower() == season.lower()]

    # Filter by occasion
    if occasion:
        df_filtered = df_filtered[df_filtered['AI_Tags_Cleaned'].str.contains(occasion, case=False, na=False)]

    # Filter by price range
    if price_range:
        min_price, max_price = price_range
        df_filtered = df_filtered[(df_filtered['PricePKR'] >= min_price) & (df_filtered['PricePKR'] <= max_price)]

    # Apply trending/popularity filter if available
    if trending and 'PopularityScore' in df_filtered.columns:
        df_filtered = df_filtered.sort_values('PopularityScore', ascending=False)
    else:
        # Sorting options
        if sort_by == 'price_low_to_high':
            df_filtered = df_filtered.sort_values('PricePKR', ascending=True)
        elif sort_by == 'price_high_to_low':
            df_filtered = df_filtered.sort_values('PricePKR', ascending=False)
        elif sort_by == 'latest':
            df_filtered = df_filtered.sort_values('ProductID', ascending=False)
        else:
            df_filtered = df_filtered.sample(frac=1, random_state=42)  # random if no sort

    # Pick top N
    recommendations = df_filtered.head(n)

    return recommendations[['ProductID','SellerName','Category','SubCategory',
                            'ProductName','PricePKR','Corrected_Gender','Material','Season','AI_Tags_Cleaned']]

# --- Example Usage ---
sample_recommendations = ai_stylist_filtered(
    gender='Women', 
    season='Summer', 
    occasion='casual', 
    price_range=(1000,15000), 
    n=5,
    sort_by='price_low_to_high',
    trending=True
)
print(sample_recommendations)

    ProductID           SellerName            Category   SubCategory  \
88      P0089     Quetta Style Hub        Eastern Wear         Abaya
341     P0342      EasternElegance  Bags & Accessories      Backpack
78      P0079  Multan Cloth Market        Western Wear  Formal Shirt
916     P0917      OutfitObsession               Shoes      Sneakers
813     P0814      StyleHubKarachi        Eastern Wear         Saree

                 ProductName  PricePKR Corrected_Gender Material  Season  \
88           Pink Lawn Abaya      2040            Women     Lawn  Summer
341       Pink Lawn Backpack      2259            Women     Lawn  Summer
78   Beige Wool Formal Shirt      3469            Women     Wool  Summer
916      White Wool Sneakers      3504            Women     Wool  Summer
813         Green Lawn Saree      3690            Women     Lawn  Summer

                            AI_Tags_Cleaned
88     party, formal, casual, women, summer
341   ethnic, formal, casual, women, summer
78   ethnic, western, casual, women, summer
916          wedding, casual, summer, women
813    trendy, casual, party, women, summer

In [58]:
import pandas as pd
from IPython.display import display, HTML

# Load dataset
df = pd.read_csv("FashionHub_products_cleaned.csv")

def ai_stylist_dashboard(gender, season=None, occasion=None, price_range=None, n=5):
    # Filter by gender
    df_filtered = df[df['Corrected_Gender'].str.lower() == gender.lower()]
    if gender.lower() in ['men', 'women']:
        df_filtered = df_filtered[~df_filtered['Category'].str.lower().eq('kids wear')]
    if season:
        df_filtered = df_filtered[df_filtered['Season'].str.lower() == season.lower()]
    if occasion:
        df_filtered = df_filtered[df_filtered['AI_Tags_Cleaned'].str.contains(occasion, case=False, na=False)]
    if price_range:
        min_price, max_price = price_range
        df_filtered = df_filtered[(df_filtered['PricePKR'] >= min_price) & (df_filtered['PricePKR'] <= max_price)]
    
    recommendations = df_filtered.sample(n=min(n, len(df_filtered)), random_state=42)
    
    # Use Pandas Styler to make a nice table
    styled = (recommendations[['ProductID','SellerName','Category','SubCategory','ProductName','PricePKR','Material','Season','AI_Tags_Cleaned']]
              .style
              .set_table_styles([
                  {'selector':'th','props':[('background-color','#4CAF50'),('color','white'),('font-size','12pt')]},
                  {'selector':'td','props':[('font-size','11pt'),('padding','6px')]}
              ])
              .set_properties(**{'text-align':'center'})
              .highlight_max(subset=['PricePKR'], color='lightcoral')
              .highlight_min(subset=['PricePKR'], color='lightgreen'))
    
    display(HTML(f"<h3>AI Stylist Recommendations for {gender}</h3>"))
    display(styled)

# --- Example usage ---
ai_stylist_dashboard(gender='Women', season='Summer', occasion='casual', price_range=(1000,15000))
ai_stylist_dashboard(gender='Men', season='Winter', occasion='formal')

In [59]:
import pandas as pd

# Load dataset
df = pd.read_csv("FashionHub_products_cleaned.csv")

# Allowed categories for each gender
allowed_categories = {
    'men': ['Western Wear', 'Shoes', 'Bags & Accessories', 'Others', 'Jewelry'],  # exclude Kids Wear, Abaya, Saree
    'women': ['Eastern Wear', 'Western Wear', 'Shoes', 'Bags & Accessories', 'Others', 'Jewelry'],  # exclude Kids Wear
    'kids': ['Kids Wear', 'Others']
}

def ai_stylist_filtered_clean(gender, season=None, occasion=None, price_range=None, n=5):
    gender_lower = gender.lower()
    df_filtered = df[df['Corrected_Gender'].str.lower() == gender_lower]

    # Keep only allowed categories
    df_filtered = df_filtered[df_filtered['Category'].isin(allowed_categories.get(gender_lower, []))]

    # Filter by season
    if season:
        df_filtered = df_filtered[df_filtered['Season'].str.lower() == season.lower()]
    # Filter by occasion
    if occasion:
        df_filtered = df_filtered[df_filtered['AI_Tags_Cleaned'].str.contains(occasion, case=False, na=False)]
    # Filter by price range
    if price_range:
        min_price, max_price = price_range
        df_filtered = df_filtered[(df_filtered['PricePKR'] >= min_price) & (df_filtered['PricePKR'] <= max_price)]

    # Random sample for recommendation
    return df_filtered.sample(n=min(n, len(df_filtered)), random_state=42)[
        ['ProductID','SellerName','Category','SubCategory','ProductName','PricePKR','Corrected_Gender','Material','Season','AI_Tags_Cleaned']
    ]

# Example usage: Recommend 5 Men products, Winter, formal
recommendations_men = ai_stylist_filtered_clean('Men', season='Winter', occasion='formal', n=5)
print(recommendations_men)

     ProductID               SellerName            Category   SubCategory  \
1529     P1530               GlamCartPK  Bags & Accessories          Belt
712      P0713               GlamCartPK              Others     Kids Wear
1244     P1245          EasternElegance               Shoes      Sneakers
1355     P1356      Multan Cloth Market               Shoes  Formal Shoes
776      P0777  Faisalabad Fabric Point              Others     Kids Wear

                    ProductName  PricePKR Corrected_Gender   Material  Season  \
1529         Yellow Cotton Belt      7612              Men     Cotton  Winter
712       Black Denim Kids Wear     12520              Men      Denim  Winter
1244      White Cotton Sneakers      8822              Men     Cotton  Winter
1355    Grey Linen Formal Shoes     18980              Men      Linen  Winter
776   Black Polyester Kids Wear      7321              Men  Polyester  Winter

                           AI_Tags_Cleaned
1529  trendy, formal, wedding, men, winter
712           formal, winter, wedding, men
1244          winter, formal, wedding, men
1355           formal, ethnic, winter, men
776           western, winter, formal, men

In [60]:
# Allowed categories per gender
allowed_categories = {
    'men': ['Western Wear', 'Shoes', 'Bags & Accessories', 'Others', 'Jewelry'],  # exclude Kids Wear
    'women': ['Eastern Wear', 'Western Wear', 'Shoes', 'Bags & Accessories', 'Others', 'Jewelry'],  # exclude Kids Wear
    'kids': ['Kids Wear', 'Others']
}

# Filter dataset
gender_lower = 'men'
df_filtered = df[df['Corrected_Gender'].str.lower() == gender_lower]

# Keep only allowed categories
df_filtered = df_filtered[df_filtered['Category'].isin(allowed_categories[gender_lower])]

print(df_filtered)

     ProductID SellerID               SellerName            Category  \
0        P0001     S001        Okara Dress House              Others
4        P0005     S002                Limelight  Bags & Accessories
6        P0007     S003  Faisalabad Fabric Point        Western Wear
8        P0009     S003  Faisalabad Fabric Point  Bags & Accessories
11       P0012     S004   Karachi Bazaar Fashion        Western Wear
...        ...      ...                      ...                 ...
1540     P1541     S428             Cross Stitch        Western Wear
1546     P1547     S430             Sana Safinaz             Jewelry
1550     P1551     S430             Sana Safinaz        Western Wear
1552     P1553     S431               KurtiCraze             Jewelry
1556     P1557     S432            DailyFitStyle               Shoes

     SubCategory            ProductName  PricePKR Gender  Color   Material  \
0            Cap    White Polyester Cap     18057    Men  White  Polyester
4         Wallet   Brown Leather Wallet       887    Men  Brown    Leather
6         Hoodie      Green Lawn Hoodie     12948    Men  Green       Lawn
8           Belt        White Silk Belt      5732    Men  White       Silk
11       T-Shirt   White Cotton T-Shirt     18834    Men  White     Cotton
...          ...                    ...       ...    ...    ...        ...
1540     T-Shirt     Brown Wool T-Shirt     11986    Men  Brown       Wool
1546    Necklace     Pink Lawn Necklace      7062    Men   Pink       Lawn
1550       Jeans  Green Polyester Jeans     17886    Men  Green  Polyester
1552    Earrings    Beige Silk Earrings     18549    Men  Beige       Silk
1556       Heels     Black Cotton Heels      1385    Men  Black     Cotton

          Season  StockQty                   AI_Tags Corrected_Gender  \
0     All-season       245    summer, ethnic, casual              Men
4         Winter       386     formal, party, winter              Men
6         Summer       179  western, wedding, formal              Men
8         Summer       453     party, summer, winter              Men
11        Winter        88    winter, casual, formal              Men
...          ...       ...                       ...              ...
1540      Summer       183    wedding, winter, party              Men
1546      Summer       126  summer, western, wedding              Men
1550      Winter       356     party, ethnic, trendy              Men
1552      Winter       265   ethnic, summer, wedding              Men
1556      Winter       407   winter, ethnic, wedding              Men

                              AI_Tags_Cleaned
0     summer, ethnic, casual, men, all-season
4                  formal, party, winter, men
6       western, wedding, formal, men, summer
8                  party, summer, winter, men
11                winter, casual, formal, men
...                                       ...
1540      wedding, winter, party, men, summer
1546            summer, western, wedding, men
1550       party, ethnic, trendy, men, winter
1552     ethnic, summer, wedding, men, winter
1556             winter, ethnic, wedding, men

[332 rows x 15 columns]

In [61]:
allowed_categories = {
    'men': ['Western Wear', 'Shoes', 'Bags & Accessories', 'Others', 'Jewelry'],  # exclude Kids Wear
    'women': ['Eastern Wear', 'Western Wear', 'Shoes', 'Bags & Accessories', 'Others', 'Jewelry'],  # exclude Kids Wear
    'kids': ['Kids Wear', 'Others']
}

In [62]:
gender_lower = 'men'  # or 'women' based on user selection
df_filtered = df[df['Corrected_Gender'].str.lower() == gender_lower]

# Only keep allowed categories
df_filtered = df_filtered[df_filtered['Category'].isin(allowed_categories[gender_lower])]

# Optional: remove specific subcategories you know are not for that gender
exclude_subcategories = ['Necklace', 'Earrings', 'Abaya', 'Saree']  # for Men
df_filtered = df_filtered[~df_filtered['SubCategory'].isin(exclude_subcategories)]

print(df_filtered)

     ProductID SellerID               SellerName            Category  \
0        P0001     S001        Okara Dress House              Others
4        P0005     S002                Limelight  Bags & Accessories
6        P0007     S003  Faisalabad Fabric Point        Western Wear
8        P0009     S003  Faisalabad Fabric Point  Bags & Accessories
11       P0012     S004   Karachi Bazaar Fashion        Western Wear
...        ...      ...                      ...                 ...
1537     P1538     S427         ThreadsAndTrends  Bags & Accessories
1539     P1540     S428             Cross Stitch             Jewelry
1540     P1541     S428             Cross Stitch        Western Wear
1550     P1551     S430             Sana Safinaz        Western Wear
1556     P1557     S432            DailyFitStyle               Shoes

     SubCategory            ProductName  PricePKR Gender  Color   Material  \
0            Cap    White Polyester Cap     18057    Men  White  Polyester
4         Wallet   Brown Leather Wallet       887    Men  Brown    Leather
6         Hoodie      Green Lawn Hoodie     12948    Men  Green       Lawn
8           Belt        White Silk Belt      5732    Men  White       Silk
11       T-Shirt   White Cotton T-Shirt     18834    Men  White     Cotton
...          ...                    ...       ...    ...    ...        ...
1537     Handbag   Grey Leather Handbag     17915    Men   Grey    Leather
1539        Ring   Black Polyester Ring      6973    Men  Black  Polyester
1540     T-Shirt     Brown Wool T-Shirt     11986    Men  Brown       Wool
1550       Jeans  Green Polyester Jeans     17886    Men  Green  Polyester
1556       Heels     Black Cotton Heels      1385    Men  Black     Cotton

          Season  StockQty                   AI_Tags Corrected_Gender  \
0     All-season       245    summer, ethnic, casual              Men
4         Winter       386     formal, party, winter              Men
6         Summer       179  western, wedding, formal              Men
8         Summer       453     party, summer, winter              Men
11        Winter        88    winter, casual, formal              Men
...          ...       ...                       ...              ...
1537      Summer       117  summer, western, wedding              Men
1539      Summer       134    formal, summer, winter              Men
1540      Summer       183    wedding, winter, party              Men
1550      Winter       356     party, ethnic, trendy              Men
1556      Winter       407   winter, ethnic, wedding              Men

                              AI_Tags_Cleaned
0     summer, ethnic, casual, men, all-season
4                  formal, party, winter, men
6       western, wedding, formal, men, summer
8                  party, summer, winter, men
11                winter, casual, formal, men
...                                       ...
1537            summer, western, wedding, men
1539              formal, summer, winter, men
1540      wedding, winter, party, men, summer
1550       party, ethnic, trendy, men, winter
1556             winter, ethnic, wedding, men

[291 rows x 15 columns]

In [63]:
import pandas as pd

# Load the cleaned product dataset
df = pd.read_csv("FashionHub_products_cleaned.csv")

# Define allowed categories and subcategory exclusions per gender
allowed_categories = {
    'men': ['Western Wear', 'Shoes', 'Bags & Accessories', 'Others', 'Jewelry'],
    'women': ['Eastern Wear', 'Western Wear', 'Shoes', 'Bags & Accessories', 'Others', 'Jewelry'],
    'kids': ['Kids Wear', 'Others']
}

exclude_subcategories = {
    'men': ['Necklace', 'Earrings', 'Abaya', 'Saree', 'Heels'],  # for Men
    'women': [],  # optional exclusions for Women if needed
    'kids': []
}

def ai_stylist_filtered(gender, season=None, occasion=None, price_range=None, n=5):
    """
    Recommend products based on user-selected gender and optional filters.
    """
    gender_lower = gender.lower()
    
    # Filter by gender
    df_filtered = df[df['Corrected_Gender'].str.lower() == gender_lower]
    
    # Keep only allowed categories
    df_filtered = df_filtered[df_filtered['Category'].isin(allowed_categories[gender_lower])]
    
    # Exclude gender-inappropriate subcategories
    df_filtered = df_filtered[~df_filtered['SubCategory'].isin(exclude_subcategories[gender_lower])]
    
    # Filter by season
    if season:
        df_filtered = df_filtered[df_filtered['Season'].str.lower() == season.lower()]
    
    # Filter by occasion (AI_Tags_Cleaned)
    if occasion:
        df_filtered = df_filtered[df_filtered['AI_Tags_Cleaned'].str.contains(occasion, case=False, na=False)]
    
    # Filter by price range
    if price_range:
        min_price, max_price = price_range
        df_filtered = df_filtered[(df_filtered['PricePKR'] >= min_price) & (df_filtered['PricePKR'] <= max_price)]
    
    # Randomize and pick top N
    recommendations = df_filtered.sample(n=min(n, len(df_filtered)), random_state=42)
    
    return recommendations[['ProductID','SellerName','Category','SubCategory','ProductName','PricePKR','Corrected_Gender','Material','Season','AI_Tags_Cleaned']]

# --- Example Usage ---
sample_recommendations = ai_stylist_filtered(gender='Men', season='Winter', occasion='formal', price_range=(1000,15000), n=5)
print(sample_recommendations)

     ProductID               SellerName      Category SubCategory  \
712      P0713               GlamCartPK        Others   Kids Wear
1244     P1245          EasternElegance         Shoes    Sneakers
132      P0133        Rawalpindi Styles        Others         Cap
1286     P1287   Sialkot Fashion Corner  Western Wear     T-Shirt
776      P0777  Faisalabad Fabric Point        Others   Kids Wear

                    ProductName  PricePKR Corrected_Gender   Material  Season  \
712       Black Denim Kids Wear     12520              Men      Denim  Winter
1244      White Cotton Sneakers      8822              Men     Cotton  Winter
132             Blue Cotton Cap      6657              Men     Cotton  Winter
1286          Blue Wool T-Shirt      8750              Men       Wool  Winter
776   Black Polyester Kids Wear      7321              Men  Polyester  Winter

                          AI_Tags_Cleaned
712          formal, winter, wedding, men
1244         winter, formal, wedding, men
132   formal, casual, ethnic, men, winter
1286          winter, formal, ethnic, men
776          western, winter, formal, men

In [64]:
import pandas as pd

# Load your cleaned product dataset
df = pd.read_csv("FashionHub_products_cleaned.csv")

# Define subcategories to exclude for each gender if needed
exclude_subcategories = {
    'men': ['kids wear'],
    'women': ['kids wear'],
    'kids': [],
    'unisex': []
}

def ai_stylist_filtered(gender, season=None, occasion=None, price_range=None, n=5):
    """
    Recommend products based on gender and optional filters.
    
    Parameters:
    - gender: 'Women', 'Men', 'Kids', 'Unisex'
    - season: 'Summer', 'Winter', 'All-season' (optional)
    - occasion: 'wedding', 'casual', 'party', 'formal' (optional)
    - price_range: tuple(min_price, max_price) (optional)
    - n: number of products to recommend
    
    Returns:
    - DataFrame of recommended products
    """
    gender_lower = gender.lower()
    
    # Filter by gender first
    df_filtered = df[df['Corrected_Gender'].str.lower() == gender_lower]
    
    # Skip unwanted subcategories (e.g., Kids Wear for Men/Women)
    if gender_lower in exclude_subcategories:
        df_filtered = df_filtered[~df_filtered['Category'].str.lower().isin(exclude_subcategories[gender_lower])]
    
    # Filter by season
    if season:
        df_filtered = df_filtered[df_filtered['Season'].str.lower() == season.lower()]
    
    # Filter by occasion (check AI_Tags_Cleaned)
    if occasion:
        df_filtered = df_filtered[df_filtered['AI_Tags_Cleaned'].str.contains(occasion, case=False, na=False)]
    
    # Filter by price range
    if price_range:
        min_price, max_price = price_range
        df_filtered = df_filtered[(df_filtered['PricePKR'] >= min_price) & (df_filtered['PricePKR'] <= max_price)]
    
    # Randomize and pick top N
    recommendations = df_filtered.sample(n=min(n, len(df_filtered)), random_state=42)
    
    # Return clean dashboard-ready columns
    return recommendations[['ProductID','SellerName','Category','SubCategory','ProductName','PricePKR','Corrected_Gender','Material','Season','AI_Tags_Cleaned']]

# --- Example Usage ---
# 5 Women products, Summer, casual, price 1000-15000
women_sample = ai_stylist_filtered(gender='Women', season='Summer', occasion='casual', price_range=(1000,15000), n=5)
print("--- Women Recommendations ---")
print(women_sample)

# 5 Men products, Winter, formal, price 1000-15000
men_sample = ai_stylist_filtered(gender='Men', season='Winter', occasion='formal', price_range=(1000,15000), n=5)
print("--- Men Recommendations ---")
print(men_sample)

# Kids recommendations (optional)
kids_sample = ai_stylist_filtered(gender='Kids', n=5)
print("--- Kids Recommendations ---")
print(kids_sample)

--- Women Recommendations ---
     ProductID         SellerName            Category SubCategory  \
341      P0342    EasternElegance  Bags & Accessories    Backpack
1409     P1410    StyleHubKarachi               Shoes     Sandals
312      P0313  Rawalpindi Styles               Shoes       Heels
1053     P1054             Khaadi  Bags & Accessories     Handbag
29       P0030        ModishMoods             Jewelry        Ring

              ProductName  PricePKR Corrected_Gender Material  Season  \
341    Pink Lawn Backpack      2259            Women     Lawn  Summer
1409  Brown Linen Sandals     10953            Women    Linen  Summer
312       Pink Silk Heels     13155            Women     Silk  Summer
1053   Black Lawn Handbag      7525            Women     Lawn  Summer
29      Pink Leather Ring      9237            Women  Leather  Summer

                             AI_Tags_Cleaned
341    ethnic, formal, casual, women, summer
1409    party, casual, trendy, women, summer
312   western, trendy, casual, women, summer
1053   winter, casual, ethnic, women, summer
29      party, casual, formal, women, summer
--- Men Recommendations ---
     ProductID              SellerName            Category     SubCategory  \
1404     P1405           DailyFitStyle             Jewelry        Bracelet
1475     P1476       Okara Dress House        Eastern Wear  Shalwar Kameez
305      P0306    Ethnic by Outfitters        Western Wear         T-Shirt
600      P0601              Outfitters  Bags & Accessories            Belt
1286     P1287  Sialkot Fashion Corner        Western Wear         T-Shirt

                     ProductName  PricePKR Corrected_Gender   Material  \
1404      Yellow Cotton Bracelet      1018              Men     Cotton
1475  Green Linen Shalwar Kameez      7394              Men      Linen
305       Blue Polyester T-Shirt      7682              Men  Polyester
600              Grey Denim Belt      2064              Men      Denim
1286           Blue Wool T-Shirt      8750              Men       Wool

      Season                       AI_Tags_Cleaned
1404  Winter    formal, summer, party, men, winter
1475  Winter           winter, ethnic, formal, men
305   Winter   formal, western, party, men, winter
600   Winter  formal, western, summer, men, winter
1286  Winter           winter, formal, ethnic, men
--- Kids Recommendations ---
Empty DataFrame
Columns: [ProductID, SellerName, Category, SubCategory, ProductName, PricePKR, Corrected_Gender, Material, Season, AI_Tags_Cleaned]
Index: []

In [65]:
import pandas as pd
from IPython.display import display, HTML

# Load dataset (already cleaned)
df = pd.read_csv("FashionHub_products_cleaned.csv")

def ai_stylist_filtered(gender, season=None, occasion=None, price_range=None, n=5):
    # Filter by gender
    df_filtered = df[df['Corrected_Gender'].str.lower() == gender.lower()]
    
    # Skip 'Kids Wear' for Men/Women
    if gender.lower() in ['men', 'women']:
        df_filtered = df_filtered[~df_filtered['Category'].str.lower().eq('kids wear')]
    
    # Filter by season
    if season:
        df_filtered = df_filtered[df_filtered['Season'].str.lower() == season.lower()]
    
    # Filter by occasion (AI_Tags_Cleaned)
    if occasion:
        df_filtered = df_filtered[df_filtered['AI_Tags_Cleaned'].str.contains(occasion, case=False, na=False)]
    
    # Filter by price range
    if price_range:
        min_price, max_price = price_range
        df_filtered = df_filtered[(df_filtered['PricePKR'] >= min_price) & (df_filtered['PricePKR'] <= max_price)]
    
    # Randomize and pick top N
    recommendations = df_filtered.sample(n=min(n, len(df_filtered)), random_state=42)
    
    return recommendations[['ProductID','SellerName','Category','SubCategory','ProductName','PricePKR','Corrected_Gender','Material','Season','AI_Tags_Cleaned']]

# --- Example Usage ---
women_recs = ai_stylist_filtered(gender='Women', season='Summer', occasion='casual', price_range=(1000,15000), n=5)
men_recs = ai_stylist_filtered(gender='Men', season='Winter', occasion='formal', price_range=(1000,20000), n=5)

# Styling for dashboard-like look
def style_recommendations(df):
    return df.style.set_table_styles([
        {'selector': 'thead', 'props': [('background-color', '#4CAF50'), ('color', 'white'), ('font-weight', 'bold')]},
        {'selector': 'tr:nth-child(even)', 'props': [('background-color', '#f2f2f2')]},
        {'selector': 'tr:hover', 'props': [('background-color', '#ddd')]}
    ]).set_properties(**{'text-align': 'center'}).set_caption("AI Stylist Recommendations")

# Display recommendations nicely
display(HTML("<h2>--- Women Recommendations ---</h2>"))
display(style_recommendations(women_recs))

display(HTML("<h2>--- Men Recommendations ---</h2>"))
display(style_recommendations(men_recs))

In [66]:
import pandas as pd

# Load your cleaned dataset
df = pd.read_csv("FashionHub_products_cleaned.csv")

# Function to filter products
def ai_stylist_filtered(gender, n=5):
    df_filtered = df[df['Corrected_Gender'].str.lower() == gender.lower()]
    
    # Skip Kids Wear for Men/Women
    if gender.lower() in ['men', 'women']:
        df_filtered = df_filtered[~df_filtered['Category'].str.lower().eq('kids wear')]
    
    return df_filtered.sample(n=min(n, len(df_filtered)), random_state=42)[
        ['ProductID','SellerName','Category','SubCategory','ProductName','PricePKR','Material','Season','AI_Tags_Cleaned']
    ]

# Get recommendations
women_recs = ai_stylist_filtered('Women', n=5)
men_recs = ai_stylist_filtered('Men', n=5)

# Display nicely
print("----- Women Recommendations -----")
display(women_recs)

print("\n----- Men Recommendations -----")
display(men_recs)

----- Women Recommendations -----

,ProductID,SellerName,Category,SubCategory,ProductName,PricePKR,Material,Season,AI_Tags_Cleaned
1079,P1080,ModishMoods,Jewelry,Ring,Brown Polyester Ring,2440,Polyester,Winter,"party, casual, wedding, women, winter"
1057,P1058,Okara Dress House,Western Wear,Formal Shirt,Red Silk Formal Shirt,13976,Silk,All-season,"party, trendy, winter, women, all-season"
1077,P1078,Alkaram Studio,Jewelry,Earrings,Grey Denim Earrings,16710,Denim,Winter,"ethnic, trendy, western, women, winter"
150,P0151,TheFashionRack,Bags & Accessories,Backpack,Yellow Polyester Backpack,14281,Polyester,Summer,"western, party, summer, women"
137,P0138,Lahore Trend House,Bags & Accessories,Wallet,Blue Silk Wallet,15517,Silk,Winter,"ethnic, casual, party, women, winter"

----- Men Recommendations -----

,ProductID,SellerName,Category,SubCategory,ProductName,PricePKR,Material,Season,AI_Tags_Cleaned
571,P0572,Multan Cloth Market,Eastern Wear,Abaya,Yellow Denim Abaya,11671,Denim,All-season,"ethnic, western, trendy, men, all-season"
1510,P1511,Gujranwala Wardrobe Works,Jewelry,Necklace,Pink Leather Necklace,9386,Leather,Winter,"winter, party, trendy, men"
1541,P1542,Outfitters,Eastern Wear,Shalwar Kameez,Red Leather Shalwar Kameez,11241,Leather,All-season,"trendy, wedding, winter, men, all-season"
351,P0352,Ideas by Gul Ahmed,Western Wear,Hoodie,Pink Linen Hoodie,6983,Linen,All-season,"formal, casual, winter, men, all-season"
237,P0238,OutfitObsession,Eastern Wear,Saree,Red Polyester Saree,13954,Polyester,Summer,"casual, western, trendy, men, summer"

In [67]:
import pandas as pd

# Load your full product dataset (with SellerName included)
df_full = pd.read_csv("FashionHub_products_cleaned.csv")  # Replace with your actual file path

# AI Stylist function
def ai_stylist_filtered(gender, season=None, occasion=None, price_range=None, n=5):
    """
    Recommend products based on gender and optional filters.
    """
    # Filter by gender
    df_filtered = df_full[df_full['Corrected_Gender'].str.lower() == gender.lower()]

    # Skip 'Kids Wear' for Men/Women
    if gender.lower() in ['men', 'women']:
        df_filtered = df_filtered[~df_filtered['Category'].str.lower().eq('kids wear')]

    # Filter by season
    if season:
        df_filtered = df_filtered[df_filtered['Season'].str.lower() == season.lower()]

    # Filter by occasion
    if occasion:
        df_filtered = df_filtered[df_filtered['AI_Tags_Cleaned'].str.contains(occasion, case=False, na=False)]

    # Filter by price
    if price_range:
        min_price, max_price = price_range
        df_filtered = df_filtered[(df_filtered['PricePKR'] >= min_price) & (df_filtered['PricePKR'] <= max_price)]

    # Randomize and pick top N
    recommendations = df_filtered.sample(n=min(n, len(df_filtered)), random_state=42)

    # Return relevant columns
    return recommendations[['ProductID','SellerName','Category','SubCategory','ProductName',
                            'PricePKR','Corrected_Gender','Material','Season','AI_Tags_Cleaned','StockQty']]

# --- Example Usage ---
women_recs = ai_stylist_filtered(gender='Women', season='Summer', occasion='casual', price_range=(1000,15000), n=5)
men_recs   = ai_stylist_filtered(gender='Men', season='Summer', occasion='casual', price_range=(1000,15000), n=5)

print("---- Women Recommendations ----")
print(women_recs.to_string(index=False))

print("\n---- Men Recommendations ----")
print(men_recs.to_string(index=False))

---- Women Recommendations ----
ProductID        SellerName           Category SubCategory         ProductName  PricePKR Corrected_Gender Material Season                        AI_Tags_Cleaned  StockQty
    P0342   EasternElegance Bags & Accessories    Backpack  Pink Lawn Backpack      2259            Women     Lawn Summer  ethnic, formal, casual, women, summer       479
    P1410   StyleHubKarachi              Shoes     Sandals Brown Linen Sandals     10953            Women    Linen Summer   party, casual, trendy, women, summer       181
    P0313 Rawalpindi Styles              Shoes       Heels     Pink Silk Heels     13155            Women     Silk Summer western, trendy, casual, women, summer       275
    P1054            Khaadi Bags & Accessories     Handbag  Black Lawn Handbag      7525            Women     Lawn Summer  winter, casual, ethnic, women, summer        43
    P0030       ModishMoods            Jewelry        Ring   Pink Leather Ring      9237            Women  Leather Summer   party, casual, formal, women, summer       364

---- Men Recommendations ----
ProductID          SellerName     Category    SubCategory                   ProductName  PricePKR Corrected_Gender  Material Season                      AI_Tags_Cleaned  StockQty
    P0690 Junaid Jamshed (J.) Eastern Wear Shalwar Kameez Pink Polyester Shalwar Kameez      4106              Men Polyester Summer  winter, casual, formal, men, summer       126
    P0416         UrbanWearPK        Shoes        Sandals            Grey Denim Sandals     11621              Men     Denim Summer          summer, casual, winter, men       488
    P0127          Generation      Jewelry       Necklace           Black Lawn Necklace      6803              Men      Lawn Summer western, ethnic, casual, men, summer       497
    P1354 Multan Cloth Market       Others            Hat              Beige Cotton Hat      1030              Men    Cotton Summer          trendy, summer, casual, men       235
    P1535           Limelight Eastern Wear Shalwar Kameez Pink Polyester Shalwar Kameez      1236              Men Polyester Summer          winter, casual, summer, men        30

In [68]:
import pandas as pd
from IPython.display import display, HTML

# Load your cleaned product dataset
df = pd.read_csv("FashionHub_products_cleaned.csv")

def ai_stylist_filtered(gender, season=None, occasion=None, price_range=None, n=5):
    """
    Recommend products based on gender, season, occasion, and price.
    Skips 'Kids Wear' for Men/Women.
    """
    df_filtered = df[df['Corrected_Gender'].str.lower() == gender.lower()]

    # Skip Kids Wear
    if gender.lower() in ['men', 'women']:
        df_filtered = df_filtered[~df_filtered['Category'].str.lower().eq('kids wear')]

    # Filter by season
    if season:
        df_filtered = df_filtered[df_filtered['Season'].str.lower() == season.lower()]

    # Filter by occasion
    if occasion:
        df_filtered = df_filtered[df_filtered['AI_Tags_Cleaned'].str.contains(occasion, case=False, na=False)]

    # Filter by price range
    if price_range:
        min_price, max_price = price_range
        df_filtered = df_filtered[(df_filtered['PricePKR'] >= min_price) & (df_filtered['PricePKR'] <= max_price)]

    # Random top-N
    recommendations = df_filtered.sample(n=min(n, len(df_filtered)), random_state=42)

    return recommendations[['ProductID','SellerName','Category','SubCategory','ProductName',
                            'PricePKR','Corrected_Gender','Material','Season','AI_Tags_Cleaned','StockQty']]

# Example: Filtered Men and Women recommendations
men_rec = ai_stylist_filtered(gender='Men', season='Summer', occasion='casual', price_range=(1000,15000), n=5)
women_rec = ai_stylist_filtered(gender='Women', season='Summer', occasion='casual', price_range=(1000,15000), n=5)

# Display side by side nicely
def display_side_by_side(df_list, titles=None):
    html_str = ""
    for i, df in enumerate(df_list):
        title = titles[i] if titles else f"Table {i+1}"
        html_str += f"<div style='display:inline-block; vertical-align:top; margin-right:20px;'>"
        html_str += f"<h3 style='text-align:center'>{title}</h3>"
        html_str += df.to_html(index=False)
        html_str += "</div>"
    display(HTML(html_str))

display_side_by_side([women_rec, men_rec], titles=["Women Recommendations", "Men Recommendations"])

In [69]:
# Export Men and Women recommendations to CSV
men_rec.to_csv("Men_Recommendations.csv", index=False)
women_rec.to_csv("Women_Recommendations.csv", index=False)

print("✅ Men and Women recommendations exported as CSV files successfully!")

✅ Men and Women recommendations exported as CSV files successfully!

In [70]:
import pandas as pd

# Load the cleaned product dataset
df = pd.read_csv("FashionHub_products_cleaned.csv")

def ai_stylist_all(df, n=5):
    """
    Generate top-N recommendations for all products grouped by gender.
    
    Parameters:
    - df: product DataFrame with Corrected_Gender, Season, AI_Tags_Cleaned, etc.
    - n: number of recommendations per gender
    
    Returns:
    - Dictionary with recommendations for each gender
    """
    recommendations = {}
    for gender in df['Corrected_Gender'].unique():
        df_filtered = df[df['Corrected_Gender'].str.lower() == gender.lower()]
        
        # Skip Kids Wear for Men/Women
        if gender.lower() in ['men', 'women']:
            df_filtered = df_filtered[~df_filtered['Category'].str.lower().eq('kids wear')]
        
        # Randomized top-N recommendations
        recommendations[gender] = df_filtered.sample(
            n=min(n, len(df_filtered)), random_state=42
        )[['ProductID','SellerName','Category','SubCategory',
           'ProductName','PricePKR','Corrected_Gender','Material','Season',
           'AI_Tags_Cleaned','StockQty']]
    
    return recommendations

# --- Example usage ---
top_recs = ai_stylist_all(df, n=5)

# Display recommendations nicely
for gender, recs in top_recs.items():
    print(f"--- {gender} Recommendations ---")
    print(recs)
    print("\n")

--- Men Recommendations ---
     ProductID                 SellerName      Category     SubCategory  \
571      P0572        Multan Cloth Market  Eastern Wear           Abaya
1510     P1511  Gujranwala Wardrobe Works       Jewelry        Necklace
1541     P1542                 Outfitters  Eastern Wear  Shalwar Kameez
351      P0352         Ideas by Gul Ahmed  Western Wear          Hoodie
237      P0238            OutfitObsession  Eastern Wear           Saree

                     ProductName  PricePKR Corrected_Gender   Material  \
571           Yellow Denim Abaya     11671              Men      Denim
1510       Pink Leather Necklace      9386              Men    Leather
1541  Red Leather Shalwar Kameez     11241              Men    Leather
351            Pink Linen Hoodie      6983              Men      Linen
237          Red Polyester Saree     13954              Men  Polyester

          Season                           AI_Tags_Cleaned  StockQty
571   All-season  ethnic, western, trendy, men, all-season       125
1510      Winter                winter, party, trendy, men       100
1541  All-season  trendy, wedding, winter, men, all-season       307
351   All-season   formal, casual, winter, men, all-season       214
237       Summer      casual, western, trendy, men, summer       161


--- Women Recommendations ---
     ProductID          SellerName            Category   SubCategory  \
1079     P1080         ModishMoods             Jewelry          Ring
1057     P1058   Okara Dress House        Western Wear  Formal Shirt
1077     P1078      Alkaram Studio             Jewelry      Earrings
150      P0151      TheFashionRack  Bags & Accessories      Backpack
137      P0138  Lahore Trend House  Bags & Accessories        Wallet

                    ProductName  PricePKR Corrected_Gender   Material  \
1079       Brown Polyester Ring      2440            Women  Polyester
1057      Red Silk Formal Shirt     13976            Women       Silk
1077        Grey Denim Earrings     16710            Women      Denim
150   Yellow Polyester Backpack     14281            Women  Polyester
137            Blue Silk Wallet     15517            Women       Silk

          Season                           AI_Tags_Cleaned  StockQty
1079      Winter     party, casual, wedding, women, winter       331
1057  All-season  party, trendy, winter, women, all-season       283
1077      Winter    ethnic, trendy, western, women, winter       406
150       Summer             western, party, summer, women       495
137       Winter      ethnic, casual, party, women, winter       443


--- Unisex Recommendations ---
     ProductID           SellerName      Category SubCategory  \
442      P0443  Junaid Jamshed (J.)       Jewelry        Ring
559      P0560     Quetta Style Hub       Jewelry    Necklace
89       P0090            Limelight       Jewelry        Ring
922      P0923      StyleHubKarachi        Others       Scarf
1224     P1225          ModishMoods  Eastern Wear       Saree

              ProductName  PricePKR Corrected_Gender Material      Season  \
442     White Cotton Ring      5843           Unisex   Cotton  All-season
559   Pink Linen Necklace     12656           Unisex    Linen      Summer
89      Green Cotton Ring     19888           Unisex   Cotton  All-season
922    Beige Cotton Scarf      6864           Unisex   Cotton  All-season
1224     Beige Wool Saree     12576           Unisex     Wool      Summer

                                  AI_Tags_Cleaned  StockQty
442   formal, summer, wedding, unisex, all-season       102
559       wedding, trendy, winter, unisex, summer       186
89     party, summer, wedding, unisex, all-season       339
922    summer, party, wedding, unisex, all-season       287
1224              western, ethnic, summer, unisex        95

In [71]:
import pandas as pd

# --- Step 1: Load your cleaned product dataset ---
df = pd.read_csv("FashionHub_products_cleaned.csv")  # Make sure this file exists

# --- Step 2: Define the AI Stylist recommendation function ---
def ai_stylist_filtered(df, gender, season=None, occasion=None, price_range=None, n=None):
    """
    Recommend products based on gender and optional filters.
    - gender: 'Women', 'Men', 'Unisex'
    - season: 'Summer', 'Winter', 'All-season' (optional)
    - occasion: e.g., 'wedding', 'casual', 'party', 'formal' (optional)
    - price_range: tuple(min_price, max_price) (optional)
    - n: top N products (optional, if None return all matching)
    """
    df_filtered = df[df['Corrected_Gender'].str.lower() == gender.lower()]

    # Skip 'Kids Wear' for Men or Women
    if gender.lower() in ['men', 'women']:
        df_filtered = df_filtered[~df_filtered['Category'].str.lower().eq('kids wear')]

    # Filter by season
    if season:
        df_filtered = df_filtered[df_filtered['Season'].str.lower() == season.lower()]

    # Filter by occasion
    if occasion:
        df_filtered = df_filtered[df_filtered['AI_Tags_Cleaned'].str.contains(occasion, case=False, na=False)]

    # Filter by price range
    if price_range:
        min_price, max_price = price_range
        df_filtered = df_filtered[(df_filtered['PricePKR'] >= min_price) & (df_filtered['PricePKR'] <= max_price)]

    # Randomize and pick top N if specified
    if n:
        df_filtered = df_filtered.sample(n=min(n, len(df_filtered)), random_state=42)

    return df_filtered

# --- Step 3: Generate recommendations for each gender ---
recommendations_men = ai_stylist_filtered(df, gender='Men')
recommendations_women = ai_stylist_filtered(df, gender='Women')
recommendations_unisex = ai_stylist_filtered(df, gender='Unisex')

# --- Step 4: Export each to CSV ---
recommendations_men.to_csv("recommendations_men.csv", index=False)
recommendations_women.to_csv("recommendations_women.csv", index=False)
recommendations_unisex.to_csv("recommendations_unisex.csv", index=False)

print("✅ Recommendations exported for Men, Women, and Unisex!")
print(f"Men: {len(recommendations_men)} products")
print(f"Women: {len(recommendations_women)} products")
print(f"Unisex: {len(recommendations_unisex)} products")

✅ Recommendations exported for Men, Women, and Unisex!
Men: 417 products
Women: 380 products
Unisex: 762 products

In [72]:
pip install streamlit

Requirement already satisfied: streamlit in c:\users\pmls\anaconda3\lib\site-packages (1.37.1)
Requirement already satisfied: altair<6,>=4.0 in c:\users\pmls\anaconda3\lib\site-packages (from streamlit) (5.0.1)
Requirement already satisfied: blinker<2,>=1.0.0 in c:\users\pmls\anaconda3\lib\site-packages (from streamlit) (1.6.2)
Requirement already satisfied: cachetools<6,>=4.0 in c:\users\pmls\anaconda3\lib\site-packages (from streamlit) (5.3.3)
Requirement already satisfied: click<9,>=7.0 in c:\users\pmls\anaconda3\lib\site-packages (from streamlit) (8.1.7)
Requirement already satisfied: numpy<3,>=1.20 in c:\users\pmls\anaconda3\lib\site-packages (from streamlit) (1.26.4)
Requirement already satisfied: packaging<25,>=20 in c:\users\pmls\anaconda3\lib\site-packages (from streamlit) (24.1)
Requirement already satisfied: pandas<3,>=1.3.0 in c:\users\pmls\anaconda3\lib\site-packages (from streamlit) (2.2.2)
Requirement already satisfied: pillow<11,>=7.1.0 in c:\users\pmls\anaconda3\lib\site-packages (from streamlit) (10.4.0)
Requirement already satisfied: protobuf<6,>=3.20 in c:\users\pmls\anaconda3\lib\site-packages (from streamlit) (4.25.3)
Requirement already satisfied: pyarrow>=7.0 in c:\users\pmls\anaconda3\lib\site-packages (from streamlit) (16.1.0)
Requirement already satisfied: requests<3,>=2.27 in c:\users\pmls\anaconda3\lib\site-packages (from streamlit) (2.32.3)
Requirement already satisfied: rich<14,>=10.14.0 in c:\users\pmls\anaconda3\lib\site-packages (from streamlit) (13.7.1)
Requirement already satisfied: tenacity<9,>=8.1.0 in c:\users\pmls\anaconda3\lib\site-packages (from streamlit) (8.2.3)
Requirement already satisfied: toml<2,>=0.10.1 in c:\users\pmls\anaconda3\lib\site-packages (from streamlit) (0.10.2)
Requirement already satisfied: typing-extensions<5,>=4.3.0 in c:\users\pmls\anaconda3\lib\site-packages (from streamlit) (4.11.0)
Requirement already satisfied: gitpython!=3.1.19,<4,>=3.0.7 in c:\users\pmls\anaconda3\lib\site-packages (from streamlit) (3.1.43)
Requirement already satisfied: pydeck<1,>=0.8.0b4 in c:\users\pmls\anaconda3\lib\site-packages (from streamlit) (0.8.0)
Requirement already satisfied: tornado<7,>=6.0.3 in c:\users\pmls\anaconda3\lib\site-packages (from streamlit) (6.4.1)
Requirement already satisfied: watchdog<5,>=2.1.5 in c:\users\pmls\anaconda3\lib\site-packages (from streamlit) (4.0.1)
Requirement already satisfied: jinja2 in c:\users\pmls\anaconda3\lib\site-packages (from altair<6,>=4.0->streamlit) (3.1.4)
Requirement already satisfied: jsonschema>=3.0 in c:\users\pmls\anaconda3\lib\site-packages (from altair<6,>=4.0->streamlit) (4.23.0)
Requirement already satisfied: toolz in c:\users\pmls\anaconda3\lib\site-packages (from altair<6,>=4.0->streamlit) (0.12.0)
Requirement already satisfied: colorama in c:\users\pmls\anaconda3\lib\site-packages (from click<9,>=7.0->streamlit) (0.4.6)
Requirement already satisfied: gitdb<5,>=4.0.1 in c:\users\pmls\anaconda3\lib\site-packages (from gitpython!=3.1.19,<4,>=3.0.7->streamlit) (4.0.7)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\pmls\anaconda3\lib\site-packages (from pandas<3,>=1.3.0->streamlit) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\pmls\anaconda3\lib\site-packages (from pandas<3,>=1.3.0->streamlit) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\pmls\anaconda3\lib\site-packages (from pandas<3,>=1.3.0->streamlit) (2023.3)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\pmls\anaconda3\lib\site-packages (from requests<3,>=2.27->streamlit) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\pmls\anaconda3\lib\site-packages (from requests<3,>=2.27->streamlit) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\pmls\anaconda3\lib\site-packages (from requests<3,>=2.27->streamlit) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\pmls\anaconda3\lib\site-packages (from requests<3,>=2.27->streamlit) (2025.1.31)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\pmls\anaconda3\lib\site-packages (from rich<14,>=10.14.0->streamlit) (2.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\pmls\anaconda3\lib\site-packages (from rich<14,>=10.14.0->streamlit) (2.15.1)
Requirement already satisfied: smmap<5,>=3.0.1 in c:\users\pmls\anaconda3\lib\site-packages (from gitdb<5,>=4.0.1->gitpython!=3.1.19,<4,>=3.0.7->streamlit) (4.0.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\pmls\anaconda3\lib\site-packages (from jinja2->altair<6,>=4.0->streamlit) (2.1.3)
Requirement already satisfied: attrs>=22.2.0 in c:\users\pmls\anaconda3\lib\site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (23.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in c:\users\pmls\anaconda3\lib\site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (2023.7.1)
Requirement already satisfied: referencing>=0.28.4 in c:\users\pmls\anaconda3\lib\site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (0.30.2)
Requirement already satisfied: rpds-py>=0.7.1 in c:\users\pmls\anaconda3\lib\site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (0.10.6)
Requirement already satisfied: mdurl~=0.1 in c:\users\pmls\anaconda3\lib\site-packages (from markdown-it-py>=2.2.0->rich<14,>=10.14.0->streamlit) (0.1.0)
Requirement already satisfied: six>=1.5 in c:\users\pmls\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas<3,>=1.3.0->streamlit) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

In [73]:
import streamlit as st
import pandas as pd

# Load datasets
df = pd.read_csv("FashionHub_products_cleaned.csv")  # Your product dataset

# Function to filter products (same as AI Stylist)
def filter_products(df, gender):
    df_filtered = df[df['Corrected_Gender'].str.lower() == gender.lower()]
    if gender.lower() in ['men', 'women']:
        df_filtered = df_filtered[~df_filtered['Category'].str.lower().eq('kids wear')]
    return df_filtered

# Streamlit Dashboard
st.set_page_config(page_title="FashionHub Recommendations", layout="wide")
st.title("🛍️ FashionHub AI Stylist Recommendations")

tab1, tab2, tab3 = st.tabs(["Women", "Men", "Unisex"])

with tab1:
    st.header("Women Recommendations")
    women_df = filter_products(df, 'Women')
    st.dataframe(women_df)

with tab2:
    st.header("Men Recommendations")
    men_df = filter_products(df, 'Men')
    st.dataframe(men_df)

with tab3:
    st.header("Unisex Recommendations")
    unisex_df = filter_products(df, 'Unisex')
    st.dataframe(unisex_df)

2025-09-24 18:04:47.688
  Warning: to view this Streamlit app on a browser, run it with the following
  command:

    streamlit run C:\Users\PMLS\anaconda3\Lib\site-packages\ipykernel_launcher.py [ARGUMENTS]

In [74]:
import pandas as pd
from IPython.display import display, HTML

# Load your cleaned product dataset
df = pd.read_csv("FashionHub_products_cleaned.csv")  # adjust path if needed

def show_recommendations(df, gender, n=10):
    """Display top-N recommendations for a gender in a nice table."""
    df_filtered = df[df['Corrected_Gender'].str.lower() == gender.lower()]
    
    # Skip 'Kids Wear' for Men/Women
    if gender.lower() in ['men', 'women']:
        df_filtered = df_filtered[~df_filtered['Category'].str.lower().eq('kids wear')]
    
    # Random top-N
    df_top = df_filtered.sample(n=min(n, len(df_filtered)), random_state=42)
    
    display(HTML(f"<h3>{gender} Recommendations</h3>"))
    display(df_top[['ProductID', 'SellerName', 'Category', 'SubCategory', 
                    'ProductName', 'PricePKR', 'StockQty', 'Material', 'Season', 'AI_Tags_Cleaned']])

# Example usage
show_recommendations(df, 'Women', n=5)
show_recommendations(df, 'Men', n=5)

,ProductID,SellerName,Category,SubCategory,ProductName,PricePKR,StockQty,Material,Season,AI_Tags_Cleaned
1079,P1080,ModishMoods,Jewelry,Ring,Brown Polyester Ring,2440,331,Polyester,Winter,"party, casual, wedding, women, winter"
1057,P1058,Okara Dress House,Western Wear,Formal Shirt,Red Silk Formal Shirt,13976,283,Silk,All-season,"party, trendy, winter, women, all-season"
1077,P1078,Alkaram Studio,Jewelry,Earrings,Grey Denim Earrings,16710,406,Denim,Winter,"ethnic, trendy, western, women, winter"
150,P0151,TheFashionRack,Bags & Accessories,Backpack,Yellow Polyester Backpack,14281,495,Polyester,Summer,"western, party, summer, women"
137,P0138,Lahore Trend House,Bags & Accessories,Wallet,Blue Silk Wallet,15517,443,Silk,Winter,"ethnic, casual, party, women, winter"

,ProductID,SellerName,Category,SubCategory,ProductName,PricePKR,StockQty,Material,Season,AI_Tags_Cleaned
571,P0572,Multan Cloth Market,Eastern Wear,Abaya,Yellow Denim Abaya,11671,125,Denim,All-season,"ethnic, western, trendy, men, all-season"
1510,P1511,Gujranwala Wardrobe Works,Jewelry,Necklace,Pink Leather Necklace,9386,100,Leather,Winter,"winter, party, trendy, men"
1541,P1542,Outfitters,Eastern Wear,Shalwar Kameez,Red Leather Shalwar Kameez,11241,307,Leather,All-season,"trendy, wedding, winter, men, all-season"
351,P0352,Ideas by Gul Ahmed,Western Wear,Hoodie,Pink Linen Hoodie,6983,214,Linen,All-season,"formal, casual, winter, men, all-season"
237,P0238,OutfitObsession,Eastern Wear,Saree,Red Polyester Saree,13954,161,Polyester,Summer,"casual, western, trendy, men, summer"

In [75]:
import pandas as pd
from IPython.display import display, HTML

# Load dataset
df = pd.read_csv("FashionHub_products_cleaned.csv")  # Adjust path if needed

def full_dashboard(df, gender_filters=['Women','Men','Unisex'], season=None, occasion=None, price_range=None):
    """
    Display all products in a scrollable, collapsible dashboard by gender.
    """
    html_content = "<h2>FashionHub Recommendations Dashboard</h2>"
    
    for gender in gender_filters:
        df_filtered = df[df['Corrected_Gender'].str.lower() == gender.lower()]
        
        # Skip Kids Wear for Men/Women
        if gender.lower() in ['men', 'women']:
            df_filtered = df_filtered[~df_filtered['Category'].str.lower().eq('kids wear')]
        
        # Apply season filter
        if season:
            df_filtered = df_filtered[df_filtered['Season'].str.lower() == season.lower()]
        
        # Apply occasion filter
        if occasion:
            df_filtered = df_filtered[df_filtered['AI_Tags_Cleaned'].str.contains(occasion, case=False, na=False)]
        
        # Apply price range filter
        if price_range:
            min_price, max_price = price_range
            df_filtered = df_filtered[(df_filtered['PricePKR'] >= min_price) & (df_filtered['PricePKR'] <= max_price)]
        
        # Convert to HTML table
        table_html = df_filtered[['ProductID','SellerName','Category','SubCategory',
                                  'ProductName','PricePKR','StockQty','Material','Season','AI_Tags_Cleaned']]\
                     .to_html(index=False, escape=False)
        
        # Collapsible section for each gender
        html_content += f"""
        <details open>
            <summary style="font-size:18px; font-weight:bold; margin:5px 0;">{gender} Products ({len(df_filtered)})</summary>
            <div style="max-height:400px; overflow:auto; border:1px solid #ccc; padding:5px;">
                {table_html}
            </div>
        </details><br>
        """
    
    display(HTML(html_content))

# --- Example Usage ---
# Display all products for Women, Men, and Unisex
full_dashboard(df)

In [76]:
import pandas as pd

# Load your cleaned product dataset
df = pd.read_csv("FashionHub_products_cleaned.csv")  # Make sure path is correct

def ai_stylist_all_products(df, season=None, occasion=None, price_range=None):
    """
    Generate recommendations for all products, split by gender, with optional filters.
    
    Parameters:
    - df: DataFrame with product data
    - season: 'Summer', 'Winter', 'All-season', etc. (optional)
    - occasion: e.g., 'party', 'casual', 'formal', 'wedding' (optional)
    - price_range: tuple(min_price, max_price) (optional)
    
    Returns:
    - Three DataFrames: Men, Women, Unisex
    """
    
    # Apply filters
    if season:
        df = df[df['Season'].str.lower() == season.lower()]
    if occasion:
        df = df[df['AI_Tags_Cleaned'].str.contains(occasion, case=False, na=False)]
    if price_range:
        min_price, max_price = price_range
        df = df[(df['PricePKR'] >= min_price) & (df['PricePKR'] <= max_price)]
    
    # Men recommendations (skip 'Kids Wear')
    df_men = df[(df['Corrected_Gender'].str.lower() == 'men') & (df['Category'].str.lower() != 'kids wear')]
    
    # Women recommendations (skip 'Kids Wear')
    df_women = df[(df['Corrected_Gender'].str.lower() == 'women') & (df['Category'].str.lower() != 'kids wear')]
    
    # Unisex recommendations
    df_unisex = df[df['Corrected_Gender'].str.lower() == 'unisex']
    
    # Optional: Randomize recommendations
    df_men = df_men.sample(frac=1, random_state=42).reset_index(drop=True)
    df_women = df_women.sample(frac=1, random_state=42).reset_index(drop=True)
    df_unisex = df_unisex.sample(frac=1, random_state=42).reset_index(drop=True)
    
    return df_men, df_women, df_unisex

# --- Example usage ---
men_df, women_df, unisex_df = ai_stylist_all_products(
    df, season='Summer', occasion='casual', price_range=(1000,15000)
)

# Export to CSV
men_df.to_csv("FashionHub_Men_Recommendations_Filtered.csv", index=False)
women_df.to_csv("FashionHub_Women_Recommendations_Filtered.csv", index=False)
unisex_df.to_csv("FashionHub_Unisex_Recommendations_Filtered.csv", index=False)

print("✅ Filtered recommendations exported successfully:")
print(f"Men: {len(men_df)} products")
print(f"Women: {len(women_df)} products")
print(f"Unisex: {len(unisex_df)} products")

✅ Filtered recommendations exported successfully:
Men: 37 products
Women: 28 products
Unisex: 55 products

In [77]:
import pandas as pd

# Load dataset
df = pd.read_csv("FashionHub_products_cleaned.csv")

def ai_stylist_export(df, gender, season=None, occasion=None, price_range=None):
    """
    Generate recommendations for a gender and optionally filter.
    Returns a DataFrame and exports it to CSV.
    """
    df_filtered = df[df['Corrected_Gender'].str.lower() == gender.lower()]
    
    # Skip Kids Wear for Men/Women
    if gender.lower() in ['men', 'women']:
        df_filtered = df_filtered[~df_filtered['Category'].str.lower().eq('kids wear')]
    
    # Apply season filter
    if season:
        df_filtered = df_filtered[df_filtered['Season'].str.lower() == season.lower()]
    
    # Apply occasion filter
    if occasion:
        df_filtered = df_filtered[df_filtered['AI_Tags_Cleaned'].str.contains(occasion, case=False, na=False)]
    
    # Apply price filter
    if price_range:
        min_price, max_price = price_range
        df_filtered = df_filtered[(df_filtered['PricePKR'] >= min_price) & (df_filtered['PricePKR'] <= max_price)]
    
    # Select columns to display/export
    display_cols = ['ProductID','SellerName','Category','SubCategory','ProductName','PricePKR','Corrected_Gender','Material','Season','StockQty','AI_Tags_Cleaned']
    df_export = df_filtered[display_cols]
    
    # Export CSV
    csv_name = f"{gender}_recommendations.csv"
    df_export.to_csv(csv_name, index=False)
    print(f"{csv_name} exported with {len(df_export)} products.")
    
    return df_export

# --- Generate and export for all genders ---
df_women = ai_stylist_export(df, gender='Women')
df_men = ai_stylist_export(df, gender='Men')
df_unisex = ai_stylist_export(df, gender='Unisex')

# Optional: Display first 5 products for quick check
display(df_women.head())
display(df_men.head())
display(df_unisex.head())

Women_recommendations.csv exported with 380 products.
Men_recommendations.csv exported with 417 products.
Unisex_recommendations.csv exported with 762 products.

,ProductID,SellerName,Category,SubCategory,ProductName,PricePKR,Corrected_Gender,Material,Season,StockQty,AI_Tags_Cleaned
1,P0002,Okara Dress House,Bags & Accessories,Wallet,Yellow Polyester Wallet,11044,Women,Polyester,Summer,119,"formal, party, summer, women"
3,P0004,Limelight,Western Wear,T-Shirt,Yellow Wool T-Shirt,13215,Women,Wool,Winter,461,"trendy, casual, wedding, women, winter"
10,P0011,Faisalabad Fabric Point,Eastern Wear,Abaya,Black Wool Abaya,15601,Women,Wool,All-season,53,"summer, winter, western, women, all-season"
13,P0014,Chiniot Cloth Mart,Bags & Accessories,Wallet,White Denim Wallet,10394,Women,Denim,Winter,255,"formal, casual, wedding, women, winter"
16,P0017,Ethnic by Outfitters,Eastern Wear,Shalwar Kameez,Red Polyester Shalwar Kameez,10054,Women,Polyester,All-season,461,"western, ethnic, winter, women, all-season"

,ProductID,SellerName,Category,SubCategory,ProductName,PricePKR,Corrected_Gender,Material,Season,StockQty,AI_Tags_Cleaned
0,P0001,Okara Dress House,Others,Cap,White Polyester Cap,18057,Men,Polyester,All-season,245,"summer, ethnic, casual, men, all-season"
4,P0005,Limelight,Bags & Accessories,Wallet,Brown Leather Wallet,887,Men,Leather,Winter,386,"formal, party, winter, men"
6,P0007,Faisalabad Fabric Point,Western Wear,Hoodie,Green Lawn Hoodie,12948,Men,Lawn,Summer,179,"western, wedding, formal, men, summer"
8,P0009,Faisalabad Fabric Point,Bags & Accessories,Belt,White Silk Belt,5732,Men,Silk,Summer,453,"party, summer, winter, men"
11,P0012,Karachi Bazaar Fashion,Western Wear,T-Shirt,White Cotton T-Shirt,18834,Men,Cotton,Winter,88,"winter, casual, formal, men"

,ProductID,SellerName,Category,SubCategory,ProductName,PricePKR,Corrected_Gender,Material,Season,StockQty,AI_Tags_Cleaned
2,P0003,Okara Dress House,Western Wear,T-Shirt,Green Leather T-Shirt,1628,Unisex,Leather,Summer,229,"ethnic, casual, wedding, unisex, summer"
5,P0006,Limelight,Jewelry,Earrings,Blue Linen Earrings,17571,Unisex,Linen,All-season,389,"wedding, casual, ethnic, unisex, all-season"
7,P0008,Faisalabad Fabric Point,Western Wear,Maxi Dress,Beige Silk Maxi Dress,3152,Unisex,Silk,Summer,97,"formal, wedding, summer, unisex"
9,P0010,Faisalabad Fabric Point,Jewelry,Necklace,Pink Wool Necklace,3101,Unisex,Wool,All-season,286,"ethnic, formal, trendy, unisex, all-season"
12,P0013,Karachi Bazaar Fashion,Shoes,Sandals,Beige Polyester Sandals,9380,Unisex,Polyester,All-season,80,"formal, party, wedding, unisex, all-season"

In [78]:
import pandas as pd

class FashionHubRecommender:
    def __init__(self, product_csv_path):
        # Load product dataset
        self.df = pd.read_csv(product_csv_path)

        # Clean AI tags column (handle missing values)
        self.df['AI_Tags_Cleaned'] = self.df['AI_Tags_Cleaned'].fillna('').astype(str)

    def recommend(self, gender=None, season=None, selected_tags=None, top_n=10):
        """
        Recommend products based on gender, season, and AI tags.

        Parameters:
        - gender: str ("Men", "Women", "Unisex") or None
        - season: str ("Summer", "Winter", etc.) or None
        - selected_tags: list of tags (["casual", "party", "ethnic"]) or None
        - top_n: int (number of results to return)

        Returns:
        - DataFrame of top recommended products
        """
        df_filtered = self.df.copy()

        # --- Apply filters ---
        if gender:
            df_filtered = df_filtered[df_filtered['Gender'].str.lower() == gender.lower()]

        if season:
            df_filtered = df_filtered[df_filtered['Season'].str.lower() == season.lower()]

        # --- Scoring function ---
        def tag_score(product_tags):
            if not selected_tags:
                return 0
            product_tags_set = set([t.strip().lower() for t in product_tags.split(',') if t.strip()])
            return len(product_tags_set.intersection(set([t.lower() for t in selected_tags])))

        df_filtered['Score'] = df_filtered['AI_Tags_Cleaned'].apply(tag_score)

        # --- Sort by score (highest first) ---
        df_sorted = df_filtered.sort_values(by='Score', ascending=False)

        # --- Return top N products ---
        return df_sorted.head(top_n)[
            ['ProductID', 'ProductName', 'PricePKR', 'SellerName', 'AI_Tags_Cleaned']
        ]

# ----------------- Example Usage -----------------
if __name__ == "__main__":
    recommender = FashionHubRecommender("FashionHub_products_cleaned.csv")

    # Example: Recommend summer casual outfits for women
    recommended = recommender.recommend(
        gender="Women",
        season="Summer",
        selected_tags=["casual", "party"],
        top_n=20
    )

    print("\nRecommended Products:")
    print(recommended.to_string(index=False))

Recommended Products:
ProductID              ProductName  PricePKR              SellerName                        AI_Tags_Cleaned
    P0192        Beige Denim Jeans     11927              Outfitters           summer, party, casual, women
    P0089          Pink Lawn Abaya      2040        Quetta Style Hub   party, formal, casual, women, summer
    P0814         Green Lawn Saree      3690         StyleHubKarachi   trendy, casual, party, women, summer
    P1324      Beige Leather Heels     12708         TrendyThreadsPK   party, ethnic, casual, women, summer
    P1149       Grey Polyester Cap     10954         StyleHubKarachi   party, casual, winter, women, summer
    P0862       Blue Wool Earrings     19754       Okara Dress House   party, casual, winter, women, summer
    P0180    Blue Polyester Hoodie      6224 Faisalabad Fabric Point   party, casual, formal, women, summer
    P0791     Black Linen Necklace     13177        WardrobeByAyesha  wedding, casual, party, women, summer
    P0426  Grey Denim Formal Shirt     14601         OutfitObsession   party, winter, casual, women, summer
    P1410      Brown Linen Sandals     10953         StyleHubKarachi   party, casual, trendy, women, summer
    P0496       Pink Denim T-Shirt     11280     Junaid Jamshed (J.)           casual, party, summer, women
    P1441        Green Cotton Ring      8945        Quetta Style Hub   trendy, casual, party, women, summer
    P0030        Pink Leather Ring      9237             ModishMoods   party, casual, formal, women, summer
    P1034 White Denim Formal Shirt     16796        ThreadsAndTrends   winter, party, casual, women, summer
    P0245   Grey Polyester T-Shirt     17128       Rawalpindi Styles   formal, casual, party, women, summer
    P0945      White Wool Earrings      9470                  Khaadi western, party, wedding, women, summer
    P0917      White Wool Sneakers      3504         OutfitObsession         wedding, casual, summer, women
    P0892       Grey Silk Necklace     11842                  Khaadi  formal, western, party, women, summer
    P0966        Blue Lawn T-Shirt     15031              KurtiCraze trendy, wedding, casual, women, summer
    P0997       Pink Silk Sneakers      1392         StyleHubKarachi   trendy, party, winter, women, summer

In [79]:
import pandas as pd

# Load your cleaned dataset
df = pd.read_csv("FashionHub_products_cleaned.csv")

# Example user input (this could later come from search, image detection, etc.)
user_gender = "Women"
user_season = "Summer"
user_category = "Casual"

# Step 1: Filter dataset based on gender and season
filtered = df[
    (df["Gender"].str.contains(user_gender, case=False, na=False)) &
    (df["Season"].str.contains(user_season, case=False, na=False)) &
    (df["AI_Tags_Cleaned"].str.contains(user_category, case=False, na=False))
]

# Step 2: Show top 5 matches
recommendations = filtered.head(10)

print("Recommended Products:")
print(recommendations[["ProductID", "ProductName", "PricePKR", "SellerName", "AI_Tags_Cleaned"]])

Recommended Products:
    ProductID              ProductName  PricePKR               SellerName  \
22      P0023         Blue Denim Scarf     19469   Karachi Bazaar Fashion
29      P0030        Pink Leather Ring      9237              ModishMoods
78      P0079  Beige Wool Formal Shirt      3469      Multan Cloth Market
80      P0081      Green Cotton Hoodie     19949      Multan Cloth Market
88      P0089          Pink Lawn Abaya      2040         Quetta Style Hub
148     P0149       Pink Polyester Hat     19256           TheFashionRack
179     P0180    Blue Polyester Hoodie      6224  Faisalabad Fabric Point
191     P0192        Beige Denim Jeans     11927               Outfitters
222     P0223    Brown Cotton Bracelet       609      Junaid Jamshed (J.)
223     P0224      White Leather Abaya     14615      Junaid Jamshed (J.)

                             AI_Tags_Cleaned
22    western, ethnic, casual, women, summer
29      party, casual, formal, women, summer
78    ethnic, western, casual, women, summer
80    ethnic, casual, wedding, women, summer
88      party, formal, casual, women, summer
148   wedding, casual, winter, women, summer
179     party, casual, formal, women, summer
191             summer, party, casual, women
222  western, casual, wedding, women, summer
223   wedding, trendy, casual, women, summer

In [80]:
import pandas as pd

# Load dataset
df = pd.read_csv("FashionHub_products_cleaned.csv")

# Example user input
user_gender = "Women"
user_season = "Summer"
user_category = "Casual"

# Convert input into a list of tags
target_tags = [user_gender.lower(), user_season.lower(), user_category.lower()]

# Step 1: Strict filtering for gender + season
filtered = df[
    (df["Gender"].str.contains(user_gender, case=False, na=False)) &
    (df["Season"].str.contains(user_season, case=False, na=False))
].copy()

# Step 2: Add a relevance score = number of matching tags
def calculate_score(tags, target_tags):
    tags = tags.lower().split(", ")
    return sum(tag in tags for tag in target_tags)

filtered["RelevanceScore"] = filtered["AI_Tags_Cleaned"].apply(lambda x: calculate_score(x, target_tags))

# Step 3: Sort by relevance score (higher = better match)
filtered = filtered.sort_values(by="RelevanceScore", ascending=False)

# Step 4: Show top 5 recommendations
recommendations = filtered.head(5)

print("Recommended Products:")
print(recommendations[["ProductID", "ProductName", "PricePKR", "SellerName", "AI_Tags_Cleaned", "RelevanceScore"]])

Recommended Products:
     ProductID              ProductName  PricePKR            SellerName  \
1558     P1559      Brown Silk Sneakers     12368         DailyFitStyle
425      P0426  Grey Denim Formal Shirt     14601       OutfitObsession
306      P0307       Black Leather Belt     17141  Ethnic by Outfitters
312      P0313          Pink Silk Heels     13155     Rawalpindi Styles
1148     P1149       Grey Polyester Cap     10954       StyleHubKarachi

                              AI_Tags_Cleaned  RelevanceScore
1558  casual, western, wedding, women, summer               3
425      party, winter, casual, women, summer               3
306     casual, winter, trendy, women, summer               3
312    western, trendy, casual, women, summer               3
1148     party, casual, winter, women, summer               3

In [81]:
import pandas as pd

# Load dataset
df = pd.read_csv("FashionHub_products_cleaned.csv")

# Example user input
user_gender = "Women"
user_season = "Summer"
user_category = "Casual"

# Convert input into a list of tags
target_tags = [user_gender.lower(), user_season.lower(), user_category.lower()]

# Step 1: Strict filtering for gender + season
filtered = df[
    (df["Gender"].str.contains(user_gender, case=False, na=False)) &
    (df["Season"].str.contains(user_season, case=False, na=False))
].copy()

# Step 2: Add a relevance score = number of matching tags
def calculate_score(tags, target_tags):
    tags = tags.lower().split(", ")
    return sum(tag in tags for tag in target_tags)

filtered["RelevanceScore"] = filtered["AI_Tags_Cleaned"].apply(lambda x: calculate_score(x, target_tags))

# Step 3: Season purity score (prefer products where Season == Summer only)
filtered["SeasonPurity"] = filtered["Season"].apply(lambda x: 1 if x.strip().lower() == user_season.lower() else 0)

# Step 4: Sort by RelevanceScore first, then SeasonPurity
filtered = filtered.sort_values(by=["RelevanceScore", "SeasonPurity"], ascending=False)

# Step 5: Show top 5 recommendations
recommendations = filtered.head(5)

print("Recommended Products:")
print(recommendations[["ProductID", "ProductName", "PricePKR", "SellerName", "Season", "AI_Tags_Cleaned", "RelevanceScore", "SeasonPurity"]])

Recommended Products:
   ProductID              ProductName  PricePKR              SellerName  \
22     P0023         Blue Denim Scarf     19469  Karachi Bazaar Fashion
29     P0030        Pink Leather Ring      9237             ModishMoods
78     P0079  Beige Wool Formal Shirt      3469     Multan Cloth Market
80     P0081      Green Cotton Hoodie     19949     Multan Cloth Market
88     P0089          Pink Lawn Abaya      2040        Quetta Style Hub

    Season                         AI_Tags_Cleaned  RelevanceScore  \
22  Summer  western, ethnic, casual, women, summer               3
29  Summer    party, casual, formal, women, summer               3
78  Summer  ethnic, western, casual, women, summer               3
80  Summer  ethnic, casual, wedding, women, summer               3
88  Summer    party, formal, casual, women, summer               3

    SeasonPurity
22             1
29             1
78             1
80             1
88             1

In [82]:
import pandas as pd

# Load dataset
df = pd.read_csv("FashionHub_products_cleaned.csv")

# Example user input
user_gender = "Women"
user_season = "Summer"
user_category = "Casual"
budget_preference = "budget"   # options: "budget" or "premium"

# Convert input into a list of tags
target_tags = [user_gender.lower(), user_season.lower(), user_category.lower()]

# Step 1: Strict filtering for gender + season
filtered = df[
    (df["Gender"].str.contains(user_gender, case=False, na=False)) &
    (df["Season"].str.contains(user_season, case=False, na=False))
].copy()

# Step 2: Add a relevance score = number of matching tags
def calculate_score(tags, target_tags):
    tags = tags.lower().split(", ")
    return sum(tag in tags for tag in target_tags)

filtered["RelevanceScore"] = filtered["AI_Tags_Cleaned"].apply(lambda x: calculate_score(x, target_tags))

# Step 3: Season purity score
filtered["SeasonPurity"] = filtered["Season"].apply(lambda x: 1 if x.strip().lower() == user_season.lower() else 0)

# Step 4: Sorting rules
if budget_preference == "budget":
    # Sort by relevance → season purity → lowest price first
    filtered = filtered.sort_values(by=["RelevanceScore", "SeasonPurity", "PricePKR"], ascending=[False, False, True])
elif budget_preference == "premium":
    # Sort by relevance → season purity → highest price first
    filtered = filtered.sort_values(by=["RelevanceScore", "SeasonPurity", "PricePKR"], ascending=[False, False, False])
else:
    # Default sorting: relevance + season purity only
    filtered = filtered.sort_values(by=["RelevanceScore", "SeasonPurity"], ascending=False)

# Step 5: Show top 5 recommendations
recommendations = filtered.head(5)

print("Recommended Products:")
print(recommendations[["ProductID", "ProductName", "PricePKR", "SellerName", "Season", "AI_Tags_Cleaned", "RelevanceScore", "SeasonPurity"]])

Recommended Products:
     ProductID              ProductName  PricePKR           SellerName  \
222      P0223    Brown Cotton Bracelet       609  Junaid Jamshed (J.)
1531     P1532        White Denim Saree       775            Limelight
88       P0089          Pink Lawn Abaya      2040     Quetta Style Hub
341      P0342       Pink Lawn Backpack      2259      EasternElegance
78       P0079  Beige Wool Formal Shirt      3469  Multan Cloth Market

      Season                          AI_Tags_Cleaned  RelevanceScore  \
222   Summer  western, casual, wedding, women, summer               3
1531  Summer   formal, wedding, casual, women, summer               3
88    Summer     party, formal, casual, women, summer               3
341   Summer    ethnic, formal, casual, women, summer               3
78    Summer   ethnic, western, casual, women, summer               3

      SeasonPurity
222              1
1531             1
88               1
341              1
78               1

In [83]:
import pandas as pd
import numpy as np

# -----------------------------
# Step 1: Sample product dataset
# -----------------------------
data = {
    "ProductID": ["P0023", "P0030", "P0079", "P0081", "P0089"],
    "ProductName": ["Blue Denim Scarf", "Pink Leather Ring", "Beige Wool Formal Shirt",
                    "Green Cotton Hoodie", "Pink Lawn Abaya"],
    "PricePKR": [19469, 9237, 3469, 19949, 2040],
    "SellerName": ["Karachi Bazaar Fashion", "ModishMoods", "Multan Cloth Market",
                   "Multan Cloth Market", "Quetta Style Hub"],
    "AI_Tags_Cleaned": [
        "western, ethnic, casual, women, summer",
        "party, casual, formal, women, summer",
        "ethnic, western, casual, women, summer",
        "ethnic, casual, wedding, women, summer",
        "party, formal, casual, women, summer"
    ],
    "RelevanceScore": [3, 3, 3, 3, 3]  # baseline
}

df = pd.DataFrame(data)

# -----------------------------
# Step 2: Add dummy popularity values
# -----------------------------
np.random.seed(42)  # reproducibility
df["Views"] = np.random.randint(100, 1000, size=len(df))
df["AddToCart"] = np.random.randint(10, 200, size=len(df))
df["Sales"] = np.random.randint(1, 50, size=len(df))

# Popularity formula
df["PopularityScore"] = (0.5 * df["Views"]) + (1.0 * df["AddToCart"]) + (2.0 * df["Sales"])

# -----------------------------
# Step 3: Simulated user feedback
# -----------------------------
feedback_data = {
    "UserID": ["U001", "U001", "U002"],
    "ProductID": ["P0089", "P0079", "P0023"],
    "FeedbackType": ["like", "dislike", "wishlist"]
}
feedback_df = pd.DataFrame(feedback_data)

# -----------------------------
# Step 4: Apply feedback rules for a given user
# -----------------------------
def apply_feedback(user_id, df, feedback_df):
    df = df.copy()
    user_feedback = feedback_df[feedback_df["UserID"] == user_id]

    df["FeedbackBoost"] = 0  # default
    for _, row in user_feedback.iterrows():
        if row["FeedbackType"] == "like":
            df.loc[df["ProductID"] == row["ProductID"], "FeedbackBoost"] += 2
        elif row["FeedbackType"] == "wishlist":
            df.loc[df["ProductID"] == row["ProductID"], "FeedbackBoost"] += 3
        elif row["FeedbackType"] == "dislike":
            df = df[df["ProductID"] != row["ProductID"]]  # filter out

    # Final score = relevance + popularity + feedback
    df["FinalScore"] = df["RelevanceScore"] + df["PopularityScore"] + df["FeedbackBoost"]
    return df.sort_values(by="FinalScore", ascending=False)

# -----------------------------
# Step 5: Test with a user
# -----------------------------
print("=== Recommendations for U001 ===")
print(apply_feedback("U001", df, feedback_df)[["ProductID", "ProductName", "FinalScore"]])

print("\n=== Recommendations for U002 ===")
print(apply_feedback("U002", df, feedback_df)[["ProductID", "ProductName", "FinalScore"]])

=== Recommendations for U001 ===
  ProductID          ProductName  FinalScore
1     P0030    Pink Leather Ring       514.5
3     P0081  Green Cotton Hoodie       322.0
4     P0089      Pink Lawn Abaya       287.0
0     P0023     Blue Denim Scarf       223.0

=== Recommendations for U002 ===
  ProductID              ProductName  FinalScore
2     P0079  Beige Wool Formal Shirt       535.0
1     P0030        Pink Leather Ring       514.5
3     P0081      Green Cotton Hoodie       322.0
4     P0089          Pink Lawn Abaya       285.0
0     P0023         Blue Denim Scarf       226.0

In [84]:
import pandas as pd
import numpy as np

# -----------------------------
# Step 1: Sample product dataset
# -----------------------------
data = {
    "ProductID": ["P0023", "P0030", "P0079", "P0081", "P0089"],
    "ProductName": ["Blue Denim Scarf", "Pink Leather Ring", "Beige Wool Formal Shirt",
                    "Green Cotton Hoodie", "Pink Lawn Abaya"],
    "PricePKR": [19469, 9237, 3469, 19949, 2040],
    "SellerName": ["Karachi Bazaar Fashion", "ModishMoods", "Multan Cloth Market",
                   "Multan Cloth Market", "Quetta Style Hub"],
    "AI_Tags_Cleaned": [
        "western, ethnic, casual, women, summer",
        "party, casual, formal, women, summer",
        "ethnic, western, casual, women, summer",
        "ethnic, casual, wedding, women, summer",
        "party, formal, casual, women, summer"
    ],
    "RelevanceScore": [3, 3, 3, 3, 3]  # baseline
}

df = pd.DataFrame(data)

# -----------------------------
# Step 2: Add dummy popularity values
# -----------------------------
np.random.seed(42)  # reproducibility
df["Views"] = np.random.randint(100, 1000, size=len(df))
df["AddToCart"] = np.random.randint(10, 200, size=len(df))
df["Sales"] = np.random.randint(1, 50, size=len(df))

# Popularity formula
df["PopularityScore"] = (0.5 * df["Views"]) + (1.0 * df["AddToCart"]) + (2.0 * df["Sales"])

# -----------------------------
# Step 3: Simulated user feedback
# -----------------------------
feedback_data = {
    "UserID": ["U001", "U001", "U002"],
    "ProductID": ["P0089", "P0079", "P0023"],
    "FeedbackType": ["like", "dislike", "wishlist"]
}
feedback_df = pd.DataFrame(feedback_data)

# -----------------------------
# Step 4: Functions
# -----------------------------
def baseline_recommendations(df):
    return df.sort_values(by="RelevanceScore", ascending=False)

def popularity_recommendations(df):
    df = df.copy()
    df["Score"] = df["RelevanceScore"] + df["PopularityScore"]
    return df.sort_values(by="Score", ascending=False)

def feedback_recommendations(user_id, df, feedback_df):
    df = df.copy()
    user_feedback = feedback_df[feedback_df["UserID"] == user_id]

    df["FeedbackBoost"] = 0
    for _, row in user_feedback.iterrows():
        if row["FeedbackType"] == "like":
            df.loc[df["ProductID"] == row["ProductID"], "FeedbackBoost"] += 2
        elif row["FeedbackType"] == "wishlist":
            df.loc[df["ProductID"] == row["ProductID"], "FeedbackBoost"] += 3
        elif row["FeedbackType"] == "dislike":
            df = df[df["ProductID"] != row["ProductID"]]  # remove

    df["FinalScore"] = df["RelevanceScore"] + df["PopularityScore"] + df["FeedbackBoost"]
    return df.sort_values(by="FinalScore", ascending=False)

# -----------------------------
# Step 5: Show comparison
# -----------------------------
print("=== BASELINE (Relevance Only) ===")
print(baseline_recommendations(df)[["ProductID", "ProductName", "RelevanceScore"]])

print("\n=== WITH POPULARITY ===")
print(popularity_recommendations(df)[["ProductID", "ProductName", "Score"]])

print("\n=== WITH POPULARITY + FEEDBACK (User U001) ===")
print(feedback_recommendations("U001", df, feedback_df)[["ProductID", "ProductName", "FinalScore"]])

print("\n=== WITH POPULARITY + FEEDBACK (User U002) ===")
print(feedback_recommendations("U002", df, feedback_df)[["ProductID", "ProductName", "FinalScore"]])

=== BASELINE (Relevance Only) ===
  ProductID              ProductName  RelevanceScore
0     P0023         Blue Denim Scarf               3
1     P0030        Pink Leather Ring               3
2     P0079  Beige Wool Formal Shirt               3
3     P0081      Green Cotton Hoodie               3
4     P0089          Pink Lawn Abaya               3

=== WITH POPULARITY ===
  ProductID              ProductName  Score
2     P0079  Beige Wool Formal Shirt  535.0
1     P0030        Pink Leather Ring  514.5
3     P0081      Green Cotton Hoodie  322.0
4     P0089          Pink Lawn Abaya  285.0
0     P0023         Blue Denim Scarf  223.0

=== WITH POPULARITY + FEEDBACK (User U001) ===
  ProductID          ProductName  FinalScore
1     P0030    Pink Leather Ring       514.5
3     P0081  Green Cotton Hoodie       322.0
4     P0089      Pink Lawn Abaya       287.0
0     P0023     Blue Denim Scarf       223.0

=== WITH POPULARITY + FEEDBACK (User U002) ===
  ProductID              ProductName  FinalScore
2     P0079  Beige Wool Formal Shirt       535.0
1     P0030        Pink Leather Ring       514.5
3     P0081      Green Cotton Hoodie       322.0
4     P0089          Pink Lawn Abaya       285.0
0     P0023         Blue Denim Scarf       226.0

In [85]:
import pandas as pd
import random

# Load your dataset
df = pd.read_csv("FashionHub_products_cleaned.csv")

# -------------------------
# Category Mapping
# -------------------------
category_map = {
    "tops": ["shirt", "kurta", "kameez", "blouse", "hoodie", "t-shirt", "abaya", "saree"],
    "bottoms": ["jeans", "trousers", "shalwar", "pants", "skirt"],
    "footwear": ["shoes", "heels", "sandals", "sneakers"],
    "accessories": ["scarf", "dupatta", "belt", "bracelet", "ring", "hat", "cap", "jewelry"],
    "bags": ["handbag", "backpack", "clutch"],
    "outerwear": ["jacket", "coat", "sweater"]
}

def detect_category(product_name):
    name = product_name.lower()
    for cat, keywords in category_map.items():
        if any(word in name for word in keywords):
            return cat
    return "other"

df["Category"] = df["ProductName"].apply(detect_category)

# -------------------------
# Styling Rules
# -------------------------
style_rules = {
    "abaya": ["accessories", "footwear", "bags"],      # scarf + flats + handbag
    "saree": ["footwear", "accessories", "bags"],      # heels + jewelry + clutch
    "jeans": ["tops", "footwear", "bags"],             # shirt + sneakers + backpack
    "shirt": ["bottoms", "footwear", "accessories"],   # trousers + shoes + belt
}

# -------------------------
# Outfit Builder Function
# -------------------------
def build_outfit(selected_product_id, df):
    main_item = df[df["ProductID"] == selected_product_id].iloc[0]
    main_name = main_item["ProductName"].lower()
    main_cat = main_item["Category"]
    tags = set(main_item["AI_Tags_Cleaned"].split(", "))
    season = main_item["Season"]
    gender = main_item["Gender"]

    # Outfit starter
    outfit = [main_item]

    # Check which style rule applies
    matched_rule = None
    for keyword, comp_cats in style_rules.items():
        if keyword in main_name:
            matched_rule = comp_cats
            break

    if matched_rule:
        for comp_cat in matched_rule:
            candidates = df[(df["Category"] == comp_cat) &
                            (df["Season"] == season) &
                            (df["Gender"] == gender)]

            # Match tags
            candidates = candidates[candidates["AI_Tags_Cleaned"].apply(
                lambda x: len(tags.intersection(set(x.split(", ")))) > 0
            )]

            if not candidates.empty:
                outfit.append(candidates.sample(1).iloc[0])

    return pd.DataFrame(outfit)

# -------------------------
# DEMO: Generate Logical Outfits
# -------------------------
print("=== Abaya Outfit ===")
abaya_outfit = build_outfit("P0089", df)  # Pink Lawn Abaya
print(abaya_outfit[["ProductID", "ProductName", "Category", "AI_Tags_Cleaned"]])

print("\n=== Saree Outfit ===")
saree_outfit = build_outfit("P0814", df)  # Green Lawn Saree
print(saree_outfit[["ProductID", "ProductName", "Category", "AI_Tags_Cleaned"]])

print("\n=== Jeans Outfit ===")
jeans_outfit = build_outfit("P0192", df)  # Beige Denim Jeans
print(jeans_outfit[["ProductID", "ProductName", "Category", "AI_Tags_Cleaned"]])

=== Abaya Outfit ===
     ProductID                ProductName     Category  \
88       P0089            Pink Lawn Abaya         tops
861      P0862         Blue Wool Earrings  accessories
1323     P1324        Beige Leather Heels     footwear
150      P0151  Yellow Polyester Backpack         bags

                           AI_Tags_Cleaned
88    party, formal, casual, women, summer
861   party, casual, winter, women, summer
1323  party, ethnic, casual, women, summer
150          western, party, summer, women

=== Saree Outfit ===
     ProductID          ProductName     Category  \
813      P0814     Green Lawn Saree         tops
1558     P1559  Brown Silk Sneakers     footwear
562      P0563     Grey Leather Hat  accessories
799      P0800    Blue Silk Handbag         bags

                              AI_Tags_Cleaned
813      trendy, casual, party, women, summer
1558  casual, western, wedding, women, summer
562     winter, formal, casual, women, summer
799    winter, formal, western, women, summer

=== Jeans Outfit ===
     ProductID          ProductName  Category  \
191      P0192    Beige Denim Jeans   bottoms
813      P0814     Green Lawn Saree      tops
1420     P1421    Yellow Lawn Heels  footwear
371      P0372  Grey Linen Backpack      bags

                            AI_Tags_Cleaned
191            summer, party, casual, women
813    trendy, casual, party, women, summer
1420  wedding, trendy, party, women, summer
371          summer, wedding, winter, women

In [86]:
import pandas as pd
import random

# ========================
# 1. Load Dataset
# ========================
df = pd.read_csv("FashionHub_products_cleaned.csv")

# ========================
# 2. Category Mapping
# ========================
category_map = {
    "Shirt": "Top",
    "T-Shirt": "Top",
    "Kurta": "Top",
    "Blouse": "Top",
    "Hoodie": "Top",
    "Abaya": "Dress/Modest",
    "Maxi": "Dress/Modest",
    "Saree": "Dress/Modest",
    "Gown": "Dress/Modest",
    "Trouser": "Bottom",
    "Jeans": "Bottom",
    "Skirt": "Bottom",
    "Shalwar": "Bottom",
    "Churidar": "Bottom",
    "Dupatta": "Accessory",
    "Scarf": "Accessory",
    "Ring": "Accessory",
    "Necklace": "Accessory",
    "Bag": "Accessory",
    "Shoes": "Shoes",
    "Heels": "Shoes",
    "Sneakers": "Shoes",
    "Sandals": "Shoes"
}

def map_category(name):
    for key, value in category_map.items():
        if key.lower() in name.lower():
            return value
    return "Other"

df["MappedCategory"] = df["ProductName"].apply(map_category)

# ========================
# 3. Occasion Rules
# ========================
occasion_rules = {
    "casual": {
        "must_have": ["Top", "Bottom"],
        "optional": ["Shoes", "Accessory"]
    },
    "formal": {
        "must_have": ["Top", "Bottom"],
        "optional": ["Shoes", "Accessory"]
    },
    "party": {
        "must_have": ["Dress/Modest"],
        "optional": ["Shoes", "Accessory"]
    },
    "wedding": {
        "must_have": ["Dress/Modest"],
        "optional": ["Shoes", "Accessory", "Accessory"]
    }
}

# ========================
# 4. Outfit Builder
# ========================
def build_outfit(occasion="casual", season=None, style=None, gender=None):
    rules = occasion_rules.get(occasion, {})
    must_have = rules.get("must_have", [])
    optional = rules.get("optional", [])

    outfit = []

    def filter_items(category):
        items = df[df["MappedCategory"] == category]

        # Apply season filter if given
        if season:
            items = items[items["Season"].str.contains(season, case=False, na=False)]

        # Apply style filter if given (AI_Tags)
        if style:
            items = items[items["AI_Tags_Cleaned"].str.contains(style, case=False, na=False)]

        # Apply gender filter if given
        if gender:
            items = items[items["Gender"].str.contains(gender, case=False, na=False)]

        return items

    # Must-have categories
    for cat in must_have:
        items = filter_items(cat)
        if not items.empty:
            outfit.append(items.sample(1).iloc[0])

    # Optional categories
    for cat in optional:
        if random.random() > 0.5:  # 50% chance
            items = filter_items(cat)
            if not items.empty:
                outfit.append(items.sample(1).iloc[0])

    return pd.DataFrame(outfit)

# ========================
# 5. Test Runs
# ========================
print("=== Casual Summer Outfit (Women) ===")
print(build_outfit("casual", season="Summer", gender="Women")[["ProductID", "ProductName", "MappedCategory", "Season"]])

print("\n=== Party Outfit (Western Style) ===")
print(build_outfit("party", style="western")[["ProductID", "ProductName", "MappedCategory", "AI_Tags_Cleaned"]])

print("\n=== Wedding Outfit (Ethnic, Women) ===")
print(build_outfit("wedding", style="ethnic", gender="Women")[["ProductID", "ProductName", "MappedCategory", "AI_Tags_Cleaned"]])

=== Casual Summer Outfit (Women) ===
     ProductID                 ProductName MappedCategory  Season
696      P0697           Beige Denim Kurta            Top  Summer
1156     P1157  Brown Denim Shalwar Kameez         Bottom  Summer
1409     P1410         Brown Linen Sandals          Shoes  Summer
637      P0638             Red Cotton Ring      Accessory  Summer

=== Party Outfit (Western Style) ===
     ProductID      ProductName MappedCategory  \
1041     P1042  Pink Silk Saree   Dress/Modest

                              AI_Tags_Cleaned
1041  wedding, western, winter, women, summer

=== Wedding Outfit (Ethnic, Women) ===
     ProductID                  ProductName MappedCategory  \
1032     P1033            Red Leather Abaya   Dress/Modest
133      P0134  Grey Polyester Formal Shoes          Shoes
1186     P1187         Brown Denim Earrings      Accessory
1082     P1083          Green Lawn Earrings      Accessory

                                AI_Tags_Cleaned
1032      winter, ethnic, formal, women, summer
133   winter, ethnic, formal, women, all-season
1186              casual, ethnic, winter, women
1082      winter, trendy, ethnic, women, summer

In [87]:
import pandas as pd
import random

# ========================
# 1. Load Dataset
# ========================
df = pd.read_csv("FashionHub_products_cleaned.csv")

# Add dummy popularity + feedback (for now)
df["Popularity"] = df["PricePKR"] % 100   # proxy: price variation
df["Feedback"] = (df.index % 5) * 10      # proxy: likes/wishlist

# ========================
# 2. Category Mapping
# ========================
category_map = {
    "Shirt": "Top", "T-Shirt": "Top", "Kurta": "Top", "Blouse": "Top", "Hoodie": "Top",
    "Abaya": "Dress/Modest", "Maxi": "Dress/Modest", "Saree": "Dress/Modest", "Gown": "Dress/Modest",
    "Trouser": "Bottom", "Jeans": "Bottom", "Skirt": "Bottom", "Shalwar": "Bottom", "Churidar": "Bottom",
    "Dupatta": "Accessory", "Scarf": "Accessory", "Ring": "Accessory", "Necklace": "Accessory", "Bag": "Accessory",
    "Shoes": "Shoes", "Heels": "Shoes", "Sneakers": "Shoes", "Sandals": "Shoes"
}

def map_category(name):
    for key, value in category_map.items():
        if key.lower() in name.lower():
            return value
    return "Other"

df["MappedCategory"] = df["ProductName"].apply(map_category)

# ========================
# 3. Occasion Rules
# ========================
occasion_rules = {
    "casual": {"must_have": ["Top", "Bottom"], "optional": ["Shoes", "Accessory"]},
    "formal": {"must_have": ["Top", "Bottom"], "optional": ["Shoes", "Accessory"]},
    "party": {"must_have": ["Dress/Modest"], "optional": ["Shoes", "Accessory"]},
    "wedding": {"must_have": ["Dress/Modest"], "optional": ["Shoes", "Accessory", "Accessory"]}
}

# ========================
# 4. Outfit Builder with Scoring
# ========================
def build_outfit(occasion="casual", season=None, style=None, gender=None, top_n=3):
    rules = occasion_rules.get(occasion, {})
    must_have, optional = rules.get("must_have", []), rules.get("optional", [])

    outfits = []
    for _ in range(10):  # generate multiple outfit candidates
        outfit = []

        def filter_items(category):
            items = df[df["MappedCategory"] == category]
            if season:
                items = items[items["Season"].str.contains(season, case=False, na=False)]
            if style:
                items = items[items["AI_Tags_Cleaned"].str.contains(style, case=False, na=False)]
            if gender:
                items = items[items["Gender"].str.contains(gender, case=False, na=False)]
            return items

        # Must-have
        for cat in must_have:
            items = filter_items(cat)
            if not items.empty:
                outfit.append(items.sample(1).iloc[0])

        # Optional
        for cat in optional:
            if random.random() > 0.5:
                items = filter_items(cat)
                if not items.empty:
                    outfit.append(items.sample(1).iloc[0])

        if outfit:
            outfit_df = pd.DataFrame(outfit)

            # Scoring: relevance (3), popularity, feedback
            outfit_df["ItemScore"] = (
                3 + outfit_df["Popularity"] * 0.5 + outfit_df["Feedback"] * 0.8
            )
            outfit_score = outfit_df["ItemScore"].sum()

            outfits.append((outfit_score, outfit_df))

    # Rank outfits
    outfits = sorted(outfits, key=lambda x: x[0], reverse=True)
    return [(score, outfit) for score, outfit in outfits[:top_n]]

# ========================
# 5. Test Runs
# ========================
print("=== Casual Summer Outfit (Women) ===")
for score, outfit in build_outfit("casual", season="Summer", gender="Women"):
    print(f"\nOutfit Score: {score}")
    print(outfit[["ProductID", "ProductName", "MappedCategory", "ItemScore"]])

print("\n=== Party Outfit (Western Style) ===")
for score, outfit in build_outfit("party", style="western"):
    print(f"\nOutfit Score: {score}")
    print(outfit[["ProductID", "ProductName", "MappedCategory", "ItemScore"]])

=== Casual Summer Outfit (Women) ===

Outfit Score: 184.0
     ProductID          ProductName MappedCategory  ItemScore
1138     P1139   Yellow Linen Kurta            Top       48.5
282      P0283   Grey Leather Jeans         Bottom       21.5
996      P0997   Pink Silk Sneakers          Shoes       57.0
866      P0867  White Lawn Necklace      Accessory       57.0

Outfit Score: 167.0
     ProductID                ProductName MappedCategory  ItemScore
1130     P1131          Grey Silk T-Shirt            Top       51.5
1343     P1344  Black Lawn Shalwar Kameez         Bottom       54.5
270      P0271         Grey Denim Sandals          Shoes        7.5
22       P0023           Blue Denim Scarf      Accessory       53.5

Outfit Score: 159.5
    ProductID                 ProductName MappedCategory  ItemScore
515     P0516        Beige Cotton T-Shirt            Top       10.0
114     P0115  Blue Cotton Shalwar Kameez         Bottom       84.0
338     P0339          Beige Lawn Sandals          Shoes       65.5

=== Party Outfit (Western Style) ===

Outfit Score: 148.0
     ProductID              ProductName MappedCategory  ItemScore
479      P0480    Brown Lawn Maxi Dress   Dress/Modest       69.0
1087     P1088  Grey Linen Formal Shoes          Shoes       52.0
1328     P1329         Black Lawn Scarf      Accessory       27.0

Outfit Score: 143.0
     ProductID          ProductName MappedCategory  ItemScore
805      P0806  Red Wool Maxi Dress   Dress/Modest       13.0
1558     P1559  Brown Silk Sneakers          Shoes       61.0
184      P0185  Blue Linen Earrings      Accessory       69.0

Outfit Score: 137.0
    ProductID               ProductName MappedCategory  ItemScore
649     P0650         Yellow Silk Saree   Dress/Modest       46.5
41      P0042  Green Linen Formal Shoes          Shoes       47.0
397     P0398           Grey Denim Ring      Accessory       43.5

In [88]:
import pandas as pd
import random

# ========================
# 1. Load Dataset
# ========================
df = pd.read_csv("FashionHub_products_cleaned.csv")

# Add dummy popularity + feedback (for now)
df["Popularity"] = df["PricePKR"] % 100   # proxy: price variation
df["Feedback"] = (df.index % 5) * 10      # proxy: likes/wishlist

# ========================
# 2. Category Mapping
# ========================
category_map = {
    "Shirt": "Top", "T-Shirt": "Top", "Kurta": "Top", "Blouse": "Top", "Hoodie": "Top",
    "Abaya": "Dress/Modest", "Maxi": "Dress/Modest", "Saree": "Dress/Modest", "Gown": "Dress/Modest",
    "Trouser": "Bottom", "Jeans": "Bottom", "Skirt": "Bottom", "Shalwar": "Bottom", "Churidar": "Bottom",
    "Dupatta": "Accessory", "Scarf": "Accessory", "Ring": "Accessory", "Necklace": "Accessory", "Bag": "Accessory",
    "Shoes": "Shoes", "Heels": "Shoes", "Sneakers": "Shoes", "Sandals": "Shoes"
}

def map_category(name):
    for key, value in category_map.items():
        if key.lower() in name.lower():
            return value
    return "Other"

df["MappedCategory"] = df["ProductName"].apply(map_category)

# ========================
# 3. Occasion Rules
# ========================
occasion_rules = {
    "casual": {"must_have": ["Top", "Bottom"], "optional": ["Shoes", "Accessory"]},
    "formal": {"must_have": ["Top", "Bottom"], "optional": ["Shoes", "Accessory"]},
    "party": {"must_have": ["Dress/Modest"], "optional": ["Shoes", "Accessory"]},
    "wedding": {"must_have": ["Dress/Modest"], "optional": ["Shoes", "Accessory", "Accessory"]}
}

# Icons for display
category_icons = {
    "Top": "👕", "Bottom": "👖", "Shoes": "👠", "Accessory": "👜", "Dress/Modest": "👗", "Other": "✨"
}

# ========================
# 4. Outfit Builder with Scoring
# ========================
def build_outfit(occasion="casual", season=None, style=None, gender=None, top_n=3):
    rules = occasion_rules.get(occasion, {})
    must_have, optional = rules.get("must_have", []), rules.get("optional", [])

    outfits = []
    for _ in range(10):  # generate multiple outfit candidates
        outfit = []

        def filter_items(category):
            items = df[df["MappedCategory"] == category]
            if season:
                items = items[items["Season"].str.contains(season, case=False, na=False)]
            if style:
                items = items[items["AI_Tags_Cleaned"].str.contains(style, case=False, na=False)]
            if gender:
                items = items[items["Gender"].str.contains(gender, case=False, na=False)]
            return items

        # Must-have
        for cat in must_have:
            items = filter_items(cat)
            if not items.empty:
                outfit.append(items.sample(1).iloc[0])

        # Optional
        for cat in optional:
            if random.random() > 0.5:
                items = filter_items(cat)
                if not items.empty:
                    outfit.append(items.sample(1).iloc[0])

        if outfit:
            outfit_df = pd.DataFrame(outfit)

            # Scoring
            outfit_df["ItemScore"] = (
                3 + outfit_df["Popularity"] * 0.5 + outfit_df["Feedback"] * 0.8
            )
            outfit_score = outfit_df["ItemScore"].sum()

            outfits.append((outfit_score, outfit_df))

    # Rank outfits
    outfits = sorted(outfits, key=lambda x: x[0], reverse=True)
    return [(score, outfit) for score, outfit in outfits[:top_n]]

# ========================
# 5. Display Pretty Outfits
# ========================
def show_outfits(occasion="casual", season=None, style=None, gender=None):
    outfits = build_outfit(occasion, season, style, gender, top_n=3)
    for score, outfit in outfits:
        print(f"\nOutfit Score: {int(score)}")
        for _, row in outfit.iterrows():
            cat = row["MappedCategory"]
            icon = category_icons.get(cat, "✨")
            print(f"{icon} {cat}: {row['ProductName']}")
        print("-" * 40)

# ========================
# 6. Test Runs
# ========================
print("=== Casual Summer Outfit (Women) ===")
show_outfits("casual", season="Summer", gender="Women")

print("\n=== Party Outfit (Western Style) ===")
show_outfits("party", style="western")

=== Casual Summer Outfit (Women) ===

Outfit Score: 221
👕 Top: Yellow Linen Kurta
👖 Bottom: Grey Cotton Jeans
👠 Shoes: Pink Silk Heels
👜 Accessory: Yellow Denim Earrings
----------------------------------------

Outfit Score: 172
👕 Top: Pink Denim T-Shirt
👖 Bottom: Grey Leather Jeans
👠 Shoes: Pink Silk Sneakers
👜 Accessory: Brown Wool Scarf
----------------------------------------

Outfit Score: 151
👕 Top: Grey Denim Formal Shirt
👖 Bottom: Green Linen Shalwar Kameez
👠 Shoes: Brown Silk Sneakers
👜 Accessory: Pink Cotton Handbag
----------------------------------------

=== Party Outfit (Western Style) ===

Outfit Score: 136
👗 Dress/Modest: Blue Leather Maxi Dress
👠 Shoes: White Denim Sneakers
👜 Accessory: Pink Lawn Earrings
----------------------------------------

Outfit Score: 114
👗 Dress/Modest: Yellow Cotton Abaya
👠 Shoes: Beige Lawn Sandals
----------------------------------------

Outfit Score: 102
👗 Dress/Modest: Blue Leather Maxi Dress
👜 Accessory: Green Lawn Handbag
----------------------------------------

In [89]:
import pandas as pd
import random

# ========================
# 1. Load Dataset
# ========================
df = pd.read_csv("FashionHub_products_cleaned.csv")

# Add dummy popularity + feedback (for now)
df["Popularity"] = df["PricePKR"] % 100   # proxy: price variation
df["Feedback"] = (df.index % 5) * 10      # proxy: likes/wishlist

# ========================
# 2. Category Mapping
# ========================
category_map = {
    "Shirt": "Top", "T-Shirt": "Top", "Kurta": "Top", "Blouse": "Top", "Hoodie": "Top",
    "Abaya": "Dress/Modest", "Maxi": "Dress/Modest", "Saree": "Dress/Modest", "Gown": "Dress/Modest",
    "Trouser": "Bottom", "Jeans": "Bottom", "Skirt": "Bottom", "Shalwar": "Bottom", "Churidar": "Bottom",
    "Dupatta": "Accessory", "Scarf": "Accessory", "Ring": "Accessory", "Necklace": "Accessory", "Bag": "Accessory",
    "Shoes": "Shoes", "Heels": "Shoes", "Sneakers": "Shoes", "Sandals": "Shoes"
}

def map_category(name):
    for key, value in category_map.items():
        if key.lower() in name.lower():
            return value
    return "Other"

df["MappedCategory"] = df["ProductName"].apply(map_category)

# ========================
# 3. Occasion Rules
# ========================
occasion_rules = {
    "casual": {"must_have": ["Top", "Bottom"], "optional": ["Shoes", "Accessory"]},
    "formal": {"must_have": ["Top", "Bottom"], "optional": ["Shoes", "Accessory"]},
    "party": {"must_have": ["Dress/Modest"], "optional": ["Shoes", "Accessory"]},
    "wedding": {"must_have": ["Dress/Modest"], "optional": ["Shoes", "Accessory", "Accessory"]}
}

# Icons for display
category_icons = {
    "Top": "👕", "Bottom": "👖", "Shoes": "👠", "Accessory": "👜", "Dress/Modest": "👗", "Other": "✨"
}

# ========================
# 4. Outfit Builder Around a Product
# ========================
def build_outfit_around(product_id, top_n=3):
    main_item = df[df["ProductID"] == product_id]
    if main_item.empty:
        print(f"❌ Product {product_id} not found.")
        return []

    main_item = main_item.iloc[0]
    occasion = None
    for key in occasion_rules.keys():
        if key in str(main_item["AI_Tags_Cleaned"]).lower():
            occasion = key
            break

    if not occasion:
        occasion = "casual"  # fallback

    rules = occasion_rules[occasion]
    must_have, optional = rules.get("must_have", []), rules.get("optional", [])

    outfits = []
    for _ in range(10):  # generate multiple outfit candidates
        outfit = [main_item]

        def filter_items(category):
            items = df[df["MappedCategory"] == category]
            if main_item["Season"]:
                items = items[items["Season"].str.contains(main_item["Season"], case=False, na=False)]
            if main_item["Gender"]:
                items = items[items["Gender"].str.contains(main_item["Gender"], case=False, na=False)]
            return items

        # Must-have (excluding main item category)
        for cat in must_have:
            if cat != main_item["MappedCategory"]:
                items = filter_items(cat)
                if not items.empty:
                    outfit.append(items.sample(1).iloc[0])

        # Optional
        for cat in optional:
            if random.random() > 0.5:
                items = filter_items(cat)
                if not items.empty:
                    outfit.append(items.sample(1).iloc[0])

        if outfit:
            outfit_df = pd.DataFrame(outfit)

            # Scoring
            outfit_df["ItemScore"] = (
                3 + outfit_df["Popularity"] * 0.5 + outfit_df["Feedback"] * 0.8
            )
            outfit_score = outfit_df["ItemScore"].sum()
            outfits.append((outfit_score, outfit_df))

    outfits = sorted(outfits, key=lambda x: x[0], reverse=True)
    return [(score, outfit) for score, outfit in outfits[:top_n]]

# ========================
# 5. Display Outfits
# ========================
def show_outfits_for_product(product_id):
    outfits = build_outfit_around(product_id)
    if not outfits:
        return
    main_item = df[df["ProductID"] == product_id].iloc[0]
    print(f"\n=== Outfit Suggestions for {main_item['ProductName']} ({main_item['ProductID']}) ===")
    for score, outfit in outfits:
        print(f"\nOutfit Score: {int(score)}")
        for _, row in outfit.iterrows():
            cat = row["MappedCategory"]
            icon = category_icons.get(cat, "✨")
            print(f"{icon} {cat}: {row['ProductName']}")
        print("-" * 40)

# ========================
# 6. Test Example
# ========================
show_outfits_for_product("P0089")  # Example: Pink Lawn Abaya

=== Outfit Suggestions for Pink Lawn Abaya (P0089) ===

Outfit Score: 240
👗 Dress/Modest: Pink Lawn Abaya
👕 Top: Green Polyester Hoodie
👖 Bottom: Grey Silk Jeans
👠 Shoes: Pink Silk Heels
👜 Accessory: Red Leather Ring
----------------------------------------

Outfit Score: 214
👗 Dress/Modest: Pink Lawn Abaya
👕 Top: Yellow Polyester T-Shirt
👖 Bottom: Beige Denim Jeans
👠 Shoes: Brown Silk Sneakers
----------------------------------------

Outfit Score: 188
👗 Dress/Modest: Pink Lawn Abaya
👕 Top: Yellow Polyester T-Shirt
👖 Bottom: Grey Silk Jeans
----------------------------------------

In [90]:
import pandas as pd
import random

# -------------------------------
# 1. Sample Product Dataset
# -------------------------------
products = [
    {"ProductID": "P001", "ProductName": "Blue Denim Jeans", "Category": "Bottom", "Occasion": "Casual", "Season": "All"},
    {"ProductID": "P002", "ProductName": "White Cotton Shirt", "Category": "Top", "Occasion": "Casual", "Season": "Summer"},
    {"ProductID": "P003", "ProductName": "Black Formal Trousers", "Category": "Bottom", "Occasion": "Formal", "Season": "All"},
    {"ProductID": "P004", "ProductName": "Grey Blazer", "Category": "Outerwear", "Occasion": "Formal", "Season": "Winter"},
    {"ProductID": "P005", "ProductName": "Red Lawn Kurti", "Category": "Top", "Occasion": "Casual", "Season": "Summer"},
    {"ProductID": "P006", "ProductName": "Pink Lawn Abaya", "Category": "Dress", "Occasion": "Traditional", "Season": "Summer"},
    {"ProductID": "P007", "ProductName": "Beige Wool Shawl", "Category": "Outerwear", "Occasion": "Traditional", "Season": "Winter"},
    {"ProductID": "P008", "ProductName": "Green Cotton Hoodie", "Category": "Outerwear", "Occasion": "Casual", "Season": "Winter"},
    {"ProductID": "P009", "ProductName": "Leather Formal Shoes", "Category": "Shoes", "Occasion": "Formal", "Season": "All"},
    {"ProductID": "P010", "ProductName": "White Sneakers", "Category": "Shoes", "Occasion": "Casual", "Season": "All"},
]
df = pd.DataFrame(products)

# -------------------------------
# 2. Outfit Rules (Logical Mapping)
# -------------------------------
outfit_rules = {
    "Casual": {
        "Top": ["Bottom", "Shoes", "Outerwear"],
        "Bottom": ["Top", "Shoes"],
        "Outerwear": ["Top", "Bottom", "Shoes"]
    },
    "Formal": {
        "Top": ["Bottom", "Outerwear", "Shoes"],
        "Bottom": ["Top", "Outerwear", "Shoes"],
        "Outerwear": ["Top", "Bottom", "Shoes"]
    },
    "Traditional": {
        "Dress": ["Shoes", "Outerwear"],
        "Top": ["Bottom", "Shoes", "Outerwear"],
        "Outerwear": ["Dress", "Top", "Shoes"]
    }
}

# -------------------------------
# 3. Outfit Builder Function
# -------------------------------
def build_outfit(occasion="Casual", season=None):
    """
    Generate a logical outfit based on occasion + season.
    """
    candidates = df[df["Occasion"] == occasion]

    if season:
        candidates = candidates[(candidates["Season"] == season) | (candidates["Season"] == "All")]

    if candidates.empty:
        return f"No outfits found for {occasion} in {season}"

    outfit = []
    used_categories = set()

    # Start with a random base item (like Top or Dress)
    base_item = candidates.sample(1).iloc[0]
    outfit.append(base_item)
    used_categories.add(base_item["Category"])

    # Match other categories based on rules
    if base_item["Category"] in outfit_rules[occasion]:
        valid_matches = outfit_rules[occasion][base_item["Category"]]

        for category in valid_matches:
            options = candidates[candidates["Category"] == category]
            if not options.empty and category not in used_categories:
                match = options.sample(1).iloc[0]
                outfit.append(match)
                used_categories.add(match["Category"])

    return pd.DataFrame(outfit)

# -------------------------------
# 4. Demo
# -------------------------------
print("=== Casual Summer Outfit ===")
print(build_outfit(occasion="Casual", season="Summer"))

print("\n=== Formal Winter Outfit ===")
print(build_outfit(occasion="Formal", season="Winter"))

print("\n=== Traditional Winter Outfit ===")
print(build_outfit(occasion="Traditional", season="Winter"))

=== Casual Summer Outfit ===
  ProductID         ProductName Category Occasion  Season
1      P002  White Cotton Shirt      Top   Casual  Summer
0      P001    Blue Denim Jeans   Bottom   Casual     All
9      P010      White Sneakers    Shoes   Casual     All

=== Formal Winter Outfit ===
  ProductID            ProductName   Category Occasion  Season
3      P004            Grey Blazer  Outerwear   Formal  Winter
2      P003  Black Formal Trousers     Bottom   Formal     All
8      P009   Leather Formal Shoes      Shoes   Formal     All

=== Traditional Winter Outfit ===
  ProductID       ProductName   Category     Occasion  Season
6      P007  Beige Wool Shawl  Outerwear  Traditional  Winter

In [91]:
import pandas as pd
import random

# -------------------------------
# 1. Sample Product Dataset
# -------------------------------
products = [
    {"ProductID": "P001", "ProductName": "Blue Denim Jeans", "Category": "Bottom", "Occasion": "Casual", "Season": "All", "Popularity": 120, "Feedback": 4.5},
    {"ProductID": "P002", "ProductName": "White Cotton Shirt", "Category": "Top", "Occasion": "Casual", "Season": "Summer", "Popularity": 90, "Feedback": 4.2},
    {"ProductID": "P003", "ProductName": "Black Formal Trousers", "Category": "Bottom", "Occasion": "Formal", "Season": "All", "Popularity": 150, "Feedback": 4.7},
    {"ProductID": "P004", "ProductName": "Grey Blazer", "Category": "Outerwear", "Occasion": "Formal", "Season": "Winter", "Popularity": 200, "Feedback": 4.9},
    {"ProductID": "P005", "ProductName": "Red Lawn Kurti", "Category": "Top", "Occasion": "Casual", "Season": "Summer", "Popularity": 80, "Feedback": 4.1},
    {"ProductID": "P006", "ProductName": "Pink Lawn Abaya", "Category": "Dress", "Occasion": "Traditional", "Season": "Summer", "Popularity": 95, "Feedback": 4.4},
    {"ProductID": "P007", "ProductName": "Beige Wool Shawl", "Category": "Outerwear", "Occasion": "Traditional", "Season": "Winter", "Popularity": 110, "Feedback": 4.6},
    {"ProductID": "P008", "ProductName": "Green Cotton Hoodie", "Category": "Outerwear", "Occasion": "Casual", "Season": "Winter", "Popularity": 105, "Feedback": 4.3},
    {"ProductID": "P009", "ProductName": "Leather Formal Shoes", "Category": "Shoes", "Occasion": "Formal", "Season": "All", "Popularity": 140, "Feedback": 4.8},
    {"ProductID": "P010", "ProductName": "White Sneakers", "Category": "Shoes", "Occasion": "Casual", "Season": "All", "Popularity": 170, "Feedback": 4.5},
]
df = pd.DataFrame(products)

# -------------------------------
# 2. Outfit Rules (Logical Mapping)
# -------------------------------
outfit_rules = {
    "Casual": {
        "Top": ["Bottom", "Shoes", "Outerwear"],
        "Bottom": ["Top", "Shoes"],
        "Outerwear": ["Top", "Bottom", "Shoes"]
    },
    "Formal": {
        "Top": ["Bottom", "Outerwear", "Shoes"],
        "Bottom": ["Top", "Outerwear", "Shoes"],
        "Outerwear": ["Top", "Bottom", "Shoes"]
    },
    "Traditional": {
        "Dress": ["Shoes", "Outerwear"],
        "Top": ["Bottom", "Shoes", "Outerwear"],
        "Outerwear": ["Dress", "Top", "Shoes"]
    }
}

# -------------------------------
# 3. Recommendation Function
# -------------------------------
def recommend_products(user_id, occasion=None, season=None, top_n=5):
    # Filter products by occasion/season
    candidates = df.copy()
    if occasion:
        candidates = candidates[candidates["Occasion"] == occasion]
    if season:
        candidates = candidates[(candidates["Season"] == season) | (candidates["Season"] == "All")]

    # Compute score = Popularity + Feedback*100
    candidates["Score"] = candidates["Popularity"] + (candidates["Feedback"] * 100)

    # Sort and select top_n
    return candidates.sort_values("Score", ascending=False).head(top_n)

# -------------------------------
# 4. Outfit Builder Function
# -------------------------------
def build_outfit_from_recs(recommended_df, occasion, season=None):
    if recommended_df.empty:
        return f"No recommendations found for {occasion} in {season}"

    outfit = []
    used_categories = set()

    # Choose a base item (like Top/Dress) from recs
    base_item = recommended_df.sample(1).iloc[0]
    outfit.append(base_item)
    used_categories.add(base_item["Category"])

    if base_item["Category"] in outfit_rules[occasion]:
        valid_matches = outfit_rules[occasion][base_item["Category"]]
        for category in valid_matches:
            options = recommended_df[recommended_df["Category"] == category]
            if not options.empty and category not in used_categories:
                match = options.sample(1).iloc[0]
                outfit.append(match)
                used_categories.add(match["Category"])

    return pd.DataFrame(outfit)

# -------------------------------
# 5. Demo
# -------------------------------
user = "U001"
occasion = "Casual"
season = "Summer"

print(f"=== Recommendations for {user} ({occasion}, {season}) ===")
recs = recommend_products(user, occasion=occasion, season=season)
print(recs[["ProductID", "ProductName", "Score"]])

print(f"\n=== Outfit Suggestion for {user} ({occasion}, {season}) ===")
print(build_outfit_from_recs(recs, occasion, season))

=== Recommendations for U001 (Casual, Summer) ===
  ProductID         ProductName  Score
9      P010      White Sneakers  620.0
0      P001    Blue Denim Jeans  570.0
1      P002  White Cotton Shirt  510.0
4      P005      Red Lawn Kurti  490.0

=== Outfit Suggestion for U001 (Casual, Summer) ===
  ProductID       ProductName Category Occasion  Season  Popularity  Feedback  \
0      P001  Blue Denim Jeans   Bottom   Casual     All         120       4.5
4      P005    Red Lawn Kurti      Top   Casual  Summer          80       4.1
9      P010    White Sneakers    Shoes   Casual     All         170       4.5

   Score
0  570.0
4  490.0
9  620.0

In [92]:
import pandas as pd
import random

# ========================
# 1. Sample Dataset (replace with your FashionHub_products_cleaned.csv)
# ========================
data = {
    "ProductID": ["P001", "P002", "P005", "P007", "P010", "P011", "P012", "P015"],
    "ProductName": [
        "Blue Denim Jeans", "White Cotton Shirt", "Red Lawn Kurti", "Black Abaya",
        "White Sneakers", "Gold Necklace", "Beige Silk Saree", "Brown Leather Bag"
    ],
    "Category": ["Bottom", "Top", "Top", "Dress/Modest", "Shoes", "Accessory", "Dress/Modest", "Accessory"],
    "Occasion": ["Casual", "Casual", "Casual", "Formal", "Casual", "Wedding", "Wedding", "Casual"],
    "Season": ["All", "Summer", "Summer", "All", "All", "All", "Summer", "All"],
    "Popularity": [120, 90, 80, 60, 170, 100, 95, 85],
    "Feedback": [4.5, 4.2, 4.1, 4.3, 4.5, 4.7, 4.6, 4.0]
}
df = pd.DataFrame(data)

# ========================
# 2. Occasion Rules
# ========================
occasion_rules = {
    "casual": {"must_have": ["Top", "Bottom"], "optional": ["Shoes", "Accessory"]},
    "formal": {"must_have": ["Top", "Bottom"], "optional": ["Shoes", "Accessory"]},
    "party": {"must_have": ["Dress/Modest"], "optional": ["Shoes", "Accessory"]},
    "wedding": {"must_have": ["Dress/Modest"], "optional": ["Shoes", "Accessory", "Accessory"]},
}

# ========================
# 3. Scoring System
# ========================
def score_product(row):
    return row["Popularity"] * 2 + row["Feedback"] * 10

df["Score"] = df.apply(score_product, axis=1)

# ========================
# 4. Outfit Builder
# ========================
def build_outfit(occasion="casual", season="All"):
    rules = occasion_rules.get(occasion, {})
    must_have = rules.get("must_have", [])
    optional = rules.get("optional", [])
    outfit = []

    # Filter dataset for season + occasion
    filtered = df[(df["Season"].isin([season, "All"])) & (df["Occasion"].str.lower() == occasion)]

    # Add must-have
    for cat in must_have:
        items = filtered[filtered["Category"] == cat]
        if not items.empty:
            outfit.append(items.sort_values("Score", ascending=False).iloc[0])

    # Add optional (random)
    for cat in optional:
        items = filtered[filtered["Category"] == cat]
        if not items.empty and random.random() > 0.5:
            outfit.append(items.sample(1).iloc[0])

    return pd.DataFrame(outfit)

# ========================
# 5. Generate Multiple Outfits
# ========================
def generate_outfits(user_id="U001", occasion="casual", season="All", n_outfits=3):
    print(f"\n=== Outfit Suggestions for {user_id} ({occasion.title()}, {season}) ===")
    for i in range(n_outfits):
        outfit = build_outfit(occasion, season)
        if not outfit.empty:
            print(f"\n--- Outfit {i+1} ---")
            print(outfit[["ProductID", "ProductName", "Category", "Score"]].to_string(index=False))
        else:
            print(f"\n--- Outfit {i+1} --- No valid outfit found.")

# ========================
# 6. Test for Casual, Summer
# ========================
generate_outfits("U001", occasion="casual", season="Summer", n_outfits=3)

=== Outfit Suggestions for U001 (Casual, Summer) ===

--- Outfit 1 ---
ProductID        ProductName Category  Score
     P002 White Cotton Shirt      Top  222.0
     P001   Blue Denim Jeans   Bottom  285.0

--- Outfit 2 ---
ProductID        ProductName  Category  Score
     P002 White Cotton Shirt       Top  222.0
     P001   Blue Denim Jeans    Bottom  285.0
     P010     White Sneakers     Shoes  385.0
     P015  Brown Leather Bag Accessory  210.0

--- Outfit 3 ---
ProductID        ProductName Category  Score
     P002 White Cotton Shirt      Top  222.0
     P001   Blue Denim Jeans   Bottom  285.0
     P010     White Sneakers    Shoes  385.0

In [93]:
print(df.columns)

Index(['ProductID', 'ProductName', 'Category', 'Occasion', 'Season',
       'Popularity', 'Feedback', 'Score'],
      dtype='object')

In [94]:
import pandas as pd
import numpy as np
import random

# ======================
# 1. Load your dataset
# ======================
df = pd.read_csv("FashionHub_products_cleaned.csv")  # update path if needed

# ======================
# 2. Add Dummy Popularity & Feedback
# ======================
np.random.seed(42)  # reproducibility
df["Popularity"] = np.random.randint(50, 1000, size=len(df))  # likes/sales
df["Feedback"] = np.round(np.random.uniform(3.0, 5.0, size=len(df)), 1)  # ratings

# ======================
# 3. Define Outfit Rules
# ======================
outfit_rules = {
    "party": ["Top", "Bottom", "Shoes", "Accessory"],
    "casual": ["Top", "Bottom", "Shoes"],
    "wedding": ["Dress", "Shoes", "Accessory"],
    "formal": ["Top", "Bottom", "Shoes"],
    "ethnic": ["Kurta", "Bottom", "Shoes", "Dupatta"]
}

# ======================
# 4. Outfit Generator
# ======================
def generate_outfits(occasion, season, style_preference, n_outfits=3):
    outfits = []
    
    # Filter dataset by season + style (if AI_Tags_Cleaned contains it)
    filtered = df[
        (df["Season"].str.lower().isin([season.lower(), "all"])) &
        (df["AI_Tags_Cleaned"].str.contains(style_preference.lower(), na=False)) &
        (df["AI_Tags_Cleaned"].str.contains(occasion.lower(), na=False))
    ]
    
    if filtered.empty:
        print("⚠️ No products match this filter. Try changing inputs.")
        return []
    
    # Get categories for the occasion
    categories = outfit_rules.get(occasion.lower(), ["Top", "Bottom", "Shoes"])
    
    for _ in range(n_outfits):
        outfit = []
        for cat in categories:
            options = filtered[filtered["Category"].str.lower() == cat.lower()]
            if not options.empty:
                # Sort by popularity + feedback
                best = options.sort_values(by=["Popularity", "Feedback"], ascending=False).head(5)
                choice = best.sample(1).iloc[0]
                outfit.append(choice)
        if outfit:
            outfits.append(pd.DataFrame(outfit))
    
    return outfits

# ======================
# 5. Example Run
# ======================
occasion = "party"
season = "winter"
style_preference = "western"

outfits = generate_outfits(occasion, season, style_preference, n_outfits=2)

# Show results
for i, outfit in enumerate(outfits, 1):
    print(f"\n=== Outfit {i} Suggestion ({occasion}, {season}, {style_preference}) ===")
    print(outfit[["ProductID", "ProductName", "Category", "Season", "Popularity", "Feedback"]])

=== Outfit 1 Suggestion (party, winter, western) ===
     ProductID         ProductName Category  Season  Popularity  Feedback
1463     P1464  Grey Silk Sneakers    Shoes  Winter         412       4.2

=== Outfit 2 Suggestion (party, winter, western) ===
     ProductID         ProductName Category  Season  Popularity  Feedback
1463     P1464  Grey Silk Sneakers    Shoes  Winter         412       4.2

In [95]:
import pandas as pd
import numpy as np
import random

# ======================
# 1. Load your dataset
# ======================
df = pd.read_csv("FashionHub_products_cleaned.csv")  # update path if needed

# ======================
# 2. Add Dummy Popularity & Feedback
# ======================
np.random.seed(42)  # reproducibility
df["Popularity"] = np.random.randint(50, 1000, size=len(df))  # likes/sales
df["Feedback"] = np.round(np.random.uniform(3.0, 5.0, size=len(df)), 1)  # ratings

# ======================
# 3. Realistic Outfit Rules (Pakistani + Western)
# ======================
outfit_rules = {
    "casual": ["Top", "Bottom", "Shoes"],  
    "party": ["Top", "Bottom", "Shoes", "Accessory"],  
    "formal": ["Shirt", "Trousers", "Blazer", "Shoes"],  
    "wedding": ["Dress", "Shoes", "Dupatta", "Accessory"],  
    "ethnic": ["Kurta", "Shalwar", "Dupatta", "Shoes"],  
    "work": ["Shirt", "Trousers", "Shoes"],  
    "summer": ["Kurti", "Jeans", "Sandals"],  
    "winter": ["Sweater", "Jeans", "Jacket", "Shoes"]
}

# ======================
# 4. Outfit Generator
# ======================
def generate_outfits(occasion, season, style_preference, n_outfits=3):
    outfits = []
    
    # Filter dataset by season + style (if AI_Tags_Cleaned contains it)
    filtered = df[
        (df["Season"].str.lower().isin([season.lower(), "all"])) &
        (df["AI_Tags_Cleaned"].str.contains(style_preference.lower(), na=False)) &
        (df["AI_Tags_Cleaned"].str.contains(occasion.lower(), na=False))
    ]
    
    if filtered.empty:
        print("⚠️ No products match this filter. Try changing inputs.")
        return []
    
    # Get categories for the occasion
    categories = outfit_rules.get(occasion.lower(), ["Top", "Bottom", "Shoes"])
    
    for _ in range(n_outfits):
        outfit = []
        for cat in categories:
            options = filtered[filtered["Category"].str.lower() == cat.lower()]
            if not options.empty:
                # Sort by popularity + feedback
                best = options.sort_values(by=["Popularity", "Feedback"], ascending=False).head(5)
                choice = best.sample(1).iloc[0]
                outfit.append(choice)
        if outfit:
            outfits.append(pd.DataFrame(outfit))
    
    return outfits

# ======================
# 5. Example Run
# ======================
occasion = "wedding"       # try: casual, party, formal, ethnic, work
season = "summer"          # try: summer, winter, all
style_preference = "ethnic"  # try: ethnic, western

outfits = generate_outfits(occasion, season, style_preference, n_outfits=2)

# Show results
for i, outfit in enumerate(outfits, 1):
    print(f"\n=== Outfit {i} Suggestion ({occasion}, {season}, {style_preference}) ===")
    print(outfit[["ProductID", "ProductName", "Category", "Season", "Popularity", "Feedback"]])

=== Outfit 1 Suggestion (wedding, summer, ethnic) ===
     ProductID               ProductName Category  Season  Popularity  \
1471     P1472  Brown Linen Formal Shoes    Shoes  Summer         877

      Feedback
1471       3.3

=== Outfit 2 Suggestion (wedding, summer, ethnic) ===
    ProductID           ProductName Category  Season  Popularity  Feedback
186     P0187  Brown Linen Sneakers    Shoes  Summer         913       3.1

In [96]:
# premium_ai_stylist.py
# Paste into Jupyter or save & run with: python premium_ai_stylist.py
import pandas as pd
import numpy as np
import random
from typing import List, Dict

random.seed(42)
np.random.seed(42)

# ---------- 0. Load dataset ----------
# Update the path if needed. Assumes file is in same folder.
CSV_PATH = "FashionHub_products_cleaned.csv"

df = pd.read_csv(CSV_PATH)

# ---------- 1. Make sure required columns exist ----------
# We saw the user's dataset columns earlier:
# ['ProductID', 'SellerID', 'SellerName', 'Category', 'SubCategory',
#  'ProductName', 'PricePKR', 'Gender', 'Color', 'Material', 'Season',
#  'StockQty', 'AI_Tags', 'Corrected_Gender', 'AI_Tags_Cleaned']

# Normalize some column names that might vary
if "AI_Tags_Cleaned" not in df.columns and "AI_Tags" in df.columns:
    df["AI_Tags_Cleaned"] = df["AI_Tags"].astype(str)
if "AI_Tags_Cleaned" not in df.columns:
    df["AI_Tags_Cleaned"] = df["ProductName"].astype(str)  # fallback

# add Popularity and Feedback columns if missing (dummy values)
if "Popularity" not in df.columns:
    df["Popularity"] = np.random.randint(50, 1000, size=len(df))
if "Feedback" not in df.columns:
    df["Feedback"] = np.round(np.random.uniform(3.0, 5.0, size=len(df)), 1)

# Ensure Category column exists and normalized
if "Category" not in df.columns:
    # try SubCategory fallback or infer from ProductName
    if "SubCategory" in df.columns:
        df["Category"] = df["SubCategory"]
    else:
        df["Category"] = df["ProductName"].apply(lambda x: "Other")

# normalize text columns
df["AI_Tags_Cleaned"] = df["AI_Tags_Cleaned"].fillna("").astype(str).str.lower()
df["Category"] = df["Category"].fillna("Other").astype(str)
df["Season"] = df["Season"].fillna("all").astype(str).str.lower()
df["Gender"] = df["Gender"].fillna("").astype(str).str.lower()

# ---------- 2. Category keyword mapping (helps when Category names are messy) ----------
# Keywords mapped to normalized category types we use for outfit rules
KEYWORD_CATEGORY_MAP = {
    "jeans": "bottom",
    "trouser": "bottom",
    "trousers": "bottom",
    "pant": "bottom",
    "shalwar": "bottom",
    "kurta": "top",
    "kameez": "top",
    "shirt": "top",
    "t-shirt": "top",
    "tshirt": "top",
    "hoodie": "top",
    "sweater": "outerwear",
    "jacket": "outerwear",
    "coat": "outerwear",
    "abaya": "dress_modest",
    "saree": "dress_modest",
    "gown": "dress_modest",
    "maxi": "dress_modest",
    "lehenga": "dress_modest",
    "dress": "dress_modest",
    "kurti": "top",
    "dupatt": "dupatt a",  # will match dupatta with startswith check
    "dupatta": "dupatt a",
    "scarf": "accessory",
    "belt": "accessory",
    "ring": "accessory",
    "necklace": "accessory",
    "bracelet": "accessory",
    "bag": "bag",
    "handbag": "bag",
    "backpack": "bag",
    "clutch": "bag",
    "shoe": "shoes",
    "shoes": "shoes",
    "sneaker": "shoes",
    "sneakers": "shoes",
    "heels": "shoes",
    "sandals": "shoes",
    "khussa": "shoes",
    "loafers": "shoes",
}

def normalize_category(name: str) -> str:
    name_l = str(name).lower()
    # direct match against existing category string
    for k, normalized in KEYWORD_CATEGORY_MAP.items():
        if k in name_l:
            return normalized
    # fallback: use original category (lower)
    return name_l.strip()

df["NormCategory"] = df["Category"].apply(normalize_category)

# ---------- 3. Gender-aware outfit rule sets ----------
# We'll keep separate templates for male & female, plus neutral fallback
OUTFIT_TEMPLATES = {
    "female": {
        "casual": ["top", "bottom", "shoes", "accessory"],
        "formal": ["top", "bottom", "shoes", "accessory"],
        "party": ["dress_modest", "shoes", "accessory", "bag"],
        "wedding": ["dress_modest", "shoes", "accessory", "bag"],
        "ethnic": ["top", "bottom", "dupatt a", "shoes", "accessory"],
        "work": ["top", "bottom", "shoes", "accessory"]
    },
    "male": {
        "casual": ["top", "bottom", "shoes", "outerwear"],
        "formal": ["top", "bottom", "shoes", "outerwear"],
        "party": ["top", "bottom", "shoes", "accessory"],
        "wedding": ["dress_modest", "shoes", "accessory"],  # dress_modest for sherwani etc.
        "ethnic": ["top", "bottom", "shoes", "accessory"],
        "work": ["top", "bottom", "shoes"]
    },
    "neutral": {
        "casual": ["top", "bottom", "shoes"],
        "formal": ["top", "bottom", "shoes"],
        "party": ["dress_modest", "shoes", "accessory"],
        "wedding": ["dress_modest", "shoes", "accessory"],
        "ethnic": ["top", "bottom", "dupatt a", "shoes"],
        "work": ["top", "bottom", "shoes"]
    }
}

# ---------- 4. Scoring helpers ----------
def relevance_tag_score(item_tags: str, desired_tags: List[str]) -> int:
    # desired_tags: e.g., ['summer', 'ethnic', 'party']
    if not item_tags:
        return 0
    item_set = set([t.strip() for t in item_tags.split(",") if t.strip()])
    # count matches
    return sum(1 for dt in desired_tags if dt in item_set)

def item_score(row: pd.Series, desired_tags: List[str]) -> float:
    # base relevance (tag matches)
    rel = relevance_tag_score(row["AI_Tags_Cleaned"], desired_tags)
    # popularity normalized and feedback weighted
    pop = row.get("Popularity", 0)
    fb = row.get("Feedback", 0)
    # normalize pop roughly to 0-1 by dividing by a scale (we'll use 1000)
    pop_norm = pop / 1000.0
    # feedback is typically 1-5 -> normalize to 0-1
    fb_norm = (fb - 1.0) / 4.0 if fb >= 1 else 0
    # final weighted score
    return rel * 2.0 + pop_norm * 1.5 + fb_norm * 1.0

# ---------- 5. Outfit generation core ----------
def generate_style_aware_outfits(
    occasion: str,
    season: str,
    style_preference: str,
    gender: str = None,
    n_outfits: int = 3,
    top_k_candidates: int = 10
) -> List[Dict]:
    """
    Returns a list of outfits. Each outfit is a dict:
    { "score": float, "items": [row_dicts...] }
    Inputs:
     - occasion: casual|formal|party|wedding|ethnic|work
     - season: summer|winter|all
     - style_preference: western|ethnic|trendy|modest (string matched against AI_Tags_Cleaned)
     - gender: 'male' | 'female' or None
    """
    occ = str(occasion).lower()
    sea = str(season).lower()
    style = str(style_preference).lower()
    gender_norm = (str(gender).lower() if gender else None)
    if gender_norm not in ("male", "female"):
        gender_key = "neutral"
    else:
        gender_key = gender_norm

    # choose template
    template = OUTFIT_TEMPLATES.get(gender_key, OUTFIT_TEMPLATES["neutral"])
    if occ not in template:
        occ = "casual"  # fallback
    slot_list = template[occ]  # sequence of category keys to fill

    # desired tags list used for relevance
    desired_tags = [t.strip().lower() for t in [sea, style, occ] if t]

    # Pre-filter the catalog by season & style & (optionally) gender-ish tags
    def product_filter(df_local):
        # season: allow "all" or matching season
        df_local = df_local[df_local["Season"].fillna("all").str.lower().isin([sea, "all"])]
        # style_preference: must appear in AI tags (if style empty skip)
        if style:
            df_local = df_local[df_local["AI_Tags_Cleaned"].str.contains(style, na=False)]
        # optional: prefer gender-specific matches if Gender column exists and user specified gender
        if gender_norm:
            # match Corrected_Gender or Gender if exists
            if "Corrected_Gender" in df_local.columns:
                df_local = df_local[df_local["Corrected_Gender"].fillna("").str.lower().str.contains(gender_norm) | df_local["Corrected_Gender"].isnull()]
            elif "Gender" in df_local.columns:
                df_local = df_local[df_local["Gender"].fillna("").str.lower().str.contains(gender_norm) | df_local["Gender"].isnull()]
        return df_local

    catalog = df.copy()
    catalog = product_filter(catalog)

    if catalog.empty:
        return []

    # For each category slot, build candidate pools
    # We map normalized category keys (slot_list entries) to products whose NormCategory matches.
    candidates_by_slot = {}
    for slot in set(slot_list):
        # slot might be e.g. "dupatt a" or "dress_modest", etc.
        pool = catalog[catalog["NormCategory"].str.contains(slot, na=False)]
        # fallback: if pool empty, try matching by Category exact lowercase
        if pool.empty:
            pool = catalog[catalog["Category"].str.lower() == slot]
        # compute item scores and keep top_k_candidates
        if not pool.empty:
            pool = pool.copy()
            pool["ItemScore"] = pool.apply(lambda r: item_score(r, desired_tags), axis=1)
            pool = pool.sort_values(by="ItemScore", ascending=False).head(top_k_candidates)
        candidates_by_slot[slot] = pool

    # Generate outfit candidates by sampling from candidate pools (yield up to many tries)
    outfits = []
    attempts = 0
    max_attempts = max(n_outfits * 30, 100)  # try enough times to get varied outfits
    while len(outfits) < n_outfits and attempts < max_attempts:
        attempts += 1
        chosen_items = []
        valid = True
        for slot in slot_list:
            pool = candidates_by_slot.get(slot, pd.DataFrame())
            if pool.empty:
                # fallback: try any item in catalog that matches season & style & not duplicate category
                fallback_pool = catalog.copy()
                fallback_pool["ItemScore"] = fallback_pool.apply(lambda r: item_score(r, desired_tags), axis=1)
                fallback_pool = fallback_pool.sort_values("ItemScore", ascending=False).head(top_k_candidates)
                if fallback_pool.empty:
                    valid = False
                    break
                chosen = fallback_pool.sample(1).iloc[0]
            else:
                chosen = pool.sample(1).iloc[0]
            # avoid duplicate productID in same outfit
            if any(chosen["ProductID"] == it["ProductID"] for it in chosen_items):
                valid = False
                break
            chosen_items.append(chosen.to_dict())
        if not valid:
            continue
        # compute outfit score = sum item scores (recompute to be safe)
        total_score = sum(item_score(pd.Series(item), desired_tags) for item in chosen_items)
        outfits.append({"score": total_score, "items": chosen_items})

    # sort outfits by score descending and return
    outfits = sorted(outfits, key=lambda x: x["score"], reverse=True)
    return outfits

# ---------- 6. Pretty display helper ----------
def print_outfits(outfits: List[Dict], occasion: str, season: str, style_preference: str):
    if not outfits:
        print("No outfits found for these inputs.")
        return
    print(f"\n=== AI Stylist: {occasion.title()} | {season.title()} | {style_preference.title()} ===")
    for idx, outfit in enumerate(outfits, 1):
        print("\n" + ("=" * 48))
        print(f"Outfit {idx}  —  Score: {int(outfit['score'])}")
        for item in outfit["items"]:
            cat = item.get("Category", item.get("NormCategory", ""))
            print(f" • {cat.title():15} : {item.get('ProductName')}  |  PKR {item.get('PricePKR')}  |  Seller: {item.get('SellerName')}")
        print("=" * 48)

# ---------- 7. Example usage ----------
if __name__ == "__main__":
    # Example 1: Female, Casual, Summer, Ethnic style
    outfits1 = generate_style_aware_outfits(occasion="casual", season="summer", style_preference="ethnic", gender="female", n_outfits=3)
    print_outfits(outfits1, "casual", "summer", "ethnic")

    # Example 2: Female, Wedding, Summer, Ethnic
    outfits2 = generate_style_aware_outfits(occasion="wedding", season="summer", style_preference="ethnic", gender="female", n_outfits=3)
    print_outfits(outfits2, "wedding", "summer", "ethnic")

    # Example 3: Male, Party, Winter, Western
    outfits3 = generate_style_aware_outfits(occasion="party", season="winter", style_preference="western", gender="male", n_outfits=3)
    print_outfits(outfits3, "party", "winter", "western")

No outfits found for these inputs.
No outfits found for these inputs.
No outfits found for these inputs.

In [97]:
print(df["Season"].unique())
print(df["AI_Tags_Cleaned"].head(20))
print(df["Gender"].unique() if "Gender" in df.columns else "No Gender column")

['all-season' 'summer' 'winter']
0         summer, ethnic, casual, men, all-season
1                    formal, party, summer, women
2         ethnic, casual, wedding, unisex, summer
3          trendy, casual, wedding, women, winter
4                      formal, party, winter, men
5     wedding, casual, ethnic, unisex, all-season
6           western, wedding, formal, men, summer
7                 formal, wedding, summer, unisex
8                      party, summer, winter, men
9      ethnic, formal, trendy, unisex, all-season
10     summer, winter, western, women, all-season
11                    winter, casual, formal, men
12     formal, party, wedding, unisex, all-season
13         formal, casual, wedding, women, winter
14         party, formal, ethnic, men, all-season
15           summer, casual, western, men, winter
16     western, ethnic, winter, women, all-season
17                western, formal, summer, unisex
18      wedding, summer, party, women, all-season
19        formal, ethnic, wedding, unisex, summer
Name: AI_Tags_Cleaned, dtype: object
['men' 'women' 'kids' 'unisex']

In [98]:
import pandas as pd
import random

# -------------------------------
# 1. Load dataset
# -------------------------------
df = pd.read_csv("FashionHub_products_cleaned.csv")

# Add dummy popularity + feedback if not present
if "Popularity" not in df.columns:
    df["Popularity"] = [random.randint(50, 200) for _ in range(len(df))]
if "Feedback" not in df.columns:
    df["Feedback"] = [round(random.uniform(3.0, 5.0), 1) for _ in range(len(df))]

# -------------------------------
# 2. Define Outfit Rules
# -------------------------------
outfit_rules = {
    "casual": ["Top", "Bottom", "Shoes"],
    "formal": ["Top", "Bottom", "Shoes"],
    "party": ["Top", "Bottom", "Shoes", "Accessory"],
    "wedding": ["Top", "Bottom", "Shoes", "Accessory"]
}

# -------------------------------
# 3. Outfit Generator Function
# -------------------------------
def generate_outfits(season, gender, occasion, n_outfits=3):
    if occasion not in outfit_rules:
        return pd.DataFrame([{"Message": f"No rules for {occasion}"}])
    
    categories = outfit_rules[occasion]
    
    # Filter by season + gender
    filtered = df[
        df["AI_Tags_Cleaned"].str.contains(season, case=False, na=False) &
        df["Corrected_Gender"].str.contains(gender, case=False, na=False)
    ]
    
    if filtered.empty:
        return pd.DataFrame([{"Message": "⚠️ No outfits found for these filters"}])
    
    outfits = []
    for _ in range(n_outfits):
        outfit_items = []
        for cat in categories:
            options = filtered[filtered["Category"] == cat]
            if not options.empty:
                best = options.sort_values(
                    by=["Popularity", "Feedback"], ascending=False
                ).head(5)
                chosen = best.sample(1).iloc[0]
                outfit_items.append(chosen)
        
        if outfit_items:
            outfit_df = pd.DataFrame([item for _, item in pd.DataFrame(outfit_items).iterrows()])
            outfits.append(outfit_df[["ProductID", "ProductName", "Category", "Season", "Popularity", "Feedback"]])
    
    return outfits if outfits else pd.DataFrame([{"Message": "⚠️ Couldn’t form a full outfit"}])

# -------------------------------
# 4. Example Test Run
# -------------------------------
results = generate_outfits(season="summer", gender="women", occasion="casual", n_outfits=2)

if isinstance(results, list):
    for i, outfit in enumerate(results, 1):
        print(f"\n=== Outfit {i} ===")
        display(outfit)
else:
    display(results)

=== Outfit 1 ===

    ProductID         ProductName Category      Season  Popularity  Feedback
719     P0720  Blue Denim Sandals    Shoes  All-season         185       3.4

=== Outfit 2 ===

,ProductID,ProductName,Category,Season,Popularity,Feedback
272,P0273,Black Polyester Sneakers,Shoes,All-season,199,3.7

In [99]:
import pandas as pd
import numpy as np

# ===============================
# Load Dataset
# ===============================
df = pd.read_csv("FashionHub_products_cleaned.csv")

# -------------------------------
# Step 1: Add synthetic popularity & feedback for testing
# -------------------------------
np.random.seed(42)
df["Popularity"] = np.random.randint(50, 200, size=len(df))
df["Feedback"] = np.round(np.random.uniform(3, 5, size=len(df)), 1)

# -------------------------------
# Step 2: Map SubCategory → OutfitCategory
# -------------------------------
category_map = {
    # Tops
    "shirt": "Top", "tshirt": "Top", "kurti": "Top", "hoodie": "Top",
    "abaya": "Top", "scarf": "Top", "kameez": "Top", "blouse": "Top",

    # Bottoms
    "jeans": "Bottom", "trouser": "Bottom", "pants": "Bottom", "shalwar": "Bottom",
    "skirt": "Bottom", "saree": "Bottom", "shorts": "Bottom",

    # Shoes
    "sneakers": "Shoes", "sandals": "Shoes", "heels": "Shoes",
    "shoes": "Shoes", "boots": "Shoes",

    # Accessories
    "ring": "Accessory", "bag": "Accessory", "watch": "Accessory",
    "bracelet": "Accessory", "cap": "Accessory"
}

def map_outfit_category(subcat):
    subcat = str(subcat).lower()
    for key, value in category_map.items():
        if key in subcat:
            return value
    return "Other"

df["OutfitCategory"] = df["SubCategory"].apply(map_outfit_category)

# -------------------------------
# Step 3: Outfit rules
# -------------------------------
outfit_rules = {
    "casual": ["Top", "Bottom", "Shoes"],
    "party": ["Top", "Bottom", "Shoes", "Accessory"],
    "wedding": ["Top", "Bottom", "Shoes", "Accessory"],
    "formal": ["Top", "Bottom", "Shoes"]
}

# -------------------------------
# Step 4: Outfit generator
# -------------------------------
def generate_outfits(occasion, season, style_pref=None, n_outfits=3):
    # Filter by season (allow all-season too)
    filtered = df[
        (df["Season"].str.lower().str.contains(season.lower())) |
        (df["Season"].str.lower().str.contains("all-season"))
    ]

    # Further filter by style preference if given
    if style_pref:
        filtered = filtered[filtered["AI_Tags_Cleaned"].str.contains(style_pref, case=False, na=False)]

    categories = outfit_rules.get(occasion.lower(), ["Top", "Bottom", "Shoes"])
    outfits = []

    for _ in range(n_outfits):
        outfit_items = []
        for cat in categories:
            options = filtered[filtered["OutfitCategory"] == cat]
            if not options.empty:
                best = options.sort_values(
                    by=["Popularity", "Feedback"],
                    ascending=False
                ).head(5).sample(1)
                outfit_items.append(best)

        if len(outfit_items) == len(categories):  # only keep complete outfits
            outfits.append(pd.concat(outfit_items))

    return outfits

# -------------------------------
# Step 5: Test the system
# -------------------------------
occasion = "party"
season = "summer"
style_preference = "western"

outfits = generate_outfits(occasion, season, style_preference, n_outfits=2)

if outfits:
    for i, outfit in enumerate(outfits, 1):
        print(f"\n=== Outfit {i} ({occasion.title()}, {season.title()}, {style_preference}) ===")
        print(outfit[["ProductID", "ProductName", "OutfitCategory", "Season", "Popularity", "Feedback"]])
else:
    print("❌ No outfits found for these inputs.")

=== Outfit 1 (Party, Summer, western) ===
     ProductID          ProductName OutfitCategory      Season  Popularity  \
1379     P1380  Yellow Cotton Abaya            Top  All-season         197
1486     P1487   Yellow Denim Saree         Bottom      Summer         170
1466     P1467     Red Wool Sandals          Shoes      Summer         188
1218     P1219      Beige Silk Ring      Accessory  All-season         190

      Feedback
1379       3.7
1486       4.9
1466       4.6
1218       4.6

=== Outfit 2 (Party, Summer, western) ===
     ProductID         ProductName OutfitCategory      Season  Popularity  \
1298     P1299  Red Leather Hoodie            Top      Summer         191
437      P0438    Black Silk Saree         Bottom  All-season         169
814      P0815   Grey Lawn Sandals          Shoes  All-season         187
1498     P1499      Grey Denim Cap      Accessory      Summer         199

      Feedback
1298       3.0
437        4.6
814        4.0
1498       3.2

In [100]:
import pandas as pd
import random

# Load dataset
df = pd.read_csv("FashionHub_products_cleaned.csv")

# --- STEP 0: Add missing columns if not exist ---
if "Popularity" not in df.columns:
    df["Popularity"] = [random.randint(50, 200) for _ in range(len(df))]
if "Feedback" not in df.columns:
    df["Feedback"] = [round(random.uniform(3.0, 5.0), 1) for _ in range(len(df))]

# --- STEP 1: Define outfit categories ---
category_map = {
    "Top": ["Shirt", "Kurta", "Hoodie", "Abaya", "Jacket", "T-Shirt"],
    "Bottom": ["Trousers", "Jeans", "Shalwar", "Saree", "Skirt"],
    "Shoes": ["Shoes", "Sneakers", "Sandals", "Heels", "Khussa"],
    "Accessory": ["Watch", "Ring", "Bag", "Cap", "Scarf", "Jewelry"]
}

def map_outfit_category(product_name):
    for cat, keywords in category_map.items():
        if any(kw.lower() in str(product_name).lower() for kw in keywords):
            return cat
    return None

df["OutfitCategory"] = df["ProductName"].apply(map_outfit_category)
df = df.dropna(subset=["OutfitCategory"])  # keep only relevant products

# --- STEP 2: Outfit generator ---
def generate_outfits(style_tags, num_outfits=2):
    outfits = []

    for _ in range(num_outfits):
        outfit = {}
        for cat in ["Top", "Bottom", "Shoes", "Accessory"]:
            candidates = df[
                (df["OutfitCategory"] == cat) &
                (df["AI_Tags_Cleaned"].str.contains(style_tags[0], case=False, na=False)) &
                (df["AI_Tags_Cleaned"].str.contains(style_tags[1], case=False, na=False)) &
                (df["AI_Tags_Cleaned"].str.contains(style_tags[2], case=False, na=False))
            ]

            if candidates.empty:
                candidates = df[df["OutfitCategory"] == cat]  # fallback

            if not candidates.empty:
                outfit[cat] = candidates.sample(1).iloc[0]

        outfits.append(outfit)

    return outfits

# --- STEP 3: Pretty printing ---
def display_outfits(outfits, style_tags):
    for i, outfit in enumerate(outfits, 1):
        print(f"\n=== Outfit {i} ({', '.join(style_tags)}) ===")
        rows = []
        for cat, item in outfit.items():
            rows.append({
                "ProductID": item["ProductID"],
                "ProductName": item["ProductName"],
                "OutfitCategory": cat,
                "Season": item["Season"],
                "Popularity": item["Popularity"],
                "Feedback": item["Feedback"]
            })
        display(pd.DataFrame(rows))

# --- Example run ---
style_tags = ["party", "summer", "western"]
outfits = generate_outfits(style_tags, num_outfits=2)
display_outfits(outfits, style_tags)

=== Outfit 1 (party, summer, western) ===

,ProductID,ProductName,OutfitCategory,Season,Popularity,Feedback
0,P0895,Grey Wool T-Shirt,Top,Summer,134,3.6
1,P0438,Black Silk Saree,Bottom,All-season,193,4.2
2,P1398,Black Wool Formal Shoes,Shoes,Summer,182,4.3
3,P0185,Blue Linen Earrings,Accessory,Winter,149,3.5

=== Outfit 2 (party, summer, western) ===

,ProductID,ProductName,OutfitCategory,Season,Popularity,Feedback
0,P0338,Grey Denim Formal Shirt,Top,Summer,151,3.9
1,P0438,Black Silk Saree,Bottom,All-season,193,4.2
2,P1467,Red Wool Sandals,Shoes,Summer,196,4.2
3,P1433,Beige Denim Cap,Accessory,All-season,194,3.8

In [101]:
import pandas as pd
import random

# Load dataset
df = pd.read_csv("FashionHub_products_cleaned.csv")

# --- STEP 0: Add missing columns if not exist ---
if "Popularity" not in df.columns:
    df["Popularity"] = [random.randint(50, 200) for _ in range(len(df))]
if "Feedback" not in df.columns:
    df["Feedback"] = [round(random.uniform(3.0, 5.0), 1) for _ in range(len(df))]

# --- STEP 1: Define outfit categories ---
category_map = {
    "Top": ["Shirt", "Kurta", "Hoodie", "Abaya", "Jacket", "T-Shirt", "Kurti"],
    "Bottom": ["Trousers", "Jeans", "Shalwar", "Saree", "Skirt", "Pants"],
    "Shoes": ["Shoes", "Sneakers", "Sandals", "Heels", "Khussa", "Loafers"],
    "Accessory": ["Watch", "Ring", "Bag", "Cap", "Scarf", "Jewelry", "Belt"]
}

def map_outfit_category(product_name):
    for cat, keywords in category_map.items():
        if any(kw.lower() in str(product_name).lower() for kw in keywords):
            return cat
    return None

df["OutfitCategory"] = df["ProductName"].apply(map_outfit_category)
df = df.dropna(subset=["OutfitCategory"])  # keep only relevant products

# --- STEP 2: Outfit generator with gender consistency ---
def generate_outfits(style_tags, num_outfits=2):
    outfits = []

    for _ in range(num_outfits):
        # Pick a gender randomly for this outfit (men/women/unisex)
        chosen_gender = random.choice(["men", "women", "unisex"])
        
        outfit = {}
        for cat in ["Top", "Bottom", "Shoes", "Accessory"]:
            candidates = df[
                (df["OutfitCategory"] == cat) &
                (df["Corrected_Gender"].str.lower() == chosen_gender) &
                (df["AI_Tags_Cleaned"].str.contains(style_tags[0], case=False, na=False)) &
                (df["AI_Tags_Cleaned"].str.contains(style_tags[1], case=False, na=False)) &
                (df["AI_Tags_Cleaned"].str.contains(style_tags[2], case=False, na=False))
            ]

            if candidates.empty:
                # fallback: same gender only
                candidates = df[
                    (df["OutfitCategory"] == cat) &
                    (df["Corrected_Gender"].str.lower() == chosen_gender)
                ]

            if not candidates.empty:
                outfit[cat] = candidates.sample(1).iloc[0]

        outfits.append((chosen_gender, outfit))

    return outfits

# --- STEP 3: Pretty printing ---
def display_outfits(outfits, style_tags):
    for i, (gender, outfit) in enumerate(outfits, 1):
        print(f"\n=== Outfit {i} ({', '.join(style_tags)}, Gender: {gender}) ===")
        rows = []
        for cat, item in outfit.items():
            rows.append({
                "ProductID": item["ProductID"],
                "ProductName": item["ProductName"],
                "OutfitCategory": cat,
                "Season": item["Season"],
                "Popularity": item["Popularity"],
                "Feedback": item["Feedback"]
            })
        display(pd.DataFrame(rows))

# --- Example run ---
style_tags = ["party", "summer", "western"]
outfits = generate_outfits(style_tags, num_outfits=2)
display_outfits(outfits, style_tags)

=== Outfit 1 (party, summer, western, Gender: unisex) ===

,ProductID,ProductName,OutfitCategory,Season,Popularity,Feedback
0,P1018,Brown Leather Formal Shirt,Top,All-season,126,3.0
1,P0438,Black Silk Saree,Bottom,All-season,198,4.6
2,P1467,Red Wool Sandals,Shoes,Summer,57,3.5
3,P1379,Grey Lawn Cap,Accessory,Summer,81,3.2

=== Outfit 2 (party, summer, western, Gender: women) ===

,ProductID,ProductName,OutfitCategory,Season,Popularity,Feedback
0,P0366,Green Cotton Kurta,Top,Summer,75,3.2
1,P1044,Beige Leather Saree,Bottom,Summer,137,3.6
2,P1133,Grey Denim Formal Shoes,Shoes,Summer,87,3.2
3,P0945,White Wool Earrings,Accessory,Summer,193,3.8

In [102]:
import pandas as pd
import random

# Load dataset
df = pd.read_csv("FashionHub_products_cleaned.csv")

# --- STEP 0: Add missing columns if not exist ---
if "Popularity" not in df.columns:
    df["Popularity"] = [random.randint(50, 200) for _ in range(len(df))]
if "Feedback" not in df.columns:
    df["Feedback"] = [round(random.uniform(3.0, 5.0), 1) for _ in range(len(df))]

# --- STEP 1: Define outfit categories ---
category_map = {
    "Top": ["Shirt", "Kurta", "Hoodie", "Abaya", "Jacket", "T-Shirt", "Kurti"],
    "Bottom": ["Trousers", "Jeans", "Shalwar", "Saree", "Skirt", "Pants"],
    "Shoes": ["Shoes", "Sneakers", "Sandals", "Heels", "Khussa", "Loafers"],
    "Accessory": ["Watch", "Ring", "Bag", "Cap", "Scarf", "Jewelry", "Belt"]
}

def map_outfit_category(product_name):
    for cat, keywords in category_map.items():
        if any(kw.lower() in str(product_name).lower() for kw in keywords):
            return cat
    return None

df["OutfitCategory"] = df["ProductName"].apply(map_outfit_category)
df = df.dropna(subset=["OutfitCategory"])  # keep only relevant products

# --- STEP 2: Outfit generator with chosen gender ---
def generate_outfits(style_tags, chosen_gender="unisex", num_outfits=2):
    outfits = []

    for _ in range(num_outfits):
        outfit = {}
        for cat in ["Top", "Bottom", "Shoes", "Accessory"]:
            candidates = df[
                (df["OutfitCategory"] == cat) &
                (df["Corrected_Gender"].str.lower() == chosen_gender.lower()) &
                (df["AI_Tags_Cleaned"].str.contains(style_tags[0], case=False, na=False)) &
                (df["AI_Tags_Cleaned"].str.contains(style_tags[1], case=False, na=False)) &
                (df["AI_Tags_Cleaned"].str.contains(style_tags[2], case=False, na=False))
            ]

            if candidates.empty:
                # fallback: same gender only
                candidates = df[
                    (df["OutfitCategory"] == cat) &
                    (df["Corrected_Gender"].str.lower() == chosen_gender.lower())
                ]

            if not candidates.empty:
                outfit[cat] = candidates.sample(1).iloc[0]

        outfits.append(outfit)

    return outfits

# --- STEP 3: Pretty printing ---
def display_outfits(outfits, style_tags, chosen_gender):
    for i, outfit in enumerate(outfits, 1):
        print(f"\n=== Outfit {i} ({', '.join(style_tags)}, Gender: {chosen_gender}) ===")
        rows = []
        for cat, item in outfit.items():
            rows.append({
                "ProductID": item["ProductID"],
                "ProductName": item["ProductName"],
                "OutfitCategory": cat,
                "Season": item["Season"],
                "Popularity": item["Popularity"],
                "Feedback": item["Feedback"]
            })
        display(pd.DataFrame(rows))

# --- Example run ---
style_tags = ["party", "summer", "western"]
chosen_gender = "women"  # 🔥 Change to "men", "women", or "unisex"
outfits = generate_outfits(style_tags, chosen_gender=chosen_gender, num_outfits=2)
display_outfits(outfits, style_tags, chosen_gender)

=== Outfit 1 (party, summer, western, Gender: women) ===

,ProductID,ProductName,OutfitCategory,Season,Popularity,Feedback
0,P0516,Beige Cotton T-Shirt,Top,Summer,95,3.5
1,P1344,Black Lawn Shalwar Kameez,Bottom,Summer,101,4.1
2,P1133,Grey Denim Formal Shoes,Shoes,Summer,108,4.7
3,P0945,White Wool Earrings,Accessory,Summer,61,3.8

=== Outfit 2 (party, summer, western, Gender: women) ===

,ProductID,ProductName,OutfitCategory,Season,Popularity,Feedback
0,P0516,Beige Cotton T-Shirt,Top,Summer,95,3.5
1,P1044,Beige Leather Saree,Bottom,Summer,151,3.2
2,P1133,Grey Denim Formal Shoes,Shoes,Summer,108,4.7
3,P1334,White Lawn Belt,Accessory,All-season,86,4.3

In [103]:
def generate_outfit_from_template(template):
    outfit = {}
    tags = [template["Occasion"], template["Season"], template["Style"]]
    gender = template["Gender"]

    for cat in ["Top", "Bottom", "Shoes", "Accessory"]:
        # start with base mask
        mask = (df["OutfitCategory"] == cat) & (df["Corrected_Gender"].str.lower() == gender.lower())
        
        # refine with tags
        for tag in tags:
            mask &= df["AI_Tags_Cleaned"].str.contains(tag, case=False, na=False)

        candidates = df[mask]

        if candidates.empty:
            candidates = df[
                (df["OutfitCategory"] == cat) &
                (df["Corrected_Gender"].str.lower() == gender.lower())
            ]

        if not candidates.empty:
            candidates = candidates.copy()
            candidates["Score"] = candidates["Popularity"] * candidates["Feedback"]
            best_item = candidates.sort_values("Score", ascending=False).iloc[0]
            outfit[cat] = best_item

    return outfit

In [104]:
import pandas as pd
import random

# ------------------- Load dataset -------------------
df = pd.read_csv("FashionHub_products_cleaned.csv")

# ------------------- Ensure columns exist -------------------
if "Popularity" not in df.columns:
    df["Popularity"] = [random.randint(50, 200) for _ in range(len(df))]
if "Feedback" not in df.columns:
    df["Feedback"] = [round(random.uniform(3.0, 5.0), 1) for _ in range(len(df))]

# ------------------- Map Outfit Categories -------------------
category_map = {
    "Top": ["Shirt", "Kurta", "Hoodie", "Abaya", "Jacket", "T-Shirt", "Kurti"],
    "Bottom": ["Trousers", "Jeans", "Shalwar", "Saree", "Skirt", "Pants"],
    "Shoes": ["Shoes", "Sneakers", "Sandals", "Heels", "Khussa", "Loafers"],
    "Accessory": ["Watch", "Ring", "Bag", "Cap", "Scarf", "Jewelry", "Belt"]
}

def map_outfit_category(name):
    for cat, kws in category_map.items():
        if any(kw.lower() in str(name).lower() for kw in kws):
            return cat
    return None

df["OutfitCategory"] = df["ProductName"].apply(map_outfit_category)
df = df.dropna(subset=["OutfitCategory"])

# ------------------- Dynamic Templates -------------------
outfit_templates = [
    {"Occasion": "party", "Season": "summer", "Style": "western", "Gender": "women"},
    {"Occasion": "casual", "Season": "winter", "Style": "eastern", "Gender": "men"},
    {"Occasion": "wedding", "Season": "all", "Style": "fusion", "Gender": "women"},
    {"Occasion": "work", "Season": "summer", "Style": "western", "Gender": "men"},
    {"Occasion": "streetwear", "Season": "all", "Style": "western", "Gender": "unisex"}
]

# ------------------- Outfit Generator -------------------
def generate_outfit_from_template(template, randomness=True):
    outfit = {}
    tags = [template["Occasion"], template["Season"], template["Style"]]
    gender = template["Gender"]

    for cat in ["Top", "Bottom", "Shoes", "Accessory"]:
        mask = (df["OutfitCategory"] == cat) & (df["Corrected_Gender"].str.lower() == gender.lower())
        for tag in tags:
            mask &= df["AI_Tags_Cleaned"].str.contains(tag, case=False, na=False)

        candidates = df[mask]

        # Fallbacks if no exact match
        if candidates.empty:
            mask_partial = (df["OutfitCategory"] == cat) & (df["Corrected_Gender"].str.lower() == gender.lower())
            candidates = df[mask_partial]

        if not candidates.empty:
            candidates = candidates.copy()
            candidates["Score"] = candidates["Popularity"] * candidates["Feedback"]
            if randomness and random.random() < 0.3:
                # 30% chance pick random
                best_item = candidates.sample(1).iloc[0]
            else:
                # 70% pick highest score
                best_item = candidates.sort_values("Score", ascending=False).iloc[0]
            outfit[cat] = best_item

    return outfit

# ------------------- Display Outfits -------------------
for t in outfit_templates:
    outfit = generate_outfit_from_template(t)
    print(f"\n=== Outfit ({t['Occasion']}, {t['Season']}, {t['Style']}, Gender: {t['Gender']}) ===")
    if outfit:
        rows = []
        for cat, item in outfit.items():
            rows.append({
                "ProductID": item["ProductID"],
                "ProductName": item["ProductName"],
                "OutfitCategory": cat,
                "Season": item["Season"],
                "Popularity": item["Popularity"],
                "Feedback": item["Feedback"],
                "Score": item["Score"]
            })
        display(pd.DataFrame(rows))
    else:
        print("⚠️ No outfit generated for this template.")

=== Outfit (party, summer, western, Gender: women) ===

,ProductID,ProductName,OutfitCategory,Season,Popularity,Feedback,Score
0,P0516,Beige Cotton T-Shirt,Top,Summer,77,3.6,277.2
1,P1044,Beige Leather Saree,Bottom,Summer,186,4.0,744.0
2,P1133,Grey Denim Formal Shoes,Shoes,Summer,170,3.9,663.0
3,P1329,Black Lawn Scarf,Accessory,Summer,134,4.7,629.8

=== Outfit (casual, winter, eastern, Gender: men) ===

,ProductID,ProductName,OutfitCategory,Season,Popularity,Feedback,Score
0,P0385,Brown Wool T-Shirt,Top,Summer,184,4.9,901.6
1,P0100,Pink Polyester Saree,Bottom,Summer,185,4.4,814.0
2,P0901,Black Lawn Sneakers,Shoes,Summer,184,4.9,901.6
3,P0503,Grey Cotton Ring,Accessory,All-season,199,4.9,975.1

=== Outfit (wedding, all, fusion, Gender: women) ===

,ProductID,ProductName,OutfitCategory,Season,Popularity,Feedback,Score
0,P0079,Beige Wool Formal Shirt,Top,Summer,192,4.8,921.6
1,P1157,Brown Denim Shalwar Kameez,Bottom,Summer,89,3.5,311.5
2,P1537,Blue Lawn Sandals,Shoes,All-season,168,5.0,840.0
3,P1266,Blue Lawn Belt,Accessory,Summer,164,4.3,705.2

=== Outfit (work, summer, western, Gender: men) ===

,ProductID,ProductName,OutfitCategory,Season,Popularity,Feedback,Score
0,P0385,Brown Wool T-Shirt,Top,Summer,184,4.9,901.6
1,P1452,Yellow Denim Jeans,Bottom,All-season,88,3.4,299.2
2,P0901,Black Lawn Sneakers,Shoes,Summer,184,4.9,901.6
3,P0503,Grey Cotton Ring,Accessory,All-season,199,4.9,975.1

=== Outfit (streetwear, all, western, Gender: unisex) ===

,ProductID,ProductName,OutfitCategory,Season,Popularity,Feedback,Score
0,P0598,Brown Linen Hoodie,Top,Summer,193,5.0,965.0
1,P0511,Black Linen Shalwar Kameez,Bottom,Winter,194,4.8,931.2
2,P0268,Grey Denim Sneakers,Shoes,Summer,156,3.9,608.4
3,P0065,Red Leather Earrings,Accessory,All-season,194,4.9,950.6

In [216]:
import pandas as pd
import random

# ------------------- Load dataset -------------------
df = pd.read_csv("FashionHub_products_cleaned.csv")

# ------------------- Ensure columns exist -------------------
if "Popularity" not in df.columns:
    df["Popularity"] = [random.randint(50, 200) for _ in range(len(df))]
if "Feedback" not in df.columns:
    df["Feedback"] = [round(random.uniform(3.0, 5.0), 1) for _ in range(len(df))]

# ------------------- Map Outfit Categories -------------------
category_map = {
    "Top": ["Shirt", "Kurta", "Hoodie", "Abaya", "Jacket", "T-Shirt", "Kurti"],
    "Bottom": ["Trousers", "Jeans", "Shalwar", "Saree", "Skirt", "Pants"],
    "Shoes": ["Shoes", "Sneakers", "Sandals", "Heels", "Khussa", "Loafers"],
    "Accessory": ["Watch", "Ring", "Bag", "Cap", "Scarf", "Jewelry", "Belt"]
}

def map_outfit_category(name):
    for cat, kws in category_map.items():
        if any(kw.lower() in str(name).lower() for kw in kws):
            return cat
    return None

df["OutfitCategory"] = df["ProductName"].apply(map_outfit_category)
df = df.dropna(subset=["OutfitCategory"])

# ------------------- Dynamic Templates -------------------
outfit_templates = [
    {"Occasion": "party", "Season": "summer", "Style": "western", "Gender": "women"},
    {"Occasion": "casual", "Season": "winter", "Style": "eastern", "Gender": "men"},
    {"Occasion": "wedding", "Season": "all", "Style": "fusion", "Gender": "women"},
    {"Occasion": "work", "Season": "summer", "Style": "western", "Gender": "men"},
    {"Occasion": "streetwear", "Season": "all", "Style": "western", "Gender": "unisex"}
]

# ------------------- Outfit Generator -------------------
def generate_outfit_from_template(template, num_outfits=2, randomness=True):
    all_outfits = []
    tags = [template["Occasion"], template["Season"], template["Style"]]
    gender = template["Gender"]

    for _ in range(num_outfits):
        outfit = {}
        for cat in ["Top", "Bottom", "Shoes", "Accessory"]:
            mask = (df["OutfitCategory"] == cat) & (df["Corrected_Gender"].str.lower() == gender.lower())
            for tag in tags:
                mask &= df["AI_Tags_Cleaned"].str.contains(tag, case=False, na=False)

            candidates = df[mask]

            # Fallbacks if no exact match
            if candidates.empty:
                mask_partial = (df["OutfitCategory"] == cat) & (df["Corrected_Gender"].str.lower() == gender.lower())
                candidates = df[mask_partial]

            if not candidates.empty:
                candidates = candidates.copy()
                candidates["Score"] = candidates["Popularity"] * candidates["Feedback"]
                if randomness and random.random() < 0.3:
                    best_item = candidates.sample(1).iloc[0]  # 30% random
                else:
                    best_item = candidates.sort_values("Score", ascending=False).iloc[0]  # 70% best
                outfit[cat] = best_item

        all_outfits.append(outfit)
    return all_outfits

# ------------------- Display Outfits -------------------
for t in outfit_templates:
    outfits = generate_outfit_from_template(t, num_outfits=3)  # 3 outfits per template
    for i, outfit in enumerate(outfits, 1):
        print(f"\n=== Outfit {i} ({t['Occasion']}, {t['Season']}, {t['Style']}, Gender: {t['Gender']}) ===")
        rows = []
        for cat, item in outfit.items():
            rows.append({
                "ProductID": item["ProductID"],
                "ProductName": item["ProductName"],
                "OutfitCategory": cat,
                "Season": item["Season"],
                "Popularity": item["Popularity"],
                "Feedback": item["Feedback"],
                "Score": item["Score"]
            })
        display(pd.DataFrame(rows))

=== Outfit 1 (party, summer, western, Gender: women) ===

,ProductID,ProductName,OutfitCategory,Season,Popularity,Feedback,Score
0,P0366,Green Cotton Kurta,Top,Summer,126,3.4,428.4
1,P1344,Black Lawn Shalwar Kameez,Bottom,Summer,132,4.6,607.2
2,P1133,Grey Denim Formal Shoes,Shoes,Summer,61,4.7,286.7
3,P1329,Black Lawn Scarf,Accessory,Summer,138,4.3,593.4

=== Outfit 2 (party, summer, western, Gender: women) ===

,ProductID,ProductName,OutfitCategory,Season,Popularity,Feedback,Score
0,P0366,Green Cotton Kurta,Top,Summer,126,3.4,428.4
1,P1344,Black Lawn Shalwar Kameez,Bottom,Summer,132,4.6,607.2
2,P1133,Grey Denim Formal Shoes,Shoes,Summer,61,4.7,286.7
3,P1329,Black Lawn Scarf,Accessory,Summer,138,4.3,593.4

=== Outfit 3 (party, summer, western, Gender: women) ===

,ProductID,ProductName,OutfitCategory,Season,Popularity,Feedback,Score
0,P0366,Green Cotton Kurta,Top,Summer,126,3.4,428.4
1,P1344,Black Lawn Shalwar Kameez,Bottom,Summer,132,4.6,607.2
2,P1133,Grey Denim Formal Shoes,Shoes,Summer,61,4.7,286.7
3,P1329,Black Lawn Scarf,Accessory,Summer,138,4.3,593.4

=== Outfit 1 (casual, winter, eastern, Gender: men) ===

,ProductID,ProductName,OutfitCategory,Season,Popularity,Feedback,Score
0,P0897,White Cotton Formal Shirt,Top,Winter,78,4.8,374.4
1,P1443,Black Polyester Shalwar Kameez,Bottom,Winter,193,4.8,926.4
2,P1472,Brown Linen Formal Shoes,Shoes,Summer,196,4.1,803.6
3,P0485,Yellow Lawn Cap,Accessory,Summer,191,4.8,916.8

=== Outfit 2 (casual, winter, eastern, Gender: men) ===

,ProductID,ProductName,OutfitCategory,Season,Popularity,Feedback,Score
0,P1417,Beige Linen Formal Shirt,Top,Summer,194,4.7,911.8
1,P1443,Black Polyester Shalwar Kameez,Bottom,Winter,193,4.8,926.4
2,P0510,Black Cotton Heels,Shoes,Winter,171,4.2,718.2
3,P0175,White Silk Belt,Accessory,All-season,158,3.6,568.8

=== Outfit 3 (casual, winter, eastern, Gender: men) ===

,ProductID,ProductName,OutfitCategory,Season,Popularity,Feedback,Score
0,P0573,Yellow Linen Kurta,Top,Summer,108,4.5,486.0
1,P1452,Yellow Denim Jeans,Bottom,All-season,81,5.0,405.0
2,P1472,Brown Linen Formal Shoes,Shoes,Summer,196,4.1,803.6
3,P0485,Yellow Lawn Cap,Accessory,Summer,191,4.8,916.8

=== Outfit 1 (wedding, all, fusion, Gender: women) ===

,ProductID,ProductName,OutfitCategory,Season,Popularity,Feedback,Score
0,P0011,Black Wool Abaya,Top,All-season,85,3.6,306.0
1,P0481,Blue Leather Jeans,Bottom,All-season,176,4.7,827.2
2,P0977,Pink Wool Sandals,Shoes,All-season,197,4.6,906.2
3,P0872,Red Denim Scarf,Accessory,Winter,67,3.1,207.7

=== Outfit 2 (wedding, all, fusion, Gender: women) ===

,ProductID,ProductName,OutfitCategory,Season,Popularity,Feedback,Score
0,P1033,Red Leather Abaya,Top,Summer,198,4.6,910.8
1,P0481,Blue Leather Jeans,Bottom,All-season,176,4.7,827.2
2,P0977,Pink Wool Sandals,Shoes,All-season,197,4.6,906.2
3,P1489,Red Lawn Handbag,Accessory,Winter,190,4.8,912.0

=== Outfit 3 (wedding, all, fusion, Gender: women) ===

,ProductID,ProductName,OutfitCategory,Season,Popularity,Feedback,Score
0,P0280,Red Lawn Kurta,Top,Winter,59,3.8,224.2
1,P1044,Beige Leather Saree,Bottom,Summer,69,3.8,262.2
2,P0977,Pink Wool Sandals,Shoes,All-season,197,4.6,906.2
3,P1334,White Lawn Belt,Accessory,All-season,119,3.7,440.3

=== Outfit 1 (work, summer, western, Gender: men) ===

,ProductID,ProductName,OutfitCategory,Season,Popularity,Feedback,Score
0,P1417,Beige Linen Formal Shirt,Top,Summer,194,4.7,911.8
1,P1443,Black Polyester Shalwar Kameez,Bottom,Winter,193,4.8,926.4
2,P1472,Brown Linen Formal Shoes,Shoes,Summer,196,4.1,803.6
3,P0485,Yellow Lawn Cap,Accessory,Summer,191,4.8,916.8

=== Outfit 2 (work, summer, western, Gender: men) ===

,ProductID,ProductName,OutfitCategory,Season,Popularity,Feedback,Score
0,P0408,Green Denim T-Shirt,Top,Winter,100,3.4,340.0
1,P1443,Black Polyester Shalwar Kameez,Bottom,Winter,193,4.8,926.4
2,P1472,Brown Linen Formal Shoes,Shoes,Summer,196,4.1,803.6
3,P0485,Yellow Lawn Cap,Accessory,Summer,191,4.8,916.8

=== Outfit 3 (work, summer, western, Gender: men) ===

,ProductID,ProductName,OutfitCategory,Season,Popularity,Feedback,Score
0,P1417,Beige Linen Formal Shirt,Top,Summer,194,4.7,911.8
1,P1443,Black Polyester Shalwar Kameez,Bottom,Winter,193,4.8,926.4
2,P1472,Brown Linen Formal Shoes,Shoes,Summer,196,4.1,803.6
3,P0485,Yellow Lawn Cap,Accessory,Summer,191,4.8,916.8

=== Outfit 1 (streetwear, all, western, Gender: unisex) ===

,ProductID,ProductName,OutfitCategory,Season,Popularity,Feedback,Score
0,P0630,Black Cotton T-Shirt,Top,Summer,77,4.7,361.9
1,P1362,Blue Polyester Saree,Bottom,Summer,190,4.9,931.0
2,P1426,Grey Leather Sandals,Shoes,All-season,133,4.4,585.2
3,P0065,Red Leather Earrings,Accessory,All-season,200,5.0,1000.0

=== Outfit 2 (streetwear, all, western, Gender: unisex) ===

,ProductID,ProductName,OutfitCategory,Season,Popularity,Feedback,Score
0,P0073,Green Silk Kurta,Top,Summer,183,5.0,915.0
1,P1362,Blue Polyester Saree,Bottom,Summer,190,4.9,931.0
2,P1395,Red Denim Formal Shoes,Shoes,Summer,116,3.0,348.0
3,P0065,Red Leather Earrings,Accessory,All-season,200,5.0,1000.0

=== Outfit 3 (streetwear, all, western, Gender: unisex) ===

,ProductID,ProductName,OutfitCategory,Season,Popularity,Feedback,Score
0,P1135,Grey Denim Abaya,Top,Winter,159,3.4,540.6
1,P1362,Blue Polyester Saree,Bottom,Summer,190,4.9,931.0
2,P0968,Beige Cotton Sandals,Shoes,All-season,199,4.7,935.3
3,P0065,Red Leather Earrings,Accessory,All-season,200,5.0,1000.0

In [106]:
import pandas as pd
import random

# ------------------- Load dataset -------------------
df = pd.read_csv("FashionHub_products_cleaned.csv")

# ------------------- Ensure columns exist -------------------
if "Popularity" not in df.columns:
    df["Popularity"] = [random.randint(50, 200) for _ in range(len(df))]
if "Feedback" not in df.columns:
    df["Feedback"] = [round(random.uniform(3.0, 5.0), 1) for _ in range(len(df))]

# ------------------- Map Outfit Categories -------------------
category_map = {
    "Top": ["Shirt", "Kurta", "Hoodie", "Abaya", "Jacket", "T-Shirt", "Kurti"],
    "Bottom": ["Trousers", "Jeans", "Shalwar", "Saree", "Skirt", "Pants"],
    "Shoes": ["Shoes", "Sneakers", "Sandals", "Heels", "Khussa", "Loafers"],
    "Accessory": ["Watch", "Ring", "Bag", "Cap", "Scarf", "Jewelry", "Belt"]
}

def map_outfit_category(name):
    for cat, kws in category_map.items():
        if any(kw.lower() in str(name).lower() for kw in kws):
            return cat
    return None

df["OutfitCategory"] = df["ProductName"].apply(map_outfit_category)
df = df.dropna(subset=["OutfitCategory"])

# ------------------- Dynamic Templates -------------------
outfit_templates = [
    {"Occasion": "party", "Season": "summer", "Style": "western", "Gender": "women"},
    {"Occasion": "casual", "Season": "winter", "Style": "eastern", "Gender": "men"},
    {"Occasion": "wedding", "Season": "all", "Style": "fusion", "Gender": "women"},
    {"Occasion": "work", "Season": "summer", "Style": "western", "Gender": "men"},
    {"Occasion": "streetwear", "Season": "all", "Style": "western", "Gender": "unisex"}
]

# ------------------- Outfit Generator -------------------
def generate_outfit_from_template(template, num_outfits=10, randomness=True):
    all_outfits = []
    tags = [template["Occasion"], template["Season"], template["Style"]]
    gender = template["Gender"]

    for _ in range(num_outfits):
        outfit = {}
        for cat in ["Top", "Bottom", "Shoes", "Accessory"]:
            mask = (df["OutfitCategory"] == cat) & (df["Corrected_Gender"].str.lower() == gender.lower())
            for tag in tags:
                mask &= df["AI_Tags_Cleaned"].str.contains(tag, case=False, na=False)

            candidates = df[mask]

            # Fallbacks if no exact match
            if candidates.empty:
                mask_partial = (df["OutfitCategory"] == cat) & (df["Corrected_Gender"].str.lower() == gender.lower())
                candidates = df[mask_partial]

            if not candidates.empty:
                candidates = candidates.copy()
                candidates["Score"] = candidates["Popularity"] * candidates["Feedback"]
                if randomness and random.random() < 0.3:
                    best_item = candidates.sample(1).iloc[0]  # 30% random
                else:
                    best_item = candidates.sort_values("Score", ascending=False).iloc[0]  # 70% best
                outfit[cat] = best_item

        all_outfits.append(outfit)
    return all_outfits

# ------------------- Display Outfits -------------------
for t in outfit_templates:
    outfits = generate_outfit_from_template(t, num_outfits=10)  # 10 outfits per template
    for i, outfit in enumerate(outfits, 1):
        print(f"\n=== Outfit {i} ({t['Occasion']}, {t['Season']}, {t['Style']}, Gender: {t['Gender']}) ===")
        rows = []
        for cat, item in outfit.items():
            rows.append({
                "ProductID": item["ProductID"],
                "ProductName": item["ProductName"],
                "OutfitCategory": cat,
                "Season": item["Season"],
                "Popularity": item["Popularity"],
                "Feedback": item["Feedback"],
                "Score": item["Score"]
            })
        display(pd.DataFrame(rows))

=== Outfit 1 (party, summer, western, Gender: women) ===

,ProductID,ProductName,OutfitCategory,Season,Popularity,Feedback,Score
0,P0516,Beige Cotton T-Shirt,Top,Summer,120,3.9,468.0
1,P1044,Beige Leather Saree,Bottom,Summer,78,4.5,351.0
2,P1133,Grey Denim Formal Shoes,Shoes,Summer,102,3.5,357.0
3,P1334,White Lawn Belt,Accessory,All-season,188,4.8,902.4

=== Outfit 2 (party, summer, western, Gender: women) ===

,ProductID,ProductName,OutfitCategory,Season,Popularity,Feedback,Score
0,P0516,Beige Cotton T-Shirt,Top,Summer,120,3.9,468.0
1,P1044,Beige Leather Saree,Bottom,Summer,78,4.5,351.0
2,P1133,Grey Denim Formal Shoes,Shoes,Summer,102,3.5,357.0
3,P1334,White Lawn Belt,Accessory,All-season,188,4.8,902.4

=== Outfit 3 (party, summer, western, Gender: women) ===

,ProductID,ProductName,OutfitCategory,Season,Popularity,Feedback,Score
0,P0516,Beige Cotton T-Shirt,Top,Summer,120,3.9,468.0
1,P1044,Beige Leather Saree,Bottom,Summer,78,4.5,351.0
2,P1133,Grey Denim Formal Shoes,Shoes,Summer,102,3.5,357.0
3,P1334,White Lawn Belt,Accessory,All-season,188,4.8,902.4

=== Outfit 4 (party, summer, western, Gender: women) ===

,ProductID,ProductName,OutfitCategory,Season,Popularity,Feedback,Score
0,P0516,Beige Cotton T-Shirt,Top,Summer,120,3.9,468.0
1,P1044,Beige Leather Saree,Bottom,Summer,78,4.5,351.0
2,P1133,Grey Denim Formal Shoes,Shoes,Summer,102,3.5,357.0
3,P1334,White Lawn Belt,Accessory,All-season,188,4.8,902.4

=== Outfit 5 (party, summer, western, Gender: women) ===

,ProductID,ProductName,OutfitCategory,Season,Popularity,Feedback,Score
0,P0516,Beige Cotton T-Shirt,Top,Summer,120,3.9,468.0
1,P1044,Beige Leather Saree,Bottom,Summer,78,4.5,351.0
2,P1133,Grey Denim Formal Shoes,Shoes,Summer,102,3.5,357.0
3,P1418,Beige Lawn Scarf,Accessory,Summer,130,4.4,572.0

=== Outfit 6 (party, summer, western, Gender: women) ===

,ProductID,ProductName,OutfitCategory,Season,Popularity,Feedback,Score
0,P0516,Beige Cotton T-Shirt,Top,Summer,120,3.9,468.0
1,P1044,Beige Leather Saree,Bottom,Summer,78,4.5,351.0
2,P1133,Grey Denim Formal Shoes,Shoes,Summer,102,3.5,357.0
3,P1334,White Lawn Belt,Accessory,All-season,188,4.8,902.4

=== Outfit 7 (party, summer, western, Gender: women) ===

,ProductID,ProductName,OutfitCategory,Season,Popularity,Feedback,Score
0,P0516,Beige Cotton T-Shirt,Top,Summer,120,3.9,468.0
1,P1044,Beige Leather Saree,Bottom,Summer,78,4.5,351.0
2,P1133,Grey Denim Formal Shoes,Shoes,Summer,102,3.5,357.0
3,P1334,White Lawn Belt,Accessory,All-season,188,4.8,902.4

=== Outfit 8 (party, summer, western, Gender: women) ===

,ProductID,ProductName,OutfitCategory,Season,Popularity,Feedback,Score
0,P0516,Beige Cotton T-Shirt,Top,Summer,120,3.9,468.0
1,P1344,Black Lawn Shalwar Kameez,Bottom,Summer,53,5.0,265.0
2,P1133,Grey Denim Formal Shoes,Shoes,Summer,102,3.5,357.0
3,P1334,White Lawn Belt,Accessory,All-season,188,4.8,902.4

=== Outfit 9 (party, summer, western, Gender: women) ===

,ProductID,ProductName,OutfitCategory,Season,Popularity,Feedback,Score
0,P0516,Beige Cotton T-Shirt,Top,Summer,120,3.9,468.0
1,P1044,Beige Leather Saree,Bottom,Summer,78,4.5,351.0
2,P1133,Grey Denim Formal Shoes,Shoes,Summer,102,3.5,357.0
3,P1334,White Lawn Belt,Accessory,All-season,188,4.8,902.4

=== Outfit 10 (party, summer, western, Gender: women) ===

,ProductID,ProductName,OutfitCategory,Season,Popularity,Feedback,Score
0,P0516,Beige Cotton T-Shirt,Top,Summer,120,3.9,468.0
1,P1044,Beige Leather Saree,Bottom,Summer,78,4.5,351.0
2,P1133,Grey Denim Formal Shoes,Shoes,Summer,102,3.5,357.0
3,P1334,White Lawn Belt,Accessory,All-season,188,4.8,902.4

=== Outfit 1 (casual, winter, eastern, Gender: men) ===

,ProductID,ProductName,OutfitCategory,Season,Popularity,Feedback,Score
0,P0685,Beige Leather Abaya,Top,All-season,193,4.9,945.7
1,P0949,Red Silk Saree,Bottom,Summer,130,4.9,637.0
2,P1283,White Wool Sneakers,Shoes,Winter,198,4.7,930.6
3,P1221,White Leather Handbag,Accessory,Summer,197,4.7,925.9

=== Outfit 2 (casual, winter, eastern, Gender: men) ===

,ProductID,ProductName,OutfitCategory,Season,Popularity,Feedback,Score
0,P0685,Beige Leather Abaya,Top,All-season,193,4.9,945.7
1,P1452,Yellow Denim Jeans,Bottom,All-season,70,4.2,294.0
2,P1283,White Wool Sneakers,Shoes,Winter,198,4.7,930.6
3,P1221,White Leather Handbag,Accessory,Summer,197,4.7,925.9

=== Outfit 3 (casual, winter, eastern, Gender: men) ===

,ProductID,ProductName,OutfitCategory,Season,Popularity,Feedback,Score
0,P1136,Green Cotton Abaya,Top,Summer,102,4.6,469.2
1,P0763,Blue Linen Shalwar Kameez,Bottom,All-season,83,3.9,323.7
2,P1112,Pink Leather Sandals,Shoes,All-season,190,3.7,703.0
3,P1221,White Leather Handbag,Accessory,Summer,197,4.7,925.9

=== Outfit 4 (casual, winter, eastern, Gender: men) ===

,ProductID,ProductName,OutfitCategory,Season,Popularity,Feedback,Score
0,P0685,Beige Leather Abaya,Top,All-season,193,4.9,945.7
1,P0462,Blue Cotton Saree,Bottom,Summer,194,4.8,931.2
2,P1283,White Wool Sneakers,Shoes,Winter,198,4.7,930.6
3,P1221,White Leather Handbag,Accessory,Summer,197,4.7,925.9

=== Outfit 5 (casual, winter, eastern, Gender: men) ===

,ProductID,ProductName,OutfitCategory,Season,Popularity,Feedback,Score
0,P0685,Beige Leather Abaya,Top,All-season,193,4.9,945.7
1,P0462,Blue Cotton Saree,Bottom,Summer,194,4.8,931.2
2,P1283,White Wool Sneakers,Shoes,Winter,198,4.7,930.6
3,P0222,Grey Polyester Ring,Accessory,Winter,117,3.5,409.5

=== Outfit 6 (casual, winter, eastern, Gender: men) ===

,ProductID,ProductName,OutfitCategory,Season,Popularity,Feedback,Score
0,P0685,Beige Leather Abaya,Top,All-season,193,4.9,945.7
1,P0942,Blue Leather Saree,Bottom,Winter,68,3.9,265.2
2,P1283,White Wool Sneakers,Shoes,Winter,198,4.7,930.6
3,P1221,White Leather Handbag,Accessory,Summer,197,4.7,925.9

=== Outfit 7 (casual, winter, eastern, Gender: men) ===

,ProductID,ProductName,OutfitCategory,Season,Popularity,Feedback,Score
0,P0685,Beige Leather Abaya,Top,All-season,193,4.9,945.7
1,P0462,Blue Cotton Saree,Bottom,Summer,194,4.8,931.2
2,P1283,White Wool Sneakers,Shoes,Winter,198,4.7,930.6
3,P1281,Brown Linen Belt,Accessory,Winter,102,4.2,428.4

=== Outfit 8 (casual, winter, eastern, Gender: men) ===

,ProductID,ProductName,OutfitCategory,Season,Popularity,Feedback,Score
0,P0203,Black Lawn Kurta,Top,Winter,151,4.8,724.8
1,P0462,Blue Cotton Saree,Bottom,Summer,194,4.8,931.2
2,P1283,White Wool Sneakers,Shoes,Winter,198,4.7,930.6
3,P0026,Red Cotton Ring,Accessory,Winter,199,3.2,636.8

=== Outfit 9 (casual, winter, eastern, Gender: men) ===

,ProductID,ProductName,OutfitCategory,Season,Popularity,Feedback,Score
0,P0687,Grey Leather Formal Shirt,Top,All-season,158,3.5,553.0
1,P0521,Grey Silk Shalwar Kameez,Bottom,Winter,197,3.3,650.1
2,P1283,White Wool Sneakers,Shoes,Winter,198,4.7,930.6
3,P1124,Grey Lawn Belt,Accessory,All-season,186,4.0,744.0

=== Outfit 10 (casual, winter, eastern, Gender: men) ===

,ProductID,ProductName,OutfitCategory,Season,Popularity,Feedback,Score
0,P0787,Grey Silk Abaya,Top,All-season,187,3.6,673.2
1,P0462,Blue Cotton Saree,Bottom,Summer,194,4.8,931.2
2,P1112,Pink Leather Sandals,Shoes,All-season,190,3.7,703.0
3,P1221,White Leather Handbag,Accessory,Summer,197,4.7,925.9

=== Outfit 1 (wedding, all, fusion, Gender: women) ===

,ProductID,ProductName,OutfitCategory,Season,Popularity,Feedback,Score
0,P0588,Beige Silk Formal Shirt,Top,Winter,77,4.9,377.3
1,P0453,Blue Polyester Jeans,Bottom,All-season,148,4.5,666.0
2,P0286,Brown Linen Sandals,Shoes,Winter,196,4.2,823.2
3,P0740,Beige Polyester Belt,Accessory,All-season,109,3.7,403.3

=== Outfit 2 (wedding, all, fusion, Gender: women) ===

,ProductID,ProductName,OutfitCategory,Season,Popularity,Feedback,Score
0,P0230,Beige Denim T-Shirt,Top,Winter,180,4.8,864.0
1,P1532,White Denim Saree,Bottom,Summer,196,4.6,901.6
2,P0386,Brown Denim Sneakers,Shoes,All-season,147,3.1,455.7
3,P0024,Green Leather Ring,Accessory,Summer,117,3.2,374.4

=== Outfit 3 (wedding, all, fusion, Gender: women) ===

,ProductID,ProductName,OutfitCategory,Season,Popularity,Feedback,Score
0,P0230,Beige Denim T-Shirt,Top,Winter,180,4.8,864.0
1,P1532,White Denim Saree,Bottom,Summer,196,4.6,901.6
2,P0932,Pink Polyester Formal Shoes,Shoes,All-season,71,3.6,255.6
3,P1334,White Lawn Belt,Accessory,All-season,188,4.8,902.4

=== Outfit 4 (wedding, all, fusion, Gender: women) ===

,ProductID,ProductName,OutfitCategory,Season,Popularity,Feedback,Score
0,P0243,Yellow Leather T-Shirt,Top,Winter,153,3.8,581.4
1,P1532,White Denim Saree,Bottom,Summer,196,4.6,901.6
2,P0286,Brown Linen Sandals,Shoes,Winter,196,4.2,823.2
3,P1334,White Lawn Belt,Accessory,All-season,188,4.8,902.4

=== Outfit 5 (wedding, all, fusion, Gender: women) ===

,ProductID,ProductName,OutfitCategory,Season,Popularity,Feedback,Score
0,P0230,Beige Denim T-Shirt,Top,Winter,180,4.8,864.0
1,P1532,White Denim Saree,Bottom,Summer,196,4.6,901.6
2,P1267,Blue Leather Formal Shoes,Shoes,Winter,120,3.2,384.0
3,P1334,White Lawn Belt,Accessory,All-season,188,4.8,902.4

=== Outfit 6 (wedding, all, fusion, Gender: women) ===

,ProductID,ProductName,OutfitCategory,Season,Popularity,Feedback,Score
0,P0230,Beige Denim T-Shirt,Top,Winter,180,4.8,864.0
1,P1532,White Denim Saree,Bottom,Summer,196,4.6,901.6
2,P1133,Grey Denim Formal Shoes,Shoes,Summer,102,3.5,357.0
3,P1334,White Lawn Belt,Accessory,All-season,188,4.8,902.4

=== Outfit 7 (wedding, all, fusion, Gender: women) ===

,ProductID,ProductName,OutfitCategory,Season,Popularity,Feedback,Score
0,P0230,Beige Denim T-Shirt,Top,Winter,180,4.8,864.0
1,P0626,Pink Lawn Shalwar Kameez,Bottom,Summer,62,4.5,279.0
2,P0286,Brown Linen Sandals,Shoes,Winter,196,4.2,823.2
3,P0033,Beige Cotton Scarf,Accessory,Winter,131,3.9,510.9

=== Outfit 8 (wedding, all, fusion, Gender: women) ===

,ProductID,ProductName,OutfitCategory,Season,Popularity,Feedback,Score
0,P0212,Blue Silk Kurta,Top,Winter,176,4.4,774.4
1,P0115,Blue Cotton Shalwar Kameez,Bottom,Summer,95,4.6,437.0
2,P1324,Beige Leather Heels,Shoes,Summer,50,3.9,195.0
3,P1334,White Lawn Belt,Accessory,All-season,188,4.8,902.4

=== Outfit 9 (wedding, all, fusion, Gender: women) ===

,ProductID,ProductName,OutfitCategory,Season,Popularity,Feedback,Score
0,P0230,Beige Denim T-Shirt,Top,Winter,180,4.8,864.0
1,P1532,White Denim Saree,Bottom,Summer,196,4.6,901.6
2,P0286,Brown Linen Sandals,Shoes,Winter,196,4.2,823.2
3,P1340,Black Cotton Belt,Accessory,Summer,191,3.4,649.4

=== Outfit 10 (wedding, all, fusion, Gender: women) ===

,ProductID,ProductName,OutfitCategory,Season,Popularity,Feedback,Score
0,P0230,Beige Denim T-Shirt,Top,Winter,180,4.8,864.0
1,P0274,White Cotton Shalwar Kameez,Bottom,All-season,88,3.0,264.0
2,P0286,Brown Linen Sandals,Shoes,Winter,196,4.2,823.2
3,P1334,White Lawn Belt,Accessory,All-season,188,4.8,902.4

=== Outfit 1 (work, summer, western, Gender: men) ===

,ProductID,ProductName,OutfitCategory,Season,Popularity,Feedback,Score
0,P0685,Beige Leather Abaya,Top,All-season,193,4.9,945.7
1,P0462,Blue Cotton Saree,Bottom,Summer,194,4.8,931.2
2,P0227,Red Linen Formal Shoes,Shoes,Winter,89,4.0,356.0
3,P0995,Red Silk Ring,Accessory,Summer,145,5.0,725.0

=== Outfit 2 (work, summer, western, Gender: men) ===

,ProductID,ProductName,OutfitCategory,Season,Popularity,Feedback,Score
0,P0685,Beige Leather Abaya,Top,All-season,193,4.9,945.7
1,P1315,Grey Leather Jeans,Bottom,Winter,189,4.7,888.3
2,P1112,Pink Leather Sandals,Shoes,All-season,190,3.7,703.0
3,P1079,Pink Leather Handbag,Accessory,Winter,100,3.6,360.0

=== Outfit 3 (work, summer, western, Gender: men) ===

,ProductID,ProductName,OutfitCategory,Season,Popularity,Feedback,Score
0,P0685,Beige Leather Abaya,Top,All-season,193,4.9,945.7
1,P0462,Blue Cotton Saree,Bottom,Summer,194,4.8,931.2
2,P0227,Red Linen Formal Shoes,Shoes,Winter,89,4.0,356.0
3,P1221,White Leather Handbag,Accessory,Summer,197,4.7,925.9

=== Outfit 4 (work, summer, western, Gender: men) ===

,ProductID,ProductName,OutfitCategory,Season,Popularity,Feedback,Score
0,P0787,Grey Silk Abaya,Top,All-season,187,3.6,673.2
1,P1179,Yellow Leather Jeans,Bottom,Winter,148,3.4,503.2
2,P1283,White Wool Sneakers,Shoes,Winter,198,4.7,930.6
3,P1221,White Leather Handbag,Accessory,Summer,197,4.7,925.9

=== Outfit 5 (work, summer, western, Gender: men) ===

,ProductID,ProductName,OutfitCategory,Season,Popularity,Feedback,Score
0,P0685,Beige Leather Abaya,Top,All-season,193,4.9,945.7
1,P0462,Blue Cotton Saree,Bottom,Summer,194,4.8,931.2
2,P1283,White Wool Sneakers,Shoes,Winter,198,4.7,930.6
3,P1221,White Leather Handbag,Accessory,Summer,197,4.7,925.9

=== Outfit 6 (work, summer, western, Gender: men) ===

,ProductID,ProductName,OutfitCategory,Season,Popularity,Feedback,Score
0,P0947,Grey Lawn Abaya,Top,All-season,88,4.3,378.4
1,P0462,Blue Cotton Saree,Bottom,Summer,194,4.8,931.2
2,P0811,White Silk Sneakers,Shoes,Winter,98,4.9,480.2
3,P0846,Grey Cotton Scarf,Accessory,All-season,78,3.3,257.4

=== Outfit 7 (work, summer, western, Gender: men) ===

,ProductID,ProductName,OutfitCategory,Season,Popularity,Feedback,Score
0,P0007,Green Lawn Hoodie,Top,Summer,96,4.0,384.0
1,P0462,Blue Cotton Saree,Bottom,Summer,194,4.8,931.2
2,P1356,Grey Linen Formal Shoes,Shoes,Winter,76,3.3,250.8
3,P0776,Grey Silk Handbag,Accessory,Winter,132,4.8,633.6

=== Outfit 8 (work, summer, western, Gender: men) ===

,ProductID,ProductName,OutfitCategory,Season,Popularity,Feedback,Score
0,P0685,Beige Leather Abaya,Top,All-season,193,4.9,945.7
1,P1443,Black Polyester Shalwar Kameez,Bottom,Winter,133,4.6,611.8
2,P1283,White Wool Sneakers,Shoes,Winter,198,4.7,930.6
3,P1221,White Leather Handbag,Accessory,Summer,197,4.7,925.9

=== Outfit 9 (work, summer, western, Gender: men) ===

,ProductID,ProductName,OutfitCategory,Season,Popularity,Feedback,Score
0,P0685,Beige Leather Abaya,Top,All-season,193,4.9,945.7
1,P0462,Blue Cotton Saree,Bottom,Summer,194,4.8,931.2
2,P1283,White Wool Sneakers,Shoes,Winter,198,4.7,930.6
3,P1221,White Leather Handbag,Accessory,Summer,197,4.7,925.9

=== Outfit 10 (work, summer, western, Gender: men) ===

,ProductID,ProductName,OutfitCategory,Season,Popularity,Feedback,Score
0,P0685,Beige Leather Abaya,Top,All-season,193,4.9,945.7
1,P0462,Blue Cotton Saree,Bottom,Summer,194,4.8,931.2
2,P1518,Green Wool Heels,Shoes,Summer,143,3.9,557.7
3,P0133,Blue Cotton Cap,Accessory,Winter,72,4.0,288.0

=== Outfit 1 (streetwear, all, western, Gender: unisex) ===

,ProductID,ProductName,OutfitCategory,Season,Popularity,Feedback,Score
0,P0593,Yellow Lawn Hoodie,Top,All-season,135,3.0,405.0
1,P0653,Beige Cotton Jeans,Bottom,All-season,188,4.6,864.8
2,P0208,Black Denim Heels,Shoes,Summer,192,4.1,787.2
3,P0118,White Lawn Earrings,Accessory,Winter,129,4.7,606.3

=== Outfit 2 (streetwear, all, western, Gender: unisex) ===

,ProductID,ProductName,OutfitCategory,Season,Popularity,Feedback,Score
0,P0088,Pink Wool Formal Shirt,Top,All-season,197,4.9,965.3
1,P0653,Beige Cotton Jeans,Bottom,All-season,188,4.6,864.8
2,P1398,Black Wool Formal Shoes,Shoes,Summer,150,3.1,465.0
3,P0813,Yellow Wool Handbag,Accessory,All-season,196,5.0,980.0

=== Outfit 3 (streetwear, all, western, Gender: unisex) ===

,ProductID,ProductName,OutfitCategory,Season,Popularity,Feedback,Score
0,P0076,Red Lawn Abaya,Top,Summer,99,4.3,425.7
1,P0653,Beige Cotton Jeans,Bottom,All-season,188,4.6,864.8
2,P0314,Yellow Denim Sneakers,Shoes,All-season,195,4.8,936.0
3,P0813,Yellow Wool Handbag,Accessory,All-season,196,5.0,980.0

=== Outfit 4 (streetwear, all, western, Gender: unisex) ===

,ProductID,ProductName,OutfitCategory,Season,Popularity,Feedback,Score
0,P0088,Pink Wool Formal Shirt,Top,All-season,197,4.9,965.3
1,P0653,Beige Cotton Jeans,Bottom,All-season,188,4.6,864.8
2,P1242,Red Leather Formal Shoes,Shoes,Summer,163,3.9,635.7
3,P0813,Yellow Wool Handbag,Accessory,All-season,196,5.0,980.0

=== Outfit 5 (streetwear, all, western, Gender: unisex) ===

,ProductID,ProductName,OutfitCategory,Season,Popularity,Feedback,Score
0,P0088,Pink Wool Formal Shirt,Top,All-season,197,4.9,965.3
1,P0767,Yellow Polyester Shalwar Kameez,Bottom,Summer,64,3.5,224.0
2,P0314,Yellow Denim Sneakers,Shoes,All-season,195,4.8,936.0
3,P0813,Yellow Wool Handbag,Accessory,All-season,196,5.0,980.0

=== Outfit 6 (streetwear, all, western, Gender: unisex) ===

,ProductID,ProductName,OutfitCategory,Season,Popularity,Feedback,Score
0,P0088,Pink Wool Formal Shirt,Top,All-season,197,4.9,965.3
1,P0569,Blue Leather Shalwar Kameez,Bottom,All-season,82,4.5,369.0
2,P0314,Yellow Denim Sneakers,Shoes,All-season,195,4.8,936.0
3,P0482,Grey Leather Ring,Accessory,Summer,155,3.1,480.5

=== Outfit 7 (streetwear, all, western, Gender: unisex) ===

,ProductID,ProductName,OutfitCategory,Season,Popularity,Feedback,Score
0,P0088,Pink Wool Formal Shirt,Top,All-season,197,4.9,965.3
1,P0948,Black Linen Shalwar Kameez,Bottom,Summer,131,3.8,497.8
2,P0314,Yellow Denim Sneakers,Shoes,All-season,195,4.8,936.0
3,P1234,White Leather Handbag,Accessory,Summer,119,3.6,428.4

=== Outfit 8 (streetwear, all, western, Gender: unisex) ===

,ProductID,ProductName,OutfitCategory,Season,Popularity,Feedback,Score
0,P0088,Pink Wool Formal Shirt,Top,All-season,197,4.9,965.3
1,P0653,Beige Cotton Jeans,Bottom,All-season,188,4.6,864.8
2,P1464,Grey Silk Sneakers,Shoes,Winter,82,3.8,311.6
3,P0813,Yellow Wool Handbag,Accessory,All-season,196,5.0,980.0

=== Outfit 9 (streetwear, all, western, Gender: unisex) ===

,ProductID,ProductName,OutfitCategory,Season,Popularity,Feedback,Score
0,P0088,Pink Wool Formal Shirt,Top,All-season,197,4.9,965.3
1,P0087,Yellow Denim Saree,Bottom,Winter,83,4.0,332.0
2,P0314,Yellow Denim Sneakers,Shoes,All-season,195,4.8,936.0
3,P0813,Yellow Wool Handbag,Accessory,All-season,196,5.0,980.0

=== Outfit 10 (streetwear, all, western, Gender: unisex) ===

,ProductID,ProductName,OutfitCategory,Season,Popularity,Feedback,Score
0,P0088,Pink Wool Formal Shirt,Top,All-season,197,4.9,965.3
1,P0653,Beige Cotton Jeans,Bottom,All-season,188,4.6,864.8
2,P0314,Yellow Denim Sneakers,Shoes,All-season,195,4.8,936.0
3,P0813,Yellow Wool Handbag,Accessory,All-season,196,5.0,980.0

In [220]:
import pandas as pd
import random

# ------------------- Load dataset -------------------
df = pd.read_csv("FashionHub_products_cleaned.csv")

# ------------------- Ensure columns exist -------------------
if "Popularity" not in df.columns:
    df["Popularity"] = [random.randint(50, 200) for _ in range(len(df))]
if "Feedback" not in df.columns:
    df["Feedback"] = [round(random.uniform(3.0, 5.0), 1) for _ in range(len(df))]

# ------------------- Map Outfit Categories -------------------
category_map = {
    "Top": ["Shirt", "Kurta", "Hoodie", "Abaya", "Jacket", "T-Shirt", "Kurti"],
    "Bottom": ["Trousers", "Jeans", "Shalwar", "Saree", "Skirt", "Pants"],
    "Shoes": ["Shoes", "Sneakers", "Sandals", "Heels", "Khussa", "Loafers"],
    "Accessory": ["Watch", "Ring", "Bag", "Cap", "Scarf", "Jewelry", "Belt"]
}

def map_outfit_category(name):
    for cat, kws in category_map.items():
        if any(kw.lower() in str(name).lower() for kw in kws):
            return cat
    return None

df["OutfitCategory"] = df["ProductName"].apply(map_outfit_category)
df = df.dropna(subset=["OutfitCategory"])

# ------------------- Outfit Generator -------------------
def generate_outfit_from_template(template, num_outfits=10, randomness=True):
    all_outfits = []
    tags = [template["Occasion"], template["Season"], template["Style"]]
    gender = template["Gender"]

    for outfit_num in range(1, num_outfits + 1):
        outfit = {}
        for cat in ["Top", "Bottom", "Shoes", "Accessory"]:
            mask = (df["OutfitCategory"] == cat) & (df["Corrected_Gender"].str.lower() == gender.lower())
            
            # filter by tags
            for tag in tags:
                mask &= df["AI_Tags_Cleaned"].str.contains(tag, case=False, na=False)

            candidates = df[mask]

            # fallback if no exact match
            if candidates.empty:
                mask_partial = (df["OutfitCategory"] == cat) & (df["Corrected_Gender"].str.lower() == gender.lower())
                candidates = df[mask_partial]

            if not candidates.empty:
                candidates = candidates.copy()
                candidates["Score"] = (candidates["Popularity"] * 0.4 +
                                       candidates["Feedback"] * 0.3 +
                                       random.random() * 0.3)  # improved scoring

                if randomness and random.random() < 0.3:
                    best_item = candidates.sample(1).iloc[0]  # 30% random pick
                else:
                    best_item = candidates.sort_values("Score", ascending=False).iloc[0]  # 70% best
                outfit[cat] = best_item

        all_outfits.append(outfit)
    return all_outfits

# ------------------- Templates -------------------
outfit_templates = [
    {"Occasion": "party", "Season": "summer", "Style": "western", "Gender": "women"},
    {"Occasion": "casual", "Season": "winter", "Style": "eastern", "Gender": "men"},
    {"Occasion": "wedding", "Season": "all", "Style": "fusion", "Gender": "women"},
    {"Occasion": "work", "Season": "summer", "Style": "western", "Gender": "men"},
    {"Occasion": "streetwear", "Season": "all", "Style": "western", "Gender": "unisex"}
]

# ------------------- Run Generator -------------------
all_outfits_rows = []

for t in outfit_templates:
    outfits = generate_outfit_from_template(t, num_outfits=10)  # 10 outfits per template
    for i, outfit in enumerate(outfits, 1):
        for cat, item in outfit.items():
            all_outfits_rows.append({
                "Template": f"{t['Occasion']}_{t['Season']}_{t['Style']}_{t['Gender']}",
                "OutfitNumber": i,
                "ProductID": item["ProductID"],
                "ProductName": item["ProductName"],
                "OutfitCategory": cat,
                "Season": item["Season"],
                "Popularity": item["Popularity"],
                "Feedback": item["Feedback"],
                "Score": item["Score"]
            })

# Create DataFrame of all generated outfits
all_outfits_df = pd.DataFrame(all_outfits_rows)

# Export to CSV
all_outfits_df.to_csv("FashionHub_Generated_Outfits.csv", index=False)
print("✅ All generated outfits exported to 'FashionHub_Generated_Outfits.csv'")

✅ All generated outfits exported to 'FashionHub_Generated_Outfits.csv'

In [222]:
import pandas as pd

outfits = pd.read_csv("FashionHub_Generated_Outfits.csv")
print(outfits.shape)   # check rows and columns
outfits.head(20)       # preview first 20 rows

(200, 9)

,Template,OutfitNumber,ProductID,ProductName,OutfitCategory,Season,Popularity,Feedback,Score
0,party_summer_western_women,1,P0366,Green Cotton Kurta,Top,Summer,192,3.8,78.154314
1,party_summer_western_women,1,P1344,Black Lawn Shalwar Kameez,Bottom,Summer,189,4.0,76.962965
2,party_summer_western_women,1,P1133,Grey Denim Formal Shoes,Shoes,Summer,184,3.2,74.602772
3,party_summer_western_women,1,P1334,White Lawn Belt,Accessory,All-season,54,3.2,22.840682
4,party_summer_western_women,2,P0366,Green Cotton Kurta,Top,Summer,192,3.8,78.162919
5,party_summer_western_women,2,P1044,Beige Leather Saree,Bottom,Summer,149,4.2,60.919254
6,party_summer_western_women,2,P1133,Grey Denim Formal Shoes,Shoes,Summer,184,3.2,74.788499
7,party_summer_western_women,2,P1418,Beige Lawn Scarf,Accessory,Summer,149,5.0,61.289677
8,party_summer_western_women,3,P0516,Beige Cotton T-Shirt,Top,Summer,127,3.9,52.213209
9,party_summer_western_women,3,P1344,Black Lawn Shalwar Kameez,Bottom,Summer,189,4.0,76.884279
10,party_summer_western_women,3,P1133,Grey Denim Formal Shoes,Shoes,Summer,184,3.2,74.789813
11,party_summer_western_women,3,P1418,Beige Lawn Scarf,Accessory,Summer,149,5.0,61.208014
12,party_summer_western_women,4,P0366,Green Cotton Kurta,Top,Summer,192,3.8,78.104228
13,party_summer_western_women,4,P1344,Black Lawn Shalwar Kameez,Bottom,Summer,189,4.0,76.880815
14,party_summer_western_women,4,P1133,Grey Denim Formal Shoes,Shoes,Summer,184,3.2,74.590308
15,party_summer_western_women,4,P1418,Beige Lawn Scarf,Accessory,Summer,149,5.0,61.313259
16,party_summer_western_women,5,P0366,Green Cotton Kurta,Top,Summer,192,3.8,78.165822
17,party_summer_western_women,5,P1344,Black Lawn Shalwar Kameez,Bottom,Summer,189,4.0,76.834102
18,party_summer_western_women,5,P1133,Grey Denim Formal Shoes,Shoes,Summer,184,3.2,74.731410
19,party_summer_western_women,5,P1418,Beige Lawn Scarf,Accessory,Summer,149,5.0,61.104969

In [224]:
from sklearn.preprocessing import MinMaxScaler

def calculate_score(df, season=None, trend_tags=[]):
    """
    Calculate a weighted score for products based on popularity, feedback, trends, and season.
    """

    # Normalize Popularity and Feedback
    scaler = MinMaxScaler()
    df[['Popularity_norm', 'Feedback_norm']] = scaler.fit_transform(df[['Popularity', 'Feedback']])

    # Trend Boost (1 if any AI tag matches trend_tags, else 0)
    df['TrendBoost'] = df['AI_Tags_Cleaned'].apply(
        lambda tags: 1 if any(tag in tags for tag in trend_tags) else 0
    )

    # Seasonal Boost (1 if product season matches outfit season, else 0)
    df['SeasonalBoost'] = df['Season'].apply(
        lambda s: 1 if season and s.lower() == season.lower() else 0
    )

    # Weighted scoring
    w1, w2, w3, w4 = 0.3, 0.4, 0.2, 0.1
    df['Score'] = (
        (w1 * df['Popularity_norm']) +
        (w2 * df['Feedback_norm']) +
        (w3 * df['TrendBoost']) +
        (w4 * df['SeasonalBoost'])
    )

    return df

In [232]:
print(products.columns)

Index(['ProductID', 'ProductName', 'Category', 'Occasion', 'Season',
       'Popularity', 'Feedback'],
      dtype='object')

In [234]:
from sklearn.preprocessing import MinMaxScaler
import pandas as pd

def calculate_score(df, season=None, trend_tags=None):
    df = df.copy()
    
    # Normalize Popularity and Feedback
    scaler = MinMaxScaler()
    df[['Popularity_norm', 'Feedback_norm']] = scaler.fit_transform(df[['Popularity', 'Feedback']])
    
    # Trend Boost (check Occasion column instead of AI_Tags)
    if trend_tags:
        df['TrendBoost'] = df['Occasion'].apply(
            lambda occ: 1 if any(tag.lower() in str(occ).lower() for tag in trend_tags) else 0
        )
    else:
        df['TrendBoost'] = 0
    
    # Seasonal Boost
    if season:
        df['SeasonalBoost'] = df['Season'].apply(
            lambda s: 1 if s and s.lower() == season.lower() else 0
        )
    else:
        df['SeasonalBoost'] = 0
    
    # Final Score
    df['Score'] = (
        0.5 * df['Popularity_norm'] +
        0.3 * df['Feedback_norm'] +
        0.1 * df['TrendBoost'] +
        0.1 * df['SeasonalBoost']
    ) * 100
    
    return df

In [236]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler

# ✅ Example: Load your products dataset (update filename if needed)
# products = pd.read_csv("FashionHub_products_cleaned.csv")

# For now assuming "products" is already in memory
print("Columns in products:", products.columns)

def calculate_score(df, season=None, trend_tags=None):
    df = df.copy()
    
    # Normalize Popularity and Feedback
    scaler = MinMaxScaler()
    df[['Popularity_norm', 'Feedback_norm']] = scaler.fit_transform(df[['Popularity', 'Feedback']])
    
    # Trend Boost → based on Occasion column
    if trend_tags:
        df['TrendBoost'] = df['Occasion'].apply(
            lambda occ: 1 if any(tag.lower() in str(occ).lower() for tag in trend_tags) else 0
        )
    else:
        df['TrendBoost'] = 0
    
    # Seasonal Boost → match Season column
    if season:
        df['SeasonalBoost'] = df['Season'].apply(
            lambda s: 1 if s and s.lower() == season.lower() else 0
        )
    else:
        df['SeasonalBoost'] = 0
    
    # Final Weighted Score
    df['Score'] = (
        0.5 * df['Popularity_norm'] +
        0.3 * df['Feedback_norm'] +
        0.1 * df['TrendBoost'] +
        0.1 * df['SeasonalBoost']
    ) * 100
    
    return df

# ✅ Apply scoring
products_scored = calculate_score(products, season="summer", trend_tags=["party", "wedding"])

# ✅ Show top 10 products
print("\nTop 10 products with scores:\n")
print(products_scored[['ProductID', 'ProductName', 'Occasion', 'Season', 'Popularity', 'Feedback', 'Score']].head(10))

Columns in products: Index(['ProductID', 'ProductName', 'Category', 'Occasion', 'Season',
       'Popularity', 'Feedback'],
      dtype='object')

Top 10 products with scores:

  ProductID            ProductName     Occasion  Season  Popularity  Feedback  \
0      P001       Blue Denim Jeans       Casual     All         120       4.5
1      P002     White Cotton Shirt       Casual  Summer          90       4.2
2      P003  Black Formal Trousers       Formal     All         150       4.7
3      P004            Grey Blazer       Formal  Winter         200       4.9
4      P005         Red Lawn Kurti       Casual  Summer          80       4.1
5      P006        Pink Lawn Abaya  Traditional  Summer          95       4.4
6      P007       Beige Wool Shawl  Traditional  Winter         110       4.6
7      P008    Green Cotton Hoodie       Casual  Winter         105       4.3
8      P009   Leather Formal Shoes       Formal     All         140       4.8
9      P010         White Sneakers       Casual     All         170       4.5

       Score
0  31.666667
1  17.916667
2  51.666667
3  80.000000
4  10.000000
5  27.500000
6  31.250000
7  17.916667
8  51.250000
9  52.500000

In [240]:
import random

def generate_outfits(products, template, season=None, trend_tags=None, num_outfits=5):
    # Apply scoring
    products_scored = calculate_score(products, season=season, trend_tags=trend_tags)

    outfits = []
    categories = ["Top", "Bottom", "Shoes", "Accessory"]  # expected categories

    for outfit_num in range(1, num_outfits + 1):
        outfit_items = []

        for cat in categories:
            subset = products_scored[products_scored['Category'] == cat]

            if subset.empty:
                # Fallback: if no product in this category, skip it
                print(f"⚠️ No products found for category '{cat}', skipping...")
                continue

            # Pick 1 from top 5 scored items
            item = subset.sort_values('Score', ascending=False).head(5).sample(1)
            row = item.iloc[0].to_dict()
            row['Template'] = template
            row['OutfitNumber'] = outfit_num
            outfit_items.append(row)

        outfits.extend(outfit_items)

    return pd.DataFrame(outfits)

# ✅ Example: generate outfits for women, party, summer, western
outfits_df = generate_outfits(
    products,
    template="party_summer_western_women",
    season="summer",
    trend_tags=["party"],
    num_outfits=5
)

# ✅ Show and save
print(outfits_df[['Template','OutfitNumber','ProductID','ProductName','Category','Occasion','Season','Score']])
outfits_df.to_csv("FashionHub_Scored_Outfits.csv", index=False)
print("\n✅ Outfits exported to 'FashionHub_Scored_Outfits.csv'")

⚠️ No products found for category 'Accessory', skipping...
⚠️ No products found for category 'Accessory', skipping...
⚠️ No products found for category 'Accessory', skipping...
⚠️ No products found for category 'Accessory', skipping...
⚠️ No products found for category 'Accessory', skipping...
                      Template  OutfitNumber ProductID            ProductName  \
0   party_summer_western_women             1      P005         Red Lawn Kurti
1   party_summer_western_women             1      P003  Black Formal Trousers
2   party_summer_western_women             1      P010         White Sneakers
3   party_summer_western_women             2      P005         Red Lawn Kurti
4   party_summer_western_women             2      P003  Black Formal Trousers
5   party_summer_western_women             2      P009   Leather Formal Shoes
6   party_summer_western_women             3      P005         Red Lawn Kurti
7   party_summer_western_women             3      P003  Black Formal Trousers
8   party_summer_western_women             3      P010         White Sneakers
9   party_summer_western_women             4      P005         Red Lawn Kurti
10  party_summer_western_women             4      P001       Blue Denim Jeans
11  party_summer_western_women             4      P009   Leather Formal Shoes
12  party_summer_western_women             5      P002     White Cotton Shirt
13  party_summer_western_women             5      P001       Blue Denim Jeans
14  party_summer_western_women             5      P009   Leather Formal Shoes

   Category Occasion  Season      Score
0       Top   Casual  Summer  10.000000
1    Bottom   Formal     All  51.666667
2     Shoes   Casual     All  52.500000
3       Top   Casual  Summer  10.000000
4    Bottom   Formal     All  51.666667
5     Shoes   Formal     All  51.250000
6       Top   Casual  Summer  10.000000
7    Bottom   Formal     All  51.666667
8     Shoes   Casual     All  52.500000
9       Top   Casual  Summer  10.000000
10   Bottom   Casual     All  31.666667
11    Shoes   Formal     All  51.250000
12      Top   Casual  Summer  17.916667
13   Bottom   Casual     All  31.666667
14    Shoes   Formal     All  51.250000

✅ Outfits exported to 'FashionHub_Scored_Outfits.csv'

In [256]:
def safe_pick(df, category, top_n=5):
    """
    Safely pick one product from a category. 
    Returns empty DataFrame if none found.
    """
    subset = df[df['Category'] == category]
    if subset.empty:
        print(f"⚠️ No products found for category '{category}', skipping...")
        return pd.DataFrame()
    return subset.sort_values('Score', ascending=False).head(top_n).sample(1)


def generate_outfits(products, template, season=None, trend_tags=None, num_outfits=5):
    outfits = []
    products_scored = calculate_score(products.copy(), season=season, trend_tags=trend_tags)

    for outfit_num in range(1, num_outfits+1):
        # Core picks with safe fallback
        top = safe_pick(products_scored, "Top")
        bottom = safe_pick(products_scored, "Bottom")
        shoes = safe_pick(products_scored, "Shoes")
        accessory = safe_pick(products_scored, "Accessory")

        # Fallback if accessory missing → add extra Top
        if accessory.empty:
            accessory = safe_pick(products_scored, "Top")

        # Combine items
        for item in [top, bottom, shoes, accessory]:
            if not item.empty:
                outfits.append({
                    "Template": template,
                    "OutfitNumber": outfit_num,
                    **item.iloc[0].to_dict()
                })

    return pd.DataFrame(outfits)

In [258]:
def preview_outfit(outfits_df, outfit_number=1):
    """
    Nicely print a single outfit from the generated outfits dataframe.
    """
    outfit = outfits_df[outfits_df['OutfitNumber'] == outfit_number]
    if outfit.empty:
        print(f"⚠️ Outfit {outfit_number} not found.")
        return

    template = outfit['Template'].iloc[0]
    print(f"\n=== Outfit {outfit_number} ({template}) ===\n")
    for _, row in outfit.iterrows():
        print(f"- {row['Category']}: {row['ProductName']} (Occasion: {row['Occasion']}, Season: {row['Season']}, Score: {round(row['Score'],1)})")


# === Example: Preview first outfit ===
preview_outfit(outfits_df, outfit_number=1)

=== Outfit 1 (party_summer_western_women) ===

- Top: Red Lawn Kurti (Occasion: Casual, Season: Summer, Score: 10.0)
- Bottom: Black Formal Trousers (Occasion: Formal, Season: All, Score: 51.7)
- Shoes: White Sneakers (Occasion: Casual, Season: All, Score: 52.5)

In [260]:
def preview_outfits(outfits_df):
    """
    Print outfits in a clean lookbook style.
    """
    grouped = outfits_df.groupby("OutfitNumber")
    for outfit_num, group in grouped:
        template = group["Template"].iloc[0]
        print(f"\n=== Outfit {outfit_num} ({template}) ===")
        for _, row in group.iterrows():
            print(f"- {row['Category']}: {row['ProductName']} "
                  f"(Occasion: {row['Occasion']}, Season: {row['Season']}, Score: {round(row['Score'],1)})")


# ✅ Example run
outfits_df = generate_outfits(
    products,
    template="party_summer_western_women",
    season="Summer",
    trend_tags=["party"],
    num_outfits=5
)

# Preview in lookbook style
preview_outfits(outfits_df)

⚠️ No products found for category 'Accessory', skipping...
⚠️ No products found for category 'Accessory', skipping...
⚠️ No products found for category 'Accessory', skipping...
⚠️ No products found for category 'Accessory', skipping...
⚠️ No products found for category 'Accessory', skipping...

=== Outfit 1 (party_summer_western_women) ===
- Top: White Cotton Shirt (Occasion: Casual, Season: Summer, Score: 17.9)
- Bottom: Black Formal Trousers (Occasion: Formal, Season: All, Score: 51.7)
- Shoes: White Sneakers (Occasion: Casual, Season: All, Score: 52.5)
- Top: Red Lawn Kurti (Occasion: Casual, Season: Summer, Score: 10.0)

=== Outfit 2 (party_summer_western_women) ===
- Top: Red Lawn Kurti (Occasion: Casual, Season: Summer, Score: 10.0)
- Bottom: Black Formal Trousers (Occasion: Formal, Season: All, Score: 51.7)
- Shoes: Leather Formal Shoes (Occasion: Formal, Season: All, Score: 51.3)
- Top: Red Lawn Kurti (Occasion: Casual, Season: Summer, Score: 10.0)

=== Outfit 3 (party_summer_western_women) ===
- Top: White Cotton Shirt (Occasion: Casual, Season: Summer, Score: 17.9)
- Bottom: Black Formal Trousers (Occasion: Formal, Season: All, Score: 51.7)
- Shoes: Leather Formal Shoes (Occasion: Formal, Season: All, Score: 51.3)
- Top: White Cotton Shirt (Occasion: Casual, Season: Summer, Score: 17.9)

=== Outfit 4 (party_summer_western_women) ===
- Top: White Cotton Shirt (Occasion: Casual, Season: Summer, Score: 17.9)
- Bottom: Blue Denim Jeans (Occasion: Casual, Season: All, Score: 31.7)
- Shoes: Leather Formal Shoes (Occasion: Formal, Season: All, Score: 51.3)
- Top: Red Lawn Kurti (Occasion: Casual, Season: Summer, Score: 10.0)

=== Outfit 5 (party_summer_western_women) ===
- Top: Red Lawn Kurti (Occasion: Casual, Season: Summer, Score: 10.0)
- Bottom: Blue Denim Jeans (Occasion: Casual, Season: All, Score: 31.7)
- Shoes: Leather Formal Shoes (Occasion: Formal, Season: All, Score: 51.3)
- Top: White Cotton Shirt (Occasion: Casual, Season: Summer, Score: 17.9)

In [266]:
import pandas as pd

df = pd.read_csv("FashionHub_products_cleaned.csv")
print(df.columns)
print(df.head())

Index(['ProductID', 'SellerID', 'SellerName', 'Category', 'SubCategory',
       'ProductName', 'PricePKR', 'Gender', 'Color', 'Material', 'Season',
       'StockQty', 'AI_Tags', 'Corrected_Gender', 'AI_Tags_Cleaned'],
      dtype='object')
  ProductID SellerID         SellerName            Category SubCategory  \
0     P0001     S001  Okara Dress House              Others         Cap
1     P0002     S001  Okara Dress House  Bags & Accessories      Wallet
2     P0003     S001  Okara Dress House        Western Wear     T-Shirt
3     P0004     S002          Limelight        Western Wear     T-Shirt
4     P0005     S002          Limelight  Bags & Accessories      Wallet

               ProductName  PricePKR Gender   Color   Material      Season  \
0      White Polyester Cap     18057    Men   White  Polyester  All-season
1  Yellow Polyester Wallet     11044  Women  Yellow  Polyester      Summer
2    Green Leather T-Shirt      1628   Kids   Green    Leather      Summer
3      Yellow Wool T-Shirt     13215  Women  Yellow       Wool      Winter
4     Brown Leather Wallet       887    Men   Brown    Leather      Winter

   StockQty                  AI_Tags Corrected_Gender  \
0       245   summer, ethnic, casual              Men
1       119    formal, party, summer            Women
2       229  ethnic, casual, wedding           Unisex
3       461  trendy, casual, wedding            Women
4       386    formal, party, winter              Men

                           AI_Tags_Cleaned
0  summer, ethnic, casual, men, all-season
1             formal, party, summer, women
2  ethnic, casual, wedding, unisex, summer
3   trendy, casual, wedding, women, winter
4               formal, party, winter, men

In [268]:
import numpy as np

# Ensure Popularity & Feedback exist
if "Popularity" not in df.columns:
    df["Popularity"] = np.random.randint(50, 200, size=len(df))  # popularity score 50–200

if "Feedback" not in df.columns:
    df["Feedback"] = np.round(np.random.uniform(2.5, 5.0, size=len(df)), 1)  # rating 2.5–5.0

# Create Score
df["Score"] = df["Popularity"] * df["Feedback"]

In [270]:
import pandas as pd
import numpy as np
import random

# === Load dataset ===
df = pd.read_csv("FashionHub_products_cleaned.csv")

# === Step 1: Ensure Popularity & Feedback exist ===
if "Popularity" not in df.columns:
    df["Popularity"] = np.random.randint(50, 200, size=len(df))  # popularity score 50–200

if "Feedback" not in df.columns:
    df["Feedback"] = np.round(np.random.uniform(2.5, 5.0, size=len(df)), 1)  # rating 2.5–5.0

# Create Score
df["Score"] = df["Popularity"] * df["Feedback"]

# === Step 2: Outfit generator function ===
def generate_outfits(products, template, season, trend_tags, num_outfits=5):
    outfits = []
    required_categories = ["Top", "Bottom", "Shoes", "Accessory"]
    layering_items = ["jacket", "blazer", "kurti", "shawl", "cardigan", "coat"]

    # Filter by season
    filtered = products[(products["Season"].str.contains(season, case=False)) | 
                        (products["Season"].str.contains("All", case=False))]

    # Trend tags filter (optional)
    if trend_tags:
        mask = filtered["AI_Tags_Cleaned"].apply(lambda x: any(tag in str(x).lower() for tag in trend_tags))
        filtered = filtered[mask]

    for outfit_num in range(1, num_outfits + 1):
        selected_items = {}

        for category in required_categories:
            pool = filtered[filtered["Category"].str.contains(category, case=False, na=False)]
            
            if not pool.empty:
                chosen = pool.sort_values("Score", ascending=False).head(5).sample(1)
                selected_items[category] = chosen.iloc[0].to_dict()
            else:
                print(f"⚠️ No products found for category '{category}', applying fallback...")

                # === Fallback logic ===
                if category == "Accessory":
                    layering_candidates = filtered[
                        (filtered["Category"].str.contains("Top", case=False)) &
                        (filtered["ProductName"].str.lower().str.contains("|".join(layering_items)))
                    ]
                    if not layering_candidates.empty:
                        chosen = layering_candidates.sort_values("Score", ascending=False).head(5).sample(1)
                        selected_items["LayeringTop"] = chosen.iloc[0].to_dict()
                    else:
                        # pick random item from available pool
                        if not filtered.empty:
                            chosen = filtered.sample(1)
                            selected_items["ExtraItem"] = chosen.iloc[0].to_dict()

        outfits.append((template, outfit_num, selected_items))

    return outfits


# === Step 3: Run example ===
outfits = generate_outfits(
    df,
    template="party_summer_western_women",
    season="Summer",
    trend_tags=["party"],
    num_outfits=5
)

# === Step 4: Pretty print ===
for tpl, num, items in outfits:
    print(f"\n=== Outfit {num} ({tpl}) ===")
    for cat, item in items.items():
        print(f"- {cat}: {item['ProductName']} "
              f"(Occasion: {item.get('AI_Tags_Cleaned','')}, "
              f"Season: {item['Season']}, "
              f"Score: {round(item['Score'],1)})")

⚠️ No products found for category 'Top', applying fallback...
⚠️ No products found for category 'Bottom', applying fallback...
⚠️ No products found for category 'Accessory', applying fallback...
⚠️ No products found for category 'Top', applying fallback...
⚠️ No products found for category 'Bottom', applying fallback...
⚠️ No products found for category 'Accessory', applying fallback...
⚠️ No products found for category 'Top', applying fallback...
⚠️ No products found for category 'Bottom', applying fallback...
⚠️ No products found for category 'Accessory', applying fallback...
⚠️ No products found for category 'Top', applying fallback...
⚠️ No products found for category 'Bottom', applying fallback...
⚠️ No products found for category 'Accessory', applying fallback...
⚠️ No products found for category 'Top', applying fallback...
⚠️ No products found for category 'Bottom', applying fallback...
⚠️ No products found for category 'Accessory', applying fallback...

=== Outfit 1 (party_summer_western_women) ===
- Shoes: Green Cotton Formal Shoes (Occasion: casual, ethnic, party, men, summer, Season: Summer, Score: 819.0)
- ExtraItem: Green Silk Maxi Dress (Occasion: trendy, summer, party, unisex, Season: Summer, Score: 528.9)

=== Outfit 2 (party_summer_western_women) ===
- Shoes: Green Cotton Formal Shoes (Occasion: casual, ethnic, party, men, summer, Season: Summer, Score: 819.0)
- ExtraItem: Blue Linen Hat (Occasion: ethnic, wedding, party, unisex, all-season, Season: All-season, Score: 736.0)

=== Outfit 3 (party_summer_western_women) ===
- Shoes: Brown Wool Sneakers (Occasion: wedding, party, summer, men, all-season, Season: All-season, Score: 844.8)
- ExtraItem: Pink Wool Maxi Dress (Occasion: summer, party, trendy, unisex, Season: Summer, Score: 560.0)

=== Outfit 4 (party_summer_western_women) ===
- Shoes: Brown Wool Sneakers (Occasion: wedding, party, summer, men, all-season, Season: All-season, Score: 844.8)
- ExtraItem: Grey Lawn T-Shirt (Occasion: casual, party, ethnic, men, all-season, Season: All-season, Score: 605.5)

=== Outfit 5 (party_summer_western_women) ===
- Shoes: Brown Wool Sneakers (Occasion: wedding, party, summer, men, all-season, Season: All-season, Score: 844.8)
- ExtraItem: Green Polyester Necklace (Occasion: summer, wedding, party, men, all-season, Season: All-season, Score: 584.8)

In [272]:
import pandas as pd
import numpy as np

# === Load dataset ===
df = pd.read_csv("FashionHub_products_cleaned.csv")

# === Step 1: Map SubCategory to OutfitCategory ===
def map_outfit_category(row):
    sub = str(row["SubCategory"]).lower()
    if any(x in sub for x in ["t-shirt", "shirt", "kurti", "top", "blazer", "hoodie", "coat", "jacket"]):
        return "Top"
    elif any(x in sub for x in ["jeans", "trouser", "shalwar", "pants", "skirt", "bottom"]):
        return "Bottom"
    elif any(x in sub for x in ["shoe", "sneaker", "sandal", "loafer", "boot"]):
        return "Shoes"
    elif any(x in sub for x in ["bag", "scarf", "wallet", "watch", "necklace", "accessory", "cap"]):
        return "Accessory"
    else:
        return "Other"

df["OutfitCategory"] = df.apply(map_outfit_category, axis=1)

# === Step 2: Score products ===
# Simple scoring (you can improve later)
df["Score"] = df.index % 100 + np.random.randint(10, 100, size=len(df))

# === Step 3: Outfit generator with fallback ===
def generate_outfits(df, template="party_summer_western_women", season="Summer", trend_tags=["party"], num_outfits=5):
    outfits = []

    # Filter by season if possible
    filtered = df[(df["Season"].str.lower().str.contains(season.lower())) | (df["Season"].str.lower() == "all-season")]

    for outfit_num in range(1, num_outfits+1):
        selected_items = {}

        for category in ["Top", "Bottom", "Shoes", "Accessory"]:
            candidates = filtered[filtered["OutfitCategory"] == category].sort_values("Score", ascending=False)
            if not candidates.empty:
                selected_items[category] = candidates.sample(1)
            else:
                print(f"⚠️ No products found for category '{category}', applying fallback...")
                # fallback = pick any random from filtered
                if not filtered.empty:
                    selected_items[category] = filtered.sample(1).assign(OutfitCategory="ExtraItem")

        # Collect items
        for cat, item in selected_items.items():
            for _, row in item.iterrows():
                outfits.append({
                    "Template": template,
                    "OutfitNumber": outfit_num,
                    "ProductID": row["ProductID"],
                    "ProductName": row["ProductName"],
                    "Category": row["OutfitCategory"],
                    "Season": row["Season"],
                    "Score": row["Score"],
                    "Tags": row["AI_Tags_Cleaned"]
                })

    return pd.DataFrame(outfits)

# === Step 4: Run generator ===
outfits_df = generate_outfits(
    df,
    template="party_summer_western_women",
    season="Summer",
    trend_tags=["party"],
    num_outfits=5
)

# === Step 5: Show and save results ===
for outfit_num in range(1, 6):
    outfit_items = outfits_df[outfits_df["OutfitNumber"] == outfit_num]
    print(f"\n=== Outfit {outfit_num} (party_summer_western_women) ===")
    for _, row in outfit_items.iterrows():
        print(f"- {row['Category']}: {row['ProductName']} (Season: {row['Season']}, Score: {row['Score']})")

outfits_df.to_csv("FashionHub_Outfits_Generated.csv", index=False)
print("\n✅ Outfits exported to 'FashionHub_Outfits_Generated.csv'")

=== Outfit 1 (party_summer_western_women) ===
- Top: Grey Denim Formal Shirt (Season: Summer, Score: 101)
- Bottom: Green Leather Shalwar Kameez (Season: All-season, Score: 141)
- Shoes: Pink Silk Sneakers (Season: Summer, Score: 149)
- Accessory: Pink Polyester Scarf (Season: Summer, Score: 142)

=== Outfit 2 (party_summer_western_women) ===
- Top: Brown Polyester Formal Shirt (Season: Summer, Score: 124)
- Bottom: Blue Wool Shalwar Kameez (Season: All-season, Score: 159)
- Shoes: Red Polyester Formal Shoes (Season: All-season, Score: 75)
- Accessory: Blue Lawn Necklace (Season: All-season, Score: 72)

=== Outfit 3 (party_summer_western_women) ===
- Top: Red Lawn Hoodie (Season: All-season, Score: 107)
- Bottom: Blue Linen Jeans (Season: All-season, Score: 30)
- Shoes: Pink Wool Formal Shoes (Season: All-season, Score: 141)
- Accessory: Brown Linen Wallet (Season: All-season, Score: 99)

=== Outfit 4 (party_summer_western_women) ===
- Top: Pink Leather Hoodie (Season: All-season, Score: 52)
- Bottom: Red Linen Shalwar Kameez (Season: All-season, Score: 61)
- Shoes: Grey Silk Sneakers (Season: All-season, Score: 85)
- Accessory: White Linen Scarf (Season: All-season, Score: 181)

=== Outfit 5 (party_summer_western_women) ===
- Top: Brown Linen Hoodie (Season: Summer, Score: 175)
- Bottom: Red Polyester Shalwar Kameez (Season: All-season, Score: 24)
- Shoes: White Silk Sneakers (Season: Summer, Score: 185)
- Accessory: Brown Lawn Handbag (Season: Summer, Score: 153)

✅ Outfits exported to 'FashionHub_Outfits_Generated.csv'

In [274]:
import pandas as pd
import random

# Load dataset
df = pd.read_csv("FashionHub_products_cleaned.csv")

# Define categories mapping (so filtering is easier)
CATEGORY_MAP = {
    "Top": ["Top", "Shirt", "Kurta", "Hoodie", "T-Shirt", "Maxi Dress", "Formal Shirt"],
    "Bottom": ["Bottom", "Jeans", "Trouser", "Shalwar", "Shalwar Kameez", "Pant"],
    "Shoes": ["Shoes", "Sneakers", "Sandals", "Formal Shoes", "Khussa"],
    "Accessory": ["Accessory", "Scarf", "Handbag", "Necklace", "Cap", "Wallet", "Ring", "Hat"]
}

# Outfit templates (standard set)
TEMPLATES = [
    ("casual", "summer", "western", "men"),
    ("casual", "winter", "western", "women"),
    ("party", "summer", "western", "women"),
    ("party", "winter", "western", "men"),
    ("formal", "all-season", "eastern", "men"),
    ("formal", "all-season", "eastern", "women"),
    ("wedding", "summer", "eastern", "women"),
    ("wedding", "winter", "eastern", "men")
]

# Function to filter products
def filter_products(df, category, occasion, season, gender):
    # Match category by keywords
    mask_category = df["SubCategory"].apply(
        lambda x: any(cat.lower() in str(x).lower() for cat in CATEGORY_MAP[category])
    )
    mask_tags = df["AI_Tags_Cleaned"].apply(
        lambda x: occasion in str(x).lower() and gender in str(x).lower()
    )
    mask_season = df["Season"].str.lower().isin([season.lower(), "all-season"])
    
    filtered = df[mask_category & mask_tags & mask_season]
    
    if filtered.empty:
        print(f"⚠️ No products found for category '{category}', applying fallback...")
        # Fallback: relax filtering
        filtered = df[mask_category & mask_season]
        if filtered.empty:
            filtered = df[mask_category]
    
    return filtered

# Function to score products
def score_product(row):
    return row["StockQty"] * 0.4 + random.uniform(0.5, 1.5) * 100

# Generate outfits
outfits = []
for template in TEMPLATES:
    occasion, season, style, gender = template
    template_name = f"{occasion}_{season}_{style}_{gender}"
    
    for i in range(10):  # 10 outfits per template
        outfit = {"TemplateName": template_name, "OutfitNumber": i+1}
        
        for category in ["Top", "Bottom", "Shoes", "Accessory"]:
            products = filter_products(df, category, occasion, season, gender)
            if not products.empty:
                products = products.copy()
                products["Score"] = products.apply(score_product, axis=1)
                chosen = products.sort_values("Score", ascending=False).sample(1).iloc[0]
                outfit[category] = f"{chosen['ProductName']} (Season: {chosen['Season']}, Score: {int(chosen['Score'])})"
            else:
                outfit[category] = "❌ No product"
        
        outfits.append(outfit)

# Save results
outfits_df = pd.DataFrame(outfits)
outfits_df.to_csv("FashionHub_Outfits_AllTemplates.csv", index=False)

print("✅ Outfits generated and saved to 'FashionHub_Outfits_AllTemplates.csv'")

✅ Outfits generated and saved to 'FashionHub_Outfits_AllTemplates.csv'

In [280]:
import pandas as pd
import random

# Load dataset
df = pd.read_csv("FashionHub_products_cleaned.csv")

# If Score column doesn’t exist, create it
if "Score" not in df.columns:
    if "Popularity" in df.columns and "Feedback" in df.columns:
        df["Score"] = df["Popularity"] * df["Feedback"]
    else:
        # Fallback score using Price + Stock (normalized)
        df["Score"] = df["PricePKR"].rank(pct=True) * 100 + df["StockQty"].rank(pct=True) * 50

# --- Step 1: Map Category/SubCategory into OutfitCategory ---
def map_outfit_category(row):
    cat = str(row["Category"]).lower()
    sub = str(row["SubCategory"]).lower()

    if "shirt" in sub or "kurta" in sub or "t-shirt" in sub or "hoodie" in sub or "top" in sub:
        return "Top"
    elif "jean" in sub or "trouser" in sub or "shalwar" in sub or "bottom" in sub or "kameez" in sub:
        return "Bottom"
    elif "shoe" in sub or "sneaker" in sub or "sandal" in sub or "khussa" in sub:
        return "Shoes"
    elif "bag" in cat or "accessor" in cat or "scarf" in sub or "wallet" in sub or "hat" in sub or "watch" in sub:
        return "Accessory"
    else:
        return None

df["OutfitCategory"] = df.apply(map_outfit_category, axis=1)

# --- Step 2: Outfit Generator ---
required_categories = ["Top", "Bottom", "Shoes", "Accessory"]

def generate_outfits(df, occasion="party", season="summer", style="western", gender="women", n_outfits=5):
    outfits = []
    
    # Filter dataset
    filtered = df[
        df["AI_Tags_Cleaned"].str.contains(occasion, case=False, na=False) &
        df["AI_Tags_Cleaned"].str.contains(season, case=False, na=False) &
        df["AI_Tags_Cleaned"].str.contains(gender, case=False, na=False)
    ].copy()
    
    if filtered.empty:
        print("⚠️ No products found matching filters, using full dataset as fallback.")
        filtered = df.copy()

    for i in range(n_outfits):
        selected_items = {}

        for cat in required_categories:
            candidates = filtered[filtered["OutfitCategory"] == cat]

            if candidates.empty:
                print(f"⚠️ No products found for category '{cat}', applying fallback...")
                fallback = df[df["OutfitCategory"] == cat]
                if not fallback.empty:
                    candidates = fallback
                else:
                    continue  

            # Weighted random choice by Score
            weights = candidates["Score"] / candidates["Score"].sum()
            choice = candidates.sample(1, weights=weights).iloc[0]
            selected_items[cat] = choice

        # Save outfit
        outfits.append(selected_items)

    return outfits

# --- Step 3: Run Outfit Generation ---
outfits = generate_outfits(df, occasion="party", season="summer", style="western", gender="women", n_outfits=5)

# --- Step 4: Print results ---
for idx, outfit in enumerate(outfits, 1):
    print(f"\n=== Outfit {idx} (party_summer_western_women) ===")
    for cat, item in outfit.items():
        print(f"- {cat}: {item['ProductName']} (Season: {item['Season']}, Score: {item['Score']:.0f})")

# --- Step 5: Export to CSV ---
out_data = []
for idx, outfit in enumerate(outfits, 1):
    for cat, item in outfit.items():
        out_data.append({
            "OutfitID": idx,
            "Category": cat,
            "ProductID": item["ProductID"],
            "ProductName": item["ProductName"],
            "Season": item["Season"],
            "Score": item["Score"]
        })

out_df = pd.DataFrame(out_data)
out_df.to_csv("FashionHub_Outfits_Generated.csv", index=False)
print("\n✅ Outfits exported to 'FashionHub_Outfits_Generated.csv'")

=== Outfit 1 (party_summer_western_women) ===
- Top: Grey Polyester T-Shirt (Season: Summer, Score: 99)
- Bottom: Beige Denim Jeans (Season: Summer, Score: 85)
- Shoes: Grey Denim Formal Shoes (Season: Summer, Score: 96)
- Accessory: Yellow Polyester Wallet (Season: Summer, Score: 68)

=== Outfit 2 (party_summer_western_women) ===
- Top: Pink Silk Hoodie (Season: Winter, Score: 111)
- Bottom: Green Linen Shalwar Kameez (Season: Summer, Score: 125)
- Shoes: Brown Linen Sandals (Season: Summer, Score: 74)
- Accessory: Green Polyester Wallet (Season: Winter, Score: 123)

=== Outfit 3 (party_summer_western_women) ===
- Top: Green Denim Formal Shirt (Season: Winter, Score: 133)
- Bottom: Black Lawn Shalwar Kameez (Season: Summer, Score: 59)
- Shoes: Grey Denim Formal Shoes (Season: Summer, Score: 96)
- Accessory: White Linen Belt (Season: Summer, Score: 104)

=== Outfit 4 (party_summer_western_women) ===
- Top: Pink Denim T-Shirt (Season: Summer, Score: 106)
- Bottom: Beige Lawn Shalwar Kameez (Season: All-season, Score: 59)
- Shoes: Blue Lawn Sandals (Season: All-season, Score: 79)
- Accessory: White Lawn Belt (Season: All-season, Score: 69)

=== Outfit 5 (party_summer_western_women) ===
- Top: Blue Polyester Hoodie (Season: Summer, Score: 77)
- Bottom: Beige Denim Jeans (Season: Summer, Score: 85)
- Shoes: Red Linen Sneakers (Season: All-season, Score: 53)
- Accessory: Brown Wool Scarf (Season: Summer, Score: 102)

✅ Outfits exported to 'FashionHub_Outfits_Generated.csv'

In [282]:
import pandas as pd
import random

# === Load Dataset ===
df = pd.read_csv("FashionHub_products_cleaned.csv")

# === Compute Score ===
# If 'Popularity' and 'Feedback' are missing, we can assign default random scores
if "Score" not in df.columns:
    df["Score"] = df.apply(lambda x: random.randint(50, 200), axis=1)

# === Define function to generate outfits ===
def generate_outfits(df, templates, n_outfits=5):
    outfits_all = []

    # Define required categories
    required_categories = ["Top", "Bottom", "Shoes", "Accessory"]
    layering_items = ["jacket", "blazer", "kurti", "shawl", "cardigan", "coat"]

    for template in templates:
        occasion = template["occasion"]
        season = template["season"]
        style = template["style"]
        gender = template["gender"]

        filtered = df[
            df["AI_Tags_Cleaned"].str.contains(occasion, case=False, na=False) &
            df["AI_Tags_Cleaned"].str.contains(season, case=False, na=False) &
            df["AI_Tags_Cleaned"].str.contains(style, case=False, na=False) &
            df["Corrected_Gender"].str.contains(gender, case=False, na=False)
        ]

        for outfit_num in range(1, n_outfits + 1):
            selected_items = {}
            for cat in required_categories:
                candidates = filtered[
                    filtered["Category"].str.contains(cat, case=False, na=False) |
                    filtered["SubCategory"].str.contains(cat, case=False, na=False)
                ]
                if candidates.empty:
                    print(f"⚠️ No products found for category '{cat}', applying fallback...")
                    # Try to add a layering item if Top missing
                    if cat == "Top":
                        layering_candidates = filtered[
                            filtered["ProductName"].str.lower().str.contains("|".join(layering_items))
                        ]
                        if not layering_candidates.empty:
                            candidates = layering_candidates
                        else:
                            candidates = filtered  # fallback to any product
                if not candidates.empty:
                    # Pick highest score item
                    best_item = candidates.loc[candidates["Score"].idxmax()]
                    selected_items[cat] = f"{best_item['ProductName']} (Season: {best_item['Season']}, Score: {best_item['Score']})"

            outfits_all.append({
                "TemplateName": f"{occasion}_{season}_{style}_{gender}",
                "OutfitNumber": outfit_num,
                "Top": selected_items.get("Top", ""),
                "Bottom": selected_items.get("Bottom", ""),
                "Shoes": selected_items.get("Shoes", ""),
                "Accessory": selected_items.get("Accessory", "")
            })
    return pd.DataFrame(outfits_all)

# === Define Templates ===
templates = [
    {"occasion": "casual", "season": "summer", "style": "western", "gender": "men"},
    {"occasion": "party", "season": "summer", "style": "western", "gender": "women"},
    {"occasion": "formal", "season": "winter", "style": "ethnic", "gender": "women"}
]

# === Generate Outfits ===
outfits_df = generate_outfits(df, templates, n_outfits=5)

# === Display & Save CSV ===
print(outfits_df.head(10))
outfits_df.to_csv("FashionHub_Outfits_AllTemplates.csv", index=False)
print("✅ Outfits exported to 'FashionHub_Outfits_AllTemplates.csv'")

⚠️ No products found for category 'Top', applying fallback...
⚠️ No products found for category 'Bottom', applying fallback...
⚠️ No products found for category 'Accessory', applying fallback...
⚠️ No products found for category 'Top', applying fallback...
⚠️ No products found for category 'Bottom', applying fallback...
⚠️ No products found for category 'Accessory', applying fallback...
⚠️ No products found for category 'Top', applying fallback...
⚠️ No products found for category 'Bottom', applying fallback...
⚠️ No products found for category 'Accessory', applying fallback...
⚠️ No products found for category 'Top', applying fallback...
⚠️ No products found for category 'Bottom', applying fallback...
⚠️ No products found for category 'Accessory', applying fallback...
⚠️ No products found for category 'Top', applying fallback...
⚠️ No products found for category 'Bottom', applying fallback...
⚠️ No products found for category 'Accessory', applying fallback...
⚠️ No products found for category 'Top', applying fallback...
⚠️ No products found for category 'Bottom', applying fallback...
⚠️ No products found for category 'Accessory', applying fallback...
⚠️ No products found for category 'Top', applying fallback...
⚠️ No products found for category 'Bottom', applying fallback...
⚠️ No products found for category 'Accessory', applying fallback...
⚠️ No products found for category 'Top', applying fallback...
⚠️ No products found for category 'Bottom', applying fallback...
⚠️ No products found for category 'Accessory', applying fallback...
⚠️ No products found for category 'Top', applying fallback...
⚠️ No products found for category 'Bottom', applying fallback...
⚠️ No products found for category 'Accessory', applying fallback...
⚠️ No products found for category 'Top', applying fallback...
⚠️ No products found for category 'Bottom', applying fallback...
⚠️ No products found for category 'Accessory', applying fallback...
⚠️ No products found for category 'Top', applying fallback...
⚠️ No products found for category 'Bottom', applying fallback...
⚠️ No products found for category 'Accessory', applying fallback...
⚠️ No products found for category 'Top', applying fallback...
⚠️ No products found for category 'Bottom', applying fallback...
⚠️ No products found for category 'Accessory', applying fallback...
⚠️ No products found for category 'Top', applying fallback...
⚠️ No products found for category 'Bottom', applying fallback...
⚠️ No products found for category 'Accessory', applying fallback...
⚠️ No products found for category 'Top', applying fallback...
⚠️ No products found for category 'Bottom', applying fallback...
⚠️ No products found for category 'Accessory', applying fallback...
⚠️ No products found for category 'Top', applying fallback...
⚠️ No products found for category 'Bottom', applying fallback...
⚠️ No products found for category 'Accessory', applying fallback...
                 TemplateName  OutfitNumber  \
0   casual_summer_western_men             1
1   casual_summer_western_men             2
2   casual_summer_western_men             3
3   casual_summer_western_men             4
4   casual_summer_western_men             5
5  party_summer_western_women             1
6  party_summer_western_women             2
7  party_summer_western_women             3
8  party_summer_western_women             4
9  party_summer_western_women             5

                                                 Top Bottom  \
0     Blue Silk Sandals (Season: Summer, Score: 196)
1     Blue Silk Sandals (Season: Summer, Score: 196)
2     Blue Silk Sandals (Season: Summer, Score: 196)
3     Blue Silk Sandals (Season: Summer, Score: 196)
4     Blue Silk Sandals (Season: Summer, Score: 196)
5  Red Polyester Handbag (Season: Summer, Score: ...
6  Red Polyester Handbag (Season: Summer, Score: ...
7  Red Polyester Handbag (Season: Summer, Score: ...
8  Red Polyester Handbag (Season: Summer, Score: ...
9  Red Polyester Handbag (Season: Summer, Score: ...

                                               Shoes Accessory
0     Blue Silk Sandals (Season: Summer, Score: 196)
1     Blue Silk Sandals (Season: Summer, Score: 196)
2     Blue Silk Sandals (Season: Summer, Score: 196)
3     Blue Silk Sandals (Season: Summer, Score: 196)
4     Blue Silk Sandals (Season: Summer, Score: 196)
5  Grey Denim Formal Shoes (Season: Summer, Score...
6  Grey Denim Formal Shoes (Season: Summer, Score...
7  Grey Denim Formal Shoes (Season: Summer, Score...
8  Grey Denim Formal Shoes (Season: Summer, Score...
9  Grey Denim Formal Shoes (Season: Summer, Score...
✅ Outfits exported to 'FashionHub_Outfits_AllTemplates.csv'

In [290]:
import pandas as pd
import random

# Load dataset
df = pd.read_csv("FashionHub_products_cleaned.csv")

# If 'Score' doesn't exist, create a default column
if "Score" not in df.columns:
    df["Score"] = 100  # default score

# Correct gender column name if needed
if "Corrected_Gender" not in df.columns:
    df["Corrected_Gender"] = df["Gender"]  # fallback

# Infer category if missing
def infer_category(name):
    name = name.lower()
    if any(x in name for x in ["shirt", "t-shirt", "hoodie", "kurta", "blouse"]):
        return "Top"
    elif any(x in name for x in ["jeans", "shalwar", "trousers", "pants", "saree", "kameez"]):
        return "Bottom"
    elif any(x in name for x in ["shoes", "sandals", "heels", "sneakers", "boots"]):
        return "Shoes"
    elif any(x in name for x in ["scarf", "bag", "wallet", "belt", "necklace", "handbag", "cap"]):
        return "Accessory"
    else:
        return "Other"

df["Category"] = df["ProductName"].apply(infer_category)

# Outfit generator
def generate_outfits(df, occasion, season, style, gender, n_outfits=5):
    outfits = []
    filtered = df[
        df["AI_Tags_Cleaned"].str.contains(occasion, case=False, na=False) &
        ((df["AI_Tags_Cleaned"].str.contains(season, case=False, na=False)) | df["Season"].str.contains("All-season", case=False)) &
        df["AI_Tags_Cleaned"].str.contains(style, case=False, na=False) &
        df["Corrected_Gender"].str.contains(gender, case=False, na=False)
    ]
    
    categories = ["Top", "Bottom", "Shoes", "Accessory"]
    
    # To avoid repeating fallback warnings too much
    fallback_warned = {cat: False for cat in categories}
    
    for i in range(n_outfits):
        outfit = {}
        outfit["TemplateName"] = f"{occasion}_{season}_{style}_{gender}"
        outfit["OutfitNumber"] = i + 1
        
        for cat in categories:
            candidates = filtered[filtered["Category"].str.contains(cat, case=False, na=False)]
            
            if candidates.empty:
                fallback_candidates = df[df["Category"].str.contains(cat, case=False, na=False)]
                if fallback_candidates.empty:
                    outfit[cat] = None
                    continue
                chosen = fallback_candidates.sort_values("Score", ascending=False).sample(n=1).iloc[0]
                if not fallback_warned[cat]:
                    print(f"⚠️ No products found in filtered dataset for '{cat}', applying fallback...")
                    fallback_warned[cat] = True
            else:
                top_candidates = candidates.sort_values("Score", ascending=False).head(5)
                chosen = top_candidates.sample(n=1).iloc[0]
            
            outfit[cat] = f"{chosen['ProductName']} (Season: {chosen['Season']}, Score: {chosen['Score']})"
        
        outfits.append(outfit)
    
    return outfits

# Templates
templates = [
    {"occasion": "casual", "season": "summer", "style": "western", "gender": "men", "n_outfits": 10},
    {"occasion": "party", "season": "summer", "style": "western", "gender": "women", "n_outfits": 10},
    {"occasion": "formal", "season": "winter", "style": "western", "gender": "women", "n_outfits": 10},
]

all_outfits = []
for tpl in templates:
    all_outfits.extend(generate_outfits(
        df, tpl["occasion"], tpl["season"], tpl["style"], tpl["gender"], tpl["n_outfits"]
    ))

# Export all outfits
outfits_df = pd.DataFrame(all_outfits)
outfits_df.to_csv("FashionHub_Outfits_AllTemplates.csv", index=False)
print("✅ Outfits exported to 'FashionHub_Outfits_AllTemplates.csv'")
print(outfits_df.head(10))

⚠️ No products found in filtered dataset for 'Shoes', applying fallback...
✅ Outfits exported to 'FashionHub_Outfits_AllTemplates.csv'
                TemplateName  OutfitNumber  \
0  casual_summer_western_men             1
1  casual_summer_western_men             2
2  casual_summer_western_men             3
3  casual_summer_western_men             4
4  casual_summer_western_men             5
5  casual_summer_western_men             6
6  casual_summer_western_men             7
7  casual_summer_western_men             8
8  casual_summer_western_men             9
9  casual_summer_western_men            10

                                                 Top  \
0  White Leather Hoodie (Season: Summer, Score: 100)
1  Beige Wool Formal Shirt (Season: Summer, Score...
2  Red Polyester Kurta (Season: All-season, Score...
3  Beige Wool Formal Shirt (Season: Summer, Score...
4  Red Polyester Kurta (Season: All-season, Score...
5  Beige Wool Formal Shirt (Season: Summer, Score...
6  Red Polyester Kurta (Season: All-season, Score...
7  Red Leather T-Shirt (Season: All-season, Score...
8  Red Leather T-Shirt (Season: All-season, Score...
9  Red Leather T-Shirt (Season: All-season, Score...

                                              Bottom  \
0  Green Linen Shalwar Kameez (Season: All-season...
1  Green Cotton Jeans (Season: All-season, Score:...
2  White Cotton Shalwar Kameez (Season: Summer, S...
3  White Cotton Shalwar Kameez (Season: Summer, S...
4  Blue Polyester Shalwar Kameez (Season: Summer,...
5  Blue Polyester Shalwar Kameez (Season: Summer,...
6   Red Polyester Saree (Season: Summer, Score: 100)
7  Green Linen Shalwar Kameez (Season: All-season...
8  Green Cotton Jeans (Season: All-season, Score:...
9  Blue Polyester Shalwar Kameez (Season: Summer,...

                                               Shoes  \
0   Yellow Silk Sandals (Season: Summer, Score: 100)
1     Blue Silk Sandals (Season: Summer, Score: 100)
2     Blue Silk Sandals (Season: Summer, Score: 100)
3     Blue Silk Sandals (Season: Summer, Score: 100)
4       Pink Silk Heels (Season: Summer, Score: 100)
5    Beige Lawn Sandals (Season: Summer, Score: 100)
6       Pink Silk Heels (Season: Summer, Score: 100)
7  Grey Lawn Sandals (Season: All-season, Score: ...
8    Beige Lawn Sandals (Season: Summer, Score: 100)
9    Beige Lawn Sandals (Season: Summer, Score: 100)

                                           Accessory
0      Blue Denim Scarf (Season: Summer, Score: 100)
1      Blue Denim Scarf (Season: Summer, Score: 100)
2  Red Leather Handbag (Season: All-season, Score...
3     Brown Wool Wallet (Season: Summer, Score: 100)
4   Black Lawn Necklace (Season: Summer, Score: 100)
5      Blue Denim Scarf (Season: Summer, Score: 100)
6     Brown Wool Wallet (Season: Summer, Score: 100)
7      Blue Denim Scarf (Season: Summer, Score: 100)
8   Black Lawn Necklace (Season: Summer, Score: 100)
9  Beige Wool Handbag (Season: All-season, Score:...

In [294]:
import pandas as pd
import random

# === Load dataset ===
df = pd.read_csv("FashionHub_products_cleaned.csv")  # update path if needed

# Ensure Score column exists
if 'Score' not in df.columns:
    df['Score'] = 100  # default score if missing

# === Category keywords mapping ===
category_keywords = {
    "Top": ["Shirt", "Kurta", "T-Shirt", "Hoodie", "Jacket", "Sweater", "Blouse", "Tunic"],
    "Bottom": ["Shalwar", "Jeans", "Trousers", "Saree", "Skirt", "Pant"],
    "Shoes": ["Shoes", "Sandals", "Sneakers", "Heels", "Flats", "Loafers", "Boots"],
    "Accessory": ["Bag", "Wallet", "Belt", "Scarf", "Necklace", "Ring", "Cap", "Handbag"]
}

# Optional: Shoes priority by style
shoes_priority = {
    "western": ["Sneakers", "Heels", "Flats", "Loafers", "Boots", "Sandals"],
    "ethnic": ["Sandals", "Heels", "Flats", "Loafers", "Boots", "Sneakers"]
}

# === Outfit generation function ===
def generate_outfits(df, occasion, season, style, gender, n_outfits=5):
    filtered = df[df['Gender'].str.lower() == gender.lower()]
    filtered = filtered[filtered['Season'].str.lower().isin([season.lower(), 'all-season'])]

    categories = ["Top", "Bottom", "Shoes", "Accessory"]
    outfits = []

    for i in range(n_outfits):
        outfit = {}
        for cat in categories:
            # Filter products by category keywords
            candidates = filtered[
                filtered['ProductName'].str.contains('|'.join(category_keywords[cat]), case=False, na=False)
            ]

            # Shoes: apply style priority if possible
            if cat == "Shoes" and style.lower() in shoes_priority:
                priority_list = shoes_priority[style.lower()]
                candidates = candidates[
                    candidates['ProductName'].str.contains('|'.join(priority_list), case=False, na=False)
                ]

            # Fallback if no candidates
            if candidates.empty:
                chosen = filtered.sample(n=1).iloc[0]
                print(f"⚠️ No products found in filtered dataset for '{cat}', applying fallback...")
            else:
                top_candidates = candidates.sort_values("Score", ascending=False).head(5)
                chosen = top_candidates.sample(n=1).iloc[0]

            outfit[cat] = f"{chosen['ProductName']} (Season: {chosen['Season']}, Score: {chosen['Score']})"

        outfit["TemplateName"] = f"{occasion}_{season}_{style}_{gender}"
        outfit["OutfitNumber"] = i + 1
        outfits.append(outfit)

    return outfits

# === Define multiple templates ===
templates = [
    {"occasion": "casual", "season": "summer", "style": "western", "gender": "men", "n_outfits": 10},
    {"occasion": "party", "season": "summer", "style": "western", "gender": "women", "n_outfits": 10},
    {"occasion": "formal", "season": "winter", "style": "western", "gender": "men", "n_outfits": 10}
]

# === Generate outfits for all templates ===
all_outfits = []
for tpl in templates:
    all_outfits.extend(generate_outfits(
        df, tpl["occasion"], tpl["season"], tpl["style"], tpl["gender"], tpl["n_outfits"]
    ))

# Convert to DataFrame and export
all_outfits_df = pd.DataFrame(all_outfits)
all_outfits_df = all_outfits_df[["TemplateName", "OutfitNumber", "Top", "Bottom", "Shoes", "Accessory"]]

# Export CSV
all_outfits_df.to_csv("FashionHub_Outfits_AllTemplates.csv", index=False)
print("✅ Outfits exported to 'FashionHub_Outfits_AllTemplates.csv'")

# Display first few rows
print(all_outfits_df.head(10))

✅ Outfits exported to 'FashionHub_Outfits_AllTemplates.csv'
                TemplateName  OutfitNumber  \
0  casual_summer_western_men             1
1  casual_summer_western_men             2
2  casual_summer_western_men             3
3  casual_summer_western_men             4
4  casual_summer_western_men             5
5  casual_summer_western_men             6
6  casual_summer_western_men             7
7  casual_summer_western_men             8
8  casual_summer_western_men             9
9  casual_summer_western_men            10

                                                 Top  \
0     Green Lawn Hoodie (Season: Summer, Score: 100)
1   Red Linen Kurta (Season: All-season, Score: 100)
2   Red Linen Kurta (Season: All-season, Score: 100)
3  Brown Leather Hoodie (Season: Summer, Score: 100)
4  Red Leather T-Shirt (Season: All-season, Score...
5     Green Lawn Hoodie (Season: Summer, Score: 100)
6  Brown Leather Hoodie (Season: Summer, Score: 100)
7  Brown Leather Hoodie (Season: Summer, Score: 100)
8  Black Lawn Hoodie (Season: All-season, Score: ...
9  Red Leather T-Shirt (Season: All-season, Score...

                                              Bottom  \
0  Brown Polyester Saree (Season: All-season, Sco...
1  Brown Polyester Shalwar Kameez (Season: Summer...
2  Yellow Denim Shalwar Kameez (Season: All-seaso...
3  Brown Polyester Saree (Season: All-season, Sco...
4  Brown Polyester Saree (Season: All-season, Sco...
5  Brown Polyester Saree (Season: All-season, Sco...
6       Grey Lawn Saree (Season: Summer, Score: 100)
7       Grey Lawn Saree (Season: Summer, Score: 100)
8  Brown Polyester Saree (Season: All-season, Sco...
9  Yellow Denim Shalwar Kameez (Season: All-seaso...

                                               Shoes  \
0  Grey Silk Sneakers (Season: All-season, Score:...
1  Yellow Linen Heels (Season: All-season, Score:...
2  Blue Linen Sandals (Season: All-season, Score:...
3  Grey Silk Sneakers (Season: All-season, Score:...
4  White Leather Sandals (Season: Summer, Score: ...
5  Grey Silk Sneakers (Season: All-season, Score:...
6  Blue Linen Sandals (Season: All-season, Score:...
7   Yellow Silk Sandals (Season: Summer, Score: 100)
8   Yellow Silk Sandals (Season: Summer, Score: 100)
9  Blue Linen Sandals (Season: All-season, Score:...

                                           Accessory
0   Blue Leather Wallet (Season: Summer, Score: 100)
1    Grey Lawn Belt (Season: All-season, Score: 100)
2    Grey Lawn Belt (Season: All-season, Score: 100)
3    Blue Denim Handbag (Season: Summer, Score: 100)
4    Blue Denim Handbag (Season: Summer, Score: 100)
5   Blue Leather Wallet (Season: Summer, Score: 100)
6   Blue Leather Wallet (Season: Summer, Score: 100)
7   Blue Leather Wallet (Season: Summer, Score: 100)
8    Blue Denim Handbag (Season: Summer, Score: 100)
9  White Polyester Cap (Season: All-season, Score...

In [296]:
import pandas as pd

# === Load datasets ===
outfits_df = pd.read_csv("FashionHub_Outfits_AllTemplates.csv")
products_df = pd.read_csv("FashionHub_products_cleaned.csv")

# Function to map product info
def map_product_info(product_str, products_df):
    # Extract product name before " (Season: ...)"
    product_name = product_str.split(" (Season:")[0].strip()
    
    match = products_df[products_df['ProductName'].str.lower() == product_name.lower()]
    if not match.empty:
        row = match.iloc[0]
        return pd.Series({
            "ID": row['ProductID'],
            "Price": row['PricePKR'],
            "Seller": row['SellerName']
        })
    else:
        # Fallback for missing product
        return pd.Series({"ID": None, "Price": None, "Seller": None})

# Map all categories
for cat in ["Top", "Bottom", "Shoes", "Accessory"]:
    mapped = outfits_df[cat].apply(lambda x: map_product_info(x, products_df))
    outfits_df[f"{cat}_ID"] = mapped["ID"]
    outfits_df[f"{cat}_Price"] = mapped["Price"]
    outfits_df[f"{cat}_Seller"] = mapped["Seller"]

# Optional: Reorder columns for website use
columns_order = [
    "TemplateName", "OutfitNumber",
    "Top", "Top_ID", "Top_Price", "Top_Seller",
    "Bottom", "Bottom_ID", "Bottom_Price", "Bottom_Seller",
    "Shoes", "Shoes_ID", "Shoes_Price", "Shoes_Seller",
    "Accessory", "Accessory_ID", "Accessory_Price", "Accessory_Seller"
]
outfits_df = outfits_df[columns_order]

# Export web-ready CSV
outfits_df.to_csv("FashionHub_Outfits_WebReady.csv", index=False)
print("✅ Web-ready outfits exported to 'FashionHub_Outfits_WebReady.csv'")

# Display first few rows
print(outfits_df.head())

✅ Web-ready outfits exported to 'FashionHub_Outfits_WebReady.csv'
                TemplateName  OutfitNumber  \
0  casual_summer_western_men             1
1  casual_summer_western_men             2
2  casual_summer_western_men             3
3  casual_summer_western_men             4
4  casual_summer_western_men             5

                                                 Top Top_ID  Top_Price  \
0     Green Lawn Hoodie (Season: Summer, Score: 100)  P0007      12948
1   Red Linen Kurta (Season: All-season, Score: 100)  P0782       7619
2   Red Linen Kurta (Season: All-season, Score: 100)  P0782       7619
3  Brown Leather Hoodie (Season: Summer, Score: 100)  P0658      14107
4  Red Leather T-Shirt (Season: All-season, Score...  P0810       2546

                Top_Seller                                             Bottom  \
0  Faisalabad Fabric Point  Brown Polyester Saree (Season: All-season, Sco...
1            DailyFitStyle  Brown Polyester Shalwar Kameez (Season: Summer...
2            DailyFitStyle  Yellow Denim Shalwar Kameez (Season: All-seaso...
3             Sana Safinaz  Brown Polyester Saree (Season: All-season, Sco...
4      Multan Cloth Market  Brown Polyester Saree (Season: All-season, Sco...

  Bottom_ID  Bottom_Price     Bottom_Seller  \
0     P0620         12130  Hyderabad Drapes
1     P1039         18008         Gul Ahmed
2     P0101          3212  Hyderabad Drapes
3     P0620         12130  Hyderabad Drapes
4     P0620         12130  Hyderabad Drapes

                                               Shoes Shoes_ID  Shoes_Price  \
0  Grey Silk Sneakers (Season: All-season, Score:...    P0625         2331
1  Yellow Linen Heels (Season: All-season, Score:...    P1394         1970
2  Blue Linen Sandals (Season: All-season, Score:...    P1515          814
3  Grey Silk Sneakers (Season: All-season, Score:...    P0625         2331
4  White Leather Sandals (Season: Summer, Score: ...    P0954        15232

       Shoes_Seller                                         Accessory  \
0    TheFashionRack  Blue Leather Wallet (Season: Summer, Score: 100)
1     DailyFitStyle   Grey Lawn Belt (Season: All-season, Score: 100)
2       ModishMoods   Grey Lawn Belt (Season: All-season, Score: 100)
3    TheFashionRack   Blue Denim Handbag (Season: Summer, Score: 100)
4  Quetta Style Hub   Blue Denim Handbag (Season: Summer, Score: 100)

  Accessory_ID  Accessory_Price     Accessory_Seller
0        P1089            18795     Quetta Style Hub
1        P1124            18144           Generation
2        P1124            18144           Generation
3        P0980            12576  Multan Cloth Market
4        P0980            12576  Multan Cloth Market

In [298]:
import pandas as pd

# === Load datasets ===
outfits_df = pd.read_csv("FashionHub_Outfits_AllTemplates.csv")
products_df = pd.read_csv("FashionHub_products_cleaned.csv")

# Base URL for product pages (adjust to your website)
BASE_URL = "https://www.fashionhub.pk/product/"

# Function to map product info
def map_product_info(product_str, products_df):
    product_name = product_str.split(" (Season:")[0].strip()
    match = products_df[products_df['ProductName'].str.lower() == product_name.lower()]
    if not match.empty:
        row = match.iloc[0]
        return pd.Series({
            "ID": row['ProductID'],
            "Price": row['PricePKR'],
            "Seller": row['SellerName'],
            "Stock": row.get("Stock", 1),  # default stock if missing
            "Season": row.get("Season", "All-season"),
            "Popularity": row.get("Popularity", 0),
            "Feedback": row.get("Feedback", 0),
            "URL": f"{BASE_URL}{row['ProductID']}"
        })
    else:
        return pd.Series({
            "ID": None, "Price": 0, "Seller": None, "Stock": 0,
            "Season": "All-season", "Popularity": 0, "Feedback": 0, "URL": None
        })

# Map all categories
for cat in ["Top", "Bottom", "Shoes", "Accessory"]:
    mapped = outfits_df[cat].apply(lambda x: map_product_info(x, products_df))
    outfits_df[f"{cat}_ID"] = mapped["ID"]
    outfits_df[f"{cat}_Price"] = mapped["Price"]
    outfits_df[f"{cat}_Seller"] = mapped["Seller"]
    outfits_df[f"{cat}_Stock"] = mapped["Stock"]
    outfits_df[f"{cat}_Season"] = mapped["Season"]
    outfits_df[f"{cat}_Popularity"] = mapped["Popularity"]
    outfits_df[f"{cat}_Feedback"] = mapped["Feedback"]
    outfits_df[f"{cat}_URL"] = mapped["URL"]

# Total outfit price
outfits_df["Total_Price"] = (
    outfits_df["Top_Price"] + outfits_df["Bottom_Price"] +
    outfits_df["Shoes_Price"] + outfits_df["Accessory_Price"]
)

# Availability
outfits_df["Availability"] = outfits_df[["Top_Stock","Bottom_Stock","Shoes_Stock","Accessory_Stock"]].min(axis=1).apply(
    lambda x: "Available" if x > 0 else "Out of stock"
)

# Optional: Season, Popularity, Feedback columns for filtering
outfits_df["Max_Popularity"] = outfits_df[["Top_Popularity","Bottom_Popularity","Shoes_Popularity","Accessory_Popularity"]].max(axis=1)
outfits_df["Avg_Feedback"] = outfits_df[["Top_Feedback","Bottom_Feedback","Shoes_Feedback","Accessory_Feedback"]].mean(axis=1)

# Reorder columns for website
columns_order = [
    "TemplateName", "OutfitNumber",
    "Top", "Top_ID", "Top_Price", "Top_Seller", "Top_Stock", "Top_Season", "Top_Popularity", "Top_Feedback", "Top_URL",
    "Bottom", "Bottom_ID", "Bottom_Price", "Bottom_Seller", "Bottom_Stock", "Bottom_Season", "Bottom_Popularity", "Bottom_Feedback", "Bottom_URL",
    "Shoes", "Shoes_ID", "Shoes_Price", "Shoes_Seller", "Shoes_Stock", "Shoes_Season", "Shoes_Popularity", "Shoes_Feedback", "Shoes_URL",
    "Accessory", "Accessory_ID", "Accessory_Price", "Accessory_Seller", "Accessory_Stock", "Accessory_Season", "Accessory_Popularity", "Accessory_Feedback", "Accessory_URL",
    "Total_Price", "Availability", "Max_Popularity", "Avg_Feedback"
]
outfits_df = outfits_df[columns_order]

# Export final web-ready CSV
outfits_df.to_csv("FashionHub_Outfits_WebReady_Full.csv", index=False)
print("✅ Final full web-ready CSV exported to 'FashionHub_Outfits_WebReady_Full.csv'")

# Display first few rows
print(outfits_df.head())

✅ Final full web-ready CSV exported to 'FashionHub_Outfits_WebReady_Full.csv'
                TemplateName  OutfitNumber  \
0  casual_summer_western_men             1
1  casual_summer_western_men             2
2  casual_summer_western_men             3
3  casual_summer_western_men             4
4  casual_summer_western_men             5

                                                 Top Top_ID  Top_Price  \
0     Green Lawn Hoodie (Season: Summer, Score: 100)  P0007      12948
1   Red Linen Kurta (Season: All-season, Score: 100)  P0782       7619
2   Red Linen Kurta (Season: All-season, Score: 100)  P0782       7619
3  Brown Leather Hoodie (Season: Summer, Score: 100)  P0658      14107
4  Red Leather T-Shirt (Season: All-season, Score...  P0810       2546

                Top_Seller  Top_Stock  Top_Season  Top_Popularity  \
0  Faisalabad Fabric Point          1      Summer               0
1            DailyFitStyle          1  All-season               0
2            DailyFitStyle          1  All-season               0
3             Sana Safinaz          1      Summer               0
4      Multan Cloth Market          1  All-season               0

   Top_Feedback  ...     Accessory_Seller Accessory_Stock Accessory_Season  \
0             0  ...     Quetta Style Hub               1           Summer
1             0  ...           Generation               1       All-season
2             0  ...           Generation               1       All-season
3             0  ...  Multan Cloth Market               1           Summer
4             0  ...  Multan Cloth Market               1           Summer

   Accessory_Popularity Accessory_Feedback  \
0                     0                  0
1                     0                  0
2                     0                  0
3                     0                  0
4                     0                  0

                             Accessory_URL Total_Price  Availability  \
0  https://www.fashionhub.pk/product/P1089       46204     Available
1  https://www.fashionhub.pk/product/P1124       45741     Available
2  https://www.fashionhub.pk/product/P1124       29789     Available
3  https://www.fashionhub.pk/product/P0980       41144     Available
4  https://www.fashionhub.pk/product/P0980       42484     Available

   Max_Popularity Avg_Feedback
0               0          0.0
1               0          0.0
2               0          0.0
3               0          0.0
4               0          0.0

[5 rows x 42 columns]

In [300]:
import pandas as pd
import random

# === Load datasets ===
df = pd.read_csv("FashionHub_products_cleaned.csv")  # product dataset

# Ensure Score column exists
if 'Score' not in df.columns:
    df['Score'] = 100  # default score if missing

# Category keywords mapping
category_keywords = {
    "Top": ["Shirt", "Kurta", "T-Shirt", "Hoodie", "Jacket", "Sweater", "Blouse", "Tunic"],
    "Bottom": ["Shalwar", "Jeans", "Trousers", "Saree", "Skirt", "Pant"],
    "Shoes": ["Shoes", "Sandals", "Sneakers", "Heels", "Flats", "Loafers", "Boots"],
    "Accessory": ["Bag", "Wallet", "Belt", "Scarf", "Necklace", "Ring", "Cap", "Handbag"]
}

# Optional: Shoes priority by style
shoes_priority = {
    "western": ["Sneakers", "Heels", "Flats", "Loafers", "Boots", "Sandals"],
    "ethnic": ["Sandals", "Heels", "Flats", "Loafers", "Boots", "Sneakers"]
}

# === Outfit generation function ===
def generate_outfits(df, occasion, season, style, gender, n_outfits=5):
    filtered = df[df['Gender'].str.lower() == gender.lower()]
    filtered = filtered[filtered['Season'].str.lower().isin([season.lower(), 'all-season'])]

    categories = ["Top", "Bottom", "Shoes", "Accessory"]
    outfits = []

    for i in range(n_outfits):
        outfit = {}
        for cat in categories:
            # Filter products by category keywords
            candidates = filtered[
                filtered['ProductName'].str.contains('|'.join(category_keywords[cat]), case=False, na=False)
            ]

            # Shoes: apply style priority if possible
            if cat == "Shoes" and style.lower() in shoes_priority:
                priority_list = shoes_priority[style.lower()]
                temp_candidates = candidates[
                    candidates['ProductName'].str.contains('|'.join(priority_list), case=False, na=False)
                ]
                if not temp_candidates.empty:
                    candidates = temp_candidates

            # Fallback if no candidates
            if candidates.empty:
                chosen = filtered.sample(n=1).iloc[0]
            else:
                top_candidates = candidates.sort_values("Score", ascending=False).head(5)
                chosen = top_candidates.sample(n=1).iloc[0]

            outfit[cat] = f"{chosen['ProductName']} (Season: {chosen['Season']}, Score: {chosen['Score']})"

        outfit["TemplateName"] = f"{occasion}_{season}_{style}_{gender}"
        outfit["OutfitNumber"] = i + 1
        outfits.append(outfit)

    return outfits

# === Templates ===
templates = [
    {"occasion": "casual", "season": "summer", "style": "western", "gender": "men", "n_outfits": 10},
    {"occasion": "party", "season": "summer", "style": "western", "gender": "women", "n_outfits": 10},
    {"occasion": "formal", "season": "winter", "style": "western", "gender": "men", "n_outfits": 10}
]

# Generate all outfits
all_outfits = []
for tpl in templates:
    all_outfits.extend(generate_outfits(
        df, tpl["occasion"], tpl["season"], tpl["style"], tpl["gender"], tpl["n_outfits"]
    ))

# Convert to DataFrame
outfits_df = pd.DataFrame(all_outfits)

# === Map product info ===
BASE_URL = "https://www.fashionhub.pk/product/"

def map_product_info(product_str):
    product_name = product_str.split(" (Season:")[0].strip()
    match = df[df['ProductName'].str.lower() == product_name.lower()]
    if not match.empty:
        row = match.iloc[0]
        return pd.Series({
            "ID": row['ProductID'],
            "Price": row['PricePKR'],
            "Seller": row['SellerName'],
            "Stock": row.get("Stock", 1),
            "Season": row.get("Season", "All-season"),
            "Popularity": row.get("Popularity", 0),
            "Feedback": row.get("Feedback", 0),
            "URL": f"{BASE_URL}{row['ProductID']}"
        })
    else:
        return pd.Series({
            "ID": None, "Price": 0, "Seller": None, "Stock": 0,
            "Season": "All-season", "Popularity": 0, "Feedback": 0, "URL": None
        })

for cat in ["Top","Bottom","Shoes","Accessory"]:
    mapped = outfits_df[cat].apply(map_product_info)
    outfits_df[f"{cat}_ID"] = mapped["ID"]
    outfits_df[f"{cat}_Price"] = mapped["Price"]
    outfits_df[f"{cat}_Seller"] = mapped["Seller"]
    outfits_df[f"{cat}_Stock"] = mapped["Stock"]
    outfits_df[f"{cat}_Season"] = mapped["Season"]
    outfits_df[f"{cat}_Popularity"] = mapped["Popularity"]
    outfits_df[f"{cat}_Feedback"] = mapped["Feedback"]
    outfits_df[f"{cat}_URL"] = mapped["URL"]

# Total price
outfits_df["Total_Price"] = (
    outfits_df["Top_Price"] + outfits_df["Bottom_Price"] +
    outfits_df["Shoes_Price"] + outfits_df["Accessory_Price"]
)

# Availability
outfits_df["Availability"] = outfits_df[["Top_Stock","Bottom_Stock","Shoes_Stock","Accessory_Stock"]].min(axis=1).apply(
    lambda x: "Available" if x>0 else "Out of stock"
)

# Max popularity & avg feedback
outfits_df["Max_Popularity"] = outfits_df[["Top_Popularity","Bottom_Popularity","Shoes_Popularity","Accessory_Popularity"]].max(axis=1)
outfits_df["Avg_Feedback"] = outfits_df[["Top_Feedback","Bottom_Feedback","Shoes_Feedback","Accessory_Feedback"]].mean(axis=1)

# AI Stylist Score
def season_style_weight(template_name):
    if "summer" in template_name.lower() and "western" in template_name.lower():
        return 100
    else:
        return 50

outfits_df["AI_Stylist_Score"] = (
    outfits_df['Max_Popularity']*0.4 +
    outfits_df['Avg_Feedback']*20*0.4 +
    outfits_df['TemplateName'].apply(season_style_weight)*0.2
)

# Reorder columns
columns_order = [
    "TemplateName", "OutfitNumber",
    "Top", "Top_ID", "Top_Price", "Top_Seller", "Top_Stock", "Top_Season", "Top_Popularity", "Top_Feedback", "Top_URL",
    "Bottom", "Bottom_ID", "Bottom_Price", "Bottom_Seller", "Bottom_Stock", "Bottom_Season", "Bottom_Popularity", "Bottom_Feedback", "Bottom_URL",
    "Shoes", "Shoes_ID", "Shoes_Price", "Shoes_Seller", "Shoes_Stock", "Shoes_Season", "Shoes_Popularity", "Shoes_Feedback", "Shoes_URL",
    "Accessory", "Accessory_ID", "Accessory_Price", "Accessory_Seller", "Accessory_Stock", "Accessory_Season", "Accessory_Popularity", "Accessory_Feedback", "Accessory_URL",
    "Total_Price", "Availability", "Max_Popularity", "Avg_Feedback", "AI_Stylist_Score"
]
outfits_df = outfits_df[columns_order]

# Export final CSV
outfits_df.to_csv("FashionHub_Outfits_WebReady_Scored.csv", index=False)
print("✅ Final web-ready CSV with AI_Stylist_Score exported to 'FashionHub_Outfits_WebReady_Scored.csv'")

# Display top 5 outfits by AI_Stylist_Score
top_outfits = outfits_df.sort_values("AI_Stylist_Score", ascending=False).head(5)
print(top_outfits[['TemplateName','OutfitNumber','AI_Stylist_Score','Total_Price','Availability']])

✅ Final web-ready CSV with AI_Stylist_Score exported to 'FashionHub_Outfits_WebReady_Scored.csv'
                  TemplateName  OutfitNumber  AI_Stylist_Score  Total_Price  \
0    casual_summer_western_men             1              20.0        38470
11  party_summer_western_women             2              20.0        32263
19  party_summer_western_women            10              20.0        34031
18  party_summer_western_women             9              20.0        20445
17  party_summer_western_women             8              20.0        30079

   Availability
0     Available
11    Available
19    Available
18    Available
17    Available

In [302]:
import pandas as pd
import random

# === Load product dataset ===
df = pd.read_csv("FashionHub_products_cleaned.csv")  # update path if needed

# Ensure Score column exists
if 'Score' not in df.columns:
    df['Score'] = 100  # default score if missing

# === Category keywords mapping ===
category_keywords = {
    "Top": ["Shirt", "Kurta", "T-Shirt", "Hoodie", "Jacket", "Sweater", "Blouse", "Tunic"],
    "Bottom": ["Shalwar", "Jeans", "Trousers", "Saree", "Skirt", "Pant"],
    "Shoes": ["Shoes", "Sandals", "Sneakers", "Heels", "Flats", "Loafers", "Boots"],
    "Accessory": ["Bag", "Wallet", "Belt", "Scarf", "Necklace", "Ring", "Cap", "Handbag"]
}

# Optional: Shoes priority by style
shoes_priority = {
    "western": ["Sneakers", "Heels", "Flats", "Loafers", "Boots", "Sandals"],
    "ethnic": ["Sandals", "Heels", "Flats", "Loafers", "Boots", "Sneakers"]
}

# === Outfit generation function ===
def generate_outfits(df, occasion, season, style, gender, n_outfits=5):
    filtered = df[df['Gender'].str.lower() == gender.lower()]
    filtered = filtered[filtered['Season'].str.lower().isin([season.lower(), 'all-season'])]

    categories = ["Top", "Bottom", "Shoes", "Accessory"]
    outfits = []

    for i in range(n_outfits):
        outfit = {}
        for cat in categories:
            # Filter products by category keywords
            candidates = filtered[
                filtered['ProductName'].str.contains('|'.join(category_keywords[cat]), case=False, na=False)
            ]

            # Shoes: apply style priority if possible
            if cat == "Shoes" and style.lower() in shoes_priority:
                priority_list = shoes_priority[style.lower()]
                temp_candidates = candidates[
                    candidates['ProductName'].str.contains('|'.join(priority_list), case=False, na=False)
                ]
                if not temp_candidates.empty:
                    candidates = temp_candidates

            # Fallback if no candidates
            if candidates.empty:
                chosen = filtered.sample(n=1).iloc[0]
            else:
                top_candidates = candidates.sort_values("Score", ascending=False).head(5)
                chosen = top_candidates.sample(n=1).iloc[0]

            outfit[cat] = f"{chosen['ProductName']} (Season: {chosen['Season']}, Score: {chosen['Score']})"

        outfit["TemplateName"] = f"{occasion}_{season}_{style}_{gender}"
        outfit["OutfitNumber"] = i + 1
        outfits.append(outfit)

    return outfits

# === Templates ===
templates = [
    {"occasion": "casual", "season": "summer", "style": "western", "gender": "men", "n_outfits": 10},
    {"occasion": "party", "season": "summer", "style": "western", "gender": "women", "n_outfits": 10},
    {"occasion": "formal", "season": "winter", "style": "western", "gender": "men", "n_outfits": 10}
]

# === Generate all outfits ===
all_outfits = []
for tpl in templates:
    all_outfits.extend(generate_outfits(
        df, tpl["occasion"], tpl["season"], tpl["style"], tpl["gender"], tpl["n_outfits"]
    ))

# Convert to DataFrame
outfits_df = pd.DataFrame(all_outfits)

# === Map product info ===
BASE_URL = "https://www.fashionhub.pk/product/"

def map_product_info(product_str):
    product_name = product_str.split(" (Season:")[0].strip()
    match = df[df['ProductName'].str.lower() == product_name.lower()]
    if not match.empty:
        row = match.iloc[0]
        return pd.Series({
            "ID": row['ProductID'],
            "Price": row['PricePKR'],
            "Seller": row['SellerName'],
            "Stock": row.get("Stock", 1),
            "Season": row.get("Season", "All-season"),
            "Popularity": row.get("Popularity", 0),
            "Feedback": row.get("Feedback", 0),
            "URL": f"{BASE_URL}{row['ProductID']}"
        })
    else:
        return pd.Series({
            "ID": None, "Price": 0, "Seller": None, "Stock": 0,
            "Season": "All-season", "Popularity": 0, "Feedback": 0, "URL": None
        })

for cat in ["Top","Bottom","Shoes","Accessory"]:
    mapped = outfits_df[cat].apply(map_product_info)
    outfits_df[f"{cat}_ID"] = mapped["ID"]
    outfits_df[f"{cat}_Price"] = mapped["Price"]
    outfits_df[f"{cat}_Seller"] = mapped["Seller"]
    outfits_df[f"{cat}_Stock"] = mapped["Stock"]
    outfits_df[f"{cat}_Season"] = mapped["Season"]
    outfits_df[f"{cat}_Popularity"] = mapped["Popularity"]
    outfits_df[f"{cat}_Feedback"] = mapped["Feedback"]
    outfits_df[f"{cat}_URL"] = mapped["URL"]

# === Calculations ===
# Total price
outfits_df["Total_Price"] = (
    outfits_df["Top_Price"] + outfits_df["Bottom_Price"] +
    outfits_df["Shoes_Price"] + outfits_df["Accessory_Price"]
)

# Availability
outfits_df["Availability"] = outfits_df[["Top_Stock","Bottom_Stock","Shoes_Stock","Accessory_Stock"]].min(axis=1).apply(
    lambda x: "Available" if x>0 else "Out of stock"
)

# Max popularity & avg feedback
outfits_df["Max_Popularity"] = outfits_df[["Top_Popularity","Bottom_Popularity","Shoes_Popularity","Accessory_Popularity"]].max(axis=1)
outfits_df["Avg_Feedback"] = outfits_df[["Top_Feedback","Bottom_Feedback","Shoes_Feedback","Accessory_Feedback"]].mean(axis=1)

# AI Stylist Score
def season_style_weight(template_name):
    if "summer" in template_name.lower() and "western" in template_name.lower():
        return 100
    else:
        return 50

outfits_df["AI_Stylist_Score"] = (
    outfits_df['Max_Popularity']*0.4 +
    outfits_df['Avg_Feedback']*20*0.4 +
    outfits_df['TemplateName'].apply(season_style_weight)*0.2
)

# Trending/Featured flag (top 20%)
score_threshold = outfits_df['AI_Stylist_Score'].quantile(0.8)
outfits_df['Trending'] = outfits_df['AI_Stylist_Score'].apply(lambda x: "Trending" if x>=score_threshold else "Regular")

# === Reorder columns for website ===
columns_order = [
    "TemplateName", "OutfitNumber",
    "Top", "Top_ID", "Top_Price", "Top_Seller", "Top_Stock", "Top_Season", "Top_Popularity", "Top_Feedback", "Top_URL",
    "Bottom", "Bottom_ID", "Bottom_Price", "Bottom_Seller", "Bottom_Stock", "Bottom_Season", "Bottom_Popularity", "Bottom_Feedback", "Bottom_URL",
    "Shoes", "Shoes_ID", "Shoes_Price", "Shoes_Seller", "Shoes_Stock", "Shoes_Season", "Shoes_Popularity", "Shoes_Feedback", "Shoes_URL",
    "Accessory", "Accessory_ID", "Accessory_Price", "Accessory_Seller", "Accessory_Stock", "Accessory_Season", "Accessory_Popularity", "Accessory_Feedback", "Accessory_URL",
    "Total_Price", "Availability", "Max_Popularity", "Avg_Feedback", "AI_Stylist_Score", "Trending"
]
outfits_df = outfits_df[columns_order]

# === Export final CSV ===
outfits_df.to_csv("FashionHub_Outfits_WebReady_Final.csv", index=False)
print("✅ Final web-ready CSV with AI_Stylist_Score and Trending flag exported to 'FashionHub_Outfits_WebReady_Final.csv'")

# Display top 5 trending outfits
top_trending = outfits_df[outfits_df['Trending']=="Trending"].sort_values("AI_Stylist_Score", ascending=False).head(5)
print(top_trending[['TemplateName','OutfitNumber','AI_Stylist_Score','Total_Price','Availability','Trending']])

✅ Final web-ready CSV with AI_Stylist_Score and Trending flag exported to 'FashionHub_Outfits_WebReady_Final.csv'
                  TemplateName  OutfitNumber  AI_Stylist_Score  Total_Price  \
0    casual_summer_western_men             1              20.0        36928
1    casual_summer_western_men             2              20.0        32608
18  party_summer_western_women             9              20.0        20465
17  party_summer_western_women             8              20.0        47732
16  party_summer_western_women             7              20.0        47257

   Availability  Trending
0     Available  Trending
1     Available  Trending
18    Available  Trending
17    Available  Trending
16    Available  Trending

In [304]:
# Extract style and season from TemplateName
outfits_df['Style'] = outfits_df['TemplateName'].apply(lambda x: x.split('_')[2])
outfits_df['Template_Season'] = outfits_df['TemplateName'].apply(lambda x: x.split('_')[1])

# Availability as boolean
outfits_df['Is_Available'] = outfits_df['Availability'].apply(lambda x: 1 if x=="Available" else 0)

# Combined season (all items)
def combined_season(row):
    seasons = set([row['Top_Season'], row['Bottom_Season'], row['Shoes_Season'], row['Accessory_Season']])
    return ','.join(seasons)
outfits_df['Combined_Season'] = outfits_df.apply(combined_season, axis=1)

# Sort example: by AI_Stylist_Score descending
outfits_df = outfits_df.sort_values('AI_Stylist_Score', ascending=False)

# Export filtered/sorted CSV for website
outfits_df.to_csv("FashionHub_Outfits_WebReady_Filtered.csv", index=False)
print("✅ Web-ready CSV for filtering & sorting exported as 'FashionHub_Outfits_WebReady_Filtered.csv'")

# Example: top 5 outfits for each season
for season in outfits_df['Template_Season'].unique():
    print(f"\nTop 5 outfits for {season} season:")
    top5 = outfits_df[outfits_df['Template_Season']==season].head(5)
    print(top5[['TemplateName','OutfitNumber','AI_Stylist_Score','Total_Price','Availability','Trending']])

✅ Web-ready CSV for filtering & sorting exported as 'FashionHub_Outfits_WebReady_Filtered.csv'

Top 5 outfits for summer season:
                  TemplateName  OutfitNumber  AI_Stylist_Score  Total_Price  \
0    casual_summer_western_men             1              20.0        36928
11  party_summer_western_women             2              20.0        46249
19  party_summer_western_women            10              20.0        38631
18  party_summer_western_women             9              20.0        20465
17  party_summer_western_women             8              20.0        47732

   Availability  Trending
0     Available  Trending
11    Available  Trending
19    Available  Trending
18    Available  Trending
17    Available  Trending

Top 5 outfits for winter season:
                 TemplateName  OutfitNumber  AI_Stylist_Score  Total_Price  \
25  formal_winter_western_men             6              10.0        27957
28  formal_winter_western_men             9              10.0        50385
27  formal_winter_western_men             8              10.0        32885
26  formal_winter_western_men             7              10.0        25288
20  formal_winter_western_men             1              10.0        35903

   Availability Trending
25    Available  Regular
28    Available  Regular
27    Available  Regular
26    Available  Regular
20    Available  Regular

In [306]:
import pandas as pd
import random

# -------------------------
# Config / input files
# -------------------------
PRODUCTS_CSV = "FashionHub_products_cleaned.csv"  # update if path different
OUTPUT_CSV = "FashionHub_Outfits_WebReady_WithSimilar.csv"
BASE_URL = "https://www.fashionhub.pk/product/"

# -------------------------
# Load product dataset
# -------------------------
df = pd.read_csv(PRODUCTS_CSV)

# Provide defaults if some columns missing
if 'Score' not in df.columns:
    df['Score'] = 100
if 'PricePKR' not in df.columns:
    df['PricePKR'] = 0
if 'ProductID' not in df.columns:
    df['ProductID'] = ["P{:04d}".format(i) for i in range(len(df))]
if 'SellerName' not in df.columns:
    df['SellerName'] = "Unknown Seller"
if 'Stock' not in df.columns:
    df['Stock'] = 1
if 'Season' not in df.columns:
    df['Season'] = 'All-season'
if 'Gender' not in df.columns:
    # default to all genders if missing
    df['Gender'] = df.get('Gender', 'unisex')
if 'Popularity' not in df.columns:
    df['Popularity'] = 0
if 'Feedback' not in df.columns:
    df['Feedback'] = 0

# -------------------------
# Category keywords mapping
# -------------------------
category_keywords = {
    "Top": ["Shirt", "Kurta", "T-Shirt", "Hoodie", "Jacket", "Sweater", "Blouse", "Tunic"],
    "Bottom": ["Shalwar", "Jeans", "Trousers", "Saree", "Skirt", "Pant"],
    "Shoes": ["Shoes", "Sandals", "Sneakers", "Heels", "Flats", "Loafers", "Boots"],
    "Accessory": ["Bag", "Wallet", "Belt", "Scarf", "Necklace", "Ring", "Cap", "Handbag"]
}

shoes_priority = {
    "western": ["Sneakers", "Heels", "Flats", "Loafers", "Boots", "Sandals"],
    "ethnic": ["Sandals", "Heels", "Flats", "Loafers", "Boots", "Sneakers"]
}

# -------------------------
# Outfit generation function
# -------------------------
def generate_outfits(df, occasion, season, style, gender, n_outfits=10, rng_seed=None):
    if rng_seed is not None:
        random.seed(rng_seed)
    # filter by gender and season
    filtered = df[df['Gender'].str.lower().isin([gender.lower(), 'unisex', 'all'])]
    filtered = filtered[filtered['Season'].str.lower().isin([season.lower(), 'all-season'])]
    categories = ["Top", "Bottom", "Shoes", "Accessory"]
    outfits = []
    for i in range(n_outfits):
        outfit = {}
        for cat in categories:
            # find candidates by keywords
            kw = category_keywords.get(cat, [])
            if len(kw) == 0:
                candidates = filtered
            else:
                pattern = '|'.join(kw)
                candidates = filtered[filtered['ProductName'].str.contains(pattern, case=False, na=False)]
            # shoes style priority
            if cat == "Shoes" and style.lower() in shoes_priority:
                priority_list = shoes_priority[style.lower()]
                temp_candidates = candidates[candidates['ProductName'].str.contains('|'.join(priority_list), case=False, na=False)]
                if not temp_candidates.empty:
                    candidates = temp_candidates
            # fallback
            if candidates.empty:
                chosen = filtered.sample(n=1).iloc[0]
            else:
                top_candidates = candidates.sort_values("Score", ascending=False).head(5)
                chosen = top_candidates.sample(n=1).iloc[0]
            outfit[cat] = f"{chosen['ProductName']} (Season: {chosen['Season']}, Score: {chosen['Score']})"
        outfit["TemplateName"] = f"{occasion}_{season}_{style}_{gender}"
        outfit["OutfitNumber"] = i + 1
        outfits.append(outfit)
    return outfits

# -------------------------
# Expanded templates (keep genders men/women only)
# -------------------------
occasions = ["casual", "party", "formal", "wedding", "office", "travel"]
seasons = ["summer", "winter", "all-season"]
styles = ["western", "ethnic"]
genders = ["men", "women"]  # keep limited as requested

templates = []
for occ in occasions:
    for sea in seasons:
        for st in styles:
            for g in genders:
                templates.append({"occasion": occ, "season": sea, "style": st, "gender": g, "n_outfits": 8})

# -------------------------
# Generate outfits for all templates
# -------------------------
all_outfits = []
for tpl in templates:
    outfs = generate_outfits(df, tpl["occasion"], tpl["season"], tpl["style"], tpl["gender"], tpl["n_outfits"])
    all_outfits.extend(outfs)

outfits_df = pd.DataFrame(all_outfits)

# -------------------------
# Map product info (using main df)
# -------------------------
def map_product_info(product_str):
    product_name = product_str.split(" (Season:")[0].strip()
    match = df[df['ProductName'].str.lower() == product_name.lower()]
    if not match.empty:
        row = match.iloc[0]
        return pd.Series({
            "ID": row['ProductID'],
            "Price": row['PricePKR'],
            "Seller": row['SellerName'],
            "Stock": row.get("Stock", 1),
            "Season": row.get("Season", "All-season"),
            "Popularity": row.get("Popularity", 0),
            "Feedback": row.get("Feedback", 0),
            "URL": f"{BASE_URL}{row['ProductID']}"
        })
    else:
        return pd.Series({
            "ID": None, "Price": 0, "Seller": None, "Stock": 0,
            "Season": "All-season", "Popularity": 0, "Feedback": 0, "URL": None
        })

for cat in ["Top","Bottom","Shoes","Accessory"]:
    mapped = outfits_df[cat].apply(map_product_info)
    outfits_df[f"{cat}_ID"] = mapped["ID"]
    outfits_df[f"{cat}_Price"] = mapped["Price"]
    outfits_df[f"{cat}_Seller"] = mapped["Seller"]
    outfits_df[f"{cat}_Stock"] = mapped["Stock"]
    outfits_df[f"{cat}_Season"] = mapped["Season"]
    outfits_df[f"{cat}_Popularity"] = mapped["Popularity"]
    outfits_df[f"{cat}_Feedback"] = mapped["Feedback"]
    outfits_df[f"{cat}_URL"] = mapped["URL"]

# -------------------------
# Calculations: totals, availability, aggregates
# -------------------------
outfits_df["Total_Price"] = (
    outfits_df["Top_Price"].fillna(0) + outfits_df["Bottom_Price"].fillna(0) +
    outfits_df["Shoes_Price"].fillna(0) + outfits_df["Accessory_Price"].fillna(0)
)

outfits_df["Availability"] = outfits_df[["Top_Stock","Bottom_Stock","Shoes_Stock","Accessory_Stock"]].min(axis=1).apply(
    lambda x: "Available" if x>0 else "Out of stock"
)

outfits_df["Max_Popularity"] = outfits_df[["Top_Popularity","Bottom_Popularity","Shoes_Popularity","Accessory_Popularity"]].max(axis=1)
outfits_df["Avg_Feedback"] = outfits_df[["Top_Feedback","Bottom_Feedback","Shoes_Feedback","Accessory_Feedback"]].mean(axis=1).fillna(0)

# -------------------------
# AI Stylist Score
# -------------------------
def season_style_weight(template_name):
    # give highest weight to summer+western currently, others mid
    name = template_name.lower()
    if "summer" in name and "western" in name:
        return 100
    elif "wedding" in name or "party" in name:
        return 90
    else:
        return 60

outfits_df["AI_Stylist_Score"] = (
    outfits_df['Max_Popularity'] * 0.4 +
    outfits_df['Avg_Feedback'] * 20 * 0.4 +   # feedback scaled 0-5 -> 0-100 by *20
    outfits_df['TemplateName'].apply(season_style_weight) * 0.2
)

# -------------------------
# Trending flag (top 20%)
# -------------------------
score_threshold = outfits_df['AI_Stylist_Score'].quantile(0.8)
outfits_df['Trending'] = outfits_df['AI_Stylist_Score'].apply(lambda x: "Trending" if x >= score_threshold else "Regular")

# -------------------------
# Helper columns for website (Style, Template_Season)
# -------------------------
outfits_df['Style'] = outfits_df['TemplateName'].apply(lambda x: x.split('_')[2] if len(x.split('_'))>2 else "")
outfits_df['Template_Season'] = outfits_df['TemplateName'].apply(lambda x: x.split('_')[1] if len(x.split('_'))>1 else "")

# -------------------------
# Create a unique OutfitID and index for quick lookup
# -------------------------
outfits_df = outfits_df.reset_index(drop=True)
outfits_df["OutfitID"] = outfits_df.apply(lambda r: f"{r['TemplateName']}|{r['OutfitNumber']}", axis=1)

# -------------------------
# Similar_Outfits: same occasion+season+style, top 3 by AI_Stylist_Score, excluding itself
# -------------------------
# We'll parse TemplateName to get occasion/season/style part (first 3 parts)
def tpl_key(template_name):
    parts = template_name.split('_')
    # join occasion, season, style to be safe
    if len(parts) >= 3:
        return "_".join(parts[:3])
    return template_name

outfits_df["tpl_key"] = outfits_df["TemplateName"].apply(tpl_key)

# Prepare groups
groups = outfits_df.groupby("tpl_key")

similar_map = {}
for key, group in groups:
    # sort group by AI score desc
    sorted_group = group.sort_values("AI_Stylist_Score", ascending=False)
    ids = list(sorted_group["OutfitID"])
    # for each outfit in this group, take top 3 other IDs
    for idx, row in sorted_group.iterrows():
        this_id = row["OutfitID"]
        # candidates excluding itself
        others = [o for o in ids if o != this_id]
        top_similar = others[:3]  # if less than 3, shorter list
        similar_map[this_id] = top_similar

# Attach Similar_Outfits column
outfits_df["Similar_Outfits"] = outfits_df["OutfitID"].apply(lambda oid: similar_map.get(oid, []))

# -------------------------
# Reorder columns for final CSV
# -------------------------
columns_order = [
    "OutfitID", "TemplateName", "OutfitNumber",
    "Style", "Template_Season",
    "Top", "Top_ID", "Top_Price", "Top_Seller", "Top_Stock", "Top_Season", "Top_Popularity", "Top_Feedback", "Top_URL",
    "Bottom", "Bottom_ID", "Bottom_Price", "Bottom_Seller", "Bottom_Stock", "Bottom_Season", "Bottom_Popularity", "Bottom_Feedback", "Bottom_URL",
    "Shoes", "Shoes_ID", "Shoes_Price", "Shoes_Seller", "Shoes_Stock", "Shoes_Season", "Shoes_Popularity", "Shoes_Feedback", "Shoes_URL",
    "Accessory", "Accessory_ID", "Accessory_Price", "Accessory_Seller", "Accessory_Stock", "Accessory_Season", "Accessory_Popularity", "Accessory_Feedback", "Accessory_URL",
    "Total_Price", "Availability", "Is_Available" if "Is_Available" in outfits_df.columns else "Max_Popularity", 
    "Max_Popularity", "Avg_Feedback", "AI_Stylist_Score", "Trending", "Similar_Outfits"
]

# ensure columns present (avoid duplicate or missing)
final_columns = [c for c in columns_order if c in outfits_df.columns]

final_df = outfits_df[final_columns]

# -------------------------
# Export final CSV
# -------------------------
final_df.to_csv(OUTPUT_CSV, index=False)
print(f"✅ Exported final CSV with Similar_Outfits to '{OUTPUT_CSV}'")
print("\nTop 5 Trending Outfits (sample):")
print(final_df[final_df['Trending']=="Trending"].sort_values("AI_Stylist_Score", ascending=False).head(5)[
    ["OutfitID","TemplateName","OutfitNumber","AI_Stylist_Score","Total_Price","Availability","Similar_Outfits"]
])

✅ Exported final CSV with Similar_Outfits to 'FashionHub_Outfits_WebReady_WithSimilar.csv'

Top 5 Trending Outfits (sample):
                           OutfitID                  TemplateName  \
0       casual_summer_western_men|1     casual_summer_western_men
192     formal_summer_western_men|1     formal_summer_western_men
302  wedding_summer_western_women|7  wedding_summer_western_women
301  wedding_summer_western_women|6  wedding_summer_western_women
300  wedding_summer_western_women|5  wedding_summer_western_women

     OutfitNumber  AI_Stylist_Score  Total_Price Availability  \
0               1              20.0        66635    Available
192             1              20.0        40469    Available
302             7              20.0        33818    Available
301             6              20.0        54912    Available
300             5              20.0        49053    Available

                                       Similar_Outfits
0    [casual_summer_western_men|2, casual_summer_we...
192  [formal_summer_western_men|2, formal_summer_we...
302  [wedding_summer_western_men|1, wedding_summer_...
301  [wedding_summer_western_men|1, wedding_summer_...
300  [wedding_summer_western_men|1, wedding_summer_...

In [308]:
import pandas as pd
import json

# === Load previous web-ready dataset ===
df = pd.read_csv("FashionHub_Outfits_WebReady_WithSimilar.csv")

# --- Data Enhancement ---

# 1. Price Range Label
def price_range(price):
    if price < 5000:
        return "Budget"
    elif price <= 15000:
        return "Mid-range"
    else:
        return "Premium"

df["PriceRange"] = df["Total_Price"].apply(price_range)

# 2. Occasion Category
df["Occasion"] = df["TemplateName"].apply(lambda x: x.split("_")[0])

# 3. Season, Style, Gender extraction
df["Season"] = df["TemplateName"].apply(lambda x: x.split("_")[1])
df["Style"] = df["TemplateName"].apply(lambda x: x.split("_")[2])
df["Gender"] = df["TemplateName"].apply(lambda x: x.split("_")[3])

# 4. Outfit Tags (auto-generated)
df["Tags"] = df.apply(
    lambda row: ",".join([
        row["Occasion"],
        row["Season"],
        row["Style"],
        row["Gender"],
        row["PriceRange"].lower(),
        "trending" if row["Trending"] else "normal"
    ]),
    axis=1
)

# 5. Outfit Ranking Score
df["RankingScore"] = df["AI_Stylist_Score"] * (df["Max_Popularity"] + 1)

# --- Export CSV ---
enhanced_csv_path = "FashionHub_Outfits_WebReady_Enhanced.csv"
df.to_csv(enhanced_csv_path, index=False)
print(f"✅ Enhanced CSV exported: {enhanced_csv_path}")

# --- Export JSON ---
outfits_json = []

for _, row in df.iterrows():
    outfit = {
        "OutfitID": row["OutfitID"],
        "TemplateName": row["TemplateName"],
        "Occasion": row["Occasion"],
        "Season": row["Season"],
        "Style": row["Style"],
        "Gender": row["Gender"],
        "TotalPrice": int(row["Total_Price"]),
        "PriceRange": row["PriceRange"],
        "Availability": row["Availability"],
        "AI_Stylist_Score": row["AI_Stylist_Score"],
        "Max_Popularity": row["Max_Popularity"],
        "Avg_Feedback": row["Avg_Feedback"],
        "Trending": bool(row["Trending"]),
        "Tags": row["Tags"].split(","),
        "Products": {
            "Top": {
                "Name": row["Top"],
                "ID": row["Top_ID"],
                "Price": row["Top_Price"],
                "Seller": row["Top_Seller"],
                "Stock": row["Top_Stock"],
                "Season": row["Top_Season"],
                "Popularity": row["Top_Popularity"],
                "Feedback": row["Top_Feedback"],
                "URL": row["Top_URL"]
            },
            "Bottom": {
                "Name": row["Bottom"],
                "ID": row["Bottom_ID"],
                "Price": row["Bottom_Price"],
                "Seller": row["Bottom_Seller"],
                "Stock": row["Bottom_Stock"],
                "Season": row["Bottom_Season"],
                "Popularity": row["Bottom_Popularity"],
                "Feedback": row["Bottom_Feedback"],
                "URL": row["Bottom_URL"]
            },
            "Shoes": {
                "Name": row["Shoes"],
                "ID": row["Shoes_ID"],
                "Price": row["Shoes_Price"],
                "Seller": row["Shoes_Seller"],
                "Stock": row["Shoes_Stock"],
                "Season": row["Shoes_Season"],
                "Popularity": row["Shoes_Popularity"],
                "Feedback": row["Shoes_Feedback"],
                "URL": row["Shoes_URL"]
            },
            "Accessory": {
                "Name": row["Accessory"],
                "ID": row["Accessory_ID"],
                "Price": row["Accessory_Price"],
                "Seller": row["Accessory_Seller"],
                "Stock": row["Accessory_Stock"],
                "Season": row["Accessory_Season"],
                "Popularity": row["Accessory_Popularity"],
                "Feedback": row["Accessory_Feedback"],
                "URL": row["Accessory_URL"]
            }
        },
        "Similar_Outfits": eval(row["Similar_Outfits"]) if isinstance(row["Similar_Outfits"], str) else []
    }
    outfits_json.append(outfit)

enhanced_json_path = "FashionHub_Outfits_WebReady_Enhanced.json"
with open(enhanced_json_path, "w", encoding="utf-8") as f:
    json.dump(outfits_json, f, indent=2, ensure_ascii=False)

print(f"✅ Enhanced JSON exported: {enhanced_json_path}")

✅ Enhanced CSV exported: FashionHub_Outfits_WebReady_Enhanced.csv
✅ Enhanced JSON exported: FashionHub_Outfits_WebReady_Enhanced.json

In [310]:
def calculate_ai_stylist_score(row, current_season, outfit_style, budget_range=None):
    """
    row: product row (with popularity, feedback, price, season, tags, seller type, etc.)
    current_season: 'Summer', 'Winter', etc.
    outfit_style: 'casual', 'party', 'formal', 'wedding'
    budget_range: tuple (min_price, max_price) or None
    """

    # --- Base score ---
    base_score = (row["Popularity"] * row["Feedback"]) / 10

    # --- Season boost ---
    if row["Season"].lower() == current_season.lower():
        season_boost = 15
    else:
        season_boost = -10

    # --- Style boost ---
    tags = str(row.get("AI_Tags_Cleaned", "")).lower()
    if outfit_style in tags:
        style_boost = 10
    else:
        style_boost = 0

    # --- Seller boost (equal trust for all) ---
    seller_boost = 5   # same for big brands, local, Instagram, TikTok, bazaar

    # --- Price balance ---
    price_balance = 0
    if budget_range:
        min_price, max_price = budget_range
        if min_price <= row["PricePKR"] <= max_price:
            price_balance = 5
        elif row["PricePKR"] > max_price * 1.5:  # way overpriced
            price_balance = -10

    # --- Final Score ---
    return base_score + season_boost + style_boost + seller_boost + price_balance

In [316]:
import pandas as pd
import numpy as np

# === Load dataset ===
df = pd.read_csv("FashionHub_products_cleaned.csv")

# === Add dummy Popularity (50–200) and Feedback (2.5–5.0) ===
df["Popularity"] = np.random.randint(50, 200, size=len(df))
df["Feedback"] = np.round(np.random.uniform(2.5, 5.0, size=len(df)), 1)

# === AI Stylist Scoring Function ===
def calculate_ai_stylist_score(row, current_season, outfit_style, budget_range=None):
    # Base scoring
    popularity = row.get("Popularity", 50)
    feedback = row.get("Feedback", 3.0)
    base_score = (popularity * feedback) / 10

    # Season boost
    if str(row.get("Season", "")).lower() == current_season.lower():
        season_boost = 15
    else:
        season_boost = -10

    # Style boost
    tags = str(row.get("AI_Tags_Cleaned", "")).lower()
    style_boost = 10 if outfit_style in tags else 0

    # Equal seller trust for now
    seller_boost = 5

    # Price balance
    price = row.get("PricePKR", 0)
    price_balance = 0
    if budget_range:
        min_price, max_price = budget_range
        if min_price <= price <= max_price:
            price_balance = 5
        elif price > max_price * 1.5:
            price_balance = -10

    return base_score + season_boost + style_boost + seller_boost + price_balance

# === Test the function on first 5 products ===
df["AI_Score_Test"] = df.apply(
    lambda row: calculate_ai_stylist_score(row, "summer", "casual"), axis=1
)

print(df[["ProductID", "ProductName", "Popularity", "Feedback", "AI_Score_Test"]].head())

  ProductID              ProductName  Popularity  Feedback  AI_Score_Test
0     P0001      White Polyester Cap         153       2.5          43.25
1     P0002  Yellow Polyester Wallet         190       3.3          82.70
2     P0003    Green Leather T-Shirt         197       4.4         116.68
3     P0004      Yellow Wool T-Shirt          83       3.8          36.54
4     P0005     Brown Leather Wallet          99       4.5          39.55

In [318]:
import pandas as pd

# Load your cleaned dataset
df = pd.read_csv("FashionHub_products_cleaned.csv")

# Step 1: Generate dummy Popularity & Feedback (only if missing)
import numpy as np
if "Popularity" not in df.columns:
    np.random.seed(42)
    df["Popularity"] = np.random.randint(50, 200, size=len(df))
if "Feedback" not in df.columns:
    df["Feedback"] = np.round(np.random.uniform(2.0, 5.0, size=len(df)), 1)

# Step 2: Calculate raw AI Stylist Score
df["AI_Stylist_Score"] = (df["Popularity"] * df["Feedback"]) / 10

# Step 3: Normalize to 0–100
min_score = df["AI_Stylist_Score"].min()
max_score = df["AI_Stylist_Score"].max()
df["AI_Stylist_Score_Normalized"] = (
    (df["AI_Stylist_Score"] - min_score) / (max_score - min_score) * 100
).round(2)

# Step 4: Save enhanced dataset
output_file = "FashionHub_products_with_AI_Scores.csv"
df.to_csv(output_file, index=False, encoding="utf-8")

print(f"✅ Enhanced dataset exported to '{output_file}'")
print(df[["ProductID", "ProductName", "Popularity", "Feedback", "AI_Stylist_Score", "AI_Stylist_Score_Normalized"]].head())

✅ Enhanced dataset exported to 'FashionHub_products_with_AI_Scores.csv'
  ProductID              ProductName  Popularity  Feedback  AI_Stylist_Score  \
0     P0001      White Polyester Cap         152       4.9             74.48
1     P0002  Yellow Polyester Wallet         142       4.0             56.80
2     P0003    Green Leather T-Shirt          64       2.6             16.64
3     P0004      Yellow Wool T-Shirt         156       4.0             62.40
4     P0005     Brown Leather Wallet         121       2.2             26.62

   AI_Stylist_Score_Normalized
0                        71.73
1                        51.75
2                         6.37
3                        58.08
4                        17.65